### ISSUE TITLE
Scroll bar appears when enable both expand row and pagination in the datagrid.

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#1012]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The height of datagrid should be auto scaling when open the expand show and no scroll bar should appear.

### Actual behavior
Scroll bar appear when open the expand show.

### Reproduction of behavior

https://plnkr.co/edit/jMCyX9?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.X

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@steven-zou: I don't think the datagrid should automatically scale to accommodate the expanded row. If it does that the elements on the page will move on every expand/collapse. When the data is loaded we specifically make sure that the height remains the same change on every page so that the elements on the page do not move on page change. I will cc: @youdz to confirm this.

**Comment by youdz** [comment]
Well, the datagrid does scale when it's not paginated. I think @adityarb88's analysis that the datagrid should keep the same height when paginated is correct, it prevents the rest of the page from jumping up and down.

**Comment by adityarb88** [comment]
@steven-zou: I am going to close this issue but feel free to re-open it if you have additional questions.
