### ISSUE TITLE
Expand clr-tree-node by clicking its text

### ISSUE THREAD

**Issue by MattMattV** [vmware/clarity#1021]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
I was wondering if it would be possible to expand a `<clr-tree-node>` by clicking/touching it's label in addition of the caret icon

### Actual behavior
For now it's only possible to expand a `<clr-tree-node>` by clicking/touching its associated caret icon.

**Comment by adityarb88** [comment]
@MattMattV: We won't be able to provide that functionality because that wouldn't work for cases like routing with trees where users use a link in the tree-node to route to different components. But if you had to, you could simply use the `clrTreeNodeExpanded` input and toggle it when the node is clicked. Something like this: https://plnkr.co/edit/jX6JmHnEblzgqWRWYJN8?p=preview

**Comment by adityarb88** [comment]
Closing this issue based on the above comment.

**Comment by MattMattV** [comment]
Thank you for the workaround !

**Comment by hubertkubiak** [comment]
@adityarb88  Could you please reupload the Plunker? I don't know how to use the ```clrTreeNodeExpanded``` input.

**Comment by hippee-lee** [comment]
@hubertkubiak - this is a very old issue. Can you ask your question on StackOverflow and label it with `vmware-clarity`? We can answer implementation questions there.
