### ISSUE TITLE
Login background pattern black on IE11

### ISSUE THREAD

**Issue by adumesny** [vmware/clarity#105]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
login background blue background to render correctly

### Actual behavior
solid black background on IE11 (fine on Edge) 

### Reproduction of behavior
running IE11 on windows 10 (ok with Edge) open login URL to document (same issue on running app)
https://vmware.github.io/clarity/documentation/login

notice it is running with default document mode and agent (desktop).

![clarity_login_css](https://cloud.githubusercontent.com/assets/3496166/20438927/2eb0f612-ad6e-11e6-8eb2-c4992cc38d15.png)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.6.1 (according to nodes_module/clarity-ui/package.json)

* **OS and version:**  windows 10

* **Browser:** [IE 11 ]

**Comment by jaffoneh** [comment]
I couldn't personally replicate this one on IE11 on Windows 7. @adityarb88: can you take a look and see if you can replicate?

**Comment by adityarb88** [comment]
Actually even I am unable to replicate this issue and I made sure that the mode and agent are the same. Since @adumesny is actually facing this issue on the Clarity website too, it isn't related to the markup being used or styles being overridden or something like that. I even tried running this on IE10 and Edge and it worked fine on those browsers too. Not exactly sure how to debug this. 

@adumesny: When you inspect the background image, do you see a svg being used as a background image of `.login-wrapper`? Would you please try running this in incognito mode/private browsing & also try clearing the cache?

**Comment by jaffoneh** [comment]
@adumesny wanted to quickly reach out again and see if you're still facing this issue. I am unable to replicate locally neither is @adityarb88 so I wanted to make sure to check with you before closing it just in case you're still facing this issue.

**Comment by adumesny** [comment]
@adityarb88 I tried clearing cache/cookies, and running private browsing and still seeing same issue. Here is what the CSS dom looks like - yeah it has an svg background attached - maybe some of the display props are messing it up ?
![ie11_issue](https://cloud.githubusercontent.com/assets/3496166/20778661/0a085f70-b724-11e6-85e5-c8134f21be55.png)

**Comment by adityarb88** [comment]
@adumesny: Thanks for reporting this. I can see it now. Its a weird issue which occurs only on IE 11 on Windows 10 (http://stackoverflow.com/questions/34225933/ie11-using-svg-as-background-image-fails). Will work on a fix soon.

**Comment by adumesny** [comment]
great, yep I see the stackoverflow ticket - same issue. weird.
