### ISSUE TITLE
Create new icons for Clarity iconography: vol 7

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#1053]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ X ] enhancement
```

**Comment by lil-kim** [comment]
### Set 1 of 2:
[vol7_ions_1of2.zip](https://github.com/vmware/clarity/files/1093249/vol7_ions_1of2.zip)

![image](https://user-images.githubusercontent.com/23196444/27411251-6475d646-56a1-11e7-9c47-ce50126410f7.png)

**Comment by lil-kim** [comment]
See Icon categories here:
https://confluence.eng.vmware.com/pages/editpage.action?pageId=196082902

**Comment by mathisscott** [comment]
One SVG in the file is using strokes and I can't use Sketch to convert it properly. Sketch messes with the sizing too much and moves the image to the left. I've contacted @lil-kim to get a non-stroked version of this SVG.

Completion of this issue is blocked until then. This is a priority for today because today is the only day I have to get a PR in for this issue.
