### ISSUE TITLE
Undefined variables when updating from v0.8.8 to v0.9.8

### ISSUE THREAD

**Issue by efgonz** [vmware/clarity#1055]
Hi guys, I just joined a team and I'm having problems updating from v0.8.8 to v0.9.8, after update I get a bunch of Undefined variable errors like this:

>Module build failed:
    color: $clr-black,
          ^
      Undefined variable: "$clr-black".
      in /node_modules/clarity-ui/src/utils/_variables.clarity.scss (line 81, column 12)

I figured out that all imports in _variables.clarity.scss are now removed. Do I need to do something else in order to make it work?

Thanks for your help.

**Comment by mathisscott** [comment]
@adityarb88 : Could you take a look and figure out what is happening?

**Comment by adityarb88** [comment]
@efgonz: We reorganized our CSS to avoid multiple imports after 0.8.8. You would have to refer to our `main.scss` file and make sure that all imports before `variables.clarity.scss` are imported before it too. Please note that this is not a recommended way to consume Clarity CSS because internal structural changes in the project are not considered & reported as breaking changes.

**Comment by adityarb88** [comment]
Closing based on the above comment. Please feel free to reopen the issues if you still face any issues.
