### ISSUE TITLE
Define a CSS class that allows clipping cell content with ellipsis in clr-datagrid

### ISSUE THREAD

**Issue by clementcur** [vmware/clarity#1065]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
When the content of a cell gets too long it wraps automatically if we don't specify any custom CSS. If we want to have the content clipped with an ellipsis on one line, and use the expand feature to reveal the whole content, the current CSS computation does not allow that unless we override an internal Clarity class `.datagrid-computing-columns-width`. It would be great to be able to use a CSS classname on the cells we'd like to clip its content on one row, e.g. `.clr-datagrid-single-line`. 

### Actual behavior
Using the `white-space: nowrap;` in a cell class makes the whole content displayed on one row, which brings the table width to a crazy size and brings the horizontal scrollbar.

### Reproduction of behavior
See plunkr: https://plnkr.co/edit/vNwP1lG2e6hFOyUiFR7x?p=preview

### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.9.8

* **OS and version:** 

* **Browser:** all

**Comment by clementcur** [comment]
@reddolan FYI

**Comment by mathisscott** [comment]
Barring information needed to prep this for contribution, I think this is an interesting solution to a use case we are getting bombarded with.

@reddolan and @yenmade , please check out the plunkr and share your thoughts.

**Comment by reddolan** [comment]
The plunkr looks good to me

**Comment by mathisscott** [comment]
@youdz 
Your thoughts on this?

**Comment by asual** [comment]
Should this also support column headers?

**Comment by youdz** [comment]
I was part of the initial discussion, I think it makes sense to add a class like this. We have to really document the use case though, specifically the expand/collapse to show the full text, because otherwise it will be misused everywhere.

The difference between using the class we provide and manually adding the styles to the cells on the app side is that:
1) The first solution will assume the text in cells will wrap when computing column sizes, so you will definitely have ellipsis... ellipsises... ellipses? It will also probably avoid horizontal scrolling.
2) The second solution will size columns with no text wrapping whatsoever, so you will not get an ellipsis unless you also specify a width for the column. Sometimes that's actually the behavior you want for certain types of data, a little horizontal scrolling is better than an ellipsis.

If we're clear on this, then implementing a class for the 1st case seems good to me.

**Comment by joshjohnson72** [comment]
Was discussing this with @jaffoneh and one suggestion was to possibly have a switch at the datagrid level to either support multi-line without truncation or to support single-line with truncation.

**Comment by mathisscott** [comment]
That's an interesting suggestion, @joshjohnson72 . But it doesn't help users who want ellipsized truncation in components other than the datagrid (which we have) and it also doesn't cover the edge case where a UI may want to allow text wrapping on some data grid cells but not _all_ of them.

A utility/helper class would give users that kind of flexibility. We would need to be specific about its use, however.

**Comment by amalo95** [comment]
any updates on this?

**Comment by mathisscott** [comment]
@amal94671 
This is not a near-term priority for us. It's a very small amount of CSS for users and there is still an open debate within our team as to whether it is something we want to support in the long-term

**Comment by mathisscott** [comment]
This issue is still available as a reasonably good first issue for contribution. We will not be prioritizing it because the CSS to implement it in an application is so minimal.

**Comment by gnomeontherun** [comment]
Due to the availability of workarounds and that apps can easily handle this on their end, I'm going to close this as not something we'll implement. There are also accessibility considerations to truncating text and I'm not confident we can standardize the implementation to satisfy both. Closing as best handled by applications.
