### ISSUE TITLE
Create a mixin to generate arrow position styles for Signpost's and Popover's

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1096]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

Currently Signposts and Popover's use an arrow to point to the trigger. We need to create a mixin that generats the correct classes for both to simplify the style code. 

There are twelve positions to handle
- `top-X`: the arrow will point down and the popover will be above the trigger in the X position where X = left, middle or right
- `bottom-X`: the arrow will point up and the popover will be below the trigger in the X position where X = left, middle or right
- `left-X`: the arrow will point right and the popover will be left of the trigger in the X position where X = top, middle or bottom
- `right-X`: the arrow will point left and the popover will be right of the trigger in the X position where X = top, middle or bottom

### These are the positions for Signposts:

1. top-left
2. top-middle
3. top-right
4. right-top
5. right-middle
6. right-bottom
7. bottom-right
8. bottom -middle
9. bottom-left
10. left-bottom
11. left-middle
12. left-top

**Comment by mathisscott** [comment]
@hippee-lee 
Could you provide more details here so that we can open this issue for contributions?

Things we would want to know:

1. Are we talking about a SASS mixin or something for the Angular component?
2. How are these currently represented in code? To give us the expected output of this mixin.
3. Ideally, how would you expect the end user to interact with this mixin? If no end-user interaction, what you want the integration with the existing code to look like?
