### ISSUE TITLE
[NG] Datagrid: offer two-way binding on the selected state of a row

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#111]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

We want two-way binding offered on the `<clr-dg-row>` component for its selected state. This would allow users to select items programmatically more easily, or keep up-to date with the current selection status:
```html
<clr-dg-row *clrDgItems="let item of users" [clrDgItem]="item" 
    [(clrDgSelected)]="item.selected">
    ...
</clr-dg-row>
```

### Actual behavior

Currently, the only way to do this is to grab the DatagridRow instance through template variables or ViewChildren.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.7.1

* **OS and version:** all

* **Browser:** all

**Comment by sivaah** [comment]
Can we reuse 'clrDgSelected' directive offered in <clr-datagrid> to select items programmatically? 

`<clr-datagrid [(clrDgSelected)]="selected">`

currently the selected property will get updated with the list of items selected. can we make this variable two way? so that any changes to that variable will reflect in the datagrid selection.

1. Push a record to **selected** to make the row selected programmatically.
`this.selected.push(items[0]);`
2. Delete a record from **selected** to make the row the unselected programmatically.
`this.selected.splice(2, 0)`

**Comment by youdz** [comment]
@sivaah: This is already the case, 2-way biding on `[(clrDgSelected)]` on the datagrid component itself works just like you described.

**Comment by sivaah** [comment]
@youdz, The selected state works fine once the grid is rendered / displayed data. If i add some records to "selected" to make one/some record selected initially that It doesn't work. 

In the following example, I'm pushing the first record to selected as soon as the data is fetched, to make the first record selected by default but it doesn't work.
```
<clr-datagrid [(clrDgSelected)]="selected">
    ...
    <clr-dg-row *clrDgItems="let user of users" [clrDgItem]="user">
     ...
this.users = [...];
this.selected.push(this.users[0]);
```

I will try to create plunkr and update this thread

**Comment by youdz** [comment]
No need to create the plunker, I understand where the issue comes from. I'll see what we can do to fix this. 👍

**Comment by Choko256** [comment]
Hello !
Same problem for me. No way to select items in the datagrid programmatically.
Edit the array bound to the clrDgSelected directive does not change anything in the grid.
Please help !
