### ISSUE TITLE
[DOCS] Add example for fixed-height datagrid

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#1137]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
We need to add an example for a fixed-height datagrid in the documentation. It should allow to show 2 cases:
- Not enough rows, the datagrid has empty space under the last row.
- Too many rows, the datagrid scrolls.

### Actual behavior
Currently, the only mention of this feature is in the release notes: https://vmware.github.io/clarity/news/0.8.10

**Comment by marztierney** [comment]
I also ran into this issue, having it in the data-grid documentation section would of made the process quicker.

**Comment by colinreedmiller** [comment]
I made a couple quick images to address this. The scrollbar is FPO since it is going to look different depending on the browser. Will these 2 or some variation of them fulfill this need? 

Shows std data grid at a fixed size of 368px in 2 cases:
1 with fewer rows than fills the container
Another other with more than can be displayed and a scrollbar

![Screen Shot 2019-02-11 at 3.47.45 PM.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/0f00fba3-4770-4057-8014-991165b3d350)![Screen Shot 2019-02-11 at 3.47.33 PM.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/6d5ba33d-4f62-4ee8-ba7f-ad32700e749f)
