### ISSUE TITLE
Problem with settings dropdown in header-actions

### ISSUE THREAD

**Issue by yuniors87** [vmware/clarity#115]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I want to add a settings dropdown in my header, inside the header-actions as you show in your examples.

### Actual behavior
The dropdown becames to button, does not show the list on click and the icons are superimposed.
BTW I used angular-cli seed to setup the project.

I'm either doing something wrong or this is a bug in clarity.

### Reproduction of behavior

This is the source code
https://github.com/yuniors87/Clarity.git
### Environment details

* **Angular version:** 2.1.0

* **Clarity version:*0.7.1* 

* **OS and version:*Windows 10* 

* **Browser:** [ Chrome 54]

**Comment by adityarb88** [comment]
Hi @yuniors87. I had some time to take a look at your code and I found 3 issues:

1. You are using the Angular Dropdown outside of the entry point of your application. You need to place your `main-container` inside of `app.component.ts`.

2. You are placing the caret icon before the settings cog.

3. You are missing the `.content-area` wrapper inside of the `.content-container`. This is unrelated to the main issue that you raised here but its required to render your application correctly.

Once you fix these 3 issues, everything should work fine. I already tested this on my local and since I had some time and wanted to check out Angular CLI, I created a PR that you can take a look at that over here: https://github.com/yuniors87/Clarity/pull/1

**Comment by yuniors87** [comment]
Yeah! the main problem was tha I was trying to put the hearder in the principal index file.
Thanks for your time!
