### ISSUE TITLE
DataGrid filters don't stay attached to the grid when other elements grow

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#1165]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The filter box remains stationary with respect to the filter icon

### Actual behavior
Before expanding the stack view with filter box open: 
![image](https://user-images.githubusercontent.com/7132414/27979673-8ede05f6-632c-11e7-93b8-72e2ede6fc3d.png)

After expanding the stack view:
![image](https://user-images.githubusercontent.com/7132414/27979657-67568c38-632c-11e7-82d6-551013f9fdde.png)

### Reproduction of behavior
https://plnkr.co/eQAeVIACzUf9kdpjaHoH

Open a filter box then expand the stack view above it.  

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** Chrome 59

**Comment by adityarb88** [comment]
@amellnik: Thanks for raising the issue. The plnkr you posted doesn't seem to work for me. Could you please check and repost?

**Comment by amellnik** [comment]
@adityarb88 -- whoops, I forgot to set it as public.  The link has now been updated.

**Comment by adityarb88** [comment]
@amellnik: Thanks. Will take a look and get back to you soon.

**Comment by mathisscott** [comment]
The UX recommendation is for the filter to move and remain in the same position relative to the filter icon. The actual behavior outlined in the above description is a bug.

**Comment by yaooluu** [comment]
The datagrid filter seems to be "pinned" to its initial position. There is also one case that user may resize their browser. Since the datagrid columns' width get adjusted automatically,  when more than one filters are open, they may end up staying under other column, which can lead to a bit of confusion:

<img width="1312" alt="screen shot 2017-10-03 at 7 12 21 pm" src="https://user-images.githubusercontent.com/8813134/31157305-d03ea53c-a86e-11e7-9a42-dfdeb0fdb5ce.png">

**Comment by Jinnie** [comment]
I can't reproduce this in v2 anymore:
https://stackblitz.com/edit/popover-in-dg-to-header?file=src/app/app.component.html

And the newer versions are using smart-popovers, which close popovers on container scroll events.
