### ISSUE TITLE
RTL Support CSS

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#1176]
```
[ ] bug
[ x] feature request
[ x] enhancement
```

Are you support Right-To-Left that useful for Arabic language. If doesn't support, it's possible to use Bootstrap RTL package for Clarity?

Thanks

**Comment by mathisscott** [comment]
@essivision 
The Clarity Team is in the early stages of its full support for internationalization. We do not offer any custom solutions for RTL languages beyond what is available in the browsers today. This is something that is on our radar, however, as we begin to ramp up our i18n support.

I'm leaving this ticket open so we keep it in mind for i18n.

**Comment by afshin-z** [comment]
Any update or roadmap? Is this going to be supported in Clarity 2?

**Comment by hippee-lee** [comment]
Support for rtl has not been prioritized at this time. I'm closing the issue because it has gone stale. 

However, we are open to contributions for this enhancement. Feel free to re-open the issue with a design/implementation proposal that addresses the library wide changes for `rtl` support for the affected components.
