### ISSUE TITLE
Modal API Documentation

### ISSUE THREAD

**Issue by taivu** [vmware/clarity#1179]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X ] enhancement
```
https://vmware.github.io/clarity/documentation/modals#api-reference
the bottom of the page says api and lists 2 methods, but show no examples on how to access modals through code.

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/modals#api-reference

Can some one point me in the right direction?

**Comment by youdz** [comment]
The reason we don't show example is because this falls into plain Angular documentation. There are many ways for you to get access to a Modal object, here are a few of them:
- Assign it to a template reference variable and use it somewhere else in the template: https://angular.io/guide/template-syntax#template-reference-variables--var-
- If the modal is in the template of the component that needs access to it, you can use `@ViewChild`: https://angular.io/guide/component-interaction#parent-calls-an-viewchild
- If the modal is projected into your component, you can use `@ContentChild`: https://angular.io/api/core/ContentChildDecorator

If you are not familiar with any of these, I heavily recommend you read the component interaction docs for Angular: https://angular.io/guide/component-interaction
The cases where you need actual access to the modal are rare, it's much easier to simply use the inputs and outputs we offer on the component.

**Comment by taivu** [comment]
thank you for a clear explanation!
