### ISSUE TITLE
clr-modal opened via @Input clrModalOpen binding change does not fire clrModalOpenChange

### ISSUE THREAD

**Issue by ledsusop** [vmware/clarity#1184]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
clr-modal should fire clrModalOpenChange when modal opens as a result of @Input clrModalOpen binding change

### Actual behavior
clr-modal does not fire  clrModalOpenChange when modal opens as a result of @Input clrModalOpen binding change

### Reproduction of behavior

https://plnkr.co/edit/drntSosaAjVVVMO4ChSe

### Environment details

* **Angular version:** 4.2.X

* **Clarity version:** 0.9.x

* **OS and version:** any

* **Browser:** all

**Comment by adityarb88** [comment]
@ledsusop: I don't believe that an `Input` should reemit the same value as an `Output`. The `Output` is only emitted when the binding changes based on a user action. For eg: User clicks on the backdrop or clicks on the `x` button on the top right of the dialog.

ccing @youdz to confirm.

**Comment by youdz** [comment]
Yes, I confirm 100%.
The output firing because of an input just creates a loop with 2-way binding (you can easily see it by using `@Input()` on a setter. It's a terribly inefficient behavior we really want to avoid.

You can check Angular's `ngModel`, you'll notice it doesn't fire `ngModelChange` when the `@Input` changes. We're following the same pattern.

**Comment by ledsusop** [comment]
Fair enough - I was expecting this explanation somehow and a loop can be avoided by using a different output - but that creates more confusion.  

Is it a good assumption to take then that the output only gets fired when the _open value is internally modified by the modal component as a result of direct interaction with it?     

Moreover, what will be a better approach for say, a directive, to know if the modal has been opened?

**Comment by zshlomyz** [comment]
Hi,
I looking for a way to run some code when a wizard is opened.
Looking at this issue, I found that I can't use the clrWizardOpenChange event for that.
I have tried doing by implementing the ngChange method and run a code when the open input changed.
The problem is that it caused the error - ExpressionChangedAfterItHasBeenCheckedError.
Any suggestion?

**Comment by gnomeontherun** [comment]
@zshlomyz Support questions should be posted to StackOverflow with the `vmware-clarity` tag, and provide an isolated sample of your issue for others to help. If you find an issue with Clarity itself (not just a question how to use it) then please open a new GitHub issue with an isolated reproduction of the issue for us to triage. It is difficult to answer questions without seeing a reproduction.
