### ISSUE TITLE
Datagrid, grouping rows by the value of a row

### ISSUE THREAD

**Issue by marvinosswald** [vmware/clarity#1203]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
I would like to give the user a option to group by values of a column, this makes huge loads of data way  more accessible without filtering first.

<img width="524" alt="screen shot 2017-09-13 at 17 33 44" src="https://user-images.githubusercontent.com/1621844/30386520-4a2fbb6c-98aa-11e7-8487-78d2af3dc728.png">

### Actual behaviour
Not implemented

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.9.14

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by reddolan** [comment]
@marvinosswald wouldn't sorting a column do what you are asking for? If not can you elaborate a little more on the problem you or the user is trying to solve with this?

**Comment by mathisscott** [comment]
@youdz 
Could you provide the feedback we discussed on this feature request?

**Comment by marvinosswald** [comment]
@reddolan 
Sorry for my late response, 

I've put together a little mockup in sketch:

<img width="524" alt="screen shot 2017-09-13 at 17 33 44" src="https://user-images.githubusercontent.com/1621844/30386280-bac3bc76-98a9-11e7-85b8-7aeac5556195.png">

In this example i lets say wanted to show all invoice positions this year grouped by its invoice numbers invoice number is a column on the invoice position table and thereby group able without filtering 

In its header it simply shows the value its grouping and something like a show / hide button
In its footer I imagine it would be possible to show some aggregation of the values in this column in that group. this should be customisable or maybe one standard sum aggregation and then overwrite able of sorts like the filter interface with data grids..

In a MVP the footer wouldn't be included I guess only the header would be a first step

**Comment by youdz** [comment]
My biggest problem with this is that it's incompatible with many core features of datagrid. What happens in your example when you sort on the Price column? Neither of the obvious behaviors makes much sense or would lead to something nice and usable for the user.

Same thing with pagination: do inner items count? If not, then some pages might be ridiculously long. If the do, then you might have groups spread over several pages, which is counterintuitive until you discover the behavior.

Filters do make sense, but I'm worried about introducing features that turn other features off, because that would start being very messy for the consumer.

**Comment by marvinosswald** [comment]
@youdz good questions, i would say that sorting would work in context to a certain group ? it would make sense to me at least if I would sort a set of data which is grouped by one parameter that the sorting is applied after the grouping. Only thing im not sure about is would it resort groups or not .. e.g.  I have one group with values [3,1,2] which is by invoice id the second group and a second group [5,4,6] which is the first if I sort asc should it only sort inside the groups or should it also sort the groups (if possible) I would vote for only inside groups I guess.

pagination is a problem I didn't thought about yet, you are absolutely right it would be counterintuitive at first but maybe you could counter that with a marker of sorts that there is a second part to this group ? not sure on this one.

**Comment by gnomeontherun** [comment]
Have you seen any real world examples that are similar to this idea?

My reading of this sounds like when you want to 'group by column' at that point you are actually talking about a different data set. You have a list of items and a list of invoices, which are being displayed together. Since there is a one to many relationship of invoices to items, you're looking for a way to 'group' invoices in the datagrid. 

My gut feeling is that you've really got two different user flows here and mixing them into one datagrid will cause tension. Either I'm looking at a list of items, or invoices right? What are your thoughts on the UX here for what users need to do when looking at two different lists?

**Comment by marvinosswald** [comment]
@gnomeontherun yes sadly I have seen a hardcopy of that functionality which made it a requirement by a stakeholder, in that case we are talking purchase transactions listed with a column invoice_id on the table. Now in that view what you are actually doing is kinda checking if the transactions are legit for that month or something. And I guess for ux reasons the transactions are grouped by invoice id.

**Comment by gnomeontherun** [comment]
Could you share this example? 

Often requirements can be adapted for better UX if we understand the real ask. It really just seems like you can sort first by invoice id and then by transaction id so they are grouped in the list, but without a 'collapsable group' feature which introduces a lot of UX questions.

**Comment by marvinosswald** [comment]
No sadly i'm not allowed to share it.

While you are basically right it adds a few more "functions":

_This list is sorted by it's priorities_
1. it calculates totals of columns of that group
2. it shows the "group" graphically as such
3. the expand / collapse button isn't that important in my opinion but ya it is so you can go through multiple groups without filtering first and collapsing these you are done with.

**Comment by reddolan** [comment]
We won't be doing this. This is not a datagrid feature. This could be something that we look at in the future as a stand alone component. The best way to work around this would be to export the data and manipulate in something like Excel.

**Comment by aihuasxy** [comment]
ag-grid have this feature.
https://www.ag-grid.com/javascript-grid-grouping/
