### ISSUE TITLE
Datagrid selection. Add 'event.stopPropagation()' to checkbox

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#1206]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ x ] enhancement
```

### Expected behavior

Selecting grid row with checkbox should stop event propagation.

### Actual behavior

Currently I have event bound to 'clr-dg-row' click that open new page with detailed view.
When selection checkbox clicked - row event triggered as well.

### Reproduction of behavior
https://plnkr.co/25RKqC0KOvPtpQWc8F0f

**Comment by adityarb88** [comment]
@ph55: Having a checkbox inside of a clickable row is not a recommended pattern because it is like having a button inside of a button which is not valid according to W3C. More info here: https://stackoverflow.com/a/39386695 & https://github.com/vmware/clarity/issues/476

Closing the issue based on this. Please feel free to reopen the issue if you have any additional questions or feedback. Thanks!

**Comment by hippee-lee** [comment]
@ph55 in addition to the feedback from @adityarb88 above we cannot add event.stopPropagation() to our components. Clarity components will never, ever prevent event bubbling. We make that guarantee so that users can be sure that Clarity users have access to any events generated in clarity components if they need it.
