### ISSUE TITLE
clr-tree-node bug on clr-modal

### ISSUE THREAD

**Issue by quetool** [vmware/clarity#1212]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

When I try to show a clr-tree-node inside a clr-modal nodes always appear expanded no matter if i set false on [clrTreeNodeExpanded]

**Comment by adityarb88** [comment]
@quetool: This issue does not follow our new issue template (https://github.com/vmware/clarity/issues/new). Please use the template, add a plnkr to replicate the issue: https://plnkr.co/edit/uNwwZe?p=preview and provide more info about the version of clarity, browser, OS that you are using in a new issue so that we have necessary information to debug the issue. Thanks!
