### ISSUE TITLE
Changing background colour of the responsive first level navigation drawer

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1230]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior

Setting a `background-color` to the `.header-nav.clr-nav-level-1` class in css should change the background of the navigation drawer only in potrait displays and should not change the background of the normal header links in full width displays

### Actual behavior

Setting the above css property is also modifying the full width header links

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/eRrLgZdTo4ywbhN9haAP?p=preview

### Environment details

* **Angular version:** 4.3.2

* **Clarity version:** 0.9.15

* **OS and version:** Windows 10

* **Browser:** [all]

**Comment by adityarb88** [comment]
@SayakMukhopadhyay: I am not exactly sure what the issue is over here. `.clr-nav-level-1` is always applied to the nav whether its in responsive mode or not. You need to make sure your style is based on when the nav is open or not. One solution is to apply class based on the `.open-hamburger-menu` class on the `.main-container`:

![image](https://user-images.githubusercontent.com/1426805/28757930-87ff1eaa-755b-11e7-89d6-166adf176b04.png)


Also, not related to this question, I noticed is that your layout is incorrect. `.content-area` should be a direct child of the `.content-container`. You need to make sure thats always true for the layout to work.

In this case, you should apply the `.content-area` class on `app-home`

![image](https://user-images.githubusercontent.com/1426805/28757948-d75e7e5a-755b-11e7-85a9-00f3c3e589b9.png)

**Comment by SayakMukhopadhyay** [comment]
Thanks using `.open-hamburger-menu` works. I used it like this in my code
```
.main-container.open-hamburger-menu .header .header-nav.clr-nav-level-1 {
    background-color: #076;
}
```
