### ISSUE TITLE
[Feature Request] List of planed component

### ISSUE THREAD

**Issue by gperdomor** [vmware/clarity#1245]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

Hi... Great work!

I see that some common components are missing, for example avatar, icon buttons, group buttons, timelines, accordion, media items, etc etc...

Do you have any roadmap for that?

**Comment by mathisscott** [comment]
Hi @gperdomor 

We actually do have [button groups](https://vmware.github.io/clarity/documentation/button-group)! But as for the other components, we have some in the backlog and some not. Specifically I don't think we have open issues for avatars and media items. Everything else there is pretty much already a github issue for.

As for roadmaps…

Anything we communicate would have the risk of changing dramatically in real-time. I can tell you what is actively being worked and I can tell you what is slated to be worked on following that.

For everything else, we have a very funambulistic planning process. One that is chiefly driven by our users both external and internal. If there is a component that is critical to your use case, the best path is to make us aware of that fact so we can adjust our priorities if we are able to do so at that time.

Given that a roadmap could be viewed as a contract of delivery, we are hesitant to share such a document because priorities shift frequently for us.

Thanks for the question and I hope my answer helped!
