### ISSUE TITLE
Resizing columns in datagrid causes other columns to change sizes as well

### ISSUE THREAD

**Issue by oliverhanappi** [vmware/clarity#1256]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When I resize one column, other columns should not change their size.

### Actual behavior

Given a data grid whose columns were sized to a specific content. When that content changes and one column is resized by the user, the other columns are adjusted to the new content:

![demo](https://user-images.githubusercontent.com/401938/28967605-3aa8f512-791c-11e7-924d-92f25c093301.gif)

### Reproduction of behavior

1. Create a data grid with some initial content
2. Update that content such that column sizes do not fit anymore
3. Resize one column
4. Observe that other columns are resized as well

Plunkr: https://plnkr.co/cKRZCyXzkwlhOea3YHuK

Instructions:
1. Press "Set Content" and observe that the new text is clipped because it does not fit anymore.
2. Resize a single column.
3. Observe that the other columns are stretched to fit the content.

### Environment details

* **Clarity version:** 0.9
* **Browser:** all

**Comment by mathisscott** [comment]
@oliverhanappi 
Thanks for the plunkr. It was very helpful. It appears that this only occurs after the content has been replaced and only with columns that have not already been resized. For example, if I...

1. Open the plunkr
2. Resize the second column (while it only has the "s" in it)
3. Then click "Set Content"
4. Then resize the first column

...the second column is _not_ resized.

However, if I follow your steps, the datagrid resizes _all_ columns but only _after_ I use "Set Content".

If I keep the original content ("s") in the cells, the datagrid does not exhibit this behavior.

I'm pinging @youdz to get an understanding of if this is an intended behavior and, if so, why...

**Comment by Shijir** [comment]
@oliverhanappi thanks again for the plunkr. 

So currently, If a column gets resized and gets a fixed width, other columns dynamically resize themselves to compensate the difference. But, at the same time, those other columns still take their cell contents into account as long as they are flexible-width columns. That's why in your plunkr, those columns respond to not only the size change of the resized column width but also their cell content changes.  So the solution could be that columns should no longer take their cell contents into account when they need to resize themselves to compensate the resized column.

**Comment by mathisscott** [comment]
@youdz

**Comment by youdz** [comment]
Actually, I believe the recommended pattern when you have such a huge change of cell content is either to:
1) manually trigger a column resize when the "large" data comes in. You can do this by accessing the datagrid with `@ViewChild`, and then calling its `.resize()` method.
2) Put a width in the CSS for the columns that drastically change sizes, that makes sense for the data you are trying to display. We will respect that width at all times.

Our column sizing assumes reasonably homogenous data for a given column. It's needed to try and give you smart columns width without knowing the semantic of the columns, otherwise we cannot possibly guess that a column that currently has 10 items with a 1-character text in them will grow to a full 500px wide non-breakable text. Also note that said 500px on non-breakable text is heavily against our recommendations, and we will not support it more than gracefully fallback to long horizontal scrolling (which is frustrating UX).

**Comment by oliverhanappi** [comment]
@youdz Thanks for your input. Can you give an example on how to specify the widths of individual columns?

Is there a way to specify the widths relative to each other (e.g., multiples) such that all columns consume the whole available space? E.g., I want the first column to get 25% of total width, the second 50% and the last one another 25%.

**Comment by amalo95** [comment]
Any updates on this?
