### ISSUE TITLE
Use any element as a trigger for a signpost,

### ISSUE THREAD

**Issue by plamens** [vmware/clarity#1257]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Any element can be used as a trigger for a signpost, not just the default info icon.

### Actual behavior
\<clr-signpost\> shows an info icon.

### Reproduction of behavior
All examples in the clarity documentation examples use an info icon as a trigger for the signpost.

### Environment details

* **Angular version:**
4.2.4

* **Clarity version:** 
0.9.12

* **OS and version:** 
Windows 10

* **Browser:**
All

**Comment by mathisscott** [comment]
@plamens 
Our recommendation is that icons be used to trigger signposts. Enabling _any_ element to trigger a signpost does not seem like a good option for usability. Do we really want someone to be able to click on an entire datagrid to open a signpost?

Is the request to be able to change the _icon_ being used? Or are you really wanting users to be able to click on paragraphs, form fields, list items, and anything else?

**Comment by plamens** [comment]
Any element actually. My current use-case is a memory usage visualization bar.
![memory_signpost](https://user-images.githubusercontent.com/1782459/28972701-4cbbb4f2-7939-11e7-9a6c-43aa7d31e0e2.png)

> Do we really want someone to be able to click on an entire datagrid to open a signpost?

Definitely no, but I won't go as far as saying that every use of a sign post next to something that is not an info icon is illegitimate. Also, having the ability to change the target would make it possible to use a different icon and resize it, even if it is still an info icon.

**Comment by mathisscott** [comment]
Thanks for clarifying your use case, @plamens 

I'll ping the UX team on this to get their input on it.

**Comment by youdz** [comment]
Actually, we are supporting this already in `0.10.0`. The release candidate is out, so you can try upgrading right now if you want. 

You just need to put your custom trigger with a `clrSignpostTrigger` attribute inside the `<clr-signpost>` component, like this:
```html
<clr-signpost>
    <clr-icon clrSignpostTrigger shape="avatar"></clr-icon>
    <clr-signpost-content *clrIfOpen>...</clr-signpost-content>
</clr-signpost>
```
We heavily recommend using icons for signpost triggers. If you absolutely cannot use an icon, please make sure your trigger does not have clickable children, we do not support it and it could lead to bugs (it's the usual "button inside a button" issue).

I am closing this since the feature already exists. :)

**Comment by plamens** [comment]
@youdz, Thank you!
