### ISSUE TITLE
Data Grid not sorting/filtering?

### ISSUE THREAD

**Issue by manndave** [vmware/clarity#1260]
**Select one ...**  (check one with "x")
```
[x ] bug?
[ ] feature request
[ ] enhancement
```

### Expected behavior
Using Smart Iterator, data grid will sort and filter.

This is a pretty obvious problem, so I'm reasonably certain that there's something I'm missing but I couldn't find anything in the documentation/samples that pointed out what I was doing wrong.

### Actual behavior
Sorting does not change the order of the items (although the sort-indicator arrow changes) and filtering hides all items no matter what I type in.

### Reproduction of behavior
Plunkr: https://plnkr.co/edit/dqfnTHxs7EJO2h2v6uW8?p=preview 

### Environment details

* **Angular version:** 4.3.3

* **Clarity version:** 0.10.0-rc.1

* **OS and version:** Win10

* **Browser:** Chromium 5x in Electron

**Comment by youdz** [comment]
You're using `[clrDgField]="'fact.first'"`, but `fact` isn't anything here (the local template variable `fact` is defined in another part of the template, for the iterator). What you want is `[clrDgField]="'first'"`, to indicate that the column corresponds to the `first` property of your items, that's all.

Note that our doc has an outdated comment about `[clrDgField]="'first'"` being better than `clrDgField="first"`. It turns out that it doesn't matter enough to be worth the extra pain of double quoting, so feel free to use the second syntax. We need to update our doc on this. 😅 

I updated your plunker to make it work: https://plnkr.co/edit/Tydzl0sXz6Lc4FBbkr1V?p=preview

**Comment by manndave** [comment]
I knew it was something stupid I was doing wrong.  :-)  Thanks.
