### ISSUE TITLE
Support bracket syntax for array properties in clrDgField

### ISSUE THREAD

**Issue by dpcamp** [vmware/clarity#1270]
**Select one ...**  (check one with "x")
```
[x] bug?
[ ] feature request
[ ] enhancement
```

### Expected behavior
Filtering should be able to work on columns that contains data along with undefined data. the undefined data has replaced with a placeholder (i.e. {{fact.last[0]? fact.last[0].first: 'Unassigned'}}) 

### Actual behavior
filtering does not work 

### Reproduction of behavior
https://plnkr.co/edit/4SWCzEEzeOxUHFBfoiYQ?p=preview

### Environment details

* **Angular version:** 4.2.0

* **Clarity version:** 
0.9.13
* **OS and version:** 
Windows 10
* **Browser:** All

**Comment by youdz** [comment]
`clrDgField="last[0].first"` is not a syntax we support. The field property accepts a dot-separated syntax for deep properties, but brackets are not parsed.

Note that if I replace it with `clrDgField="last.0.first"` in your plunker, it works again: https://plnkr.co/edit/3OHPCp1hoszrEAi8QF3J?p=preview

I'm marking this as a feature request since we could maybe support braket syntax, but it's really not a priority knowing there is a straightforward workaround.

**Comment by dpcamp** [comment]
I agree that workaround is definitely sufficient. Thanks for the reply!
