### ISSUE TITLE
Dropdowns have excessive spacing with large lists

### ISSUE THREAD

**Issue by mattmutt** [vmware/clarity#1278]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ x ] enhancement
```

### Expected behavior

1. many entries in the list, constrained by viewport => clipped content that is not accessible

![screen shot 2017-08-09 at 18 55 56](https://user-images.githubusercontent.com/8688570/29151195-6b61e90e-7d34-11e7-8a64-26e3b950aff5.png)

2. Other problems include dividers having excessive spacing and the internal padding within `.dropdown-menu` class and its top margin ( causes a slight gap )

<img width="697" alt="screen shot 2017-08-08 at 10 41 58" src="https://user-images.githubusercontent.com/8688570/29151434-eba9c996-7d35-11e7-885e-d7c7a245c40d.png">

### Actual behavior

Suggested fix: compensate by restricting height according to a natural container and letting the list overflow with scrolling. This can be done via CSS; however it is better if widgets commonly accept some type of constraint definition to aid when real estate is limited. This aligns better to responsive strategies.
![screen shot 2017-08-09 at 12 52 23 2](https://user-images.githubusercontent.com/8688570/29151204-7a08a06a-7d34-11e7-91d2-04c5b8a51e1c.png)

### Environment details

* **Angular version:** 2.0.X
4.2
* **Clarity version:** 
0.9
* **OS and version:** 

* **Browser:** [all ]

**Comment by youdz** [comment]
I think putting a maximum height by default on Dropdown is too problematic though.

But what we can do is let you, the consumer, set a max height to any dropdown in CSS depending on your own constraints, and we would make sure that the styles can handle it and that the dropdown menu would scroll. I think that would be the most flexible solution.

**Comment by mathisscott** [comment]
Per earlier discussion with @mattmutt 

This issues covers a few suggested enhancements/changes to dropdowns...

1) Tightening up the whitespace above and below dividers in a dropdown menu.
2) Tweaking the whitespace at the top and bottom of a dropdown menu such that it better matches the perceived horizontal whitespace on the sides and, incidentally, tightens up a bit.
3) Adjusting the placement of dropdown menus triggered from the header so that they appear closer to the bottom of the header.

and

4) Gracefully handling scrolling when a dropdown is to large to fit on a page. <= this may need to be part of the "collision detection" issue #1262 

@reddolan and @lil-kim : I support the top 3 suggestions from what I have seen of them. If one of you could advise on the edits, I'd appreciate it.

@youdz : Is number 4 a collision detection feature or something that can be accomplished with just CSS on our end?

**Comment by youdz** [comment]
If we have to detect that it doesn't fit, it's collision detection, yes.

**Comment by lil-kim** [comment]
@mathisscott, Will see what I can do.

**Comment by lil-kim** [comment]
Here's the spec for padding adjustments:
![image](https://user-images.githubusercontent.com/23196444/29223972-4eac639e-7e7d-11e7-9cff-86356e4784f0.png)
Reviewed & approved by: @mathisscott, @reddolan

**Comment by mattmutt** [comment]
when a dropdown is aligned to be on the bottom, there remains a 2px top margin inside `.dropdown-menu`. While tiny, it does expose  2 pixels of non active space between the target and the top edge of the popped up dropdown widget. What does this mean in simple terms? Dropdowns would not be flush to their target container.
