### ISSUE TITLE
Wizard navService - updateNavigation not handling when currentPage is removed

### ISSUE THREAD

**Issue by syndesis** [vmware/clarity#1283]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Wizard should only advance when "Next" button is pressed while using conditional steps

### Actual behavior
When navigating around the Wizard, sometimes it will advance when interacting with form controls and not the Wizard navigation.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/QIFHe8GyHhOWjkffBmKB?p=preview

1. Open the Wizard
2. Click the "ADD" button
3. Click "Next"
4. Click "Back"
5. Click "CHANGE" button
6. Click "ADD" button
7. Click "CHANGE" button

Observe that:
1. Wizard advances to page two automatically at this point
2. Page two should be hidden but is not

It looks like this is caused by `Wizard.ngDoCheck` calling `WizardNavigationService.updateNavigation`.  The latter finds the first incomplete page via `PageCollectionService.findFirstIncompletePageIndex` and sets it to the current page.  Perhaps a race condition because the page isn't removed yet before this check?

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.9.X

* **OS and version:** Windows 7

* **Browser:** Tested in Version 59.0.3071.115 (Official Build) (32-bit)

**Comment by mathisscott** [comment]
@syndesis 
I can't get your plunkr to work. I think there's an issue with unpkg or something happening there. Can you check and verify?

**Comment by syndesis** [comment]
@mathisscott It is working for me.. You may need to disable your ad blocking add-on for that page if you're using one. I think that happened to me as well.

**Comment by mathisscott** [comment]
@syndesis 
This issue isn't with the wizard. It's with how the form fields all point to `controls[requestOperation]` call is being used. It gets called for pretty much every input in the form and interestingly enough it can't get out of its own way in state management.

So using it to set the state on whether pageTwo is visible or not doesn't seem to be viable. I would recommend using/setting a flag keyed off the validation that doesn't require repeated calls to the same property. The problem is that your logic depends on the very last property to be set and if you don't reset them ever you'll get weird truthiness and falsiness.

See the console logs here for a dive into the issue...

https://plnkr.co/edit/iRUxObl6lgf7kVSMM4lE?p=preview

**Comment by syndesis** [comment]
@mathisscott I changed it to use a boolean which is set based on changes in the form and I still see errant behavior.  After going to page two and coming `BACK`, I can click, for example:
CHANGE -> REMOVE -> ADD
or
CHANGE -> REMOVE -> CHANGE
and it still switches back to page two.   Also, I don't know if this is important, but it won't switch to page two unless I go there and then go back.  Did I misunderstand your recommendation?  Plnkr:

https://plnkr.co/edit/seSAvSrv5e3HotO1tGRY?p=preview

**Comment by mathisscott** [comment]
@syndesis 
One good thing is that you're no longer firing a half-dozen checks everytime a button is clicked.

I'm having an issue with grasping what you want this thing to do, though.

Add and Remove both cause pageTwo to show. That seems like a logic issue to me. And Change causes pageTwo to hide.

Maybe you can walk me though the intended functionality and that will help assess if there are gaps in the logic of the host component?

**Comment by syndesis** [comment]
@mathisscott Sure, no problem.  

1. I would like Page Two to be visible in the navbar when either `ADD` or `REMOVE` are selected (that is not a logic issue in my case) and not visible in the navbar when `CHANGE` is selected.  This currently works fine before the user goes to Page Two and comes back, but not after.
2. I would like for the form to advance from Page One to Page Two when the `Next` button is clicked - not when clicking any of the radio group buttons.

What I'm experiencing instead:
1. After clicking `Back` on Page Two, selecting the `CHANGE` button in a pattern (e.g. `CHANGE` -> `REMOVE` -> `CHANGE`) causes page two to both be visible in the navbar and active when it should be neither.
2. After clicking `Back` on Page Two, selecting the `ADD` button in a pattern (e.g. `CHANGE` -> `REMOVE` -> `ADD`) causes Page Two to be visible in the navbar and active when it should only be visible in the navbar- the user should still be on Page One.

Please let me know if this was not helpful.
Thanks

**Comment by mathisscott** [comment]
@syndesis 
Thanks for the clarification.

For experience no. 1. 

There is some sort of logic issue there. I put a console.log in the forEach. The steps I followed were:
1. Open Wizard
2. Click 'Add' to make pageTwo show up.
3. Click 'Next' to go to pageTwo
4. Click 'Back' to go back to pageTwo.
5. Click 'Change' to make pageTwo disappear.
6. Click 'Remove' to make pageTwo show up again.
7. Click 'Change' to make pageTwo disappear (but instead pageTwo stays visible and the wizard advances)

Something is wrong with the logic on step 7. Given the console.log I added [here](https://plnkr.co/edit/CQs0Zr?p=preview), I would expect to see Add, Change, Remove, Change.

But I don't ever see that last "Change". Instead it looks like this...

![screen shot 2017-08-22 at 9 03 16 am](https://user-images.githubusercontent.com/2728359/29569522-5b6cd6fa-8719-11e7-9918-96d50b98bffd.png)

The call to `valueChanges.forEach` on `pageOneForm` is never receiving the last request for change. Once you have that figured out we can see if the advancing wizard is an issue.

For experience 2, I'm seeing the same thing. The last 'Add' is not being fired. 

My guess is that you are relying on validation and form values and that the way the value is being checked isn't gelling with radio buttons. You seem to be relying on requestOperation _not_ having a value to prevent the form from being submitted (and potentially advancing the wizard). But the problem is that a radio button group would pass validation whenever any of its radios is selected.

Just my SWAG on it.

**Comment by syndesis** [comment]
@mathisscott 
When I add the same debugging line to my real application (outside plunkr) I see the forEach being called every time.  
When I add a breakpoint to forms.umd.js line 2725 in the plunkr, I also see the console log every time as well which leads me to believe that my original conjecture about a race condition might be correct.

**Comment by syndesis** [comment]
@mathisscott ok, I think I found the root problem.  I believe the forEach issue you found is just a side effect of the actual problem (the wizard advancing) but that's a difficult one to track down.  I can reproduce a similar issue on your demo page as follows:

1. Go to https://vmware.github.io/clarity/documentation/wizards
2. Click the "SKIPPING A PAGE IN THE WIZARD" button (side note: this may open the wrong wizard the first time.. you can close it and click the button again to get the right one)
3. Click "SHOW PAGE 2"
4. Click NEXT
5. Click BACK
6. Click HIDE PAGE 2
7. Click SHOW PAGE 2

Observe that you are now on page 3 and page 2 was not shown.  Looking at WizardNavigationService.updateNavigation(), we see:

```
public updateNavigation(): void {
        let toSetCurrent: WizardPage;
        let currentPageRemoved: boolean;

        this.pageCollection.updateCompletedStates();

        currentPageRemoved = this.pageCollection.pagesAsArray.indexOf(this.currentPage) < 0;
        toSetCurrent = this.pageCollection.findFirstIncompletePage();
        this.currentPage = toSetCurrent;
}

```

Notice that `currentPageRemoved` is set but never used.  I believe we should be doing:

```
    currentPageRemoved = this.pageCollection.pagesAsArray.indexOf(this.currentPage) < 0;
    if (currentPageRemoved) {
        toSetCurrent = this.pageCollection.findFirstIncompletePage();
        this.currentPage = toSetCurrent;
    }
```

This seems to fix my issue but my old OS is making it difficult to run the unit tests.

**Comment by mathisscott** [comment]
@syndesis 
Wow. I think you're correct there. I'll reopen this as a bug.

Thanks for tracking this down!
