### ISSUE TITLE
Error position drowpdown - clrMenuPosition

### ISSUE THREAD

**Issue by cripolgon** [vmware/clarity#1285]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Dropdown should be show on the left.
![image](https://user-images.githubusercontent.com/15108191/29205073-ed8cd942-7e7a-11e7-941c-0505c87e16ad.png)

### Actual behavior
Dropdown is always showed on the right. This is my code:

```
<clr-dropdown clrMenuPosition="bottom-right" [clrCloseMenuOnItemClick]="false" role="menu">
            <button class="nav-icon" clrDropdownToggle aria-label="Opciones" role="button">
                <clr-icon shape="user"></clr-icon>
                <clr-icon shape="caret down"></clr-icon>
            </button>
            <clr-dropdown-menu clrMenuPosition="bottom-left">
                <a clrDropdownItem (click)="openModalEmail(true)">Enviar mensaje</a>
                <a clrDropdownItem>Preferencias</a>
                <a clrDropdownItem (click)="logout()">Salir</a>
            </clr-dropdown-menu>
        </clr-dropdown>
```
![image](https://user-images.githubusercontent.com/15108191/29205046-c4f8d634-7e7a-11e7-85d0-4f5d4ba9909a.png)

### Environment details

* **Angular version:** ^4.3.4

* **Clarity version:** ^0.10.0

* **OS and version:** Arch Linux 

* **Browser:** all

**Comment by mathisscott** [comment]
@adityarb88 ^

**Comment by adityarb88** [comment]
@cripolgon: I am not sure if I understand your question correctly. Could you please provide a plnkr? Plnkr template: https://plnkr.co/uNwwZe
 Your code snippet looks incorrect because I see that you are using 2 direction Inputs. One on the `clr-dropdown` and one on `clr-dropdown-menu`.

Please note that the dropdowns API has changed since we had a breaking change in dropdowns in 0.10.0. Please refer to this release notes for more info: https://vmware.github.io/clarity/news/0.10.0-rc.1

Regarding the direction classes, if you are trying to use `bottom-left` for dropdowns in the header the dropdown should render correctly but it will be clipped off by the screen. Our UX team recommends that you use `bottom-right` direction for dropdowns in the `.settings` section in the header.

**Comment by youdz** [comment]
Your code hasn't been updated to the new API in `0.10.0`. The dropdown menu is the one who now takes a `clrPosition` input:

```html
<clr-dropdown [clrCloseMenuOnItemClick]="false" role="menu">
    <button class="nav-icon" clrDropdownToggle aria-label="Opciones" role="button">
        <clr-icon shape="user"></clr-icon>
        <clr-icon shape="caret down"></clr-icon>
    </button>
    <clr-dropdown-menu clrPosition="bottom-left">
        <a clrDropdownItem (click)="openModalEmail(true)">Enviar mensaje</a>
        <a clrDropdownItem>Preferencias</a>
        <a clrDropdownItem (click)="logout()">Salir</a>
    </clr-dropdown-menu>
</clr-dropdown>
```
