### ISSUE TITLE
Alerts component documentation

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1287]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Actual behavior

I don't know if that's intentional but I think the error alert should be in red color:
![image](https://user-images.githubusercontent.com/1977391/29221072-f9734f64-7eef-11e7-9ae9-ed481babcaeb.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@whizkidwwe1217: Thanks for raising this issue. It's definitely a bug. Will get it fixed soon.

**Comment by whizkidwwe1217** [comment]
@adityarb88 Thanks. I think it's not just the doc but also the component itself.

**Comment by adityarb88** [comment]
@whizkidwwe1217: I don't believe thats the case. For eg: this renders fine in the documentation:

![image](https://user-images.githubusercontent.com/1426805/29221331-5e444808-7e8c-11e7-9c40-7b04910cbcc4.png)

We just need to fix that instance of the alert. I think its using type `error` instead of `danger`
