### ISSUE TITLE
Data Grid Selection checkbox ID manualy

### ISSUE THREAD

**Issue by ipchaube** [vmware/clarity#1290]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Expected to assign manual ID to all check box according to the user need. SO that can be able to trigger check and un-check manually by ID.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
I'm sorry, I do not understand the feature request here and you provided very limited information.

Could you post a plunker of what you are trying to do, or describe in more detail the feature you are requesting? Thank you.

**Comment by ipchaube** [comment]
In to the datagrid, selection feature with checkbox. If I wants to check any of the check box dynamically (Not by clicking checkbox) by clicking a button outside of datagrid how i can do this.

Hope this information is sufficient.

**Comment by youdz** [comment]
We already have this feature in our documentation, see https://vmware.github.io/clarity/documentation/datagrid/selection.

> If you need an easier access to the selected state of a row, without having to go through the entire array, we also provide a boolean `[(clrDgSelected)]` two-way binding on the `<clr-dg-row>` itself. For instance, when your model itself tracks if items are selected, you can simply write:
>```html
><clr-dg-row *clrDgItems="let item of items" [clrDgItem]="item" [(clrDgSelected)]="item.selected">
>    <-- ... -->
></clr-dg-row>
>```


In other words, our datagrid rows accept a `[clrDgSelected]` input to dynamically select them.

**Comment by ipchaube** [comment]
If i want to check a checkbox by user name through ts script, how I can do that?
Example
public checkBox(name) {
// Check a checkbox by name or ID
}

**Comment by youdz** [comment]
That's up to your own model and architecture, at that point. You could keep the selection property on the model itself, you could keep a separate array of selected users, ... Once again, you're giving us no information on you app here. A plunker would go a long way.

**Comment by ipchaube** [comment]
Please find plunker below
https://plnkr.co/edit/sExZOcEW3SGaXuCvoGJD?p=preview

Their is checkElementInTable(id) method in table service by clicking button check box should be checked which row has ID =2.

**Comment by youdz** [comment]
I'm sorry, I can't make sense out of this example. You're trying to put the `checkElementInTable(id)` method in the service, which has nothing to do with the table. The table component has a button that calls this method, but the component _doesn't_ have the method.

Even if the goal was to put the method on the component, you have a "read-only" observable in the service for selected items, so that observable is always going to be out of sync with the actual items selected by the user. Which one is it?

Anyway, you're already doing something exactly identical in the service with the `filter()` thing.
Just do the same in the component itself: https://plnkr.co/edit/FwKECjdO3z6eqbgDGdIy?p=preview
But as I said, this example and the one-way binding on selection makes no sense, you're going to have bugs everywhere.
