### ISSUE TITLE
*ngIf on clr-tab affects default tab

### ISSUE THREAD

**Issue by MRamos62786** [vmware/clarity#1318]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I would expect the first tab that has an *ngIf that doesn't evaluate to false to be the default tab.
### Actual behavior

*ngIf affects the default tab. Though there is a work around.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/FpCzerJ6lqVpS9u1ObyM
Note that second tab is defaulted when run.
Work around is adding *ngIf="true" to all tabs
### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
That's a tough one. When you use the pattern in your plunker, Angular actually instantiates the second tab first because `*ngIf` happens later in the lifecycle of your app component.

I would like whoever handles this to just try moving the "default tab picking" to `ngOnInit()` as opposed to the constructor. I think that should be enough.

**Comment by mathisscott** [comment]
@youdz 
@adityarb88 tried your suggestion and it didn't work. Adjusting estimate accordingly.

**Comment by Shijir** [comment]
Closed by #1514
