### ISSUE TITLE
Pagination component re-design

### ISSUE THREAD

**Issue by koso-cocoloco** [vmware/clarity#1384]
```
[ ] bug
[ x] feature request
[ x] enhancement
```

### Expected behavior
We are designing a new data grid component as part of the new DellEMC clarity.
The new pagination component functionality would have some new UX changes and requirements:
1. Rows per page drop down selector ( e.g 10, 20, 100 rows per page)
2. an input field for navigating into a specific page by entering the page number and pressing enter.
3. next and previous page navigation buttons <>

![image](https://user-images.githubusercontent.com/18193178/29808374-7e06d300-8ca0-11e7-91d8-9d2d8dc5f41d.png)

### Actual behavior
See Data grid navigation page https://vmware.github.io/clarity/documentation/datagrid/pagination 

![image](https://user-images.githubusercontent.com/18193178/29808367-757a5f72-8ca0-11e7-8c40-91549a078279.png)

**Comment by mathisscott** [comment]
@koso-cocoloco 
Thanks for sharing this. We would not want to support two different datagrid footers in Clarity. So what we need to do is take a look at this proposal and identify the pros/cons and decide if this is what we would want Clarity to do.

@youdz and @reddolan : What are the benefits of this approach over the current datagrid pagination? Is this an improvement we want to adopt in Clarity?

CC: @jaffoneh

**Comment by TekSiDoT** [comment]
While this looks more like an extension than an overhaul, these elements are an important part to a complete datagrid component. Their addition would be extremely welcome.

**Comment by mathisscott** [comment]
@TekSiDoT 
Thanks for the feedback. Given that we should ideally promote the best UX possible for the datagrid pagination, it does not follow that we would want to support two different UIs for the datagrid footer.

Our immediate task is figuring out on our end what our recommendation is and then taking action following that.

**Comment by youdz** [comment]
From what we have and what's requested here, I would like to split this into 2 feature requests:

1. Making the current page an input, to be able to jump to a specific page number just by typing it. We will probably stick to the `1 ... n-1 n n+1 ... 40` format rather than `1 of 40`, but making the current page an input is perfectly valid.
2. Offering a component for page size selection. This needs to be opt-in, we cannot have it by default, because many apps don't want the datagrid suddenly doubling size or worse. One thing to note, though, is that it's pretty easy to write such a component yourself until we have one. Here is a quick example of how you could do it: https://plnkr.co/edit/mCS0mzwc2VhT0cH1qACd?p=preview
(Note that you will run into the cosmetic issue #1084 when reducing the number of items per page, but we're working on that right now).

**Comment by reddolan** [comment]
I agree. We have discussed redesigning it to address spacing and interaction issues.

**Comment by talolierwork** [comment]
Hello clarity guys, I have a ux question regarding the pagination bar (in https://vmware.github.io/clarity/documentation/datagrid/pagination)

When using it, we got complains that the ux experience can be enhanced if the “<” and “>” will be shown even when the data-grid is displaying the first and last page, and will be disabled instead of hidden creating a less “jumpy” and more smooth pagination between the different pages.

WDYT? 
Is that something you have in your future plans? (maybe heard before?) If not, maybe there is a way I can override it within our css - any idea how this can be done without forking your code (if any)?

--Tal

**Comment by talolierwork** [comment]
From an answer I got back I've learned that < and > are removed from the DOM with an `ngIf` — not hidden with CSS, therefore there is no css override I can use to solve it.

**Comment by talolierwork** [comment]
and another one from the not so long past

Hello clarity guys, I have a small question regarding `Server-Driven datagrid`
I notices that when I have 38 pages I get the following pagination bar:
``` 1 2 ... 38 ```
My question is this:
Can I control the amount of number of page numbers shown, I’d like to get 10 pages before getting the “…” e.g.:
``` 1 2 3 4 5 6 7 8 9 10 ... 38 ```
And when I press page number 10, I want to see
``` 10 11 12 13 14 15 16 17 18 19 20 ... 38 ```

I looked into datagrid-pagination.ts and it looks like hard coded value:
``` <li *ngIf="page.current < page.last - 2">...</li>
            <li *ngIf="page.current < page.last - 1">
```

Maybe I am looking at the wrong place or maybe there is plan to add it in the future?

**Comment by reddolan** [comment]
@talolierwork thank you for sharing this feedback, it's helpful. We will review it when we begin working on it

**Comment by tarquinrex** [comment]
The pagination component is very convenient however there should be a way to create a custom pagination component as well. Lets say I want to show pagination above the grid that follows a certain theme or style it would be great if I could hook into the grids pagination mechanism.

**Comment by gnomeontherun** [comment]
This needs some focus on the specific deliverable. It is possible to create the pagination experience outside of Clarity, which isn't ideal but can solve the needs if they are urgent in the interim.
