### ISSUE TITLE
DataGrid - server side selection not working with pagination

### ISSUE THREAD

**Issue by lohiaad** [vmware/clarity#1393]
[x ] bug
[ ] feature request
[ ] enhancement

### Expected behavior
datagrid should retain selection from previous page while paginating 

### Actual behavior
should retain selected rows of previous pages while navigating

### Reproduction of behavior
Step 1 - Select any row from page 1 of data grid
Step 2 - go to page 2
Step 3 - go to page 1 (step 1 selected row is deselected)

https://plnkr.co/edit/wnEUkRcVcFeNLdTyfrk6?p=preview

### Environment details

* **Angular version: 4.0.X

* **Clarity version:0.9.x

* **Browser: Chrome

**Comment by youdz** [comment]
The solution to this is normally to use the `trackBy` option for `*ngFor` (see https://angular.io/api/common/NgForOf), which we support. It works fine for selection + client-side datagrid, it also works fine for not re-rendering rows on server-driven datagrid, but we do have a bug with selection + server-side.

Just know that when we fix the bug, you will need to use `trackBy` anyway to get the behavior you want, since the objects you give us are recreated every time.
