### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError has been thrown in Wizard

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#1439]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

No ExpressionChangedAfterItHasBeenCheckedError.

### Actual behavior

It could be replicable in our demo app on `http://localhost:3000/wizard/stop-navigation`. Also, it's visible on our website, but only in the dev mode.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
Tracking the source of this as a race condition with calling the wizard navigation service. The buttons are projected into the wizard footer, but since they are declared (and rendered) they set an internal state before the pages of the wizard are setup (which happens afterContentInit). So the previous button throws this exception because it tries to figure out if the first page equals the current page, but it is rendered before the page-collection service knows about the pages.
