### ISSUE TITLE
Alerts overflowing bounds

### ISSUE THREAD

**Issue by dcoblentz** [vmware/clarity#1445]
**Select one ...**  (check one with "x")
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If a div containing an alert goes below a certain size, the contents of the alert should not overflow it's boundaries

### Actual behavior

An alert in a narrow container overflows it's bounds, particularly if it contains an alert-action. On smaller screens, the alert action drops down to a separate line, but a small container in a large screen will show the issue.

https://plnkr.co/edit/3NZaILPsSNHRGx1FTa07?p=preview (increase the size of the preview frame to see the issue)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

See above link, created with 0.10.4.

### Environment details

* **Angular version:** 4.4.0-RC.0

* **Clarity version:** 0.10.4

* **OS and version:** Windows 10

* **Browser:** Tested in Chrome

**Comment by mathisscott** [comment]
Thanks for the plunkr, @dcoblentz !

This issue is with how the alert is using `flex-wrap: no-wrap` to force the alert not to wrap at larger sizes.

We may want to consider using CSS Grid instead of flexbox for this. Or figure out a different way of handling layout inside alerts.

I think this can be fixed without a breaking change but there _is_ a risk that the DOM structure may need to be modified (which would be a breaking change).

**Comment by adityarb88** [comment]
We could also add `word-break: break-all` on `.alert-text`. It would then look like this:
![image](https://user-images.githubusercontent.com/1426805/30216220-4384d64a-9480-11e7-8fec-c6f2317a356e.png)

This is not ideal but having alerts in such small containers is an edge case i believe. So this could be an acceptable solution.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
