### ISSUE TITLE
Class "required" for clr-stack-label

### ISSUE THREAD

**Issue by civanova** [vmware/clarity#1449]
Allow usage of class `required` for clr-stack-label component.
In case we have an input field in the content of the stack block
and that input is required we would like to add an * to the label 

**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
When setting class `required` on element clr-stack-label to see a red * next to the label

### Actual behavior
<img width="887" alt="screen shot 2017-09-11 at 3 21 08 pm" src="https://user-images.githubusercontent.com/26875277/30274193-fdcf45b8-9704-11e7-9f6e-e35a482a1615.png">

### Reproduction of behavior
https://plnkr.co/edit/Unu7FO9a4vaAuWH8j4tc

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** latest

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@youdz ^

**Comment by youdz** [comment]
I see two issues with this request:

1. UX or a11y (I don't remember which side) told us to stay away from asterisks to denote required fields. I don't believe we have a final design yet, though.
2. There is no correlation between forms/inputs and stack view. Sure, maybe you are using stack view to display inputs, but we shouldn't bloat the API of our components to support every combination of them, because users would then spend hours trying to figure out what they want to do. Styling required rows is something that you should be able to do very easily by adding a line or two in your own CSS. Here is an example using your plunker: https://plnkr.co/edit/lAqGwhidK0YvnFGzZ0n1?p=preview

I'm closing this issue because of 2.
