### ISSUE TITLE
Datagrid. Using both 'Batch action' and 'Single row action' - order

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#1470]
**Select one ...**  (check one with "x")
```
[ ] bug
[ X ] feature request
[ ] enhancement
```

When using batch actions with single row actions - the order seems to be not correct from UX perspective.
Single row action should be first in order.

### Expected behavior

![image](https://user-images.githubusercontent.com/1386622/30442559-7d4379c2-9985-11e7-9011-322486726584.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/1386622/30442665-bef59c9c-9985-11e7-9b34-6ef7ad640847.png)

**Comment by mathisscott** [comment]
@ph55 
Could you provide us with [a plunkr](https://plnkr.co/edit/uNwwZe?p=info) to help diagnose the issue? It's hard to say what is going on with the screenshots.

**Comment by youdz** [comment]
@mathisscott: I believe @ph55 would like the order of the checkmark and vertical ellipsis to be reversed. It's currently checkmark first, and he would like ellipsis for actions first.

Marking this as a UX question/issue.

**Comment by mathisscott** [comment]
Oh. Yes, I believe you are correct @youdz 

The common standard is for the checkbox to be farthest left on datagrid rows. This is not something that we would recommend or allow users to configure.

You are in luck, however, @ph55. Because there is an easy CSS change you can make to a datagrid to move the single row actions to the far left. I've created [a plunkr to show you how to do it](https://plnkr.co/edit/1A9q2G?p=preview). The relevant CSS is in index.html and should be easy to port over to any datagrid in your application.

This is not a configuration option we would add to Clarity, though. So the workaround will have to suffice.

**Comment by ph55** [comment]
Thanks for everyone.
@mathisscott thank you, I appreciate it.
