### ISSUE TITLE
When do you want to release version 1.0.0

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#1481]
Hi,
Thanks for useful library. When do you want to release version 1.0.0?

Thanks

**Comment by sebitsi** [comment]
Hi @essivision. Good question.

I'm following developement nearly year.
It is great and has great potential. And i like it very much.

Now it looks developement is slowing down.
What is going on ? Is this the end ?

**Comment by mathisscott** [comment]
@essivision 
We continue to work towards our 1.0 backlog each week. If there is a perceived delay, it is because:

a) as we've pushed towards stability we are solving harder problems
b) our priorities are required to shift in real time due to the number of stakeholders we support through both VMware and Dell
c) the few remaining components we want to complete before 1.0 are complicated and are going to take us a while to complete

We are getting close to 1.0 now. But still months away.

Our 0.x releases are historically very stable, however, and our 1.0 efforts thus far have only made them moreso. So Clarity being pre-1.0 should not dissuade anyone from using the library.

Thanks.

**Comment by mathisscott** [comment]
@sebitsi 
I'm confused. We've been doing _weekly_ releases for the last 11 months. What is "slowing down"?

> What is going on ? Is this the end ?

This seems a little dramatic?

**Comment by boemska-nik** [comment]
I'll just leave this here http://www.timqian.com/star-history/#vmware/clarity

**Comment by sebitsi** [comment]
@mathisscott 

Hello, Scott. My intention was not to dramatize.
You are doing a very good job. And only this is important.

I just noticed (git insight) that average commits per week on master branch is sliding down 
(frrom over 10 in 1Q and 2Q to cca. 5  in last 3Q) 

That's why I asked this question.

**Comment by mathisscott** [comment]
@sebitsi 
😂  It's fine.

As mentioned above, the components we have left to do in 1.0 and the issues we are working to fix are more complicated than many of our issues a year ago.

Creating button styles is a lot easier than building a fully functional datagrid. Rearchitecting and stabilizing across multiple components while trying to limit breaking changes is a lot harder than creating a modal component.

Thanks for checking in though!

**Comment by sebitsi** [comment]
You are welcome 👍 

Just a little question. Is Roadmap (projects:  https://github.com/vmware/clarity/projects) updated ?
For example: "Upgrade to angular 4" has status "Done". This is released already. Isn't it ?

**Comment by mathisscott** [comment]
Yes we've already updated to angular 4.  that project board isn't 100% up-to-date. I'll have it up today tomorrow though.

**Comment by sebitsi** [comment]
Cool. Please let us know when update will be done.

**Comment by mathisscott** [comment]
Update was done yesterday before I left for the day.

**Comment by sebitsi** [comment]
Sorry, but only change i can see is update date.
Upgrade to angular 4" still has status "Done". 

What about other projects ? DataGrid project was updated on 12nd april. 
Is this correct ?

**Comment by mathisscott** [comment]
I'm sorry. I'm confused.

"Upgrade to Angular 4" _is_ done. So, why shouldn't it have the status of "Done"?

Other projects have not been updated. Thanks for pointing that out. I have a full day of meetings but will try to update them either today or tomorrow.

**Comment by sebitsi** [comment]
Sorry to me to bothering you with this minor things.

If working items can have "released" status, what is difference between "Done" and "Released".
In before mentioned example ("Upgrade to Angular 4") I has expected "Released" status.

If i can give you another example: In same project there is "[icons] Improved Documentation" with status 
"Done" - not "Released". What that mean ? Ok. You done your work. But i don't know if impoved documentation is published or not. If it has status "Released" everything will be much more cleaner.

Anyway regards for all work !

**Comment by mathisscott** [comment]
Ah. That makes sense. Yes, it makes no sense to have a Done and a Released column as things are generally released when they are done and still in progress when they haven't been released.

I will fix that as well. Thanks!

**Comment by mathisscott** [comment]
Updated!
