### ISSUE TITLE
Why does form-group class have a large left-padding?

### ISSUE THREAD

**Issue by hrantbagdasarian** [vmware/clarity#149]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I'm actually not sure if this is a bug, but I would like some clarification about the form-group class. 
I would expect the elements inside a form-group to be pushed to the left, but it has a default left-padding of 228. 

### Actual behavior
Elements don't align to the far left.

![form-group-example](https://cloud.githubusercontent.com/assets/5950625/20609224/f0227288-b289-11e6-9cf7-a4b867182a95.PNG)

### Reproduction of behavior
```
<div class="row">
    <div class="col-lg-12 card">
        <form class="compact" [formGroup]="viewForm">
            <section class="form-block">
                <div class="form-group">
                    <div class="radio-inline">
                        <input type="radio" id="grid-view" value="grid" name="view" formControlName="view">
                        <label for="grid-view">Grid</label>
                    </div>
                    <div class="radio-inline">
                        <input type="radio" id="list-view" value="list" name="view" formControlName="view">
                        <label for="list-view">List</label>
                    </div>
                </div>
            </section>
        </form>
    </div>
</div>
```

### Environment details

* **Angular version:** 2.2.3

* **Clarity version:** 0.7.2

* **OS and version:** Windows 10 Pro x64

* **Browser:** Chrome 54.0.2840.99 m [(64-bit)]([url](url))

**Comment by adityarb88** [comment]
Hi @hrantbagdasarian. By default, we do this to add space for the label for the form field since the label use `position: absolute` in form which are not used inside of grids. This is for users who want the most basic form with a simple  markup in which the label doesn't wrap. For more complicated forms we recommend you use forms inside of grids because it can accommodate almost any case.

By looking at the screenshot that you posted, it looks like you are not using a label to describe the what the `.form-group` is. Clarity recommends that you use a label to describe the `.form-group`. But if your application requires you to handle this case, I would recommend that you use forms in grids. Its documented here:
https://vmware.github.io/clarity/documentation/forms

I am closing this issue now but feel free to reopen it if you have any feedback or suggestions for handling this use case.
