### ISSUE TITLE
Tree view - Filtering

### ISSUE THREAD

**Issue by cripolgon** [vmware/clarity#1507]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
![image](https://user-images.githubusercontent.com/15108191/30818100-eb4de02c-a21a-11e7-99fc-72e4b45add85.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/15108191/30818134-ffab1170-a21a-11e7-94bd-c23173733e51.png)

### Environment details

* **Angular version:** 4.4.3

* **Clarity version:** ^0.10.5

* **OS and version:** 

* **Browser:** all

**Comment by adityarb88** [comment]
@cripolgon: Thanks for submitting the request but could you please provide more details on what exactly should this feature should do? I see that you have provided an image with a text box on top of the tree view in which you can type and probably filter the nodes that are in the tree view but its always better to provide detailed descriptions along with images for feature requests. This ensures that we evaluate all possibilities and don't make any assumptions or miss any details on our side.

Assuming that we provide this feature, the tree nodes in our tree view are always lazily loaded, so it will only filter the nodes in the DOM and I am not sure if that will provide much value. Also, I believe this can be achieved at your end by filtering the data you are using to render the TreeView, no?

Please let me know if I am missing something.

cc: @youdz

**Comment by cripolgon** [comment]
Hi @adityarb88. Thanks for your response. I would like that the filter updates the data which is showed, not only hide it. If I click in a checkbox of a filtered tree and then I remove this filter, the others nodes shouldn't be selected. Besides, I want the tree in my state (I use ngrx) the selected checkboxs.

**Comment by mathisscott** [comment]
@youdz ^

**Comment by youdz** [comment]
The behavior you want seems very specific to me, enough so that it might not make sense to have it in Clarity.

For instance, if you take a folder and files tree like the one we have in the documentation:
```
Home
    Documents
        Document1.txt
        Document2.txt
        Document3.txt
    Pictures
        pic1.png
        pic2.png
        pic3.png
```
If I search "Pictures" and then click on the Pictures folder, I obviously expect it to select all the files inside, not just the ones that were coincidentally also named "Pictures".

In addition to that, if you generate your tree nodes with an `*ngFor` (which seems to be the 99% case), then implementing the filter feature you want isn't very complicated to do on the app side.

I'm closing this, feel free to ask questions on StackOverflow if you need help building your feature.
