### ISSUE TITLE
Datagrid clrDgItems index on pagination

### ISSUE THREAD

**Issue by abelkbil** [vmware/clarity#1534]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
How to create a client side serial number indexing in Datagrid

### Actual behavior
On `*ngFor= "let item of items; let rowIndex = index"` will be working, here since we have pagination of 20 items, I dont know how to handle this.

### Reproduction of behavior
```
<clr-dg-row *clrDgItems="let item of items; let rowIndex = index">
        <clr-dg-cell>{{rowIndex+1}}</clr-dg-cell>
       <clr-dg-cell>{{ item.name }}</clr-dg-cell>
</clr-dg-row>
```

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.10.5

thnaks

**Comment by mathisscott** [comment]
@abelkbil 
Why don't you use an id generator in your host component?

**Comment by abelkbil** [comment]
@mathisscott Sorry I didnt get your concept. My intention in to print serial number for a paginated datagrid. The code mentioned above works fine for first page, second page on wards it will start again from 1. 

Should I have to listen pagination and multiply by limit or any other professional logic ?

thanks

**Comment by adityarb88** [comment]
@abelkbil: Please provide a plnkr which replicates the issue for us to investigate. Thanks! Plnkr template: https://plnkr.co/uNwwZe

**Comment by abelkbil** [comment]
@adityarb88 Thanks : https://plnkr.co/edit/0WlqFA?p=preview

**Comment by youdz** [comment]
Maybe we could try to do it on `*clrDgItems`, but it would never work with `*ngFor` on server-driven datagrid, so I'm a bit worried about the inconsistency. 

And to do it on `*clrDgItems` would require a lot of investigation and potentially a lot of hacks to override `*ngFor`'s context, since that's how we render the rows anyway. So I'm not sure it's going to be realistic. I'll leave this open so we can try it out later.

And regarding scott's comment, he's saying it would be pretty easy for you to just add the "serial number", as you call it, as a property on your `item` object. It's literally a `for` loop on the array when it's first built or received from the server, maybe even simpler than that depending on how you get it. So the value of us generating the index for you isn't very high.

**Comment by mathisscott** [comment]
Given @youdz feedback on the issues that this would cause for ngFor, I'm going to close this as something we won't do. If you need unique IDs for your datagrid items (and you aren't getting them from the database), you should really be using something in your code that can generate them instead of loop indices.

If you changed pages in the datagrid, for example, your loop indices would remain the same. So what you want to do wouldn't work reliably for a simple count.
