### ISSUE TITLE
Vertical Nav icon size dont change

### ISSUE THREAD

**Issue by williangd** [vmware/clarity#1539]
I'm trying to change the size of clr-icon inside Vertical Nav using `size` attribute.

**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Be able to change the icon size by the size attribute.

### Actual behavior
Size attribute don't change de size of clr-icon.

### Reproduction of behavior
https://plnkr.co/edit/HKIn8hiNBf9WB3egr7Qt?p=preview

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.7

* **OS and version:** Ubuntu 16.04

* **Browser:** [ tested on Chrome and Firefox ]

**Comment by adityarb88** [comment]
@williangd: I would recommend that you create a separate class and apply the styles to that. Please refer to this plnkr: https://plnkr.co/edit/qBTft97DXV8G8bYYBWww?p=preview (See: `app.component.css`). Your styles aren't being applied because the `flex` property is not being overridden. 

Please note that we don't recommend that you do this because as the size of the icons in the vertical nav is configured to work best in both expanded and collapsed state. If you do override the styles you would need to make sure that things are aligned properly in all states.

Closing the issue based on this. Feel free to reopen the issue if you have more questions regarding this.
