### ISSUE TITLE
Tooltip on header-actions breaks layout

### ISSUE THREAD

**Issue by zeratulmdq** [vmware/clarity#1555]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The icon should stay in place and a tooltip should appear in the right position once you hover it.

### Actual behavior
If you use a tooltip wrapping an icon inside `header-actions` the icon is mispositioned and once you hover it, it "jumps" to the right place. The tooltip position is always relative to the original icon and not to the current one.

![GIF](https://i.imgur.com/eb5h6rk.gif)
[GIF](https://i.imgur.com/eb5h6rk.gif)
[Plunker](https://plnkr.co/edit/y3oMimup1agIN6unakLv?p=preview)
### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.9.14 / 0.10.7 (tested on both)

* **OS and version:** Sierra 10.12.6

* **Browser:** Chrome 61.0.3163.100 | Firefox 56.0  | Safari 11.0

**Comment by adityarb88** [comment]
@zeratulmdq: Please note that there can only be one `.header-actions` section in the header. Also since the icon is nested in the `tooltip`, you need to add the `.nav-icon` class on the `tooltip`. Please see this: https://plnkr.co/edit/Ec4JTkyb4o0YwH7wE4t7?p=preview

Closing based on this. Please feel free to reopen the issue if you any additional questions.

**Comment by zeratulmdq** [comment]
@adityarb88 thanks for the quick response. The duplication of `header-actions` was a mistake, we just have one on the app. I'll leave this comment here because your suggestion fixes the problem for 0.10.7 but 0.9.14 still does the same (in case someone else has this issue). It's slightly better, but still mispositioned and jumping.
