### ISSUE TITLE
Tooltips [clr-tooltip] get clipped by sidebar/header when contained in a card

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#1559]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I expect a tooltip to sit on top of any content including the sidebar and header regardless of if it's wrapped by a card parent element.

### Actual behavior
If a tooltip is wrapped by a card, the tooltip overflows the card, but then gets clipped by the sidebar and header (I haven't checked other elements).

### Reproduction of behavior
This can be seen in this plunker: https://plnkr.co/edit/KvVB3nuPMBRTij8QkizP?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.8

* **OS and version:** macOS Sierra 10.12.6

* **Browser:** Chrome

**Comment by mathisscott** [comment]
@adityarb88 
Could you take a look at this? I tried putting a z-index on `.tooltip-content` but that didn't work. @jbgarr appears to be using the angular component so I'm not sure why the subnav and sidebar are clipping off the tooltip.

**Comment by adityarb88** [comment]
@jbgarr: Thanks for reporting this issue. We will add it to our queue and get this fixed. But fortunately there is a work around which solves this issue. This is happening because `.card` has a `position: relative` on it. If you override that to `position: static`, the tooltip is not clipped off. You could do that in your stylesheet right now until the fix is released. Please refer to this plnkr: https://plnkr.co/edit/RJiSwV5M7phPnkZmWlVt?p=preview

Let us know if that works.

**Comment by adityarb88** [comment]
After investigating more, I found that we can't directly remove the `position: relative` from cards as the progress bar positioning in cards depends on that. This issue is now blocked by #1469

**Comment by jbgarr** [comment]
@adityarb88 Thanks for the updates on this. I tried your suggested fix and it didn't quite do the trick. It allowed the tooltip to overflow from the `card`, but then it was still being clipped by the header and sidenav. Interestingly your example plunker doesn't do that though.

I'll keep an eye on this issue though as you continue to work on it.

**Comment by adityarb88** [comment]
@jbgarr: Could you check if any of the parent elements of your card has a `position: relative` or a `overflow: hidden`. That might clip the tooltip. Also are you using the Angular tooltip component?

**Comment by jbgarr** [comment]
@adityarb88 Ok, I found the issue, but I'm not sure the best way to handle it. Right now, the tooltip is wrapped by a parent component that has a `position: relative` in order to position the icon that anchors the tooltip correctly (in the top right of my component). Is the only solution to avoid clipping of tooltips to make sure that no parents of a tooltip has a `position: relative`? That seems like a requirement that may be hard to ensure.

**Comment by spetri** [comment]
FYI, the same thing happens with a SignPost (it gets cut off by the sidebar).

**Comment by Rush** [comment]
I am a new user of Clarity and adding a tooltip was one of the first things I tried. Unfortunately it's not looking very good.

I am trying the most basic application layout:
![](https://rush.sh/Y_EJpBD6IDeVoP1aCPshCgrAvEE/screenshot.png)

**Comment by hippee-lee** [comment]
Hi there @Rush 

You might want to follow this issue: https://github.com/vmware/clarity/issues/777 as it will add the ability to dynamically position tools tips. In the meantime, the workwround I suggest is to set the direction: 

```
<a href="#" role="tooltip" aria-haspopup="true" class="tooltip tooltip-sm tooltip-bottom-right">
    <clr-icon shape="info-circle" size="24"></clr-icon>
    <span class="tooltip-content">Lorem ipsum sit</span>
</a>
```

See here for a working example:
https://stackblitz.com/edit/gh-issue-1559

**Comment by Rush** [comment]
Thanks @hippee-lee. I think this is a good workaround in this one instance but optimally the developer should not be required to think about all the edgecases when using tooltips.

**Comment by hippee-lee** [comment]
Agreed. Dynamically figuring out when to adjust the position and where to adjust the position it to is a difficult problem to solve generically and across browsers. Please subscribe to https://github.com/vmware/clarity/issues/777 for updates when that issue gets prioritzed.

**Comment by gnomeontherun** [comment]
This is really captured under #1757, which we've decided to not tackle due to breaking changes and the future availability of Clarity Core tooltips and popovers.

There is a workaround available for this issue, and we recommend using it for Clarity Angular. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
