### ISSUE TITLE
datagrid.selected is reassigned with an empty array

### ISSUE THREAD

**Issue by colossal-squid** [vmware/clarity#1593]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```
https://plnkr.co/edit/WUNt57MsppVCqK18VtH1?p=preview
### Expected behavior
After datagrid.selected is assigned - the selection if populated on screen

### Actual behavior
The value is assigned and grid is redrawn, but after that this code from datagrid/selection.js seems to rewrite it
```
                // TODO: Discussed this with Eudes and this is fine for now.
                // But we need to figure out a different pattern for the
                // child triggering the parent change detection problem.
                // Using setTimeout for now to fix this.
                setTimeout(function () {
                    _this.current = leftOver;
                }, 0);
```

### Reproduction of behavior
https://plnkr.co/edit/WUNt57MsppVCqK18VtH1
Load plunker,
Populate some selection in both grids
Click refresh button
(the selection if grid1 is preserved, the multi-selection grid - loses selection)
### Environment details

* **Angular version:** 4.3.1

* **Clarity version:** 0.10.7 and 0.10.9

* **OS and version:** latest osx

* **Browser:** all

**Comment by mathisscott** [comment]
@youdz ^

**Comment by Shijir** [comment]
@colossal-squid 
>After datagrid.selected is assigned - the selection if populated on screen

Your expected behavior is a bit unclear here. Anyway, the selection shouldn't be preserved if the grid is populated with new items. The reason why the selection was persisting in your single selection example was that due to the `preselectComparator` directive.

**Comment by youdz** [comment]
I had a very hard time understanding what you were doing, the plunker is overly complicated for what it's trying to showcase. Your preselection directive is not something you should write yourself, that's literally what `trackBy` is for in Angular. So that means what you really want to write is simply this: https://plnkr.co/edit/HI1iuBL0Yj4fQxzto4i5?p=preview
No extra directive, just a `trackById` function and relying on the datagrid to preserve selection when the items are refreshed, as long as the ids match.

As you can see, it works fine for single selection, but there is indeed a bug on multi-selection that breaks it. I just submitted a PR to fix that bug, hopefully it can be included in this week's release. At that point, the plunker I posted should work again.
