### ISSUE TITLE
Vertical nav doesn't collapse on open-space click, but opens on it.

### ISSUE THREAD

**Issue by joshjohnsonux** [vmware/clarity#1603]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When using the vertical nav component with expand/collapse enabled, when the user clicks open space below the nav items, the component expands.  Logically, when the user clicks again in the same open space while expanded, it should collapse.

### Actual behavior
Clicking of open space does not collapse.

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.5

**Comment by dsaojose** [comment]
I also find this behaviour confusing.

**Comment by adityarb88** [comment]
@joshjohnson72: Would you mind replicate this on a Plnkr? Are you using a Vertical Nav with links on the Nav Group level as well on the Nav Group Item level? A plnkr would help us better understand the issue and effectively debug it. Thanks!

I see this on our website:
![nimbus-record-video-2017-10-17-15-17-31](https://user-images.githubusercontent.com/1426805/31684733-afe89c80-b34e-11e7-9d4d-4011f7c10a51.gif)

**Comment by dsaojose** [comment]
I believe it is in regards to the expanding behaviour when clicking on whitespace.  Here is a screenshot that may help:
<img width="356" alt="expectations" src="https://user-images.githubusercontent.com/22899950/31685021-a157e06c-b34f-11e7-8ba2-90fa61a23224.png">

**Comment by adityarb88** [comment]
Oh I understand the issue now. Let me redirect this question to our UX team and ask for their feedback on this. Thanks!

cc: @reddolan

**Comment by mathisscott** [comment]
@reddolan ^

**Comment by reddolan** [comment]
Yeah, this is a bug. It should work expanded and collapsed

**Comment by gnomeontherun** [comment]
@hippee-lee Adding this for your visibility with Core work.

This is a worthwhile request, but we are working on the Clarity Core version of this component. As we build out Clarity Core, this should be possible to realize with the applications managing the state and functionality more directly instead of Clarity Angular. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
