### ISSUE TITLE
App Header should adjust alignment when used with vertical nav

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#1605]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
When developing an application that uses both the application header and the vertical navigation component, the elements should not cause alignment discontinuities.  In particular, a collapsed vertical navigation bar should align with some element of the app header.

### Actual behavior
The collapsed vertical nav bar aligns with something approximating 2/3 of the app header icons width, which looks weird and like the components were built in isolation rather than as part of cohesive design system.
![screen shot 2017-10-17 at 12 21 25 pm](https://user-images.githubusercontent.com/8105536/31684928-1f9ef178-b336-11e7-980c-4e854afc3588.png)

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.5

**Comment by dsaojose** [comment]
I agree with this design choice.  The icons should align.

**Comment by adityarb88** [comment]
cc: @reddolan

**Comment by mathisscott** [comment]
@reddolan ^

**Comment by lil-kim** [comment]
This is not a bug. The VM logo was positioned using our base 24px left margin to align with text in most screens. We don't want to extend the width of the icon column to right align because a wider space for the icons looks awkward - too wide for the size of icons. We want the collapsed width to save as much space as reasonably allowable.
