### ISSUE TITLE
Right side fixed search filter compoent.

### ISSUE THREAD

**Issue by GnanendraPaladugu** [vmware/clarity#1639]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
Please add a component right side fixed search filter bar.  While we are scrolling up the filter section should show.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@GnanendraPaladugu: Thanks for filing the request! 
Could you please provide more information on how the component should function?
Also, could you specify what use case is this component trying to solve?
Do you have any examples that you can post here? 

We need additional details to review this request and provide feedback.

**Comment by GnanendraPaladugu** [comment]
Hi Aditya,
Please take a look once following url ans right side bar.
https://getbootstrap.com/docs/3.3/components/

**Comment by adityarb88** [comment]
@GnanendraPaladugu:
Could you please elaborate more on why this should be a separate component. Also, in the link you shared above, I dont see the search filter bar?  Would you mind adding a few screenshots to your description so that we know exactly what you are requesting.

Also, We already support:
1. Sidenav: https://vmware.github.io/clarity/documentation/sidenav
2. Vertical Nav: https://vmware.github.io/clarity/documentation/vertical-nav/basic-structure/charmander
both of which remain fixed even when the user is scrolling the content area. Did you know about the above 2 components? I feel like they are solving the same use case that you are requesting.

If you are requesting for that nav to be on the right hand side, then we can't provide that out of the box because our UX recommends that the nav should be present on the left. If you have a use case on why the nav should be on the right please provide more details so that our UX team can provide feedback on that. If this request is specific to your application, then you can easily override the CSS to render the nav on the right using the `order` css property since the nav is in a flex box.

**Comment by GnanendraPaladugu** [comment]
Hi Aditya,
Can you please help me how to add image. 
Thanks.

**Comment by mathisscott** [comment]
@GnanendraPaladugu 
You generally just have to drag the image into your comment box and it will upload. There's also the "selecting them" link at the bottom of the comment box...

**Comment by GnanendraPaladugu** [comment]
![filter](https://user-images.githubusercontent.com/32838279/32038056-cc44b9c4-ba45-11e7-9e7a-1feaeee8d0ac.png)

Please take a look above image if we are scrolling up filter will be same position.

**Comment by mathisscott** [comment]
@GnanendraPaladugu 
I see what you're trying to do. You should look into [CSS Grid](https://developer.mozilla.org/en-US/docs/Glossary/Grid) or [Flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox).

Note that a limitation of that proposed layout is if the content in the right section is too tall for a browser window.
