### ISSUE TITLE
Datagrid filters: and/or filters

### ISSUE THREAD

**Issue by gracesnoh** [vmware/clarity#1640]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Built-in filters that let you AND/OR multiple filters (e.g. aws AND azure, windows OR linux)

### Actual behavior
Needs to be a custom built filter

### Reproduction of behavior
n/a

**Comment by amellnik** [comment]
There's an example implementation of the OR version of this in [this Stackblitz](https://stackblitz.com/edit/clarity-light-theme-v012-zi1jt2?file=src%2Fapp%2Fapp.component.html) linked in https://github.com/vmware/clarity/issues/2513.  One minor annoyance is that the developer needs to create an instance of the filter object for each column that it is used in since `clrDgStringFilter` only passes the filter function the row object, and not any information about what column the filter is in.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
