### ISSUE TITLE
Registering for Datagrid Checkbox events

### ISSUE THREAD

**Issue by RainTomassi** [vmware/clarity#1652]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
[x] Question
```

We have the scenario where we are using a datagrid to display a list of 'items'.  Each item has the potential to have subitems.  

![image](https://user-images.githubusercontent.com/20799942/32117939-de59e868-bb04-11e7-8e6e-26f4eb315a0f.png)

It would be nice to be able to register for notifications when a datagrid checkbox was checked.  In our scenario, if the top level datagrid checkbox is checked, then I want to check all subitems and vice versa.  

At the moment, I see two options; use an input checkbox and not use the datagrid managed checks, or hack into the dom and do some wonky things to add handlers to the wrapping elements.   I'd like to continue using the Datagrid managed checkboxes because they are aligned nicely in the left most column. When I substitute my own, the details arrow takes up the left most column and my check is to the right, but I'm not seeing a better option.

I still feel inexperienced in the Angular world and would consider myself a hack, so from your experience, am I thinking about this the wrong way?  Is this enhancement request to receive events when checking datagrid checkboxes a valid request or is there a better way to go about it? 

Thanks!

**Comment by youdz** [comment]
`[(clrDgSelected)]` on the datagrid rows offers two-way binding, which means there is a `(clrDgSelectedChange)` output for you to use in this case. It emits `true` when the user selects the row, and `false` when the user unselects it.

I'm closing this issue because the feature already exists, but I recommend posting on StackOverflow with `vmware-clarity` tag (https://stackoverflow.com/questions/tagged/vmware-clarity) if you need help setting this up. We monitor it every day, and not only will you have a chance to get an even faster answer from someone outside of the team, your question will also be useful to everyone who needs it after you. 👍

**Comment by RainTomassi** [comment]
Thank you Eudes for the guidance.  I was unaware of the relationship between the two.  Also, good thoughts on Stackoverflow.  Thanks again.
