### ISSUE TITLE
Datagrid action icons should be vertically aligned in the middle of a grid row.

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#1661]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```
### Actual behavior

Action Icons are top aligned

![grid-alignment](https://user-images.githubusercontent.com/7592811/32229038-40122b28-be26-11e7-8622-d8af95b7953b.png)

**Comment by hippee-lee** [comment]
Thanks for reporting this. Can you update the issue with a plunker that recreates the issue so we can take a look at it?

https://embed.plnkr.co/AuJuo5/

**Comment by mathisscott** [comment]
Hi @jacobbutton 
The initials bubbles are pushing the row height of that datagrid out. Our recommendation would be to reduce the size of those bubbles so that your row heights can be 35px (plus border) tall.

If that is not something you are interested in pursuing, you can reposition the icons using CSS.

**Comment by jacobbutton** [comment]
@hippee-lee - please excuse the css hack to push the row height, I couldn't figure out how to load the ngx-avatar package into plunkr to recreate the exact scenario I have in my application. This ends up producing the same results though.

https://embed.plnkr.co/Pp51MXJYEzyLm1vS6wAB/

@mathisscott - repositioning the buttons/icons via css was my initial approach, but that ended up proving to be easier said than done. Repositioning the ellipsis action icon doesn't reposition the action overlflow menu to line up with it and I still haven't figure out how to reposition the expandable caret without modifying global css, messing with component css seems to have no affect on it. I'm open to suggestions.

**Comment by mathisscott** [comment]
@jacobbutton 

Doesn't seem too bad to me... https://plnkr.co/edit/LhpBHhVvYZl9xBo4wbJl?p=preview

YMMV

The challenge is that you don't really want the actions to center align in the row.

You want them to vertically center with the first line of your content. The reason this isn't happening is because the `ngx-avatar` is blowing out the line height to 32px.

We can't vertically center the actions because it would result in an unsightly behavior with rows that had datagrid cells which wrapped.

So the only recourse is a CSS edit. Or sizing the `ngx-avatar` down to be a height that the row can except without blowing out the layout.

**Comment by jacobbutton** [comment]
@mathisscott - I'm not seeing a difference between your plunk and mine

**Comment by mathisscott** [comment]
@jacobbutton 
My bad. Plunkr goofed up on saving my work. Hopefully [this one looks better](https://plnkr.co/edit/Kh30T6ZOg9qpbf59w7d0?p=preview)

**Comment by jacobbutton** [comment]
I wanted to avoid modifying the global css to affect the style of a single component, but I suppose I can make that work.  Any idea why adding these rules to the component css doesn't work? Thanks.

**Comment by mathisscott** [comment]
@jacobbutton 
Our datagrid rows are 36px tall. The `ngx-avatar` code you are using inside the datagrid is making the rows 42px tall. As explained above, "centering" the actions on a datagrid row is not a viable solution. What users expect is that the actions align with the first line of content in a datagrid row.

We do this now with the first line of content fitting in the design of 36px tall single-line rows. This works when we have rows wrapping inside of cells. The problem you are facing is because the avatars are blowing out the line-height to a non-supported value.

You can make the avatars smaller. Or use the CSS I gave you. If this needs to be specific to a certain type of datagrid in your application, you can use a CSS class on the datagrid to wrap these styles.

**Comment by jacobbutton** [comment]
@mathisscott - you already explained that and I accepted that answer. My next questions was why does that css have to be global?  Try placing that css you wrote in index.html and put it in app.component.css, it doesn't work, I don't understand why it doesn't.

https://plnkr.co/edit/ntNQecf8nzD1UkiJAC90?p=preview

As I said I can make it work as is, I'd just like to understand what's going on.  Sorry, you guys probably have more important things your working on.

**Comment by adityarb88** [comment]
@jacobbutton: Would you mind asking this question on StackOverflow with the `vmware-clarity` tag: https://stackoverflow.com/tags/vmware-clarity? We are very active on StackOverflow and will make sure to answer this. This way this answer can be useful to other members in the community too. Thanks!

**Comment by mathisscott** [comment]
@jacobbutton 
[It doesn't have to be global.](https://plnkr.co/edit/Y5iBV1qJOWbsnqO5jIW2?p=preview)

The reason the CSS is in index.html is because of Plunkr. Plunkr loads the CSS in weirdly so what winds up happening is your CSS on app.component.css actually gets loaded in _before_ the clarity CSS (which means the clarity CSS overrides it because it's same specificity and later in the cascade).

**Comment by jacobbutton** [comment]
Yes, you can add a specific class selector, that's not what I meant by global. Maybe I'm not using the correct terminology.  I was referring to what file you're in, whether its the index.html (global), or in the component where you're implementing the grid.  The selection for the caret does not work from the component, regardless of whether it's in plunkr or in my dev environment, it must be selected for from outside index.html.

**Comment by mathisscott** [comment]
@jacobbutton 
The issue you are having is due to view encapsulation. There are ways around that. [This is one of them](https://plnkr.co/edit/HV8735?p=preview). I can't recommend which approach is best for your application...

**Comment by jacobbutton** [comment]
Thanks. I'll look into that.
