### ISSUE TITLE
Support css utils classes to keep our code DRY

### ISSUE THREAD

**Issue by nghiado** [vmware/clarity#1663]
[ ] bug
[x] feature request
[ ] enhancement

### Expected behavior
Clarity should  support css utils like bootstrap provided here https://github.com/twbs/bootstrap/tree/v4-dev/scss/utilities?

We found that during migration our app from bootstrap based styles to Clarity, we ended up copied these classes into our codebase which I feel like they should belong to clarity-ui css since they are used everywhere.
Even on Clarity site, we mentioned 
```
Repeat 24px in Your Layout
Calculate the vertical margins and padding between elements using the Clarity baseline. A multiple of 24px can be a whole or half-ratio. Common numbers include: 6px, 12px, 18px, 24px, 30px, 36px, 42px, 48px, 54px, 60px, 66px, 72px.
```
Those should be enforced by css util classes so we don't have to repeat it everywhere.

**Comment by adityarb88** [comment]
@nghiado: Thanks for the feedback. We already do import a few utility classes from Bootstrap but we are planning to revisit those imports. We want to deprecate some of them.

We do provide alignment classes where needed for eg in our Grid: https://vmware.github.io/clarity/documentation/grid

We don't believe that we need to add utility classes for positioning and spacing because:
1. Positioning utility classes interfere with our popovers and might end up clipping them (We rarely try to use position: relative/absolute in our project).
2. Spacing utility classes are not needed because all Clarity components try to incorporate Vertical Rhythm during implementation. This makes sure that if you use Clarity components in your application, they are spaced according to the 24px grid.

In general, we haven't received a lot of requests for adding utility classes. We feel that these classes are not used by all our users and including these classes means increasing the size of our CSS deliverable for all users irrespective of whether they use it or not. Most of our users add the classes that they need at their end.

We would however like to include a few important utility classes like the ones related to screen readers. So I am going to keep this ticket open but I wanted to give you a heads up that we might not add all utility classes that other libraries provide.

Please let us know if you have any questions or feedback.
