### ISSUE TITLE
Clarity CDK

### ISSUE THREAD

**Issue by coldhamix** [vmware/clarity#1673]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
It would be great to have something like Component Development Kit based on Clarity as Angular Material has one https://material.angular.io/cdk/. Clarity implements a number of useful directives and classes that are unfortunately private for external developers. I wanted to implement a custom element based on AbstractPopover, but it did not work for me.

**Comment by gnomeontherun** [comment]
Besides AbstractPopover, do you have any other examples?

**Comment by allanbond** [comment]
@coldhamix Have you tried using Angular CDK's overlay?

Listening to [Jeremy Elbourne's talk](https://www.youtube.com/watch?v=kYDLlfpTLEA) @ Angular Mix, it sounds as if the Material team has positioned Angular CDK as something that can be used by any component lib.

**Comment by KashMoneyMillionaire** [comment]
@allanbond That was my understanding.

Clarity would use things like [`cdk-table`](https://material.angular.io/cdk/table/overview) as the bases for their grids/tables, use [`overlay`](https://material.angular.io/cdk/overlay/overview) for modals (I think), and [`stepper`](https://material.angular.io/cdk/stepper/overview) for wizards (again, I think).

Essentially, it's a component sdk that developers can build off of. I think the fact that it is on https://material.angular.io is a misnomer.

Instead of Clarity creating it's own CDK, it would use the Angular CDK to create its components. Thoughts?

**Comment by gnomeontherun** [comment]
This thread talks about two different requests. The original one is to make some internal APIs public (like popover abstract), and the other is a request to rebuild components on top of the Angular CDK.

I think making internal APIs public is a reasonable request if you have specifics about what would be helpful. We don't want to make anything part of the public API that isn't necessary or provides obvious value, because it increases the surface area of bugs and support, makes it harder to maintain, and can slow down progress. We need clear examples of what would be helpful and why.

As far as building Clarity on the CDK, it was not available when we started and its really an internal discussion that we wouldn't expect to be visible to developers. We already have our own overlays for example, and at the moment we don't have enough reason to move to the CDK.

**Comment by mathisscott** [comment]
Closing this. If there are areas of the API that we want to make public, we can open issues for them on a case-by-case or component-by-component basis.
