### ISSUE TITLE
publish clarity modules under a namespace, eg. @clarity/{angular,icons,ui}

### ISSUE THREAD

**Issue by royling** [vmware/clarity#1679]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Following popular modules on npm, using a namespace (eg. `@clarity`) to publish all modules.

### Actual behavior

now it's flat.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
We've looked into this before and the `@clarity` namespace was already taken. We don't know who has it, but they haven't published anything public with it.

We've got some plans in this space, and will be making improvements but changing the package name and location is a breaking change that we need to be careful to do it only when we're ready.

Closing since we've already got something in motion to address this.
