### ISSUE TITLE
When a button group overflows, the outer left button borders are missing

### ISSUE THREAD

**Issue by timvl** [vmware/clarity#1682]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When a button group overflows, the outer left button borders on the overflowed lines should be visible.

### Actual behavior
When a button group overflows, the outer left button borders are missing

### Reproduction of behavior
<a href="https://ibb.co/d2GL2b"><img src="https://preview.ibb.co/nnypvw/button_overflow.png" alt="button_overflow" border="0"></a>

```javascript
<div class="btn-group">
    <button *ngFor="let button of buttons"
                  [class.btn-primary]="selected"
                  class="btn btn-sm">
        <clr-icon shape="check" ></clr-icon>
        BUTTON
    </button>      
</div>
```

### Environment details

* **Angular version:** 4.4.5

* **Clarity version:** 0.10.9

* **OS and version:** Windows 7

* **Browser:** [Chrome latest]

**Comment by mathisscott** [comment]
@timvl 
That's a _lot_ of buttons!

Our UX team recommends that button groups not be allowed to wrap like that. You should consider using the [button group overflow dropdown on the Button Groups page of our documentation](https://vmware.github.io/clarity/documentation/button-group).

This may mean you use the Bootstrap-4-based hidden/visible classes at different breakpoints. But button groups wrapping is not a use case we would support. That's why we have the overflow!
