### ISSUE TITLE
Indeterminate (Looping) Progress Bars are not visible inside cards

### ISSUE THREAD

**Issue by a-student** [vmware/clarity#1719]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Consider this code:
```html
<div class="card">
  <div class="card-block">
      <div class="progress top loop">
          <progress></progress>
      </div>
      <h4 class="card-title">Card title</h4>
      <p class="card-text">...</p>
  </div>
</div>
```
The looping progress bar is expected to be visible and looping.

### Actual behavior

The looping progress bar is not visible.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/n0BcXi28jSZdeWBjliVZ?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** Latest

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@a-student 
The plunkr you provided is not working...

**Comment by a-student** [comment]
![1](https://user-images.githubusercontent.com/1752546/33282913-33ef3df4-d3bb-11e7-8f03-7edfe699a0f0.gif)

**Comment by mathisscott** [comment]
Hi @a-student 
Thanks for getting the plunkr working again. Maybe it was an issue with plunkr or something. Not sure. The fix you have in there is good. Likely there was something recently that stomped on it because I'm pretty sure those styles used to be in our CSS.

Feel free to contribute if you want or we'll have someone take a look at this when they become available.
