### ISSUE TITLE
Any suggestions about developing with Clarity UI components under AngularJS 1.5.x 

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#172]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Need information

### Environment details

* **Angular version:** 
1.5.X
* **Clarity version:** 
lastest
* **OS and version:** 
 Ubuntu 14.04
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

I'm a UI developer with AngularJS 1.5.x, recently want to migrate UI from Bootstrap based to Clarity, I found Clarity provides three approaches with UX, UI and Components. I wonder know whether it will take more efforts to use Clarity UI and Components with Angular 1.5.x or it rather upgrade to Angular 2 directly for our next UI refactoring works. Thanks a lot!

**Comment by hippee-lee** [comment]
Hi @wknet123,

1. clarity-ui / clarity-icons will work on your angular 1.5 projects as is. You just need to include the css / javascript for them in your project
2. clarity-angular can work with an angular 1.5.x app but there is some work that needs to be done to lay the foundation. I believe that if you follow the preperation steps here: https://angular.io/docs/ts/latest/guide/upgrade.html

Note: if you only use clarity-ui / clarity-icons then some components will not work (DataGrid, etc) because they depend on clarity-angular code and not just css.

**Comment by jaffoneh** [comment]
@wknet123: as @hippee-lee mentioned, you can still use Clarity (clarity-ui and clarity-icons) regardless of the framework but when it comes to using clarity-ng, we think looking at the future and building for Angular 2 applications has been the right step for us. We recommend you look into migrating your application to Angular 2, the resources @hippee-lee suggested should help!
