### ISSUE TITLE
signpost will disappears when it rolls

### ISSUE THREAD

**Issue by hlzpy** [vmware/clarity#1745]
[ ] bug
[ ] feature request
[X ] enhancement

### Expected behavior
I ran into this problem: 
signpost will disappears when it rolls
This section of the website can see the problem:
https://vmware.github.io/clarity/documentation/signposts

### Actual behavior

Whether you can implement the scroll without disappearing, on the link：https://vmware.github.io/clarity/documentation/signposts

**Comment by hlzpy** [comment]
Hi, this question is going to be fixed recently ? @mathisscott

**Comment by adityarb88** [comment]
@hlzpy: I believe this is the recommended behavior by our UX team for all popovers in general (cc: @reddolan). When a popover is open, it is expected that the user takes action on it. If the user instead chooses to scroll, we determine that the popover shouldn't be open anymore since the user is choosing to view a different part of the page.

What's the use case for the popover to remain open while the user is scrolling? What happens when the user scrolls too much and the popover isn't visible on the screen anymore? If that happens the user will lose context on the page, no?

There are usually too options when the popover is open:
1. Either block scrolling when the popover is open
2. Close the popover when the user begins scrolling.

We chose to go with the 2nd one so as to not block the scrolling behavior. Let us know if this helps.

**Comment by hlzpy** [comment]
@adityarb88  Whether there is the third option: the popover is open and scroll with the user scroll？

**Comment by adityarb88** [comment]
@hlzpy: Again, what is the use case for doing this? The popover should close when the user starts scrolling. We don't support the 3rd option as far as I know because we do not think it is valid.

cc: @youdz for confirmation.

**Comment by youdz** [comment]
Well, their are also technical issues in scrolling the popover with the page, specifically when the scrolling element is _not_ the page but some sub-container.

But I remember UX recommending to close the popover when the user scrolls, yes. You already pinged him, but I'll let @reddolan decide if we want to re-investigate this from a UX standpoint first.

**Comment by hlzpy** [comment]
Thank you very much for your answer.  i got it.
