### ISSUE TITLE
Minor: initial value is not selected when binding radio buttons to objects

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#175]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Dynamically generated radio groups that are bound to an object with `[(ngModel)]` should show an initial selection is the object is a valid selection.

### Actual behavior
No initial selection is shown, but otherwise everything else works -- clicking a radio button selects a option and correctly changes the object.  

### Reproduction of behavior
I was unable to recreate this in the new plunker (attempt [here](https://plnkr.co/edit/hzTwInGeMyFNJ3VCwLUy?p=preview)) due to what I think is an unrelated issue with the plunker, but a example can be seen [here](https://amellnik.github.io/clarity-demo/radios) (code [here](https://github.com/amellnik/clarity-demo/blob/master/src/app/radios/radios.component.html)).  

### Environment details

* **Angular version:** 2.1.0

* **Clarity version:** 0.7.0, also tested on 0.7.2

* **OS and version:** Win 8.1 x64

* **Browser:** all

**Comment by jaffoneh** [comment]
@youdz could you provide your input here?

**Comment by youdz** [comment]
This is the expected behavior in Angular 2: `ngModel` on radios uses reference equality to test if a radio button is currently selected.

You can see this easily in your example by replacing: 
```typescript
private activeTurtle = Object.assign({}, this.data.Turtles[0]);
```
by
```typescript
private activeTurtle = this.data.Turtles[0];
```
at [line 26](https://github.com/amellnik/clarity-demo/blob/master/src/app/radios/radios.component.ts#L26). The radio is correctly initially selected.

As a side note, setting this field to `private` is an error if you're using it in the template. Templates are different objects from the controller, so they need to only access public properties of said controller. This should be instantly visible if your try to AOT-compile this, it'll raise a Typescript error.

**Comment by amellnik** [comment]
Thanks for the clarification @youdz!
