### ISSUE TITLE
Clarity framework on CDN

### ISSUE THREAD

**Issue by olakara** [vmware/clarity#1759]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X ] enhancement
```

### Expected behavior
Do we have clarity framework on any CDN?

### Actual behavior
Couldn't find any CDN access to the framework's files. It would be great to have them in CDN so that we can refer them easily when doing POCs with the framework.

**Comment by SayakMukhopadhyay** [comment]
AFAIK, there is no CDN available. NPM package is the way to go.

**Comment by gnomeontherun** [comment]
Great question, and while we don't have an official CDN there are several available that serve files directly from github that you can use. We use them for our plunkr like you see here https://embed.plnkr.co/AuJuo5. 

Here is a list of a few options that I'm aware of:

* https://unpkg.com
* https://rawgit.com
* https://cdnjs.com/ (doesn't have clarity-angular package for some reason)

If you do this, you'll likely end up using SystemJS to build your application since webpack is a build time not run time bundler.

**Comment by gnomeontherun** [comment]
I've also created a stackblitz sample you could use with Clarity already setup. https://stackblitz.com/edit/clarity-starter

Should get you enough to get going, so I'll close this. We might consider adding this to our documentation in the future.

**Comment by olakara** [comment]
@gnomeontherun thanks for the stackblitz starter... I was trying to use clarity on it and posted the question!! :)
