### ISSUE TITLE
Nested, or Stacked Icons

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#1794]
Feature Request

I'd like the ability to nest or stack icons on top of each other. 

I think the nested icon should be smaller and appear in the same area that badges appear now if you were to add the badge class to an icon.

I'm picturing putting a plus icon over a user icon, or putting an upload icon on top of a file or folder icon.

**Comment by mathisscott** [comment]
@jacobbutton 
[The following plunkr](https://plnkr.co/edit/VRdj49?p=preview) should give you some direction on how to do this with clarity icons. As you can see in the example, clarity icons aren't exactly geared towards doing this sort of thing and the effect is only workable at bigger sizes.

Additionally, this opens a lot of issues in terms of supporting icons on top of one another. One of the reasons we went with an SVG-based icon framework is because we didn't want our product teams cobbling together pieces of icon fonts to create non-standard metaphors.

Between alerted and badged icons, 80% of our need for stacked or nested icons is taken care of. And the other portion can be accomplished with CSS.
