### ISSUE TITLE
Content area does not have bottom padding in FF, Edge and IE

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#1803]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Content area has bottom padding in FF, Edge.

### Actual behavior
Content area does not have bottom padding in FF, Edge and IE due to this bug:
https://stackoverflow.com/questions/39736658/padding-and-overflow-scroll-in-microsoft-edge

### Reproduction of behavior
https://embed.plnkr.co/lx6I5N/

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** Latest

* **OS and version:** Windows 10 

* **Browser:** Firefox | IE | Edge

**Comment by adityarb88** [comment]
@belyan: I don't believe this is a Clarity issue. Its how browsers clip content in a box which has padding. More info here: https://stackoverflow.com/a/20625114/8960224

Closing the issue based on this. Please feel free to reopen the issue if you have additional feedback or questions.

**Comment by belyan** [comment]
This is a very weak position. If you want to make your library better, then at least you can apply the workaround.
In my application I already fixed this error. And I spent my time to create this bugreport, but I did not expect to hear such answer. Perhaps next time I will think twice before I create a new bugreport.

**Comment by adityarb88** [comment]
@belyan: I am not exactly sure how this is a weak position when browsers themselves are disagreeing on the W3 spec. 
More details here: https://bugzilla.mozilla.org/show_bug.cgi?id=748518.
https://www.w3.org/TR/CSS21/visufx.html
https://www.w3.org/TR/CSS21/box.html

The workaround in the StackOverflow question that you posted asks you wrap your content with another `div` and add a padding to it. This workaround has to be applied at your end. There is nothing that we can do about it from our side. Even if we do recommend this workaround in our docs for an additional wrapper, I am not exactly sure how this would stop the problem from occurring in other places. It looks like a browser issue to me rather than a Clarity issue.

If you have a different workaround in mind which does not involve adding an additional wrapper inside of the `.content-area`, then feel free to submit a PR and we will review it. If you can't submit a PR due to time constraints, post a plnkr which demos it and we will include it in the library.
