### ISSUE TITLE
Able to change width, move columns and retain the state.

### ISSUE THREAD

**Issue by nsksaisaravana** [vmware/clarity#1810]
Please add these features: Changing column width, move columns and should be able to retain the state of the grid for a user. For further information please browse the below URL.

http://ui-grid.info/docs/#!/tutorial/208_save_state

**Comment by Shijir** [comment]
Our Datagrid component already supports column resizing. You can listen to column width changes through `clrDgColumnResize`  output and save the emitted data to retain state. For reordering columns, we have design specs for that, and we will start implementing it in the next few days. You can track the issue here: https://github.com/vmware/clarity/issues/1771
