### ISSUE TITLE
Card Drag & Drop (design spec)

### ISSUE THREAD

**Issue by gracesnoh** [vmware/clarity#1827]
### Description
Cards can be reordered by dragging and dropping them into new positions. They can also be merged together when dropped on each other. This is not a default behavior for all cards.

![dox-basic](https://user-images.githubusercontent.com/8237984/34448734-102c0e08-eca5-11e7-8d31-8ce2d673d81e.gif)

### Usage
To rearrange the layout of cards in a grid and to group together cards that contain similar information

### Behavior
When a card is dragged, a “copy” of the card will be dragged with the cursor. The original card will be greyed out, indicating its previous position.
![dox-copy](https://user-images.githubusercontent.com/8237984/34448567-7216a576-eca3-11e7-99d0-70a01f0a5504.png)
Draggable cards have drag handles in the top right corner and are represented by six-dot icons inside a 18x24 container. Handles serve as visual affordances for drag & drop. The handle will take up its own row in the card, adding 18px to the top of each draggable card.
![dox-handle](https://user-images.githubusercontent.com/8237984/34448569-86f8a2f0-eca3-11e7-9a1e-2df16bd3841c.png)
While handles act as visual indicators that drag and drop is an available action, the card is draggable from anywhere inside its container. All clickable elements inside of a card remain clickable but are also draggable.
![dox-clickable](https://user-images.githubusercontent.com/8237984/34448593-bc0e56ba-eca3-11e7-8467-4a336cda5dfe.png)
Since cards are arranged into rows by default, position drop targets will appear as vertical lines in between cards. Cards arranged into columns and mergeable cards are covered in separate sections below. 

When the midpoint of the dragged card enters the range between the right-most 24px of a card and the left-most 24px width of another card (including the 24px space between the two cards), a position drop target is triggered in between.
![dox-drop](https://user-images.githubusercontent.com/8237984/34448627-06f54724-eca4-11e7-8977-0720e1141ee4.png)
For edge drop targets that appear on the very left or very right, the range is between the left-most or right-most 24px of a card as well as its 12px padding.
![dox-edge](https://user-images.githubusercontent.com/8237984/34448647-2cee88fa-eca4-11e7-9fea-069556589482.png)

### Cards in columns
When cards are arranged into columns, the position drop target becomes a horizontal line. 

![dox-columns](https://user-images.githubusercontent.com/8237984/34448736-17672edc-eca5-11e7-86e7-9317b518ce73.gif)

When the midpoint of the dragged card enters the range between the bottom-most 24px of a card and the top-most 24px of another card (including the 24px space between the two cards), a position drop target is triggered in between.
![dox-midpoint](https://user-images.githubusercontent.com/8237984/34448660-52b2e7a2-eca4-11e7-8bb0-26b14069e646.png)
For edge drop targets that appear on the very top or very bottom, the range is between the top-most or bottom-most 24px of a card as well as its 12px padding.
![dox-col-edge](https://user-images.githubusercontent.com/8237984/34448676-7d788bb8-eca4-11e7-85b9-ddb878393167.png)

### Mergeable cards
When a dragged card is merged with another card, the dragged card’s contents appear underneath the other card’s contents. The two sets of contents are separated by a divider.

![dox-mergeable](https://user-images.githubusercontent.com/8237984/34448737-1c4bd998-eca5-11e7-8c2b-35dc1864e49c.gif)

Merge drop targets are triggered when the midpoint of the cards enters the space within a card that is not already reserved for position drop targets (i.e. any space that isn’t the left-most and right-most 24px for cards in rows or top-most and bottom-most 24px for cards in columns).
![dox-merge-targets](https://user-images.githubusercontent.com/8237984/34448696-ad7bf94e-eca4-11e7-9ef7-d8150a4dd68a.png)

### Clickable cards example

![dox-clickable](https://user-images.githubusercontent.com/8237984/34448740-215a88da-eca5-11e7-9224-ad6c2a23dca2.gif)

### Cards with alerts example
The handle will appear above alerts inside of draggable cards.
![dox-alert](https://user-images.githubusercontent.com/8237984/34448712-d1ca63e4-eca4-11e7-83d2-42184df23195.png)

### Scrolling
When the card view is scrollable, dragging a card over the edge of the window will automatically scroll the view to reveal more cards. The farther away from the window the card is dragged, the faster it will scroll. Using a scroll wheel will also scroll the view and maintain the drag action.

![dox-scrolling](https://user-images.githubusercontent.com/8237984/34448741-29951092-eca5-11e7-9217-ae7268b766ff.gif)

### Invalid drop
When a card is dragged outside of range, the cursor will become disabled. If a card is dropped out of range or anywhere without a drop target, the dragged card will return to the row’s original position and fade to opacity: 0. 

The original card that was greyed out will change back to opacity: 1 once the dragged card returns to its original position.

![dox-invalid](https://user-images.githubusercontent.com/8237984/34448742-2f45ded6-eca5-11e7-8315-93dd913b2142.gif)

### Keyboard accessibility
Users can drag and drop cards using keyboard controls. Tabbing to the card object and pressing space bar will activate drag and drop mode. 

Then users can use the arrow keys to move the drop target around. Pressing space bar again will confirm the action and drop the row in its new place.
![dox-a11y](https://user-images.githubusercontent.com/8237984/34448732-07096050-eca5-11e7-9701-7b454371db1d.png)

Related Issues: #620

**Comment by nuba** [comment]
How about dragging a section of a card out (splitting it) and into a new card? Or into another card?

**Comment by mathisscott** [comment]
Hi @nuba 
That would be an enhancement that we would consider later – after we have implemented the the basic functionality of dragging and dropping whole cards.

**Comment by mattmutt** [comment]
Concerns with this UX design iteration, after participating in an implementation:

When dragging a moderately large card around the purple cane affordance often becomes obstructed or hard to visually trace.
Moreover the sporadic displacement of that purple indicator as the user hunts for an appropriate slot is frustrating. Due to the reordering of cards *after* a drop takes place, the layout instantly shifts, but not without unexpected surprises. Since the new layout (in a row-based container) has to accommodate the removal ( displacement ) of card, the new positioning requires shifting and the experience is quite jarring. Did end-user research studies find this approach to be easier for folks?

Why can't a traditional experience be used to preview the new layout and drop zones in real-time, such that when a drop occurs the layout does not need to be as disruptive?

Another upcoming limitation, in the real world scenario when the container is bit more limited in its viewport, the user would have to depend on the scrolling while dragging interaction. However this sensitivity of auto-scrolling detection mixed with the user's hand-eye coordination to trace along the jumping "purple cane" is less than ideal -- and sometimes it even gets lost, now the user is hopeless guessing where the drop will occur. The mock ups suggest that the card can visibly be dragged far outside the "container" that it is constrained to. In my opinion this is not professional and yields  a false impression that the card is droppable outside its constrained viewport.

Lastly, the accessibility issues raise another level for discussion. I'm sure a better screen reader expert can chime in. It seems counter intuitive to have to use the tab key to iterate through all the cards *and then their accessible content* just to say, move the third card around. This will become an exhaustive task when the cards contain datagrid rows or substantial number of links. Recommend a two layer navigation approach: jump between cards and use the optional menu ( or keyboard shortcut enter key) to dive into a card's content, Escape when an exit is desired.

Able to present a real, working reference with many of these improvements in mind to help improve usability.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
