### ISSUE TITLE
Weird outlines in chrome for sortable column header in datagrid

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#1839]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The outline which comes when a column is clicked (which is sortable) in datagrid should be clean

### Actual behavior
The outline which comes when a column is clicked (which is sortable) in datagrid is not a proper rectangle. Feels awkward to look at that.

### Reproduction of behavior
Directly reproducible on clarity website.
![image](https://user-images.githubusercontent.com/3402331/34518891-9b5e5444-f0a7-11e7-9ef9-0c6487640081.png)

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [chrome]

**Comment by SayakMukhopadhyay** [comment]
That is something that happens on all browsers when an element is at a focused state. It happens with all elements that acts like a link but the element is not refreshed due to no new page being loaded. Its a mild irritant, yes. Moreover the focused highlight is important from the a11y point of view since you can see it changing on pressing tab.

**Comment by envyN** [comment]
I raised the bug regarding the non rectangular shape of the outline. That
is something that can be fixed from the lib side I guess.

**Comment by adityarb88** [comment]
@envyN: We cannot remove them completely. They are present to ensure that the datagrid is accessible. I agree that the outline styles should be rectangular but that is something that we cannot control. It depends on how the browser renders it. https://stackoverflow.com/questions/35650135/outline-on-border-box-behaviour-inconsistent-on-chrome

We want to provide browser default outline styles so that users already familiar with those outline styles find it easier to navigate across the application.

Closing the issue based on this. Feel free to reopen the issue if you have more questions.
