### ISSUE TITLE
data-grid loader allows interacting with grid rows & clr-dg-action-bar.

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#1842]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When loader is being shown, data-grid should not allow :
- User to interact with action bar buttons
- Expanding/collapsing rows.
- Focussing input fields present in the grid rows after expanding it.

### Actual behavior
With loader enabled, user is able to do following:
- Click action bar buttons
- Expand or collapse the rows.
- Focus on input fields present in the expanded grid row.
![clarity_issue](https://user-images.githubusercontent.com/4294012/34552312-aabb2922-f146-11e7-8a4c-d0eb5583f5f2.gif)

### Reproduction of behavior
https://plnkr.co/edit/XobaJiLJE2AaBGXEsysT?p=preview

### Environment details

* **Angular version:** 5.1.3

* **Clarity version:** 0.10.20

* **OS and version:**  MacOs Sierra

* **Browser:** Chrome 62.0.3202.94 (Official Build) (64-bit)

**Comment by reddolan** [comment]
Yes, I agree this is an issue. All of the points made, need to be addressed. 

I would add that covering the action button bar would be less desirable. It would be better to disable the buttons all together while the loader is active and then enable the buttons after the loader is complete.

**Comment by tarangkhandelwal** [comment]
Any progress on this bug? Which release we are targeting this fix ?

**Comment by ybian02** [comment]
When a dagagrid is loading, datagrid should not allow:
• User to interact with action bar buttons.
• Focusing/expanding/collapsing rows.
• Focusing input fields present in the grid rows after expanding it.

![3a loader interaction](https://user-images.githubusercontent.com/14363961/45051698-aacd3600-b039-11e8-8008-3977970ca1da.png)

**Comment by youdz** [comment]
Partially fixed by #2670. It prevents any kind of click actions, but interactive elements can still be accessed via keyboard navigation while the datagrid is loading.

**Comment by gnomeontherun** [comment]
The workaround here is to disable your action bar buttons since they exist outside of the Datagrid and Clarity can't easily manage this for you. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
