### ISSUE TITLE
Add Statistics Component

### ISSUE THREAD

**Issue by dgrahn** [vmware/clarity#1870]
```
[ x] feature request
```

### Expected behavior
It would be great to have a 'statistics' component similar to [Semantic UI](https://semantic-ui.com/views/statistic.html). This is a common component in modern web-app design.

Alternatively, what would be the 'clarity' way to display information like this?

**Comment by dgrahn** [comment]
A plunk of what this could look like. https://plnkr.co/edit/QRfNZ6mYz4OHc5EmfiBs

**Comment by mathisscott** [comment]
We should create a Clarity UI component that will display value+label pair in horizontal and vertical orientations. It should allow for multiple sizes. We will need a quick dive with a UX resource to investigate the sizes we want to support (based on similar usage in existing products).

Refer to the Semantic UI link above for reference. 

Proposed API: 

```
<div class="clr-statistic is-horizontal"> <!-- default will be vertical -->
  <div class="clr-statistic-value">
    2,204
  </div>
  <div class="clr-statistic-label">
    Views
  </div>
</div>
```

Open question whether we will allow for changing colors of label or value with utility classes. I don't think that's an MVP.

This will likely get pushed past 1.0.

**Comment by colinreedmiller** [comment]
I started looking into this as a part of HawaiiFresh when referring to screens that exist in current products. The image below shows a vSphere Client Summary page with the existing set of 3 label/value statistics components and a sketch of how I'd realize this design need in HawaiiFresh. This example uses Clarity icons in place of the (colored) vSphere icons and does not yet include the variations required.

Note that camel case is required for all typography moving forward as all caps presents several a11y issues and should be avoided except in cases where it would be awkward or incorrect otherwise e.g. CPU

![statistics-component-ruff.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/f13743ba-7b93-457e-be80-4d61d653a134)

**Comment by colinreedmiller** [comment]
also: This has a dependency on HawaiiFresh re: type classes / sizes and will be postponed until that work is complete. Unless there is a case for interaction or editability this should be grouped with label / value pairs. In the above example the information may be incomplete because it displays only the amount but not in reference to the total available.

e.g.
Storage usage
61.3 of 120 GB

Another possible case would be toggling between the data above and a percentage:

Storage usage
51.8%

**Comment by colinreedmiller** [comment]
Circular Progress is part of a statistics component: https://github.com/vmware/clarity/issues/2245

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
