### ISSUE TITLE
Pinned bootstrap dependency

### ISSUE THREAD

**Issue by nishantshreshth** [vmware/clarity#1899]
We're currently _pinning_ clr-ui dependency on bootstrap to version 4.0.0-alpha.5 instead of specifying a range. This results in a peer dependency warning even if one has a higher (4.0.0) version of bootstrap installed.

If there's no specific reason to depend exactly on 4.0.0-alpha.5, we should probably use a range like "^4.0.0".

https://github.com/vmware/clarity/blob/62eb343cfa3105dc6fc53832cdec64fdf8d3ece5/npm/clr-ui/package.json#L12

**Comment by adityarb88** [comment]
@nishantshreshth: Thanks for the feedback. The only major dependency that we have on BS4 is the grid and the reason we are on alpha5 is because alpha6 has a breaking change in grid. So far, we haven't found any issues with the grid that we currently use and thats why we aren't upgrading to future versions.

We are planning to get rid of the BS4 dependency and work on our own grid but thats not a priority at the moment.

Closing the issue based on this.
