### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when selecting item in datagrid

### ISSUE THREAD

**Issue by s6joui** [vmware/clarity#1959]
```
[x] bug
[ ] feature request
[ ] enhancement
```
I have a datagrid but I use a number as the "clrDgItem" and this seems to mess up with how it works. I am not able to select the first item in the list and ExpressionChangedAfterItHasBeenCheckedError is thrown. **If I go back to version 0.10.4 it works as expected.**

### Expected behavior
Selection working

### Actual behavior
ExpressionChangedAfterItHasBeenCheckedError is fired and selection doesn't work for the first item.

### Reproduction of behavior
Not working (0.10.24): https://plnkr.co/edit/mmLobefBRWIRPYdJuHVu?p=preview
Working (0.10.4): https://plnkr.co/edit/ozhnSumfaVWmn67zxhAY?p=preview

### Environment details

* **Angular version:** 4.0.0

* **Clarity version:** 0.10.24

* **OS and version:** Windows

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
If you use 'task' for the `[clrDgItem]' instead of 'i' there is no error. 

I modified your plunker with this

```<clr-dg-row *clrDgItems="let task of tasks;let i = index;" [clrDgItem]="task">```

https://plnkr.co/edit/VRSCrNbrnkvT1tcCteg9?p=preview

Does that help?

**Comment by s6joui** [comment]
@hippee-lee Hi, thanks for answering. Unfortunately in the full project I wanted to use the index (i) as the item because I then use it to access a different array that's linked to the tasks array. However this is not possible since I upgraded to v0.10.24. I'm not sure if it's a bug or if it's intended behaviour.

**Comment by hippee-lee** [comment]
Ah, I see.  You will have to specify the `trackBy` function to use the index instead of `task`. Take a look [here](https://plnkr.co/edit/96RjMwabmUnkvvbQAmsV?p=preview), I updated your plunker with:

```
<clr-dg-row *clrDgItems="let task of tasks; trackBy: trackById; let i = index;" [clrDgItem]="task">
```

```
trackById(id: number, item: User) {
  return id;
}
```

Does this work for your use case?

**Comment by s6joui** [comment]
@hippee-lee That's not really what I'm looking for. My aim is to have the index of the selected item in the `selectedTask ` variable.

In your plunker I still get a string in `selectedTask `and if I change `[clrDgItem]="task"` back to `[clrDgItem]="i"` the bug reappears.

Thanks again for trying to help.

**Comment by gnomeontherun** [comment]
I think there is a misunderstanding about the role of `clrDgItem` in the datagrid. It is not something that you use, but rather information for the datagrid to manage internal states. In order for the grid to support some features, the row needs to be aware of the actual content of that row (such as for sorting and filtering). It is not meant to hold a numeric value like you are attempting to do, as that breaks the other features of the datagrid.

There was recent work done to fix a few issues related to selection in the datagrid that probably explain why it worked before but does not now. If you aren't using sorting/filtering, then it seemed like a convenient way to get the selectedTask to equal the index.  Therefore, the fact it worked before was a bug.

However, since your array is just a flat array of strings you could easily look up the index based on the selected item. Update your datagrid to listen for the selected event:

```<clr-datagrid [(clrDgSingleSelected)]="selectedTask" (clrDgSingleSelectedChange)="changed()">```

Then add a method to 

```  changed() {
    console.log(this.tasks.indexOf(this.selectedTask)); // Gives you the index and you can continue from here
  }```

https://plnkr.co/edit/2Q7QcLDUvDXDorMGkZB9?p=preview

**Comment by gnomeontherun** [comment]
Sorry the link above is bad, use this https://plnkr.co/edit/Wajqt5aykjAjiqVuoPgB?p=preview

**Comment by s6joui** [comment]
@gnomeontherun thank you, I understand the issue.
