### ISSUE TITLE
Theming Form Fields

### ISSUE THREAD

**Issue by ronnyek** [vmware/clarity#1972]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Reproduction of behavior
I attempted to follow theming guide in wiki documentation in both plunker and stackblitz to no avail. Importing dependencies.clarity, importing my theme, and then importing components.clarity with the ~@, which succeeded there, but blew up trying to load bootstrap variables (because reference was incompatible)

Essentially from a purely usability standpoint, I disagree with the idea inputs are just the underline, and wanted to just change border-bottom... in @mixin clr-form-fields-appearance to be border: so that I could have an entire textbox for my theme. I must not have a super clear understanding of scss, but didn't seem like defining my version of that mixin before/after or inbetween the dependencies.clarity.scss import and the components.clarity imports, really allowed changing the actual appearance of those fields.

I was wondering if I'm missing something, or if anyone has any ideas there.

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:**.11

* **OS and version:** Windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@ronnyek: If I am understanding your question correctly, your issue is more wrt the form border width and not the color. For forms we use `border-bottom: 1px solid #9a9a9a;`. This is what our UX recommends. If you override the variables, all you would be able to change is the color `#9a9a9a`. If you want borders on all sides, then you would have to add the style in your CSS to override the clarity `border-bottom` style altogether - For eg: `border: 1px solid black` but please note that this is not what our UX recommends.

Please let me know if this helps and please correct me if I didn't understand your question correctly.
I will keep this issue open until you respond but if my understanding is correct, then you would have to override clarity styles at your end. Theming will only help you change the border bottom color.

**Comment by ronnyek** [comment]
Well I was trying to make it bordered on all sides, but I am going to just try and get clarity in place as is, 
 and then see if it is really is problematic. I appreciate the input

**Comment by adityarb88** [comment]
No worries. I will close this issue as the question was answered but please feel free to reopen the issue and let us know if you have any more questions or feedback.
