### ISSUE TITLE
For Wizard control , navigation list missing when put <clr-wizard-page> tag in a sub component 

### ISSUE THREAD

**Issue by xd125** [vmware/clarity#1974]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
we have a wizard component which need to add wizard step programmatically, so we put wizard step into a component, e.g. named: app-page1, we add the component tag into the clr-wizard tag:
```
<clr-wizard #wizardmd [(clrWizardOpen)]="mdOpen" clrWizardSize="lg">
                  <clr-wizard-title>Medium-Sized Wizard</clr-wizard-title>
                  <clr-wizard-button [type]="'previous'">Back</clr-wizard-button>
                  <clr-wizard-button [type]="'next'">Next</clr-wizard-button>
                  <app-page1></app-page1>
 </clr-wizard>
```
we expected the wizard can render the page defined in the sub component.

### Actual behavior
the first page content and title are displayed, but the navigation items are empty, and we cannot navigate to next page by click next button also

### Environment details

* **Angular version: 5.2.0

* **Clarity version: 0.11.3

* **OS and version: Windows 10

* **Browser:** [all]

**Comment by gnomeontherun** [comment]
The wizard expects to have a `clr-wizard-page` element to project the content, otherwise it doesn't work. Without the page element, the internal selection of what should be displayed is unclear, so put your component inside of the page like so.

https://stackblitz.com/edit/clarity-light-theme-v11-6vy6dm?file=app%2Fapp.component.html

```
			<button class="btn" (click)="wizardOpen = true">Open</button>
			<clr-wizard #wizardmd [(clrWizardOpen)]="wizardOpen" clrWizardSize="lg">
				<clr-wizard-title>Medium-Sized Wizard</clr-wizard-title>
				<clr-wizard-button [type]="'previous'">Back</clr-wizard-button>
				<clr-wizard-button [type]="'next'">Next</clr-wizard-button>
				<clr-wizard-page>
					<ng-template clrPageTitle>Page 1</ng-template>
					<app-page1></app-page1>
				</clr-wizard-page>
			</clr-wizard>
```

I don't believe this is a bug but an implementation question so I'm going ahead and closing it. Feel free to repoen it if there are additional issues, or post to StackOverflow for help.
