### ISSUE TITLE
Move to Angular 4 and new TS

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#198]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
We need to research and make recommendations on the plan to move to Angular 4.

[This is a repurpose of the ticket originally filed. Updates: Fri. March 31st]

**Comment by hippee-lee** [comment]
- [ ] Audit the website codebase to replace the Angular 2 references with just Angular.

**Comment by jeeyun** [comment]
Most of the code changes involved animations moving out to its own package. With some code changes.. 27/469 tests are still failing: https://travis-ci.org/jeeyun/clarity/jobs/217323371

Only wizard is failing entirely. If the issue for wizard can be identified, I think the rest are not too hard to fix.

**Comment by biapar** [comment]
I install the final version of Angular cli and then I create a new solution. After I install Clarity following your guide, but I've this error at runtime: 
https://cloud.githubusercontent.com/assets/661517/24576446/4f43cf8c-16bc-11e7-835c-e170ffa94b74.png

**Comment by bertofer** [comment]
Any news on this? I have seen the other issues related to this closed. I will explain our situation and possible solutions, in case it helps.

Was mentioned that clarity will wait for dependent projects to adopt 4 before moving to 4. But this can be tricky, as maybe the reason to not move to 4 is clarity itself (our case with animations and the clrTreeNode).

What do you think about having a @next version, which is the same but changes the way animations are imported, in order to be able to work in ng4 ? (It could start being clarity 10, where angular 2 compatibility could be dropped, maybe).

**Comment by jeeyun** [comment]
Hi @bertofer, we have upgraded our code base to angular 4 and are actively testing right now. We're hoping to make it in to this week's release pending successful test completion and code review.

**Comment by jeeyun** [comment]
@biapar: have you resolved your issue? that is not related to angular version but a conflict in webpack expecting the moduleId to be a string. You can follow some of the suggestions in this closed issue and see if that helps:  https://github.com/angular/angular-cli/issues/3576

**Comment by mathisscott** [comment]
Closed by #697

**Comment by biapar** [comment]
@jeeyun not yet. I only read that we need to change moduleId: module.id.toString() into src/app/app.component.ts, but I wish to try to reinstall from scratch because you solved with #697
