### ISSUE TITLE
Datagrid - filter button nested in sort button in header columns

### ISSUE THREAD

**Issue by darrenjhayes** [vmware/clarity#1993]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

On a datagrid with sorting and filtering enabled, clicking the filter icon should open the filter overlay and should not sort the column.

### Actual behavior

Clicking on the filter icon does two things:
- Opens the filter overlay (expected)
- Sorts the column (not expected)

Example: https://plnkr.co/edit/Jov3VMt63C3lpkTp2ldi

On Chrome, the Email column filter displays the above behavior.
On Firefox, the filter does not appear and it just sorts the column.

### Reproduction of behavior
https://plnkr.co/edit/Jov3VMt63C3lpkTp2ldi

This behavior is replicated when all of the following are present:
- The list of columns are dynamic and passed in from the component
- Sorting is enabled
- There is a filter on one of the columns
- There is an Ng Template if/else within the grid
- Hide/display columns is activated

Further information including screenshot of the rendered html is here: https://stackoverflow.com/questions/48788387/datagrid-dynamic-column-generation-with-custom-filter-causing-an-issue

### Environment details

* **Angular version:** 4

* **Clarity version:** 0.10

* **OS and version:** Windows 10

* **Browser:** [Chrome XX | Firefox XX]

**Comment by youdz** [comment]
Angular treats `ng-template`s as "black boxes", so we can't go into them and split them into pieces, or even know precisely what you put in them.

In your case, you're nesting your custom filter into 2 levels of templates, which means there is no way for us to separate the custom filter from the column title, which is used as the text of the button used to sort the column (I use "text" loosely here, your column title could contain any HTML like icons). The solution is simply to put the custom filter outside, in its own `*ngIf`: https://plnkr.co/edit/Hhms3CxLmzKHark5HVsd?p=preview

I'm closing this because I don't believe there's anything we can do to drill into nested template, and I do believe the solution I posted works for your case. Feel free to reopen if you think there's something that really needs to change on our side.

**Comment by darrenjhayes** [comment]
Thank you for the suggested fix, @youdz. That works perfectly for me.
