### ISSUE TITLE
Signpost content does not display properly when used in navigation header (nav-link nav-icon)

### ISSUE THREAD

**Issue by srikanthps** [vmware/clarity#2003]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When signpost is associated with nav-link, the X button should be displayed correctly - in top-right corner.  Also, any content of sign post such as tabs should display properly.

### Actual behavior
The clr-icon used in signpost header gets rendered in center of signpost.  
If tabs are present in signpost content, the inactive tab's label is not displayed as it inherits font front from nav-link nav-icon and its text color becomes same as background color.

There seems to be some style conflicts that is making signpost content to inherit unintended styles.

### Reproduction of behavior
https://plnkr.co/edit/N1yhnc5N6lLYGifsj0XN?p=preview

Click on info-icon in header bar and observe the signpost content.

![image](https://user-images.githubusercontent.com/102016/36426546-51339908-1670-11e8-831a-439d264dbb1e.png)

### Environment details

* **Angular version:** 4.3.0

* **Clarity version:** 0.10.14

* **OS and version:** 
Windows and Linux

* **Browser:** all

**Comment by adityarb88** [comment]
@srikanthps: Thanks for raising this issue. This is happening because the header styles are interfering with the styles in signposts and tabs. Our header was created long back and we are looking to refactor it to make sure that it doesn't interfere with other Clarity components. I will be opening a different issue with the list of things we need to fix on the header soon and will add this issue as a sub issue to that. Keeping this open till then.

**Comment by mathisscott** [comment]
This is still an issue and we should try to fix it...

https://clarity-light-theme-v2-fnzbgn.stackblitz.io/

https://stackblitz.com/edit/clarity-light-theme-v2-fnzbgn?file=src/app/app.component.html

**Comment by Shijir** [comment]
It looks like we still have issues with signpost placed in header: https://stackblitz.com/edit/clarity-signpost-in-header

**Comment by gnomeontherun** [comment]
This will be fixed by #1757 and we'll close this as a duplicate.
