### ISSUE TITLE
[Question] Is there a way to only introduce filter but not sort for a certain column in datagrid?

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#2024]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```
For datagrid, is there a way to only introduce filter but not sort for a certain column?
[clrDgField] introduces both filter and sort while [clrDgSortBy] introduces only sort. I cannot find a way to only use filter. I find customized filter can work around this but it's quite verbose to write customer filter for each column.

**Comment by youdz** [comment]
We try to redirect questions to Stack Overflow with the tag `vmware-clarity`: https://stackoverflow.com/questions/tagged/vmware-clarity
This helps us keep our issue tracker clean, otherwise we'd be completely overwhelmed by questions here.

That said, when you ask the same question on Stack Overflow, could you please explain your use case for having a column be represented exactly by a simple property on your models, but wanting to disable sort? That's just hindering user experience and removing a "free" feature for which you don't have any work to do. Thank you.
