### ISSUE TITLE
Width of the columns not adapting to the content after changing page in datagrid

### ISSUE THREAD

**Issue by digitlz** [vmware/clarity#2036]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Whenever I change the page in a datagrid the width of the columns should adapt to the width / length of the content.

### Actual behavior
The width of the columns won't adapt after the first page. On the first page everything fits just right - the columns adapt to the content. But on the next page the content may overlap if it's to long and won't break (for example if it's a long word or number).

### Reproduction of behavior
Create a datagrid with pagination, insert content that changes its length from page to page.

The following example shows a datagrid in a fixed width. (This whole issue appears when there's not so much space available, so I forced a small datagrid.) The columns adapt to the content of the rows on the first page. But the second page has a different distribution of content. Column1 looks too big and the content of the first row in Column2 overlaps into Column3.
This is an over-exaggeration but it show's the issue quite well.
https://stackblitz.com/edit/clarity-light-theme-v11-bvixqb

### Environment details

* **Angular version:** 5.2.1

* **Clarity version:** 0.11.7

* **OS and version:** macOS 10.13.3

* **Browser:** [ Chrome 64 | Firefox 58 ]

**Comment by youdz** [comment]
This is expected behavior, we had reports of bad user experience when the columns were jumping around on every page change. So the fact that we compute smart column sizes based on the data in the first page is something we do on purpose and will not change.

See my answer here for more detailed information and potential solutions: https://github.com/vmware/clarity/issues/1158#issuecomment-313687873
