### ISSUE TITLE
Responsive design using other libraries.

### ISSUE THREAD

**Issue by luis-cortina** [vmware/clarity#2048]
I want to create a web app that will adapt to different devices by showing different contents or showing the same data in different ways(i.e on a desktop browser I will display a Datagrid, if mobile a list of Cards with the same information).

I was looking how to hide content based on the screen size with angular and found this library:
https://github.com/ManuCutillas/ngx-responsive

I wanted to ask you if you've ever done this and what was your approach.

Thanks,

Luis

**Comment by adityarb88** [comment]
@luis-cortina: Could you please ask this question on StackOverflow with the `vmware-clarity`, `angular`, `html` and `css` tags because your question is about responsiveness in general and there could be multiple approaches to do that. We monitor StackOverflow regularly and will respond back to you there. 

Also, please provide a StackBlitz so that the community can use that to recommend solutions to your question.

Closing the issue based on this. Thanks!
