### ISSUE TITLE
Date picker: deliver date in consistent format using ngModel

### ISSUE THREAD

**Issue by s6joui** [vmware/clarity#2056]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Change the date format to 'yyyy-mm-dd' instead of current locale format when using ngModel. 

The main reason is that the HTML5 date input always returns the date in this format so existing apps that implement the default HTML5 date input can easily replace it with the new clarity date picker by just adding 'clrDate'. With the current implementation we have to rewrite a lot of code to re-convert the date formats.

Date input specs:
http://w3c.github.io/html-reference/input.date.html
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

### Actual behavior

Right now we get the date as a string in current locale format.

### Environment details

* **Angular version:** 5

* **Clarity version:** 0.11.8

* **Browser:** all

**Comment by adityarb88** [comment]
@s6joui: You can add a binding on `clrDate` to get the Javascript Date object directly without any conversion. 
Demo: https://stackblitz.com/edit/clarity-light-theme-v11-6gls7q?file=app/app.component.html

I will consult with about the `ngModel` case with @youdz and get back to you.

**Comment by youdz** [comment]
@s6joui: I just tried `<input type="date">` + `ngModel` in Safari, which doesn't have a native date input implemented. It treated the input like any text input, and instead of returning 'yyyy-mm-dd', it just returned what I typed (in my case, 'mm/dd/yyyy'). Have you ever tried your code that relies on the  'yyyy-mm-dd' in Safari? It looks like it wouldn't work at all.

**Comment by s6joui** [comment]
@youdz my app runs on electron so I haven't tried it on Safari but I assume it would crash if they don't support date inputs.

I still think it would be nice if we could have `ngModel` deliver a consistent format. Getting the localized format is not something that can be useful IMO. Usually we want the user to see the date in their local format but when we retrieve it to save it somewhere we want to have it in a standarized format.

Anyway I have changed the code to bind on `clrDate` as a Javascript Date and I then convert it to `yyyy-mm-dd`. It's an extra step but it works.

Good job with this new component! :)

**Comment by youdz** [comment]
If `ngModel` has inconsistent behavior across different browsers, there is little we can do, not mentioning the fact that it's probably not our job to fix it (hacking into it might create problems when upgrading to future versions of Angular).
Your case is also very particular since it's an Electron app, no actual web application can hope to get a string for a date given the differences between browsers.

I understand that the in-place swap doesn't work as you hoped it would, and maybe we can think of a way to override `ngModel` somehow, but the combination of risk and low amount of people concerned means it won't be a priority for us at the moment.

**Comment by pumano** [comment]
looks like I stuck here too.
I have ISO string Date format in my domain model, I want to convert current date from date picker to Date object then use `toISOString()` without executing angular with different locale or etc. 

Looks like I need two way data binding from `clrDate` where `Date` object represented to `ngModel`.

**Comment by mxab** [comment]
I'm currently facing also the issue that I'm trying to use the clrInput in a reactive form.
Besides facing the issue that I don't know how to translate my date object to the desired format, a workaround via clrDate does also not work since it does not support the form controls Validators.
e.g. `fb.control("date", [Valdiadors.required])`

**Comment by mxab** [comment]
I'm using this know as a workarround:

template:

```
<form [formGroup]="realFormGroup" >
....
<clr-date-container>
      <label>Date</label>
      <input type="date" required clrDate 
             [formControl]="dateInputControl" 
             (clrDateChange)="setDate($event)">
      <clr-control-error>Please provide a date</clr-control-error>
</clr-date-container>
```
</form>


controller:

```
  //actual form group that holds my form data
  realFormGroup: FormGroup = this.formBuilder.group({
   ...
    date: this.formBuilder.control(null, [Validators.required]),
   ...
   });;
  //surrogate input control
  dateInputControl = new FormControl('', [Validators.required]);
  
  @ViewChild(ClrDateInput)
  dateInput: ClrDateInput;
  //called on clrDateChange
  setDate(date: Date) {
    this.realFormGroup.get('date').setValue(date) //set the date in my actual form
    this.dateInput.date = date; //sync the date, incase I load data from the backend and call set date
  }
```

**Comment by gnomeontherun** [comment]
This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. There is a workaround available for this issue, and we recommend using it for Clarity Angular.

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
