### ISSUE TITLE
How to define the contents of tabs in different files?

### ISSUE THREAD

**Issue by nithinkarthik6** [vmware/clarity#2076]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior

Fetch the contents of the tabs from different files and display in main screen
### Actual behavior

I have 4 tabs in my main screen. I have defined the contents of these tabs in main screen only. But since the contents of each tab are larger i now want to define them in different files and fetch the content from these individual files and display in their respective tabs in my main screen. How do I do this ?
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.2.8

* **Clarity version:** 0.11.8

* **OS and version:** windows enterprise 2008 R2

* **Browser:** all

**Comment by adityarb88** [comment]
@nithinkarthik6: It looks like this question has more to do with Angular than with Clarity. Could you please ask this question on StackOverflow with `angular`, `vmware-clarity` tags? Please provide a replication of your question on StackBlitz so that its easier for the StackOverflow community to answer you. Here is a StackBlitz that you can fork: https://stackblitz.com/edit/clarity-light-theme-v11. This link is available to you when you open a new issue. Thanks!
