### ISSUE TITLE
Test of datagrid custom filter errors out

### ISSUE THREAD

**Issue by kathygit** [vmware/clarity#2084]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Test should not error out.

### Actual behavior
Console throws error:
Error: No provider for FiltersProvider!

### Reproduction of behavior
component class:
```
export class CheckboxGridFilterComponent {
    public changes = new Subject<any>()
   public constructor(private filterContainer: DatagridFilter) {
        filterContainer.setFilter(this)
    }
```
Test file:
```
beforeEach(async(() => {
        TestBed.configureTestingModule({
            imports: [
                RouterTestingModule,
                ClarityModule,
                FormsModule
            ],
            declarations: [
                CheckboxGridFilterComponent
            ],
            providers: [
                DatagridFilter
            ]
        })
    }))
```
### Environment details

* **Angular version:** angular/core: "^4.4.6"

* **Clarity version:** 0.10

* **OS and version:** Mac Sierra 

* **Browser:** Chrome

**Comment by youdz** [comment]
You are declaring one of our components as a provider in your tests, which doesn't make sense since Angular won't be able to instantiate it as a provider.

You have 2 options:

1. Mock `DatagridFilter` with a class that simply offers a dummy `setFilter(filter)` method, and declare it as your provider in the testing module: 
```typescript
providers: [{provide: DatagridFilter, useClass: MockDatagridFilter}]
```
2. Have your test component include the `<clr-dg-filter>` wrapper.

Obviously the first one is much cleaner, and the mock itself is just a class with a single dummy method. That way you can even check that said method was called, bonus points!

**Comment by kathygit** [comment]
Thank you. Solution#1 works!

**Comment by laraveluserkl** [comment]
Hello Kathy,

Could you please provide more info on how did you resolve it. The above solution of Use Class not working.

**Comment by kathygit** [comment]
Create a grid with more than 2 columns. 
Create filter for 1st, 2nd and 3rd columns. 
The filter doesn't work for the 2nd column only.
