### ISSUE TITLE
Allow disabling filter for a datagrid column

### ISSUE THREAD

**Issue by realcnbs** [vmware/clarity#2086]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
Allow some kind of switch to disable filtering for a column when using clrDgField. Currently facing a situation when i don't need filtering on columns, just the sorting.

### Actual behavior
When using clrDgField both sorting and filtering is enabled by default

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-ayfrhv

**Comment by gssjr** [comment]
Using custom sorting and filtering will take precedence over clrDgField so use the appropriate directives to customize your behavior: https://vmware.github.io/clarity/documentation/v0.11/datagrid/custom-filtering

**Comment by realcnbs** [comment]
How can I remove filtering using custom filter?
And what sort and filtering directives do you mean? The documentaion is unclear on this.

**Comment by gssjr** [comment]
<clr-dg-filter> or [clrDgSortBy]

Let's say we only want to only allow sorting instead of allowing filtering:
`<clr-dg-column [clrDgSortBy]="'name'">Name</clr-dg-column>` instead of `<clr-dg-column [clrDgField]="'name'">Name</clr-dg-column>`

I haven't thought about how to do it if you're using *ngFor since you may want a different configuration per column.

**Comment by gssjr** [comment]
https://vmware.github.io/clarity/documentation/v0.11/datagrid/custom-sorting

> ... you might want to specify a custom comparator to sort the column according to your needs. This can be done by providing a comparator through the [clrDgSortBy] input, whether or not your column is declared as a clrDgField, and will always take precedence over it if it is.

**Comment by realcnbs** [comment]
Yeah, but i didn't need custom comparator. Thanks anyway.
Also, is there a way to show that column is sortable? 
E.g. here is impossible to tel which columns are sortable - http://i.imgur.com/H7cERRm.png

**Comment by mathisscott** [comment]
@adityarb88 ^

**Comment by adityarb88** [comment]
@realcnbs:
Sortable columns are underlined on hover:
![image](https://user-images.githubusercontent.com/1426805/37719976-ad25c860-2cfc-11e8-9044-83499ed5ef71.png)

They are also accessible via keyboard:
![image](https://user-images.githubusercontent.com/1426805/37720018-bfc848da-2cfc-11e8-9aef-2e9c6cac5501.png)

Our UX team decided not to have a specific indicator for sortable columns because it creates unnecessary noise.

I am going to close this issue because the question that you asked originally was answered by @gssjr. Thanks @gssjr.

Please let us know if you have more questions/feedback.

**Comment by mooncser** [comment]
> `<clr-dg-filter>` or `[clrDgSortBy]`
> 
> Let's say we only want to allow sorting instead of allowing filtering:
> `<clr-dg-column [clrDgSortBy]="'name'">Name</clr-dg-column>` instead of `<clr-dg-column [clrDgField]="'name'">Name</clr-dg-column>`
> 
> I haven't thought about how to do it if you're using *ngFor since you may want a different configuration per column.

If I use *ngFor for <clr-dg-column *ngFor="let col of tableHeader" [clrDgField]="col>,
How do I disable the [clrDgField] for specific column with *ngfor

**Comment by gnomeontherun** [comment]
@mooncser Please post questions like this on StackOverflow with an example for people to review and use the `vmware-clarity` label so we catch it. Thanks!
