### ISSUE TITLE
Datagrid Hideable Column: save the state or emit event

### ISSUE THREAD

**Issue by power721** [vmware/clarity#2117]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Datagrid Hideable Column: save the state or emit event
I want to save the hideable columns, so when I go back the columns kept.

### Actual behavior

No event when change hideable columns.

### Reproduction of behavior
Change hideable columns
go to another page
go back, hideable columns reverted

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 

* **OS and version:** 

* **Browser:**

**Comment by DonaldAlan** [comment]
I would like to be able to react to the hide/show events and use it elsewhere in my app (e.g., for query filtering).

**Comment by Kevin2iBi** [comment]
Any update about this request??

**Comment by power721** [comment]
Actually, we could get columns from Datagrid if we just want to keep state.
```
ngOnDestroy(): void {
    let hiddenarray = [];
    this.datagrid.columns.forEach(function(item,index,array) {
        hiddenarray.push(item.hidden);
    });

    localStorage.setItem('columns', JSON.stringify(hiddenarray));
}

```

**Comment by gnomeontherun** [comment]
Here is another workaround that might be useful in the interim. It is possible to get the `hidden` state of a column and unless you need to listen directly to the events of the column toggler (which we don't expose), you can always look at the columns for their current state to persist. Using ngOnDestroy as @power721 suggested is a useful approach to persisting the data when the component is destroyed.

https://github.com/vmware/clarity/issues/2204#issuecomment-383210477

**Comment by Akay7** [comment]
I find the different workaround to subscribe a hidden status event of columns, but I would like a grid to emit an event with information which column is hidden/appear.
```typescript
  @ViewChild(ClrDatagrid) datagrid;
  ngAfterViewInit() {
    this.datagrid.columns.forEach(
      (column: ClrDatagridColumn) => {
        if (column.hideable) {
          column.hideable.hiddenChangeState.subscribe((isHidden: Boolean) => {
            console.log('state changed', column, isHidden);
          })
        }

      }
    )
  }
```

**Comment by gnomeontherun** [comment]
@Akay7 be careful here as this is a memory leak, as you're going to be subscribing to each hideable column, and then you'll have orphaned subscriptions that never get cleaned up. Try to push each subscription onto an array so you can subscribe to it onDestroy.

So far the use cases described only need to save the state of the columns when the user is ready to navigate away from the page. Like when you edit a text document, you only save the changes as needed instead of with every change. That means getting an event with _every column hide change_ is overly noisy.

**Comment by Akay7** [comment]
@gnomeontherun thank you for forewarning. I'm already getting some trouble with this statement. 

In my case, I would like to save the status of columns straight after it changed. For example, the user can hide the column and after that closing the page in a browser. Noisy is not big trouble because I save a state of columns in localstorage.

Is it possible to have something like `(clrDgColumnResize)` which can emit the current hiding status of a column?

**Comment by gnomeontherun** [comment]
It is possible, which is why this ticket is open. For the moment, we don't have it prioritized so keep watching for updates.

**Comment by ph55** [comment]
There was 'OK' button that used to easily save state of hidden columns - https://github.com/vmware/clarity/issues/2100
Not sure why removed without providing backwards compatibility.

**Comment by Akay7** [comment]
@ph55 actually button OK is not necessary, state of column changed straight after change status of a checkbox. Some user can close grid settings without click OK button.

**Comment by ph55** [comment]
@Akay7 I agree it's not necessary to save state of columns in client side.
But it was handy to save state between sessions.
  
As I see it there is two easiest and straight forward options to save columns state between sessions (persist in some storage):

1. Auto  save after user hide/show some column by subscribing to event.
2. Save on demand by clicking 'Save'.

When first option is missing there was 'OK' button to use as 'Save' option. 
Placement of button was perfectly fine.

My point is that you don't need to hurry to remove some feature without providing replacement.

**Comment by ph55** [comment]
Since `ngOnDestroy` won't be triggered on page refresh/close, here another workaround to preserve state in storage.

Column selection window could be closed by clicking on 'X' icon or toggled by clicking column selection icon again.

Maybe someone will find it useful:

```ts
  @HostListener('click', ['$event']) onClick(event) {
    this.saveColumnsEvent(event);
  }

  private saveColumnsEvent(event) {
    const attr = event.target.attributes;
    const parent = objectGet(event.target, 'parentNode.parentNode.parentNode');
    const parentTwo = objectGet(event.target, 'parentNode.parentNode');

    if (!attr || !parent) {
      return;
    }

    const parentClassName = parent.className.split(' ')[0];
    const parentTwoClassName = parentTwo.className.split(' ')[1];
    const attrName = attr[0].name;
    const attrValue = attr[0].value;

    if (
      (
        attrName === 'shape' &&
        attrValue === 'close' &&
        parentClassName === 'column-switch'
      )
      ||
      (
        attrName === 'shape' &&
        attrValue === 'view-columns' &&
        parentClassName === 'datagrid-footer' &&
        parentTwoClassName !== 'active'
      )
    ) {
      // save to localstorage, request to server etc.
    }
  }
```

**Comment by mathisscott** [comment]
> My point is that you don't need to hurry to remove some feature without providing replacement.

@ph55 
We weren't in a hurry to remove the OK button. The OK button performed only one function – it closed the panel. That was all it did. 

The problem with the OK button was that it could not be localized. We try to avoid putting text in people's paths that cannot be customized, especially if the offending piece's functionality is so trivial.

We were very thorough and deliberate in our decision to remove the OK button. In the end, we looked at the work required to make every instance of that button across an app play nicely with i18n versus what was lost if it was removed and chose the latter.

We don't make decisions on breaking changes like this in the way you characterize. We debate them. Discuss with end users and _always_ post our intentions and decisions to github issues on our board so that the community can weigh in with their thoughts.

**Comment by gnomeontherun** [comment]
This is a worthwhile enhancement request, but is challenging to implement due to the existing behaviors and nature of Clarity Angular. As we build out Clarity Core, this should be possible to realize with the applications managing the state and functionality more directly instead of Clarity Angular. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
