### ISSUE TITLE
draggable modal

### ISSUE THREAD

**Issue by maxtorchel** [vmware/clarity#2184]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Like a jquery dialog box, possibility to drag modal window behind the header.

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:** 0.11.12

* **OS and version:** linuxmint mate 18.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
I believe this was discussed at the very beginning of Clarity, when we first released modals, and the decision was that it was pointless since modals are _always_ displayed with a mask, so you don't have access to the content under it. It's kind of the definition of "modal" anyway.

CC @reddolan for confirmation, if it's correct the issue can be closed.

**Comment by mathisscott** [comment]
@youdz 
That is accurate.

**Comment by maxtorchel** [comment]
this was useful, if i need to see information under modal window and fill form in modal window using this information, that was frequently use case under our business logic

**Comment by reddolan** [comment]
@youdz correct, modals have a mask that interferes with any interaction behind it. 

@maxtorchel I would argue that if the user needs to see the information behind the modal, that a modal isn't the most useful component to be using for their case. Something that expands/collapses might work better so that they don't cover any pertinent content.
