### ISSUE TITLE
Add gradient support for clarity icons

### ISSUE THREAD

**Issue by likwifi** [vmware/clarity#2185]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Actual behavior

Add gradient support for clarity icons.

**Comment by adityarb88** [comment]
@likwifi: I am sorry but I do not understand. Could you please edit your description to add more information about your request? Please add screenshots, if any, along with your description as that will help us review the feature that you are requesting.

**Comment by gnomeontherun** [comment]
I'm not sure I understand what kind of API would be useful here, this is just CSS that you could write to target any `clr-icon`.

**Comment by likwifi** [comment]
@gnomeontherun 
I mean something like this.
`<clr-icon shape="home" clr-gradient="linear-gradient(red, yellow)" size="40">`
and considering this attribute clarity-icons js should create svg defs>linearGradient tag.

**Comment by gnomeontherun** [comment]
I see, we'll mark this as an enhancement request and see if it is something that we'll support. 

@reddolan What would the UX guidance be with having gradients?

**Comment by reddolan** [comment]
@gnomeontherun is there something to prevent them from using css gradients now?

**Comment by reddolan** [comment]
@gnomeontherun I just assumed that if we allow for color change that gradient would be included. I didn't know it was an extra effort to enable it. I would think if it isn't too much effort, we would want the flexibility. If it is quite a bit of effort/time, then lets chat offline about it and figure out how to proceed.

**Comment by colinreedmiller** [comment]
With respect to actionable and indicator icons which are 16px the value of adding gradient support is dubious. It is also not clear that such a look is consistent with Clarity visual design. Since @gnomeontherun says “It means restructuring all of the icons SVG markup to include a linearGradient capability. Its non-trivial, but wanted to verify if we even recommended gradients first.” It is probably best to wait for the Clarity visual refresh and look at the pros and cons of gradient fills for icons at that time.
 
In the meantime some thoughts about usage and intent will be useful. Given the following types of icons, where do we want or need to enable gradients, and in which cases should they be programmatically applied as opposed to part of a unique and app specific design asset?
 
Icon types overview (with example)
 
	▪	Control (Karet)
	▪	Indicator static (Home)
	▪	Indicator toggle (Read / unread)
	▪	Actionable with states (filter)
	▪	Display (accompanying navigation text)
	▪	Small Illustration (on a card)
	▪	Large illustration (page level)
	▪	Application (to launch application)

Clearly some of these are too small / inappropriate for gradient, others become specific designs using colored fills etc and applying gradients will compromise the intent. What is the subset of these where a gradient is required and will be attractive, useful and appropriate for the context?

**Comment by colinreedmiller** [comment]
Closing this given the contrast with current Clarity visual design sensibilities and the effort required re: "restructuring all of the icons SVG markup" - will reopen in the context of a visual refresh if appropriate.
