### ISSUE TITLE
Wizard header area and footer border enhancement

### ISSUE THREAD

**Issue by jeremydejiacomo** [vmware/clarity#2188]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Description
Enhancements to the wizard structure and hierarchy.
- Header area
- Footer border

### Documentation
Enhancement to the wizard structure to allow for a top level header area that is separated by a horizontal rule. Header spacing maintains standard 24px padding with the added horizontal rule at the bottom of the header area. Add a horizontal rule to separate the wizard controls in the footer area from the rest of the wizard content.  Footer spacing maintains 24px padding and placement within wizard content area with horizontal rule at the top of the footer area. See specs below:

![wizard_structure_enhancement_specs](https://user-images.githubusercontent.com/7140246/38699192-5b567758-3e65-11e8-8781-8a8fe0dd1979.png)

**Comment by mathisscott** [comment]
@jeremydejiacomo 
Weren't we looking at 18px instead of 24px? To get the spacing tighter in the wizard and modal?

**Comment by jeremydejiacomo** [comment]
@mathisscott  Addressing 18px spacing in this issue: https://github.com/vmware/clarity/issues/2194

**Comment by mathisscott** [comment]
@gnomeontherun @colinreedmiller @hippee-lee : Are these Wizard enhancements something we are considering in the near future? If so, is this something we want to drive from @clr/core and push out from that vector into @clr/angular? Or is this something we would consider implementing in the angular components first? I also want to acknowledge that UX/Design is a blocker here so our answers to those questions will be impacted by that timeline.

**Comment by gnomeontherun** [comment]
This request has merit but we are not currently planning to address it due to it likely requiring a design change and possible visual breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
