### ISSUE TITLE
Clarity Configuration Guide for all the seeds mentioned in Getting Started guide

### ISSUE THREAD

**Issue by ashishsinghdev** [vmware/clarity#2190]
Clarity Configuration Guide should be for all the seeds mentioned in Getting Started guide

I've tried with [angular2-seed](https://github.com/mgechev/angular2-seed) but without any success.
@clr/angular package structure looks different from other external angular dependencies. That's why can't figure it out how to configure @clr/angular in systemjs.

**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:0.11.0

* **OS and version:**  Ubuntu 16.04 LTS

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
There are a lot of different Angular seeds, and it is not practical to try and document them all. Our recommendation is to use the Angular CLI (which you could use a seed that uses it too), because you'll get the best Angular experience. It fits the requirements of the vast majority of projects, and if it does not then you'll likely need to be very familiar with build and bundling tools to optimize your project better than the CLI. 

Minko's seed is quite well designed for complex cases, and its wiki contains details about how to add an external project. In our guide, you can see the specific files you'll need to add to your list of external scripts/styles and how to add them here (https://github.com/mgechev/angular-seed/wiki/Add-external-scripts-and-styles). Then you'll have to add Clarity itself like you see described here (https://github.com/mgechev/angular-seed/wiki/Add-external-dependency). It uses SystemJS under the hood, but the configuration files are organized specific to this project.

Closing as we can't accommodate this request, and we actually have a new option coming in Angular 6 to easily add Clarity to an Angular CLI project.
