### ISSUE TITLE
Menus which support scrolling

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#2193]
[ ] bug
[x ] feature request
[ ] enhancement
```


### Feature request

Supports for menu scrolling. We have menus with a lot of items and third 
part plugins can add their menu items to our menus.  A tall action menus 
may be cut off at the bottom when the window is too small. We would like
to have support for menu scrolling. This includes and nested menus.

**Comment by adityarb88** [comment]
@dkanev: Are you talking about dropdown menus? If yes, you could do something like this: https://stackblitz.com/edit/clarity-light-theme-v11-mzev31?file=app/app.component.html at your end.

Just wrap the options in a container and style that container to scroll. Let us know if that helps.

**Comment by dkanev** [comment]
@adityarb88 Thank you for the replay,
I mean dropdown and context menus, which have sub(nested) menus.  This makes the
layout more complicated :
https://stackblitz.com/edit/clarity-light-theme-v11-5yi3fk?file=app/app.component.html

One good example for me are menus in the Kendo UI library, the scroll buttons appears only when the 
menu items don't fit in the container:

https://dojo.telerik.com/@dkanev/IgofuSil/2

**Comment by adityarb88** [comment]
@dkanev: In your StackBlitz, the nested menu is cut off because you are not using the dropdown component for the nested menu.

Please take a look at this StackBlitz: https://stackblitz.com/edit/clarity-light-theme-v11-mpq5or?file=app/app.component.css

I will take a look if we can apply the style directly to the dropdown menu but for now the above StackBlitz apporach looks like the best option.

**Comment by dkanev** [comment]
Thank you this will work for me!
