### ISSUE TITLE
Pagination disappear after server return the results.

### ISSUE THREAD

**Issue by daveoon** [vmware/clarity#2197]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The pagination should be updated with total items based on the server return result.

### Actual behavior
When the user sort the table, it calls the refresh method and in turns, it calls the server API to get the new items based on the parameters (page, sort and filters). When the result returns, i will set the items and the total count. Whenever refresh is called, the pagination disappeared but not the initial first time.

### Environment details

* **Angular version:** 45

* **Clarity version:** 0.11.13

* **OS and version:** 

* **Browser:** [Chrome Version 65.0.3325.181 (Official Build) (64-bit)]

**Comment by gnomeontherun** [comment]
Hello, could you reproduce this with a stackblitz (https://stackblitz.com/edit/clarity-light-theme-v11) so we can understand what you are seeing? You can simulate server side rendering with a timeout, or better yet just load dummy data from an open API.

**Comment by youdz** [comment]
Looks to me like you are using `*clrDgItems` for a server-driven datagrid, instead of `*ngFor`.
Anyway, this is clearly a question so please post it (with a StackBlitz) on StackOverflow with the label `vmware-clarity`.  We monitor it daily, and maybe your question has already been answered over there.
