### ISSUE TITLE
ClarityModule is not an NgModule

### ISSUE THREAD

**Issue by BugsyFTW** [vmware/clarity#220]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When using ng serve it should compile the app.

### Actual behavior
When i type ng serve it says that the ClarityModule is not an NgModule, i've followed correctly the tutorial on installation.

```
** NG Live Development Server is running on http://localhost:4200. **

 10% building modules 3/3 modules 0 active(node:844) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ClarityModule is not an NgModule
 
21% building modules 94/94 modules 0 active
```

**Comment by adityarb88** [comment]
Hi @BugsyFTW. Does this happen when you use Angular-CLI version of the clarity-seed?

cc: @Shijir. It looks like an issue being raised over here: https://github.com/angular/angular-cli/issues/3426

**Comment by hansl** [comment]
Hi @adityarb88. I'm the lead on the Angular-CLI project.

Basically this error likely happens because you did not publish `metadata.json` files to npm. These files contain static information for your module and components.

To generate these files, follow these steps: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html (basically running `ngc` instead of `tsc` to build your project). You don't have to release the `.ngfactory.ts` files (you can use `skipTemplateCodegen: true`), just the metadata json files.

Cheers!

**Comment by jeeyun** [comment]
@hansl is right. We are actively working on supporting AoT compilation (#62) right now and plan to publish the generated `metadata.json` files as soon as we have it working. @BugsyFTW feel free to subscribe to the issue on AoT compilation so you'd know as soon as we have it out.
