### ISSUE TITLE
Latest version contains a node_modules with own rxjs

### ISSUE THREAD

**Issue by Elvander** [vmware/clarity#2205]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Clarity design to use the same version of rxjs as defined in the project package.json.

### Actual behavior
Latest version contains node_module directory. This contains @angular-devkit and rxjs. This creates collisions with rxjs version defined in my own package.json

![image](https://user-images.githubusercontent.com/2167777/39050216-d6b05e6a-44a4-11e8-82ee-2c6b8f2ddb6e.png)

### Example error
`src/app/shared/datagrid/custom-list-filter.component.ts(9,14): error TS2420: Class 'CustomListFilterComponent' incorrectly implements interface 'ClrDatagridFilterInterface<any>'.                                                                                  Types of property 'changes' are incompatible.                                                                                      Type 'EventEmitter<any>' is not assignable to type 'Observable<any>'.`

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:** 0.11.13+

* **OS and version:** 

* **Browser:** [all  ]

**Comment by gnomeontherun** [comment]
Due to schematics, we need the `@angular-devkit/schematics` and `@angular-devkit/core` packages (which depend upon `rxjs`). How is it colliding with your rxjs in your package.json?

The example error you show is known to us, and is being fixed but is not part of our actual library (its just the demo app we build upon).

**Comment by whizkidwwe1217** [comment]
I got the same error when creating custom data grid filters:
![image](https://user-images.githubusercontent.com/1977391/39082349-43919c12-4584-11e8-9c56-c831c6b632aa.png)

**Comment by gnomeontherun** [comment]
This seems like two separate issues, but related. 

First, there is concern about us adding dependency packages and it conflicting with node_modules. For this, are you using a lock file for your packages? It could be an issue if you don't, because depending on the way your dependencies are listed it could install a different version after module version resolution.

As far as the interface error, we've seen this issue lately as well, and I believe it is because of changes in TypeScript. `Subject` implements an `Observable`, but is not, and with a stricter compiler it fails. We have to fix this in our documentation as well.

**Comment by Elvander** [comment]
It is actually the same issue as described by **whizkidwwe1217**.

![image](https://user-images.githubusercontent.com/2167777/39111953-43d790d8-46d7-11e8-8180-37ed8c7cbb38.png)

I thought the problem was the node_modules, because the Subject used in the custom filter is colliding with Subject from the interface ( different versions ). If I removed the node_modules folder in the @clr/angular library everything works and compiles.This made me believe that the issue was linked to the rxjs in the @clr/angular library.

I'm using a lock file. 

`angular 5.2.9`
`rxjs 5.5.7`
`clarity 0.11.14`
`angular/cli 1.7.3`

**Comment by gnomeontherun** [comment]
This should be resolved for 0.11.
