### ISSUE TITLE
Version 0.11 Dropdowns not working, or wrongly documented

### ISSUE THREAD

**Issue by DonaldAlan** [vmware/clarity#2226]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
According to https://vmware.github.io/clarity/documentation/v0.11/dropdowns, I should be able to use the sample code snippets to make dropdowns.   
### Actual behavior
The dropdowns built using `<div class="dropdown">....</div>` don't work. I can't toggle the dropdowns open.

They work neither on that documentation page, nor when I copy the code to my project.

I tried this on both firefox, chrome, and Microsoft Edge.

But I can build working dropdowns using code like that at the bottom of the documentation page:
```
<clr-dropdown>
  ...
   <clr-dropdown-menu ....>
   ...
   </clr-dropdown-menu>
</clr-dropdown>
```

### Environment details

* **Angular version: 5.2**

* **Clarity version: 0.11**

* **OS and version: Windows 10**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Hi @DonaldAlan. 

The first example is for `@clr/ui` where it is expected that we are only providing the html and css for look-n-feel. This allows the behavior to be supplied by any JavaScript that your want or need. 

In the second example, the one that looks like `<clr-dropdown>` is for use with Angular. While most components can be used with `@clr/ui` some of the more complex components like Wizard or Datagrid can only be used with Angular. 

If you see an element that takes the form `<clr-my-component>` is only for use with `@clr/angular`. If the element markup is pure html5 elements it could be used in both. Again, for this example if you used the dropdown markup `<div class="dropdown">....</div>` in an Angular app you would still have to supply the behavior and this isn't recomended since we have the `<clr-dropdown>` component. 

In general, if you are using Angular its best to use the `<clr-****>` component if it is described in the documentation.

**Comment by DonaldAlan** [comment]
OK. Perhaps the documentation should make that clearer.
