### ISSUE TITLE
Circular progress

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#2245]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```
![donut](https://user-images.githubusercontent.com/17675259/39702750-78e4184a-520e-11e8-96ac-4691132a7fae.jpg)
just found similar in internet (for example)

### Expected behavior

Donut Chart for dashboard widgets
You have `spinner` element, that element perfectly fit for making another component "Donut Chart" with 
 or w/o percentage and possibility to change colors

**Comment by icepeng** [comment]
https://github.com/vmware/clarity/issues/372

**Comment by pumano** [comment]
I try to create simple `svg` and it works good. If you want that component we can collaborate on it. I don't know your developments process, but I wish to help with it.
![donut-custom](https://user-images.githubusercontent.com/17675259/41153555-bbf9cdbc-6b1f-11e8-8e3d-79f58736defc.jpg)

**Comment by mathisscott** [comment]
Hi @pumano 
We've updated our [contribution guidelines](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md)

This is normally something we would consider for a chart library. But I think it could make sense in our library of components as-is for now.

Let me know if you still want to contribute and I can get someone on our team to go over anything in the contribution process that is not clear.

Thanks!

**Comment by pumano** [comment]
@mathisscott thanks, currently I'm busy, but I will start it as soon as possible.

**Comment by pumano** [comment]
Hello guys, I have some time for create reusable (mostly draft) component. You can check it via stackblitz: https://stackblitz.com/edit/angular-clarity-donut-chart

Component have possibility to override some settings via options.

I know it's not finished version and not cover most cases, if you need that component, you can review code, and then provide me info how I can submit it and what changes I need to do for meet your needs.

**Comment by gnomeontherun** [comment]
Thanks for the update, we'll review this to decide if this is something we are really ready to incorporate or not, and if so we can do a deeper dive on the design.

**Comment by gnomeontherun** [comment]
Thanks @pumano for the initial design, we are going to have our UX design do an audit of this and we're not planning to talk about this as a doughnut chart since it is more of a progress bar in a circle. It could be used for a loader indicator but without more interactivity we don't think its a chart. We'll circle back soon with design inputs.

**Comment by pumano** [comment]
It can be used as progress bar for loading and as chart for example for dashboard, for showing progress in my case.

**Comment by colinreedmiller** [comment]
There is a need for a large label / value display component, of which circular progress is a part. Often values are important in the information hierarchy, particularly in dashboards as in the above example where the design uses a double affordance to illustrate the value of 85% - both numeric and with the circular progress bar graphic.

This may be the best choice for some use cases, while others may see the graphic as purely decorative, or may require a different graphic such as a trend line, may have layout needs that make a circular graphic representation inappropriate, or may simply prefer a textual / numeric label value pair that works graphically because of its design (size) e.g.

![Screen Shot 2019-05-09 at 9.26.36 AM.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/73f93ea8-c74c-4233-aee8-d479c1315f68)

![Screen Shot 2019-05-09 at 9.26.04 AM.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/bbfcf251-676c-456b-9727-c308447819c7)

![Screen Shot 2019-05-09 at 9.36.59 AM.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/582384fd-e8b9-4f30-8153-a5526879fcd7)

The design for this should cover a small variety of styles, allowing the designer using the component to utilize the attributes most suited to their use case.

**Comment by mathisscott** [comment]
@colinreedmiller 
Re: circular progress. I don't see any example of that above. Are we still waiting on that design?

**Comment by colinreedmiller** [comment]
@mathisscott - We have no design yet. My point above is that circular progress is a single case of large label/value and any component that addresses this need should consider a few standard depictions of large label/value rather than simply focusing on the use of a circular indicator only.

**Comment by colinreedmiller** [comment]
Moving forward with Circular Progress as defined here and tabling additional label/value dashboard widgets as referenced in #1810 for the time being.

UX recommendation is full circle and half circle variations including label and value with animation on load. I will do some research on this leading to the creation of a design spec.

**Comment by colinreedmiller** [comment]
@pumano are you able to contribute to this? I did some initial studies using our type classes, colors and size conventions to get started in alignment with Clarity.

**Comment by pumano** [comment]
@colinreedmiller yes, I can, just tell me what to do :)

**Comment by mathisscott** [comment]
@colinreedmiller 
When you get the chance, could you post a link to your design here so I can work off it? This is a 20% time project for me over the next couple of months.

**Comment by mathisscott** [comment]
Closing this so we can move dev work through #4043
