### ISSUE TITLE
[TreeView][Lazy Loading] The tree view arrow remains visible, even though there are no child nodes below it

### ISSUE THREAD

**Issue by MartinPenev** [vmware/clarity#2262]
Migrating from version 0.9 to 0.10, the docs are suggesting that clrTreeNodeExpandable property is not needed anymore and it will be detected automatically by clrIfExpanded directive (https://vmware.github.io/clarity/news/0.10.0-alpha)

> Not needed anymore because tree nodes automatically detect and register the clrIfExpanded directive to make themselves expandable

However after expanding a node that has no children the "expand-collapse" arrow remains visible, and since clrTreeNodeExpandable property is missing from version 0.10 we are unable to hide the icon, even though we know there are no children below it - hence no use of it.

Is this a regression or I'm doing something wrong?

**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The arrow should be hidden if there are no children according to the migration notes (to 0.10).

### Actual behavior
The arrow is not hidden.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-dark-theme-v10-skt1rg?file=app%2Fapp.component.html

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.27

* **OS and version:** 

* **Browser:** all

**Comment by youdz** [comment]
The problem is that we can't remove the caret for you as we have no guarantee that the node won't have children in the future. If these were more dynamic resources than office locations, handled concurrently by several users, I could expand and get no children, collapse, and 2 minutes later expand again and finally get children that were just created by someone else. In other words, this "was expandable but actually isn't" is not something we can do on our side, you still have to handle it on yours just like you did with `[clrTreeNodeExpandable]`.

If you know you won't have children ever _after_ trying to lazy load them, then you should store that in a boolean just like you did before with `[clrTreeNodeExpandable]` but now you use it on a simple `*ngIf` rather than a custom Clarity input. 
### Before:
```html
<clr-tree-node [clrTreeNodeExpandable]="expandable">
  My node
  <lazy-loaded-children></lazy-loaded-children>
</clr-tree-node>
```
### After:
```html
<clr-tree-node>
  My node
  <ng-template clrIfExpanded *ngIf="expandable">
    <lazy-loaded-children></lazy-loaded-children>
  </ng-template>
</clr-tree-node>
```
Your component's code stays exactly the same, your template just goes through this minor modification. And you get the benefits of proper children lazy-loading.

Here is an example of what it would look like (it'd be much better with proper components and a provider for each node, but I just quickly edited your example): https://stackblitz.com/edit/tree-lazy-loading-zero-children?file=app%2Fapp.component.html

**Comment by MartinPenev** [comment]
Actually I was looking for something that works like clrTreeNodeExpandable and your suggestion works perfectly. Thanks!
