### ISSUE TITLE
Pagination component 

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#2268]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
In [this page](https://vmware.github.io/clarity/documentation/v0.11/cards) you suggest to implement a switch between a card view and a datagrid view.
In case of large dataset I want to use pagination to load data from the server, with datagrid I can use the pagination control while there's noting can be used in Card View.

In general a "generic" pagination control would be useful in many scenarios not only involving datagrids

**Comment by d-m-s** [comment]
I was searching exactly for the same component: a generic pagination!

Especially as the pagination in the datagrid is quite small, it's hard to use on touch devices, and therefore a solution to iterate through eg. cards with a generic pagination component would be fine!

Imagine any kind of search where you don't want to present the search results in a datagrid, so you'll end up with cards quickly.

**Comment by adityarb88** [comment]
cc: @reddolan

**Comment by reddolan** [comment]
@adityarb88 yeah, this is what I have been thinking about too, is pagination outside and inside datagrid. Will make sure we include this use case when we start working on this

**Comment by reddolan** [comment]
@mcosta74 in the mean time, your suggestion is a good one that can get you by until we finish work on this.

**Comment by d-m-s** [comment]
hi @reddolan we really would like to have such a component in clarity! we start developing it, but would really look forward to contribute here to clarity. currently we would base the styling on the buttongroup component and follow the same patterns as the pager in the datagrid. is this fine with you, do you've any more advise for us?

**Comment by mcosta74** [comment]
Since I'm working to the migration to Clarity from Boostrap I'm implementing similar to the Bootstrap Pagination component.

Here a screenshot of the UI

![screen shot 2018-05-18 at 13 43 02](https://user-images.githubusercontent.com/3706809/40232998-708bb702-5aa1-11e8-80f9-4d2339c00e14.png)

**Comment by mcosta74** [comment]
Hello there, 
[here](https://stackblitz.com/edit/clarity-pagination-control) the first implementation.

I'm going to add `maxSize` and `scrolling feature

**Comment by hippee-lee** [comment]
Hi @mcosta74 and @d-m-s Thank you, we really appreciate your interest in contributing to Clarity.

While you are still getting started I'd like to point you to our [Contributing Guidelines](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md) as well as our [Code Contribution](https://github.com/vmware/clarity/blob/master/DEVELOPMENT_CONTRIBUTION.md) and [Coding Guidelines](https://github.com/vmware/clarity/blob/master/CODING_GUIDELINES.md) in order to prevent any unneeded back and forth for both the design and the implementation phases. 

Let us know if you have any more questions after taking a look at the guidelines for contributing to Clarity.

**Comment by mcosta74** [comment]
Hi @hippee-lee,

as I said before I'm not a UX designer so my implementation is only an example of what I'm doing while I'm migrating my application to Clarity.

Since this will be a new component, if I understood correctly, I shall wait for a approved UX design before start coding.

**Comment by ihildebrandt** [comment]
Has there been any movement on this? I'd like to use a generic pagination component.

**Comment by LeandroDoldan** [comment]
Same here.

**Comment by gnomeontherun** [comment]
This would be a great contribution. We changed the pagination design already so that work has been done. I would expect a similar pattern, but we need to do some diligence to understand it holistically. 

If anyone is up for it, the basic steps are:

1. Research other pagination components and compare
2. Write up a more formal and complete design spec for us to review, think MVP and then identify enhancements
3. After design approval, we can talk about API design
4. Build the implementation
5. Submit PR and documentation

**Comment by robsull** [comment]
I'd like to keep the same data set when switching between datagrid and card views. So if I'm on page three of the list and switch to cards I will be on page three of the card view. So ideally, the paging control for a card view would feel similar to paging on the list, with the same info and controls.

**Comment by gnomeontherun** [comment]
Shipped in 5.2.0

**Comment by mcosta74** [comment]
Great, thanks folks
