### ISSUE TITLE
[Icons request] social networks icons

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#2276]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Would be good to have icons of popular social networks:
facebook;
twitter;
github;
linkedin;
and etc

**Comment by adityarb88** [comment]
@lil-kim @mathisscott: Could you please take a look at this request?

**Comment by youdz** [comment]
I remember us considering it a while back and running into legal issues. Not sure what's the current status, but any attempt to work on this will have to go through legal first. 😞

**Comment by lil-kim** [comment]
Hi @pumano,
Youdz is correct. We can’t distribute other companies’ branded logos due to legal issues. 
All of these companies have very strict guidelines for how their logos can and cannot be used. For instance, Instagram’s guideline says : “Only use the official brand assets that are available from Instagram’s Brand Resources website". I know that these icons exist online in many forms in free icon packs, but Clarity as a part of VMWare cannot take the legal risk.

**Comment by lil-kim** [comment]
@pumano Thanks for understanding :-)

**Comment by hippee-lee** [comment]
@pumano - fyi - if you wanted to make your own icons for the social networks your app needs you could still do use the [clarity icons api](https://vmware.github.io/clarity/icons/api) to add something that meets your needs.

After you import ClarityIcons into your app you can add a custom icon with this:
```
ClarityIcons.add({"my-custom-icon": "<svg ... >[your SVG code goes here]</svg>"}); 
```

And then you can use it like this
```
<clr-icon shape="my-custom-icon" size="24"></clr-icon>
```

**Comment by pumano** [comment]
@hippee-lee thank you, I will try your solution, it looks good to me!
