### ISSUE TITLE
Move Clarity UI components to Angular Elements

### ISSUE THREAD

**Issue by gearsandcode** [vmware/clarity#2280]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

Transition of Clarity UI components to Angular Elements. I'm just curious if this is on the road map.

**Comment by mathisscott** [comment]
Hi @gearsandcode 
Far future. Possibly.

**Comment by gearsandcode** [comment]
@gnomeontherun - Sure. I'm looking to use Clarity as a solution in a large enterprise setting. We have several projects using different frameworks in addition to Angular. I need my components to be available to the various Angular apps via our internal package manager (Artifactory). Then, once Elements can be used to create components as vanilla JS that we can use in other frameworks, we'll make the changes needed to do that and have a single source of truth across the entire enterprise. This is what I consider the holy grail of enterprise components.

**Comment by mathisscott** [comment]
Hi @gearsandcode 
This is great information. Thank you. I can take this and communicate it to our corporate overlords. I think it is a use case that also applies to many product teams within VMware as well.

**Comment by gnomeontherun** [comment]
The biggest challenge right now is how to efficiently build and distribute components. There is no real tooling built yet for this, and therefore using components standalone will likely incur a large amount of duplicated code because each web component will share a lot of similar pieces. This is definitely something on my radar, but it really depends on prioritization and ability to make a reasonable bundle size for these elements. You can do it today, its just going to have excessive code and be a bit unwieldy to maintain.

**Comment by sdurnov** [comment]
@gnomeontherun bundle size is not THAT critical for many enterprise apps.

Btw, I have different scenario: we're migrating old Durandal large SaaS to Angular. It's not possible to migrate all modules quickly, so we'd like to have at least unified shell for both old and new apps, switching between them without changing UI dramatically. If Clarity would provide web components, we'd just use single component for layout and menu.

**Comment by gearsandcode** [comment]
@sdurnov - Agreed, the benefit of shared components outweighs the bundle size concerns right now.

**Comment by gnomeontherun** [comment]
We have an alternative plan that will address this in the future, closing this in favor of future work.

**Comment by TekSiDoT** [comment]
Looking forward to it!
