### ISSUE TITLE
Dropdown button with position: absolute overrides by position: static

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#2332]
**Select one ...** (check one with "x")

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When I set to `clr-dropdown` css: `position: absolute;` component should not override it with `position: static;` when I click on it.

### Actual behavior
I have usecase where I want to use dropdown with icon as dropdown menu. I'm positioning that dropdown as absolute value in card. But when I click to dropdown button it overrides my `position: absolute` styles.
Check screenshots below.

### Reproduction of behavior
<img width="1437" alt="before-click" src="https://user-images.githubusercontent.com/17675259/40889729-7a6dbb1e-6774-11e8-8a75-1a70af03600a.png">
<img width="1439" alt="after-click" src="https://user-images.githubusercontent.com/17675259/40889731-7feb6ba4-6774-11e8-9d99-5ce02433c304.png">

  
  
  
  

### Environment details

* **Angular version:** 6.0.3

* **Clarity version:** 0.11.20

* **OS and version:** MacOS High Sierra

* **Browser:** Chrome 67

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
