### ISSUE TITLE
Signpost disappears when scrolling

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2333]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Signpost stays open when you scroll the page.

### Actual behavior

The signpost closes itself as soon as you start scrolling. As in the documentation it says:

> A vertical scrollbar (browser default) may be used if the content exceeds the maximum height of the dialog.

I consider this a bug and not a feature, because you can never view content inside a signpost that is scrolled out of view.

### Environment details

* **Angular version:** 5.2.10

* **Clarity version:** 0.11.16

* **OS and version:** MacOS 10.12.6

* **Browser:** Tested on Chrome 66.0.3359.139 and Firefox 59.0.2

**Comment by adityarb88** [comment]
@dorthrithil: I am not sure if I understand the issue here. Please take a look at this StackBlitz:
https://stackblitz.com/edit/clarity-light-theme-v11-kgpfey?file=app/app.component.html

I am able to scroll the overflowing content in the signpost but our UX recommendation is that scrolling outside of the signpost should close the signpost itself.

![image](https://user-images.githubusercontent.com/1426805/40921728-4d24db46-67de-11e8-9583-099f0eb25e54.png)

This is the expected behavior specified by our UX team.

**Comment by dorthrithil** [comment]
OK, I checked the StackBlitz and it looks good there. The issue in my usecase seemed to be the usage of the Signpost inside another scrolling element which somehow sometimes catches the scroll event? Anyway, I think that's not a Clarity issue, I will fix this myself.
