### ISSUE TITLE
Datagrid height in modal is calculated incorrectly

### ISSUE THREAD

**Issue by jokarmus** [vmware/clarity#2364]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Visible Datagrid with records

### Actual behavior

Invisible Datagrid. Actually, height style is set to 0px (ng-reflect-selected="" style="height: 0px;")
The problem occurs when using smart iterator:

`       <clr-dg-row *clrDgItems="let user of users" [clrDgItem]="user">
`

Using ngFor everything is fine.
Latest working version is 0.11.17. I think the bug appeared after fix [#2258](https://github.com/vmware/clarity/pull/2258)

### Reproduction of behavior
1. Add users to collection
2. Show Modal

  Clarity Version: [Light Theme v11](https://stackblitz.com/edit/problem-with-datagrid-in-modal)

### Environment details

* **Angular version:** >=5.2.11

* **Clarity version:** >=0.11.17

* **OS and version:** Windows 10

* **Browser:** all

**Comment by gnomeontherun** [comment]
This looks like an issue with lifecycle and when it calculates. It might be the animations that hide and delay the ability to compute the correct values so it ends up as 0 if we run it too early.

**Comment by youdz** [comment]
This is because we are still not using structural directives for our modal, which has been in our backlog for a long time. 😞 

The workaround is pretty easy, just put and`*ngIf="open"` on the modal itself, the modal body or the datagrid, whichever you prefer. This will properly instantiate the Datagrid when you need it and everything will display fine: https://stackblitz.com/edit/datagrid-modal-fix?file=app/app.component.html
One important note here is that this is actually better for performance, because without the `*ngIf` you have a full-blown datagrid instantiated and running even though you are not displaying it. It's generally not something you want.

**Comment by mathisscott** [comment]
#895 should fix this once we get to it.

**Comment by juanmendes** [comment]
A workaround is to use `height: auto !important` if you are not able to change your code to use two way binding

**Comment by larsk27** [comment]
> A workaround is to use `height: auto !important` if you are not able to change your code to use an `*ngIf`

Great Workaround!
Had the same issue with a Datagrid in a Wizard page.
Thanks for this!
