### ISSUE TITLE
Datagrid with only one item display with a blank row

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#2372]
**Select one ...** (check one with "x")

```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Datagrid with only one item should not show a blank row.

### Actual behavior

Datagrid shows the one item and a blank row. This does not seem like the desired behavior. Two items show as two rows (with no blank).

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v11-jaqjff

(or go to Clarity docs, datagrid full demo, and enter 1 for the count.

### Environment details

* **Angular version:** any

* **Clarity version:** 11

* **OS and version:** osx 

* **Browser:** all

**Comment by hippee-lee** [comment]
The reason there is a min height on a datagrid is because we have to accommodate the loading spinner.  

This was filed discussed previously here: https://github.com/vmware/clarity/issues/402#issuecomment-274880337

That said, can you let me know a little more about your use case for a datagrid that only has a single row?

**Comment by rongery** [comment]
That's unfortunate, but it makes sense.

I have a table of created objects. It's possible to have just one, and it's possible to have 100+, so the table makes sense for the general case, though it's obviously not ideal for the "one case". Ultimately, not a very big deal.

Thanks for the quick reply.
