### ISSUE TITLE
Data-Grid: Select All not propagated to item.selected

### ISSUE THREAD

**Issue by busino** [vmware/clarity#2401]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Use `[(clrDgSelected)]` to have selection flag set on every object selected.
This works fine when selecting entry one-by-one.
But if you click on checkbox in datagrid to select all items the flag is not propagated to the item.seleted flag.

### Actual behavior
See above.

### Reproduction of behavior

https://stackblitz.com/edit/angular-ekhwqg

Select items and click `Apply`.
You can see the selection and the values for `item.selected`
Select all items by checkbox in header row:
`item.selected` is not set!!!

### Environment details

* **Angular version:** 6.1.0
* **Clarity version:** 0.12.1
* **OS and version:** hihi-OS

* **Browser:** [all ]

**Comment by StefanTT** [comment]
This is also very visible if you add pagination to a datagrid and switch between pages. The rows that were single selected keep their selection state but the select-all is lost.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
