### ISSUE TITLE
Enable Content Projection for columns and/or other inner components of the Data Grid component

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#2420]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
I have a base component that wraps the data grid component. It handles all the necessary functions to load the data from the server, provides pagination, filtering, sorting, etc. This component is used by multiple views/screens in the application. Each view just passes a server-side resource input that will be used by the base component to load the data. These views/screens have similar purpose: to display data in the grid. The only difference is the columns being displayed. They differ on the number of columns, the type of columns, etc. Hence, data grid columns should not be placed inside the grid of the base component. To address this, I have to use Angular's content projection.

```html
<app-gridpanel>
    <clr-dg-column>Id</clr-dg-column>
    <clr-dg-column>Item No</clr-dg-column>
    <clr-dg-column>Description</clr-dg-column>
</app-gridpanel>
```
### Actual behavior
Unfortunately, Clarity data grid doesn't support content projection. Columns can't be projected and generates errors:
![image](https://user-images.githubusercontent.com/1977391/42234054-cec4b5c8-7f25-11e8-82cb-e6f6d09fc10a.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  
https://stackblitz.com/edit/clarity-light-theme-v11-x5hujx
### Environment details

* **Angular version:** 6.x.x

* **Clarity version:0.12.2

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
We do support content projection, that's the entire basis of our API.

The problem is that you are wrapping part of our datagrid while still using others as part of your own public API. This is something that hardly ever works in Angular, it leads to many issues like the one you have here and there is nothing we can do on our side, your wrapper has to handle it or wrap _everything_ instead of just some pieces.

Regarding this specific error, what happens is that columns require providers declared by the datagrid, but in your case the datagrid is in the **view** of your `app-gridpanel` component. Angular's hierarchical dependency injection works based on where a component is used, not where it ends up being displayed. In the example you are showing, the columns' parent is the `app-gridpanel`, not the `clr-datagrid`. As I said, hiding some components and not the other completely breaks Angular's dependency injection when you use tightly coupled components.
