### ISSUE TITLE
Provision to allow clr-tooltip width to be auto (fitting the content)

### ISSUE THREAD

**Issue by gerinjacob** [vmware/clarity#2449]
**Select one ...** (check one with "x")

- [ ] bug
- [ ] feature request
- [x] enhancement

### Expected behavior

When the tooltip text is dynamic, fixing the clrSize (xs, sm, md, lg) to a specific value is difficult. It will be better if,
1. clrSize can take `auto` that sets `tooltip-content` width to auto. 
   OR
2. based on clrSize (xs, sm, md, lg) set max-width and keep width to auto always, so that small tooltips will not be stretched.

### Actual behavior

clrSize takes fixed values (xs, sm, md, lg)

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v11-ezysa3

  
  
  
  

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.11.x

* **OS and version:** all

* **Browser:** all

**Comment by adityarb88** [comment]
@gerinjacob: I believe both the solutions you mentioned above will clip the content once we hit the max-width. You can see that over here: https://stackblitz.com/edit/clarity-light-theme-v11-fmps1c?file=app%2Fapp.component.css

I believe that is why we assign it a `width` so that once the content hits the `width` limitation, it wraps to the next line. If you do not want the content to wrap, you could add this style at your end. Let us know if that helps.

Closing the issue based on the above info but please feel free to reopen the issue if you have more questions.

**Comment by gerinjacob** [comment]
Clipping happens with existing style also right? A tooltip content with no whitespace will not wrap even now. That is not my concern. I am okay with content to wrap, my issue is when the tooltip is small, it looks stretched
![image](https://user-images.githubusercontent.com/7568688/42575881-004b0452-853f-11e8-9114-8abe9a61be25.png)
I prefer,
![image](https://user-images.githubusercontent.com/7568688/42576130-516a011c-853f-11e8-852f-b8f2e09bb5a5.png)

**Comment by adityarb88** [comment]
@gerinjacob: Even then it doesn't work as expected. Please take a look at this: https://stackblitz.com/edit/clarity-light-theme-v11-fmps1c?file=app%2Fapp.component.html

Even though the `max-width` is `500px` and the `width` is `auto`, `position: absolute` has does not behave as expected. If I remember correctly, this is a limitation with `position: absolute` elements. I can't find the link which explains this right now though.

**Comment by gerinjacob** [comment]
Not sure what I am missing, the following style works for me,
```
.tooltip .tooltip-content.tooltip-md {
  width: auto;
  max-width: 10rem;
}
```
https://stackblitz.com/edit/clarity-light-theme-v11-vhirrs

**Comment by adityarb88** [comment]
@gerinjacob: It totally depends on the parent container width. For eg: please take a look at this: https://stackblitz.com/edit/clarity-light-theme-v11-a3svpb?file=app/app.component.css

I have wrapped the above tooltip in a container which is inline-block and has a smaller width. In that case, the tooltip does not behave the same way as expected. This is one of the reasons why we wanted to provide with various sizes for the tooltip so that users could find a way around this issue. If you parent container has a larger width, I would still recommend to use the styles you mentioned above at your end.
