### ISSUE TITLE
Datagrid with actions inside an iframe overlaps columns

### ISSUE THREAD

**Issue by javierfz1980** [vmware/clarity#2455]
**Select one ...** (check one with "x")

```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When the Datagrid is running inside an iframe and if it has enabled <clr-dg-action-overflow> it should auto fix columns width to the contents like it does when it doesn't has <clr-dg-action-overflow> enabled.

### Actual behavior

When the Datagrid is running inside an iframe and if it has enabled <clr-dg-action-overflow> it doesn't fix columns width to the contents.

### Reproduction of behavior

![datagrid-columns-iframe-issue](https://user-images.githubusercontent.com/36636787/42654191-2fc5d978-85ee-11e8-8181-7aa8058f3d85.gif)

You can reproduce the issue in the following link, please make any change in the app component (eg: change Home text button) and save it to reproduce the issue in the iframe view:

https://stackblitz.com/edit/clarity-light-theme-v11-pvcrub

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:** 0.11.9

* **OS and version:** OSX 10.13.5

* **Browser:** Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
