### ISSUE TITLE
DatePicker reset with Form usage

### ISSUE THREAD

**Issue by cptblues** [vmware/clarity#2474]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When I use FormControl on my DatePicker field, if I apply a reset on my form, I didn't want DatePicker remember the old date. I should enter the same date as before.

### Actual behavior

When I reset my FormControl, I can't choose the same date as before. The only way I found is to use the "Two-way binding" and declare var for each datePicker and set manually "undefined" for each var when I reset my form.

* **Angular version:** 5.1.0

* **Clarity version:** 0.11.17

**Comment by youdz** [comment]
The description of the bug is a bit vague, could you please post a StackBlitz reproducing the issue? Here is a link to our standard StackBlitz: https://stackblitz.com/edit/clarity-light-theme-v012
Thank you.

**Comment by mathisscott** [comment]
@cptblues 
Any update?

**Comment by youdz** [comment]
I did a quick investigation. We listen to changes to the control through the `valueChanges` Observable, which according to the docs fires on a form reset. The problem is that to avoid un-setting the date when the user is halfway through typing one, we ignore values that are not valid dates.
The result is that the HTML input itself shows no value, but our services still believe the previous value is selected.

I think we still want to ignore invalid values from the form control, but we should have a special case when the value is `null` or `""` to actually reset our services too.

**Comment by exequiel09** [comment]
Hopefully this can be ported back to 0.12.x. This is also my issue when using the datepicker component.
