### ISSUE TITLE
Passing a value to clrDgSingleSelected  doesn't make the row appear as selected.

### ISSUE THREAD

**Issue by dennitsa** [vmware/clarity#2500]
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Passing value into clrDgSingleSelected should make the row appear selected.

### Actual behavior
Passing a value to clrDgSingleSelected  doesn't make the row appear as selected.

My workaround for the time being is to use v0.11.21, where this is not happening, but this definitely needs a fix.

### Reproduction of behavior

This is reproducible in v0.11.25( See https://stackblitz.com/edit/clarity-light-theme-v11-rakdgv)
As well as in the latest v0.12.5 (See https://stackblitz.com/edit/clarity-light-theme-v11-nbupfw)

### Environment details

* **Angular version:** 5.x.x & 6.x.x

* **Clarity version: ^v0.11.25

* **OS and version: Any

* **Browser:** [all]

**Comment by youdz** [comment]
To help out whoever is going to pick this up, I'm copy-pasting here what I wrote in the issue this was split from:
> I remember we had a very similar issue a while back which we solved with debouncing. The debouncing became useless around 0.10.x, but it seems like latest refactors might have brought the issue back. Your bug clearly needs proper investigation, so creating a separate issue for it means we can consider it in our planning sessions. 👍

I think the cause of the issue is that due to the default instantiation order of our components by Angular, the current selection is set before the list of items and their `trackBy` function is available to us, and when we finally receive the list of items it ends up canceling the pre-selection because it could not find the correct item.

**Comment by ivanbest** [comment]
Hi team, this impacts my team too. Could you prioritize accordingly ?

**Comment by jordanovi** [comment]
Hi team, this impacts my team too. Could you prioritize accordingly ?

**Comment by dkanev** [comment]
I hit the same issue. The  Selection service (https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/providers/selection.ts) emits undefined.
See:
https://stackblitz.com/edit/clarity-light-theme-v11-26gr

Is there a workaround for this?
