### ISSUE TITLE
ClrLabel throws an error when element class attribute is not set

### ISSUE THREAD

**Issue by HitkoDev** [vmware/clarity#2511]
**Select one ...** (check one with "x")

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

https://github.com/vmware/clarity/blob/794ee83bc7aae3b1d4c53a093d56cf69f8679979/src/clr-angular/forms/common/label.ts#L39 throws an error (`Cannot read property 'indexOf' of null`) when label element doesn't have a `class` attribute.

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v012-g7vtt9

### Environment details

* **Angular version:** 6.1.0

* **Clarity version:** 0.12.6

* **OS and version:** Win 10

* **Browser:** all

**Comment by gnomeontherun** [comment]
We haven't released a `clrCheckbox` component yet, so that is why you're seeing this error. I'll keep this bug report open to harden against this case, but so far we have the clrInput, clrTextarea, and clrPassword components released. clrSelect and clrRadio are open PRs, and a few more will follow soon.

**Comment by gnomeontherun** [comment]
This was fixed in the radio form changes, closing as fixed in 0.13
