### ISSUE TITLE
Custom filters tied to cells in the column rather than row objects?

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#2513]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Users should be able to define column-agnostic filters that apply only to the column that the filter is associated with.

Currently, users can use the `[clrDgFilter]` and `[clrDgStringFilter]` input to create their own custom filters.  However, the power of these to filter on any property in the row also makes them less generic.  

For example, I would like to create a slightly modified version of the string filter that allows for logical OR string searches using the `|` character.  For example, this might be attached to the Pokemon name column, and the user could enter `pik|rai` to match both `Pikachu` and `Raichu`.  

This works great for a single column in the current interface -- I create a class that implements `ClrDatagridStringFilterInterface` and then pass it to `[clrDgStringFilter]`.  The problem is that the class `accepts` function receives the row object rather than the values in the column, so the column property is hardcoded in it.  If I want to attach this type of filter to n string columns, then I need to create n different instances of the class with slight modifications, one for each column.  This is not a big issue, but it seems clunky.   

It's likely that there's some easy trick I'm missing that gets around this, but I wasn't able to figure it out after trying several things.  In this case, it might be good to document how to do this since it seems like a pretty common use case.  

### Actual behavior

As described above

### Reproduction of behavior

https://clarity-light-theme-v012-zi1jt2.stackblitz.io

### Environment details

* **Angular version:** 6.x.x

* **Clarity version:** 0.12.*

* **OS and version:** Any

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
This is a worthwhile enhancement request, but is challenging to implement due to the existing behaviors and nature of Clarity Angular. As we build out Clarity Core, this should be possible to realize with the applications managing the state and functionality more directly instead of Clarity Angular. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
