### ISSUE TITLE
[Request] Generic/universal overlay

### ISSUE THREAD

**Issue by m-tomczyk** [vmware/clarity#2529]
**Select one ...** (check one with "x")

```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior

While clarity provides specialised overlay panels such tooltip and signpost it lacks simple, generic one. Tooltip works as intended and signpost is good option if you need to provide some information/documentation that is read-only but if there is need to provide some interaction in overlay panel there is no valid alternative. Signpost comes with quite restrictive styling that needs to be overridden which is cumbersome and prone to future break.

Looking at source `PopoverDirectiveOld` is used to create hide/show overlay for datagrid (with is good example of what is my use case) and there is `AbstractPopover`. Either could be released as public API but maybe it would be better If they remain as internal and new component similar to signpost but more extendable/less specific be created. This would give possibility to revise internal popup workings and not introduce breaking change.

As for workarounds: 
- Create overlay panel from scratch
- Use dedicated library (Maybe Angular CDK)

Nevertheless I think It would be optimal if Clarity provided such component/directive with minimal styling that would be compatible with rest of UI components.

Related: https://github.com/vmware/clarity/issues/1673

### Actual behavior

Lack of generic/universal overlay

### Reproduction of behavior

N/A

### Environment details

* **Angular version:** ^6.0.0

* **Clarity version:** ^0.12.0

* **OS and version:** N/A

* **Browser:** all

**Comment by youdz** [comment]
Actually, we made the choice not to have a public generic overlay because many its uses would go against our design recommendations. Clarity is an opinionated design system, and as such we want to control which specific uses of overlays we want to facilitate.

If you want overlay and insert a form in there, we recommend you use a modal dialog. If you simply have a list of actions to perform, then a dropdown is your best choice.

The documentation for signposts doesn't speak for all popovers, but being the most generic popover we provide it provides insight in what kind of behavior we **want** to support:
>Recommendations
>- ...
>- With the exception of text/image links, don't insert any actionable components, such as buttons, in the dialog
>- Don't rely on signposts as a primary method of displaying additional information - i.e. as a way to save space on a page
>- Use sparingly as a device to add immediate, relevant information

If you shared with us the use case you feel needs a signpost or some other form of overlay with actionable elements inside, maybe we could either point you towards the pattern we recommend using, or maybe identify a new type of overlay we want to support.

**Comment by m-tomczyk** [comment]
What I want to accomplish is popover containing page/partial page settings. These settings consists of few checkboxes (show/hide for elements on page) with pair of buttons associated with this page settings. Checkboxes are grouped and in columns. As for requirements, this controls cannot be always visible, must not require page change to access and controls should cause intimidate action (this should not be form with submit button). 
Also I'll have few similar popup menus that will consist of few toggles, sometimes single input field and button. Example here is download button that lets user to chose some options before sending content.

I think that modal dialog is very much overkill and it should contain form with submit, not controls that change state on the fly. As pointed signpost should not contain such controls. I did not consider dropdown but it looks like it is not good fit either - It's rather restrictive to button actions only.

This use cases are very specific and require full control over popover contents and providing specialised popovers for all possible cases does not seem feasible so I guess this is just out of clarity scope?

**Comment by youdz** [comment]
Ok, I understand the use case better now. It's always helpful to have an example, and I believe what you want is something similar to the "Share" popover on StackBlitz:
<img width="643" alt="screen shot 2018-08-10 at 08 37 10" src="https://user-images.githubusercontent.com/4647197/43958278-ce6b4130-9c78-11e8-912a-4d88efa9d66f.png">
For the StackBlitz example, moving to a new page for this menu would be severely overkill, but the content of the popover is large enough that you can't have these options displayed at all times.
Please correct me if you think this is not a good example of your use case.

I'll let our UX designers take a look at this to see how we want to address this.

**Comment by mathisscott** [comment]
My initial thought was that this would be a "mega menu". But I'm wrong on that. If this were to be offered, what use cases specifically would we be addressing? And why would a user use a form inside of a dropdown instead of a modal or a panel that slid out from the right or something like that?

I understand the use case somewhat. But I think we need to be clearer on when this pattern is appropriate for use – especially compared to existing patterns and patterns we have committed to in the future – to avoid a situation where we have 3-4 different patterns/components and developers have no clear guidance on which one is the best one for their use case.

**Comment by m-tomczyk** [comment]
I looked at possible use cases and I think it could be broken down into two distinct ones:
1. Providing real-time-effect controls
2. Providing micro-forms

As for real-time-effect, it's use case that is already present in clarity. For example there are overlay controls for datagrid such as filtering
![clarity_filter_dg](https://user-images.githubusercontent.com/24605528/44056128-99318106-9f47-11e8-9a73-226cd1718914.png)
and show/hide (This has button but it's going away according to https://github.com/vmware/clarity/issues/2100 )
![clarity_show_hide_dg](https://user-images.githubusercontent.com/24605528/44056143-a511ef92-9f47-11e8-902c-f009651efd92.png)
I can add mock example of class of usecases that will be valid for me (I know I abuse signpost here, but it's just to showcase)
![mock_settings](https://user-images.githubusercontent.com/24605528/44056211-d5861bc6-9f47-11e8-87bc-27c888725e50.png)


And the other one, micro-forms, are things that could go into modal but I feel that if they are small enough and/or are strongly attached to certain part of UI it isn't good idea to rip it from there and put in modal. Similar for sliding panel - they would feel disconnected in my opinion. Apart from show/hide mentioned above that will be changed, clarity does not have such cases. New gmail could be example here. This would work as modal as it's quite big form but it feels in right place as it overlays next to search box - it's connected to that part of UI. 
![gmail_search](https://user-images.githubusercontent.com/24605528/44056518-cb5cfbbe-9f48-11e8-9ab9-83c85a3ebf34.png)
Another mock example - download button that will be closer to my usage
![mock_download](https://user-images.githubusercontent.com/24605528/44056609-03bf2e1e-9f49-11e8-80bd-353dd6a00279.png)
Here I feel that opening modal would be overkill - this should be quick to access, panel shouldn't cover all of data that will be downloaded so user could still look at it and decide on provided options. If done on modal, user would have to close it, verify and open again. This could be done as sliding panel without this problem but I feel that it would break flow. In worst case user has to go all the way from left to right side of screen (or other way) to continue interaction.

**Comment by gnomeontherun** [comment]
This is a long standing request, and I suggest that for Angular folks look at the https://material.angular.io/cdk/overlay/overview for a generic overlay mechanism. It can be styled and match Clarity, but we are not going to commit to making our Clarity Angular overlay public and supported since it wasn't built to be generic enough for these use cases. I'm going to close this as something we won't do with Clarity Angular.
