### ISSUE TITLE
Wrong colors in components

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2535]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Colours in components should match corresponding functional colours

### Actual behavior

Warning alert in light theme v.0.12 has real bg colour #FEECB5, where as in functional colours we have a value of #FEF3B5 in standard alerts colours.

Same thing for badges:
Purple badge has #9460b8 color in reality, where as in functional colours for badges there's only #9B56BB color. #9460b8 is not present in color palette at all.
Orange badge has #eb8d00 color in reality, where as in functional colours for badges there's only #FF8400 color. #eb8d00 is not present in color palette at all.

Same thing for buttons:
Primary/Info outline button and flat button has #0077b7 color in reality, should be #007CBB ? Or there should be some level of opacity applied?
Success outline button has #308300 color in reality, should be #308700

Cards borders and dividers are also have color out of palette. Same for Datagrid dividers.

### Reproduction of behavior
Compare [Functional colors v.0.12](https://vmware.github.io/clarity/documentation/v0.12/color)
with warning alert here - [Alerts v.0.12](https://vmware.github.io/clarity/documentation/v0.12/alerts) and other listed components.

### Environment details

* **Browser:** [Chrome 68.0.3440.106]

**Comment by youdz** [comment]
Thanks for reporting this, I will let UX determine which color is the correct one, and we can then either fix the color palette docs or fix our CSS.

**Comment by colinreedmiller** [comment]
Instructions for correct colors.

![2535 color pal issue.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/66177b89-4f1d-4e91-b254-fbca04529a3f)

**Comment by mathisscott** [comment]
Also #2784

**Comment by Jinnie** [comment]
Hi all, @colinreedmiller,
I have some questions about Issue 3 (b):

1. In the textual description we see a request to change #308300 to #308700. But on the mock image I see that #318700 has to be changed to #2F8400. I can do it, but I do not understand how this relates to the original request.
2. This color (#318700) is seen at 3 places on the website - general palette, buttons, badges. Do I need to change all 3 of them?
3. This probably will be answered by answering the above question (2.), but let me ask explicitly - where in code I also fix this color? Buttons, app-level alerts, labels, badges? Or anywhere I detect the old color is used.

Thanks you!

**Comment by mathisscott** [comment]
Hey @colinreedmiller 
I got this one. I'll answer it later today when I get free from meetings.

**Comment by mathisscott** [comment]
1.

**Comment by mathisscott** [comment]
1. Green needs to change from #318700 to #2F8400. This is because #318700 was not accessible against a background of #FAFAFA.  Changes to demo app: • On color palette page (http://localhost:4200/color/color-palette) - change #318700 to #2F8400. #2F8400 is only accessible against white. Both text and color need to change. 
Changes to website:
On website (https://vmware.github.io/clarity/documentation/v0.13/color)
• In color palette, change #318700 to #2F8400. #2F8400 is only accessible against white. Both text and color need to change. • In functional colors, change #318700 to #2F8400. #2F8400 is only accessible against white. Both text and color need to change. 
Across all Clarity:
• Change #318700 to #2F8400. This is a change I did a while ago. It looks like it got stomped on in a merge though. 
2. Yes.  3. When I make changes like this, I think it's easiest to just to a "Find in files" for the Hex value. Then I look at each instance and change it unless it's in some place weird like the `dist` folder. There are never that many actual instances of these hex values. You just have to remember to update the website branch too.  ===

For all the color changes @colinreedmiller mentions above, you will want to update the values in the demo app, ks-app, components, and then the website branch. 

Hope that helps!

**Comment by Jinnie** [comment]
Fixed for v1.0

**Comment by sdurnov** [comment]
@Jinnie one more:
badge-warning class uses #fdcf08 color (not in palette) instead of #FFDC0B
