### ISSUE TITLE
Update typography section on site and typography classes in CSS

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2540]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Typography in components should match classes in typography section of Clarity website.
Description of typography classes should list components that use such class correctly.

### Actual behavior

Right now most of the components doesn't use built-in typography classes, and description of each class in docs, where use cases for each class is listed, is incorrect.
Components very often use 1pt bigger or smaller text, than listed in typography docs, and almost always they use different line height, sometimes - different letter spacing.
So, documentation on typography right now is confusing.
I'd say you need a complete revision of it.

**Comment by gnomeontherun** [comment]
There are a couple of issues here. Typography is really about guidelines for content, and should not be conflated with the typography used inside of components.

1) I agree we should clean up the typography page to not reference components and focus instead of how this is typography for static content. We can do this now.
2) We should also spend some time when we have a design lead doing the work to consolidate and simplify our use of typography for consistency. This is a long term issue that reflects work that is likely to go into Clarity after 1.0.
3) I don't know that we want to actually use the typography styles in our own components, as it really depends on each component what we'll do. Again this depends on item 2.

**Comment by colinreedmiller** [comment]
I do not agree with the notion that type classes are for content and that should not be conflated with type specifications for components. By using classes in components theming is streamlined. While this may require a few more classes to address both component and copy needs, the benefit justifies the effort. 

The existing classes already refer to their use in components in the 'style name' column of the documentation. What is needed is a survey and consolidation of classes based on product and component needs. This will be a substantial effort - in the meantime an initial pass of type system incremental improvement is in flight.

This issue superseded by: https://github.com/clr-team/planning/issues/90
