### ISSUE TITLE
Different subnav for pages

### ISSUE THREAD

**Issue by yooouuri** [vmware/clarity#2558]
**Select one ...** (check one with "x")

```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Is it possible to create a different `<nav class="subnav">` for every page? For now I have my router outlet inside content-area.

For example I have a page with invoices, and in my subnav I want links like payed, closed, open etc.

But when I am at another page the subnav needs to be completely different.

### Actual behavior

Because my router is in the content-area, i can't change the subnav dynamically.

### Reproduction of behavior

Because its more of a question, I don't know if i need to share some code?

### Environment details

* **Angular version:** 6.1.x

* **Clarity version:** 0.12.8

* **OS and version:** Mac OS 10.13.6

* **Browser:** all

**Comment by gnomeontherun** [comment]
This is better off as a question on StackOverflow https://stackoverflow.com/questions/tagged/vmware-clarity, and it is more of a question about Angular routing patterns. If you want different subnav it would need to be defined in each route instead of once globally (or you'd have to build some kind of dynamic switcher for it).

Closing as a question for StackOverflow if you need further help.

**Comment by Yorer** [comment]
> This is better off as a question on StackOverflow https://stackoverflow.com/questions/tagged/vmware-clarity, and it is more of a question about Angular routing patterns. If you want different subnav it would need to be defined in each route instead of once globally (or you'd have to build some kind of dynamic switcher for it).
> 
> Closing as a question for StackOverflow if you need further help.

If it is possible, than very hard to create subnav for every component, because the subnav must follow the header immediately, which can cause troubles when he would like to define sub navigation on each route. That's why he opened this feature request I guess to resolve this problem later on.. I'm also interested in it.

**Comment by SayakMukhopadhyay** [comment]
It's totally possible out of the box and I have implemented it on a live website. The best I can do right now is give the link to the [source](https://github.com/SayakMukhopadhyay/elitebgs/tree/86dce64a361cefe21833da94f1cfba87539b7a94) and links to the live site which demonstrates this https://elitebgs.app/ and https://elitebgs.app/api/ebgs
