### ISSUE TITLE
Stack overflow doesn't tolerate Clarity questions without code snippets

### ISSUE THREAD

**Issue by tony-shannon** [vmware/clarity#2571]
FYI Your helpful site says Ask a Question and directs to Stack Overflow..
![image](https://user-images.githubusercontent.com/939996/44417626-f2e65600-a56d-11e8-9e93-50788e6c6a0a.png)

Just so you know guys, I did that and got a lot of hassle for asking a Clarity question on Stack overflow (with your vmware-clarity tag), in fact they deleted it, see exchange here
[Clarity.Framework._.appetite_interest.in.React.components_.-.Stack.Overflow.pdf](https://github.com/vmware/clarity/files/2307317/Clarity.Framework._.appetite_interest.in.React.components_.-.Stack.Overflow.pdf)

original URL
https://stackoverflow.com/questions/51952785/clarity-framework-appetite-interest-in-react-components

deleted question
![image](https://user-images.githubusercontent.com/939996/44417676-17423280-a56e-11e8-8373-1d7031acb786.png)

**Comment by gnomeontherun** [comment]
Hi there @tony-shannon, I'm not sure who deleted it, but it wasn't our team. 

However, it is not really a question that belongs on StackOverflow since it is more of a proposal to work together instead of a question about how to do something. We don't like to use GitHub issues for asking questions about how to use Clarity, as it clutters our view of our workload. 

I'm going to close this and will respond to your other issue shortly.
