### ISSUE TITLE
Button alignment is not proper

### ISSUE THREAD

**Issue by LokeshN** [vmware/clarity#2573]
## Describe the bug

Buttons with btn-link class placed on top of datagrid is having different spaces between them and also not left aligned to the grid

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v012-yryueu?file=src%2Fapp%2Fapp.component.html

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v012-yryueu?file=src%2Fapp%2Fapp.component.html
2.  Notice the alignment of the Add button wrt to the datagrid's left alignment
3.  Also notice the gap between the Add and Edit button which is more than Edit and Enable/Disable button

## Expected behavior

Space between the buttons should be same and also first button should be left aligned with the grid

## Versions

**App**

* Angular: [e.g. 6] ^5.2.0
* Node: [e.g. 8.10.0]>= 6 < 9
* Clarity: [e.g. 0.12.5]^0.11.20

**Device:**

* Type: [e.g. MacBook] Macbook
* OS: [e.g. iOS] ios
* Browser [e.g. chrome, safari]chrome
* Version [e.g. 22]68

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
The gap differences are due to the `min-width` on the `btn` class. I'm not sure we should change that even for this use case. Same for the first button alignment, the buttons would have to remove the padding from the buttons in your example.  It might be that this is a corner case that we do want to override for the  `.datagrid-action-bar`.

I think we need UX to weigh in here before we accept this as an issue to fix in Clarity. In the meantime, I have forked your stackbliz with css overrides that might be a workaround for you: https://stackblitz.com/edit/clarity-light-theme-v012-issue-2573

**Comment by mathisscott** [comment]
The workarounds should be sufficient if an application absolutely needs this. Our recommendation for button groups with datagrids is to use the outline buttons, not flat buttons.

flat buttons do not clearly denote actions in button groups as being grouped together, which would cause a problem if you had actions that only affected single entries versus the entire datagrid  or multiple entries. think a button group with add/edit/delete and a second button group with refresh/export. you have no way of understanding those are two separate button groups with flat buttons.

additionally the design of the outline button groups stands out better against the datagrid than flat buttons. flat buttons can be easily missed in visual scanning and may be confused as links in that instance. fully recommend outline buttons.

if a product's UX team strongly recommends flat buttons, the workaround here can help developers. but Clarity would need stronger research from a UX team to go against its current recommendations.
