### ISSUE TITLE
clr-datagrid does not size its column properly when clDgRowSelection is used

### ISSUE THREAD

**Issue by ivvatov** [vmware/clarity#2611]
## Describe the bug

Clarity datagrid does not resize its first column when
(1) clDgRowSelection is set to true
(2) the grid data is set with a delay

This has been regressed, because it has been working fine in 0.11.4.

## How to reproduce

See this StackBlitz fork - https://stackblitz.com/edit/clarity-light-theme-v11-s2g4qa?file=app%2Fapp.component.html .
Also, this is observed in the clarity demonstration website -- go to https://vmware.github.io/clarity/documentation/v0.12/datagrid/selection and look for the clDgRowSelection example.

## Expected behavior

clr-datagrid should be able to size its columns properly.

## Versions

**App**

* Angular: 5.2.1
* Clarity: 0.11.29

**Device:**

* Type: All
* OS: All
* Browser latest Firefox and Chrome

**Comment by mathisscott** [comment]
Thanks for reporting this issue, @ivvatov.

clrDgRowSelection is a problematic pattern that the Clarity team supports but is reluctant to recommend due to the accessibility issues it can introduce.

Additionally, we are already approaching the release of the 0.13 release candidate. This means we are tailing off our support for 0.11.

This looks to be more of a cosmetic issue than an actual breakage and would require a significant investment from our team to investigate.

I'll mark it as needing investigation but I don't think we will be able to devote time to this anytime soon.

**Comment by dpcamp** [comment]
Experiencing the same issue. Really hoping this gets worked out, as the radio button doesn't seem as intuitive as being able to just click a row as an end user.

**Comment by youdz** [comment]
Fixed by #2670.
