### ISSUE TITLE
Side nav expanded group is not collapsed automatically , when i expand the another group 

### ISSUE THREAD

**Issue by rameshyala** [vmware/clarity#2612]
Hi, clarity team

in my use case is in vertical nav i have a few groups(parent items), i need to expand in that one group(parent), after expand another one that old expanded group is need to be closed, How can i achieve this , if this is not a right enhancement can you provide me workaround solution.
 
use case : In this attached [stackbuz](https://stackblitz.com/edit/menu-bug-mbmrk2?file=src/app/app.component.html) , first expand Reports after expand Settings the side nav showing with scrollbar, i am looking the solution when i am expand the settings reports need to be collapsed.

Thank you.

**Comment by youdz** [comment]
Letting the user keep multiple groups open is a conscious design choice, so as you're guessing this is not a feature we will provide. The reason is that we want users to be able to go back and forth between pages that are in different groups, and with the behavior you want that becomes a nightmare for them (they have to re-expand every time).

It is easily feasible by just tracking what's currently expanded and forcing a collapse whenever a new group opens, like this: https://stackblitz.com/edit/accordion-sidenav?file=src/app/app.component.html
But as I said, we recommend against it.
