### ISSUE TITLE
[WEBSITE] No documentation for v0.13

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#2614]
## Summary

The `website` branch still does not have a specific folder for v0.12 so `latest` still points to v0.12.
Having a v0.13 available would allow people to contribute on v0.13 documentation

* What is the change? Add documentation for v0.13
* Why should it go in Clarity? v0.13 is in RC, a documentation section would help people to evaluate properly the version and contribute to it (improve documentation, test, BUG, ...)
* Does this change impact existing behaviors? If so how? NO CHANGES
* If this change introduces a new behavior, is this behavior accessible? NO new behaviuor

**Comment by mathisscott** [comment]
Hi @mcosta74 
We generally don't update our latest documentation until final release of the version. The reason here being that the implementation/API may undergo changes up until that time. It's not ideal to make changes during RC but it happens every now and then.

For a preview of any breaking changes in 0.13, please refer to the release notes for the two beta releases:

**Comment by mcosta74** [comment]
Thanks for the reply.

My point was that I'm evaluating v0.13 and sometimes to understand how to use a new component (combobox for instance) I have to go to the dev app or guessing reading the API.

Understand that cannot be worth to write documentation for beta and RC but it can help people to evaluate upcoming releases and find/fix bugs

**Comment by mathisscott** [comment]
@mcosta74 
Specifically for combobox, it is not yet supported. We had to stop implementation to shift over to emergent priorities from internal teams. Note that most things we would document would be in the release notes for beta and rc releases. And a demo of every component we have is [available in our source code](https://github.com/vmware/clarity/tree/master/src/dev/src/app).

If you are specifically looking for combobox and it isn't there, it's because we aren't releasing it. The work on it is about 33% done.

**Comment by gnomeontherun** [comment]
The only new stuff for 0.13 are two form components, which the documentation for is forthcoming when we release 0.13. We are also working on better website design to better surface both versioned documentation and changelogs.

**Comment by mcosta74** [comment]
ok guys, thanks for the clarification.
and a HUGE THANKS for your awesome job
