### ISSUE TITLE
Datagrid selection event listening without two-way binding 

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#2619]
## Describe the bug

It's not possible to listen to Datagrid selection events like `(clrDgSelectedChange)` without using two-way binding to `[(clrDgSelected)]` (and similarly for the single selection equivalents).  

`clrDgSelectedChange` can't be used by itself without `clrDgSelected` (the check boxes don't appear).  If both are used, each user click fires multiple `clrDgSelectedChange` events.  

## How to reproduce

https://clarity-light-theme-v012-g16wvr.stackblitz.io

Open console, select one or more items.  

## Expected behavior

Some way to listen to selection change events only without two-way binding or extra events being triggered.  If this is already possible, it would be good to document since it seems like a fairly common use case.  

## Versions

**App**

* Angular: 6.1.0
* Clarity: 0.12.11

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Comment by gnomeontherun** [comment]
There seem to be two issues here. 1) Not being able to listen to changes on selection without the input binding is not a bug (perhaps its a feature request). 2) There are multiple emits on selection, but when you update to the latest Clarity 0.12.x version this has been fixed.

As far as not using the input binding, this is partially due to how Angular binding works and how we detect selection being enabled on a datagrid. We use the `clrDgSelected` binding to detect that a user wants to use selection, and using `(clrDgSelectedChange)="change($event)"` on its own is not the same binding to Angular and doesn't alert the datagrid to turn on selection.

See https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid.ts#L103 where it turns on selection. We'd have to introduce a second input property to just turn on selection, in addition to the one we have for tracking the current selection, which really doesn't make sense to me to bloat the API. You can set the input binding and use the change event without issue.

I'm going to mark this as closed because I don't see the issue you describe with latest Clarity 0.12 version and I don't expect we'll change the behavior of datagrid selection bindings anytime soon.
