### ISSUE TITLE
use case for: very long text without spaces in sidenav

### ISSUE THREAD

**Issue by omurbekjk** [vmware/clarity#2623]
## Describe the bug

I am using clarity sidenav component and i have very long texts in a side navigation as a link.
If I use long texts with some spaces, it is wrapping them. If the text is too long it does wrap them.
1. From UI perspective what is the best UI/UX design for long texts without spaces?

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v11-6oicnr?file=app/app.component.html

## Expected behavior

I think it should wrap them

**Comment by gnomeontherun** [comment]
If you have very long text without spaces, either figure out how to shorten it or use the `word-break: break-all;` property to wrap the text to remain visible. I'd recommend figuring out how to shorten it or break it naturally like you might see in a book, rather than rely on CSS because long words are harder to read.

Closing as it depends on the application to decide which approach to take.
