### ISSUE TITLE
ClarityWizard - Be able to display 'finish' button on each page

### ISSUE THREAD

**Issue by ChrisKaun** [vmware/clarity#2629]
## Summary

I would like to be able to use the `type=finish` button on every page of my wizard.

## Use case

We will use the wizard for editing/creating records and want to seperate the model attributes in seperate pages. Each page by itself will be validated.  
This all works as expected until I want to edit a record.  
Let's say the user wants to edit a attribute on `page 2` and clicks on a button so he will directly see the 2nd page of the wizard.  
The user edits the FormControl and can't save until he scrolls to the last page where the finish button is present.

## Workarounds

I could create a custom button which would do the exact same thing as `finish`, but this would mean that I need to define the button for each page and also need to add `prev, next, cancel` buttons for each page because the Wizard-wide buttons will be overwritten.

**Comment by mathisscott** [comment]
Hi @ChrisKaun 
I'm not sure I understand the use case here. When you save changes in the wizard is up to you. If your application only saves the changes when a user clicks on "Finish" on the last page of the wizard, that's an issue with the application. Clarity doesn't force that in any way.

If you wanted a different UX for it, a custom button would not be a bad idea. There are better ways than defining a button for each page. You could, for example, use an ng-template to insert the buttons in each page so that way your buttons are only defined in one place.

Additionally, if you are looking for a "save changes" sort of flow, I'm not sure "finish" on every page makes a lot of sense. Let's say someone clicks "Finish" what happens? It saves and closes? What about "cancel" what does that do?

Ultimately, when you save the data in the wizard is up to you and custom buttons are the way to do it if you want to have a Finish button on every page.
