### ISSUE TITLE
Breakpoints in mobile devices with different pixel ratios or screen densities

### ISSUE THREAD

**Issue by Papipo** [vmware/clarity#263]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I expect media queries to take into account pixel ratios / screen density (not sure what's the term here). In an LG G3, inline radios should be inline, and header branding should be longer than 144px (to give a couple of examples).

### Actual behavior
In my LG G3, I see inline radios stacked, or header branding with 144px of max-width.

The reason is that they are affected by the smallest breakpoint of 544px. I know that the device reports a width of 360px, but in a real use case, you don't expect this behaviour.

### Environment details

* **Browser:** Crosswalk under android. It's a Cordova application.

**Comment by Papipo** [comment]
Let's see if an screenshot clarifies this a bit. You can see the branding width (btw, the font feels smaller than expected too), the stacked radios which have .radio-inline class, and the mentioned breakpoint.

![Screenshot](https://cloud.githubusercontent.com/assets/22678/21295847/f21fc20c-c55d-11e6-980f-d4b946de8448.png)

**Comment by mathisscott** [comment]
Thanks for submitting this issue and for the thorough explanation, @Papipo. We'll take it a look at it and try to get it in the queue. A lot of us are nose-down on work related to AoT so it may be a week or two before we can get this to the top of the list.

**Comment by adityarb88** [comment]
Hi @Papipo,

Branding Area:
The reason our branding area is 144px our header supports 4 sections. There is no way for us to detect what follows the branding area using just CSS and thats why we have limited it to 144px. If we don't limit it to 144px there is a chance that it might overlap with the other sections. If you don't have additional sections on your header, i would recommend that you override the max-width at your end for now (I say for now because we are in process to implement our search and header-actions functionality and if we feel that the responsive solution for search and header-actions ends up giving us more space on the header, we might increase the max-width or get rid of it altogether)

Inline Checkbox:
Our UX team recommends that the checkboxes be stacked on smaller screens because in most cases having more than 1 checkbox in the same line will cause the text to wrap.

I will remove the `bug` and `contributions welcome` labels for now and instead assign it to our UX team for their feedback before changing anything.

**Comment by Papipo** [comment]
@adityarb88 sure, but the thing is that on a screen with less pixel-ratio, the branding is wider. I can just resize my desktop browser and see how it behaves in a completely different way (also the font looks thicker):

![clarity 2](https://cloud.githubusercontent.com/assets/22678/21353929/6b23de16-c6c8-11e6-9417-d3b315dca208.png)

In Framework7, for example, they push .pixel-ratio-# classnames into the body so they can transform-scale stuff and use different dimensions on specific elements.

Apart from that, I'm not sure that it makes sense that the branding has a max-width, does it?

**Comment by adityarb88** [comment]
@Papipo: Thanks for replying back! I will wait for our UX team to respond to this but it looks like you are using the branding area as a heading. The recommended usage for the branding area is for displaying your app name. I believe your heading `Trade a new item` belongs in the `.content-area`

Regarding the max-width consider the following example:

![image](https://cloud.githubusercontent.com/assets/1426805/21358861/fd911f14-c68e-11e6-8da6-fe0edf9fec65.png)

We want to make sure that the branding area doesn't overlap the other 2 sections & also account for the spacing for the hamburger icon + the overflow menu icon. If we don't have the max-width in place, there is a chance that it might overlap with the other sections and make them inaccessible. The max-width is in place to make sure that all sections on the header are accessible.

**Comment by Papipo** [comment]
Well, maybe you are right. It's true that I am using branding as a header.
But I still think that pixel ratios should be taken into account, generally speaking. Let's see what the UX team has to say.

Thanks.

**Comment by Papipo** [comment]
BTW, I am interested in using it as a header in order to save space. My project is a hybrid mobile app, and I chose Clarity because I like how it looks, it has a kinda mobile appearance without being too iOS nor android like. Also, it doesn't depend on JS (I am using mithril, so when needed I'll write the stuff myself. No angular at all).

So, it might be interesting to add a new class to the .header to allow this use case.

**Comment by adityarb88** [comment]
@Papipo thanks for the feedback! I will take a look at the pixel-ratio issue that you raised too.

@yenmade: could you please take a look at this issue whenever you get a chance?

**Comment by yenmade** [comment]
@Papipo Thanks for bringing this to our attention. Like Aditya pointed out, the reason there is a max width is to account for other sections that are generally found in applications. Decisions like this one and the stacked checkboxes are built this way due to us not being able to detect the content people have, and also to avoid breakage (overlaps and misalignment due to wrapped text). These defaults should be easily overridden based on specific use cases. However, there will likely be future modifications once search and common right header links are built out.

The current design is intended for application branding in the left header area to maintain context on small breakpoints, with the idea that page titles will live in the content area. Your use case of a hybrid mobile app and using the header to save space is an interesting one, and we should definitely look into this. 

@Aditya When you get back, let’s discuss this further and see if there are ways of extending the header to accommodate different cases.

**Comment by adityarb88** [comment]
I believe our UX has addressed the questions that were asked in this issue. Closing.
