### ISSUE TITLE
offer two-way binding on the single selected datagrid

### ISSUE THREAD

**Issue by zhangyuting** [vmware/clarity#2675]
## Summary

We want two-way binding offered on the <clr-dg-row> component for its single-selected state. This would allow users to select single items programmatically more easily. This feature already exist for multiple selection(Checkbox), we want this feature for single selection.

## Use case

In some cases, we need datagrid shows with predefined selection(Single). 

## Examples

```
<clr-datagrid [(clrDgSingleSelected)]="dynamicGroupWizardDTO.selectedPolicy" [clrDgRowSelection]="true">
....
<clr-dg-row class="plcrow" *clrDgItems="let plc of protectionLifecycles" [clrDgItem]="plc" [(clrDgSelected)]="plc.assetType == "123">
```
In this example, it is not working since I used clrDgSingleSelected. However, it works well for clrDgSelected.

## Workarounds

I don't know yet.

**Comment by youdz** [comment]
Ok, for what you want all you need to do is use the two-way binding at the Datagrid's level. See our documentation: https://vmware.github.io/clarity/documentation/v0.13/datagrid/selection-single

Having two-way binding on each row for single-selection makes no sense, since they're all tightly coupled. Selecting one needs to unselect the others, you can only have one selected at a time. So we offer the `[(clrDgSingleSelected)]` two-way binding at the top level, which receives and emits the currently selected item.

I'm closing this since it's a feature we have and it works, but if I misunderstood please post a StackBlitz of what you're trying to do, explaining why it's not solved by our current API. Thank you.
