### ISSUE TITLE
add functionality to nav elements

### ISSUE THREAD

**Issue by AK2083** [vmware/clarity#2736]
## Summary

Adding a button to a nav element to interact with them.

The changing is to add buttons or functions which are specific for nav elements. This should be responsive, to showing this for each screen resolution.

## Use case
I use the sidenav for a project list (e. g. Master-Detail). Each nav element is a project. If I would like
to remove a project, an icon should displayed on the right side of a nav element
to remove them. 

![image](https://user-images.githubusercontent.com/3448835/47006206-b0886200-d135-11e8-8334-17abf44cb3ee.png)

**Comment by hippee-lee** [comment]
Hi @AK2083 - Github issues are for reporting issues and bugs. This seems more like a `How do I ...` question. A better place for that is StackOverflow where you will get more eyes on your question. 

Please use a [StackBlitz](https://stackblitz.com/edit/clarity-light-theme-v013) to show what you are trying to do and then tag your question with [vmware-clarity](https://stackoverflow.com/questions/tagged/vmware-clarity). With a working re-production we can usually provide help there fairly quickly and the broader community also has the benefit of seeing your problem and the solution. 

I'm closing this because it doesn't seem like a bug. If that is not the case please update the issue with a stackblitz that recreates your issue.
