### ISSUE TITLE
TreeTable for Datagrid 

### ISSUE THREAD

**Issue by penleychan** [vmware/clarity#2759]
## Summary

Ability to group items, parent object with multiple child objects. Parent row can be expanded to show child rows and so on.

## Use case

This could improve my application user experience by using Clarity's UI, currently my application uses ng-zorro's tree data for this functionality. My use case is that my application is project management app, where I need to be able group project's milestones and it's tasks/subtasks in a treetable fashion with the ability to sort/filter.

## Examples

https://ng.ant.design/components/table/en#components-table-demo-expand-children 

or 

https://www.primefaces.org/primeng/#/treetable

**Comment by youdz** [comment]
Treetables (or hierarchical datagrids, everybody calls them differently) are not something we plan to support.

First, pagination and sorting immediately become poorly defined. The number of items per page doesn't represent much anymore, and the datagrid either jumps around or scrolls when you drill down the tree. Expandable rows do that, but they are less critical to information than actual row items you cannot find otherwise. Regarding sorting, everyone seems to want something different. I believe we already had 3 entirely different behaviors requested for sorting tree data in a datagrid, and none of them seem like the obvious default case.

Second, our datagrid is designed to display large amounts of data in a compact way, to save screen real estate. Hierarchical data in a grid loses a lot of space, both with the extra indentation needed and the fact that in many cases, either column data is redundant between parents and children or simply inapplicable and left blank. 

We recommend using a master-detail pattern (on version of which will be implemented at some point in Clarity), or ideally navigating to a dedicated details page for a particular row.
