### ISSUE TITLE
Clarity datagrid used with datagrid actions goes out of bounds

### ISSUE THREAD

**Issue by ickobombata** [vmware/clarity#2789]
## Describe the bug

When using clr-datagrid with clr-dg-action-bar and height 100%, the grid goes out of bounds.

## How to reproduce

https://stackblitz.com/edit/clarity-c6hpm7?embed=1&file=app/app.component.html

## Expected behavior

When action bar is added the datagrid should become smaller in terms of height.

## Versions

**App**

* Angular: 6.0.0
* Clarity: latest

**Device:**

* OS: Windows 10
* Browser chrome

**Comment by sdurnov** [comment]
[My example](https://stackblitz.com/edit/clarity-light-theme-v013-lls1qj)
Yes, similar issue.
But in my case I don't have height: 100%.

Issue happens if actions and paging is enabled simultaneously, and there's more than 1 page of data.

Setting _height: auto_ to **.datagrid-host** solves the problem for me

**Comment by Jinnie** [comment]
We prefer to get focused on the 1.0 release, where this is not an issue anymore. Also if needed it can be fixed in your code by overriding the CSS values for the wrapper overlay: 
min-height: initial and height: 100%
Based on this, I'll close this issue now. If you need it fixed for 0.13 and the workaround is not applicable for you, please write back to us.
