### ISSUE TITLE
Datagrid selection does not play nicely with pagination

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#2790]
## Describe the bug

The datagrid selection count does not always reflect the number of rows actually selected.  Clicking the "select all" box only selects rows on the given page.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v013-tzd3bu

The data shown in this example loads with two rows selected on each of the two pages, but the datagrid only shows two rows as being selected.  If you click the "select all" box it only selects the item on the current page.  

## Expected behavior

The selection state indicated in the datagrid as well as the number of selected items should exactly match the actual selected items when using `[(clrDgSelected)]` at the row level.  

## Versions

**App**

* Angular: 6
* Clarity: 0.13

## Other notes

I came across this while working on a stackblitz to reproduce a different, related issue.

**Comment by youdz** [comment]
I see two things here.

First, the array you are giving us at the `[(clrDgSelected)]` array you are giving us at the datagrid level is inconsistent with the `[(clrDgSelected)]` per-row boolean value. That means you have 2 sources of truth, we can't know which one to trust so you end up with inconsistent or broken behavior.
When you are in such a situation, you have to make sure your global selection array matches the slection state for each item: https://stackblitz.com/edit/datagrid-pre-selected-items?file=src%2Fapp%2Fapp.component.ts
In my Stackblitz, where I initialize `fake = this.data.filter(x => x['selected']);`, the indicated number of selected items is correct.

The second point is the fact that "Select All" only selects the current page. That is a design choice, and is actually the standard across most paginated lists and tables out there. Doing otherwise would not only confuse the user, but also make it impossible to use for many projects where the server doesn't offer an endpoint to select all the items in a large dataset.

I'm closing this based on these two answers, which I believe address your points. I will just note that whenever we offer two concurrent APIs to set the same properties (here, selection on the whole datagrid or on the rows themselves), we end up with a mountain of issues:
- either we try to synchronize them and it raises `Expression has changed after it was checked` errors half the time, 
- or we decouple them and assume our users will use one or the other, and our users actually use both at the same time with inconsistent values and the final behavior is erratic.
I tend to favor the second option because keeping a consistent state on the app is better pratice and an easier fix, but I'm open to suggestions on better solutions.
