### ISSUE TITLE
Datagrid - make it possible to use datagrid cells in the datagrid-footer

### ISSUE THREAD

**Issue by ChrisKaun** [vmware/clarity#2809]
## Summary

I would like to use datacells in the datagrid-footer so that I may align content with specific columns.

## Use case

I have a datagrid with products. In the datagrid-footer I would like to show a netTotal and grossTotal sum of all products. The value should be aligned below the product column.

See the stackblitz for a simple example.
https://stackblitz.com/edit/clarity-dark-theme-v013-i5ltyb?file=src/app/app.component.html

I can't align the footer variable `{{total}}` with `item#price`.

## Workarounds

A workaround is to make the datagrid-footer and child element act like a table with `display:table/table-cell`. But this breaks as soon the user resizes one of the columns of the datagrid.

**Comment by youdz** [comment]
This would be incompatible with pagination, selection, hideable columns, or any feature that requires something to be displayed in the footer. Since a datagrid without pagination has very limited uses (the number of items is small enough to be displayed at once, so a static table would probably be just as good), we'd be introducing a feature that doesn't work in most of the real-life datagrid cases.

I suggest simply adding a special row outside of your `*ngFor` loop, maybe customize its style a little. Something like this: https://stackblitz.com/edit/clarity-total?file=src%2Fapp%2Fapp.component.html
Does this work for your use case?

**Comment by ChrisKaun** [comment]
Ah sorry I didn't thought the through. Of course this would negate the pagination.
My current workaround is indeed to use a custom-row like you created it in the stackblitz, just thought that it would be a nice feature to use the footer instead of that custom-row. But I understand that this would make a lot of things more complicate and wouldn't have any use-cases, when there is a more or less easy workaround present.

**Comment by mattmutt** [comment]
Most grid engines support placement of fixed rows under the main body set of rows. Strong evidence is found in financial apps or big data sets where summation or some accounting terms are to be shown. 

The challenge lies in pushing the Clarity grid to reproject the layout such those special row(s) can be placed inside the footer, without vertical scrolling. I am offering an alternative solution whereby grid cells are placed in the footer with the necessary hooks to ensure tight column alignment and spacing, in case of resizing or limited layout space on the main datagrid table. In the example two numeric summary cells are placed immediately under the bottom of the grid body. A related discussion #1586 suggests pinning columns, but why not rows?

![datagrid-with-reprojected-column-in-footer](https://user-images.githubusercontent.com/8688570/60779215-b15f8a80-a0ee-11e9-894b-1f5229701328.png)

demo link with grid card: http://mattmutt.github.io/ngx-card-deck-seed/#/dashboard/dashboard-page/com_company_sample2/deck1
