### ISSUE TITLE
Datagrid string filter entry field partially displayed

### ISSUE THREAD

**Issue by zlevai** [vmware/clarity#2810]
## Describe the bug

Opened string filter entry field partially displayed for the first column of the datagrid.

## How to reproduce

1.  Oped: https://stackblitz.com/edit/first-column-filter-issue
2.  Click on string filter icon (crater icon beside of the column title: Status) for the first column-> string filter entry field opens
Actual result:
Opened string filter entry field partially displayed for the first column. The half part of it hangs out from the page.

## Expected behavior

Opened string filter entry field should be displayed fully for the first column as well. 

## Versions

Angular CLI: 6.1.9
Node: 8.11.2
Clarity: 0.13.4

Device:
Type: Dell latitude E5550
OS: Windows 10 64bit
Browser: Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit)

## Additional notes
Opened string filter entry fields are displayed correctly of rest columns.

**Comment by hippee-lee** [comment]
Hi @zlevai  - this is a known issue. I'm currently researching a more robust solution that we are tentatively calling SmartPopovers. Follow along [here](https://github.com/vmware/clarity/issues/1262)  and [here](https://github.com/vmware/clarity/issues/2683) for updates.

I'm closing due to the linked issues above. Please let me know if you believe your issue is different.
