### ISSUE TITLE
[WEB] Missing Documentation for Drag&Drop

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#2816]
## Describe the bug

The Dev and the KS apps have working demos for Drag&Drop but there's no documentation page for that feature.

**Comment by mathisscott** [comment]
Those are not public facing APIs at this time. When the documentation surfaces, it will be related to components where drag and drop is enabled.

Advanced users should be able to look at the demos and work with it in their projects for now. But there are a huge number of UX considerations for all the different combinations of drag and drop among components. That is why we leave it to advanced users at this time. As we roll out more drag and drop, this API will become more visible.

**Comment by mcosta74** [comment]
Thanks for the answer, can be the feature considered **mature** and ready for production ?
I need to implement some Drag&Drop based feature and I'm evaluating both your solution (i'd prefer to use it) and the one released in `@angular/cdk`. Any tips ?

**Comment by mathisscott** [comment]
@mcosta74 
This would be a good question for @Shijir 

I know there are some UX issues with implementing drag and drop in a product. Mostly presentational, IIRC. I believe it works fine but you would need to figure out what sort of visual cues you would need in your application.

**Comment by Shijir** [comment]
@mcosta74 I wouldn't recommend using our Drag & Drop feature in production apps yet. The reason is that we ourselves just started using and testing the feature in [one of our components](https://github.com/vmware/clarity/issues/1771) as users of the feature. Once we figure out things that need to be added, removed or changed in our newly integrated Drag & Drop feature and resolve them sufficiently, we will provide the documentation for our users and recommend using it in production apps.
