### ISSUE TITLE
Signpost close button doesn't work if the signpost is inside of a label

### ISSUE THREAD

**Issue by bvelcheva** [vmware/clarity#2819]
Signpost close button doesn't work if the signpost is inside of a label.

https://clarity-rkqmjc.stackblitz.io

In the following structure the X icon doesn't close the signpost:
![screen shot 2018-11-07 at 5 19 45 pm](https://user-images.githubusercontent.com/44831965/48140401-61a39780-e2b1-11e8-8fb4-29d27a164401.png)

 
```
<label>Some label
   <clr-signpost>
      <clr-signpost-content *clrIfOpen>
           <span>some content</span>
      </clr-signpost-content>
   </clr-signpost>
</label>
```

The X icon in the signpost content should hide the signpost even if it is inside of a label.

Angular: 6
Clarity: 1.0, 0.13, 0.12, 0.11

**Comment by youdz** [comment]
To follow-up Cory's explanation, this issue now becomes a matter of making sure forms display correctly if the signpost is put outside of the label. For instance on text inputs, the DOM should be something like:
```html
<clr-input-container>
  <label>Some label</label>
  <clr-signpost>
    <clr-signpost-content *clrIfOpen>
      <span>some content</span>
    </clr-signpost-content>
  </clr-signpost>
  <input clrInput type="text" />
</clr-input-container>
```
I'm not sure this displays correctly today, so we're keeping this issue open to update our styles in order to support this.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
