### ISSUE TITLE
In  clarity 1.0 input box  tooltip  feature  deprecated  reason 

### ISSUE THREAD

**Issue by muruganG** [vmware/clarity#2874]
## Summary

_Summary the request and address the questions as appropriate._

* What is the change?
* Why should it go in Clarity?
* Does this change impact existing behaviors? If so how?
* If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by muruganG** [comment]
We already used the older  12.0  based  all the forms used the tooltips  approach ,when see the version 1.0 ,we are seeing different approach  for  form validation error message shows.Documentation says tooltips  form validation deprecated .In my client request each form field required the tool tip  error meeage ,Let me tell how to use the version 1.0 with form validation  tooltip use with clarity feature breaking .also attached snapshot  older form   with tooltip error 

![image](https://user-images.githubusercontent.com/10629787/48878821-236cb300-ee2f-11e8-86fb-a2c2e22ed171.png)

**Comment by gnomeontherun** [comment]
This is no longer planned to be supported (hence the deprecation), particularly due to the UX challenges faced with hiding error messages inside of tooltips. There are also issues with the tooltips positioning and if they are properly visible in tight spaces (like modals). The new UX patterns are more accessible and functional, as well, because they show errors and are good for both sighted users and users with a screenreader. 

We realize that the change in format is a major change, but our research shows it is for the better of all users. I'm going to close this as a question.
