### ISSUE TITLE
Incorrect behavior of nested components inside <clr-datagrid> with v beta.2

### ISSUE THREAD

**Issue by RomanLavrinenkoDevPro** [vmware/clarity#2875]
## Describe the bug
After updating Clarity up to 1.0.0-beta.2 I got broken datagrid component.
Any custom components inside ```<clr-datagrid>``` tag doesn't rendered.

I found related issue https://github.com/vmware/clarity/issues/2373
There i found solution, but it won't work with latest Clarity versios (1.0.0-beta.2 at the moment).

## How to reproduce
https://stackblitz.com/edit/clarity-datagrid-nested-row-tttvyz

## Expected behavior
I hope that next code should work:
```
<clr-datagrid>
  <clr-dg-column [clrDgField]="'id'">User ID</clr-dg-column>
  <clr-dg-column [clrDgField]="'name'">Name</clr-dg-column>
  <user [user]="user" *clrDgItems="let user of users"></user>
</clr-datagrid>
```
user component template looks like:
```
<clr-dg-row>
  <clr-dg-cell>{{user.id}}</clr-dg-cell>
  <clr-dg-cell>{{user.name}}</clr-dg-cell>
</clr-dg-row>
```
```ngProjectAs="clr-dg-row"``` on ```<user>``` component tag also doesn't help.

## Versions
* Angular: ^6.0.6
* Clarity: ^1.0.0-beta.2

**Comment by Jinnie** [comment]
Hi, @RomanLavrinenkoDevPro,
Clarity 1.0 runs on Angular 7.
This is a fork of your example, with only the angular dependencies updated:
https://stackblitz.com/edit/clarity-datagrid-nested-row-clwyxy

**Comment by RomanLavrinenkoDevPro** [comment]
Hi @Jinnie 
Sorry, but as i can see in your example in package.json you use 
```
"@clr/angular": "^0.13.10",
"@clr/icons": "^0.13.10",
"@clr/ui": "^0.13.10",
```
This is doesn't fit requirements from my request.

**Comment by Jinnie** [comment]
You are right, I've reverted the @clr packages.
What I can see is that the CSS links inside index.html are wrong - they are pointing the v0.13 files.
This does not seem to fix it though.

**Comment by RomanLavrinenkoDevPro** [comment]
Yes, you are right.
I've updated css links but this doesn't help
https://stackblitz.com/edit/clarity-datagrid-nested-row-wdzcnz

**Comment by gnomeontherun** [comment]
This is something that did work, but with our refactoring in 1.0 this doesn't continue to work as it did before. Interestingly, the workaround I posted actually does break a number of datagrid features but they aren't being used in this demo. So in truth, this is not really a supported use case.

Can you explain why you want to wrap your datagrid row? I don't see any real reason to do this, and it does create issues for provider trees in Angular to correctly support many features.

**Comment by RomanLavrinenkoDevPro** [comment]
@gnomeontherun Hi! Sorry for delay with my answer.
Yeah, i've tried to find the reasons about why in real I need to do this and the only one reason I found is that in our project we have many (MANY) places where this is already done. So we should make a lot of refactoring to move to the v1+.

I'm not sure that I can call this like 'breaking changes' because moving clr-dg-row to external component was not documented feature, but unfortunately this looks so for us.

Anyway thanks for your answer and thoughts.
Probably this bug can be closed if described above behavior is 'by design'.

**Comment by jacobbutton** [comment]
This is a problem I'm running into after updating to 1.0 as well.

In my use case I'm using claritys datagrid as the listview component of a document library. I have each datagrid row in it's own component so I can wrap each in a [file-drop-component](https://www.npmjs.com/package/ngx-file-drop) and [drag-and-drop component](https://github.com/reppners/ngx-drag-drop) to facilitate file uploads via drag/drop to a particular location in the library and moving files/folders into one another.

**Grid Component**
```
<file-drop (onFileDrop)="uploadDropped($event)" (onFileOver)="uploadOver($event)" (onFileLeave)="uploadLeave($event)" customstyle="file-drop">
    <clr-datagrid [(clrDgSelected)]="selected" (clrDgSelectedChange)="selectedChange($event)" class="datagrid-host-fullheight" dndDropzone (dndDrop)="moveDropped($event)" (dndDragover)="moveOver($event)" (dragleave)="moveLeave($event)" [class.over]="moveOverFlag">
        <clr-dg-column>Name</clr-dg-column>
        <clr-dg-column>Size</clr-dg-column>
        <clr-dg-column>Date</clr-dg-column>
        <ng-container *clrDgItems="let item of libraryItems.items" ngProjectAs="clr-dg-row">
            <app-list-view-item [item]="item" (onEdit)="itemEdit($event)" (onMove)="itemMove($event)" (onUpdate)="itemUpdate($event)" [dndDraggable]="item" [(draggedItem)]="draggedItem" [dndDisableIf]="item.isRoot" (dndStart)="moveStart($event,item)"></app-list-view-item>
        </ng-container>
    </clr-datagrid>
</file-drop>
```

**Row Component**
```
<file-drop (onFileDrop)="uploadDropped($event)" (onFileOver)="uploadOver($event)" (onFileLeave)="uploadLeave($event)" customstyle="file-drop" [disableIf]="!item.isFolder">
    <div dndDropzone (dndDrop)="moveDropped($event)" (dndDragover)="moveOver($event)" (dragleave)="moveLeave($event)" [class.over]="moveOverFlag" [dndDisableIf]="!item.isFolder">
        <clr-dg-row [clrDgItem]="item">
            <clr-dg-action-overflow>
                [...]Library Item Actions[...]
            </clr-dg-action-overflow>

            <clr-dg-cell [routerLink]="['/document-library', item.id ]" style="cursor: pointer">
                <clr-icon [attr.shape]="item.isFolder ? 'folder': 'file'" [class.is-solid]="item.isFolder"></clr-icon>
                {{ item.name }}
                {{ item.size }}
                {{ item.date }}
            </clr-dg-cell>

        </clr-dg-row>
    </div>
</file-drop>
```

**Comment by jacobbutton** [comment]
@mathisscott - I'm not sure if you're the correct person to reach out to here, but you do seem to be the most responsive.

I really need some direction on this. If I can't count on this functionality coming back I'm going to need to abandon clarity 1.0 migration or find something other than the datagrid to use in my document library component. Both options are going to mean I wasted a lot of time. This was working perfectly for my use case prior to upgrade. Disappointing to say the least.

**Comment by mathisscott** [comment]
@jacobbutton
Thanks for reaching out. I’m in meetings for the next three days so I’m going to ping @gnomeontherun to see if he can get someone on the team to give you an answer

**Comment by hippee-lee** [comment]
Hi @jacobbutton. I'm following up on this since I'm the one who made the changes for datagrid rendering in v1.0.0. I had to modify how rendering worked in order to be able to support the planned pinned column feature. Thats why it was released in v1.0.0 instead of v0.13.x . 

I understand how much you have invested in your solution which wraps the datagrid row child component in two other components for filedrop and drag-and-drop. As was previously mentioned in this thread while this technique works in Clarity versions prior to v1.0 it:

1. Breaks several other datagrid features 
2. Will cause issues with the internal datagrid providers
3. Is not a recommended way to use a datagrid rows. 

May I ask if there is a reason that a [table](https://vmware.github.io/clarity/documentation/v1.0/tables) or [list](https://vmware.github.io/clarity/documentation/v1.0/lists) would not work for your UI? 

I'm sure that you are disappointed and am sorry for that. I had to make these changes so that we could better control where and when the child components are rendered in a way that doesn't impact what kind of data gets projected. I also tried to make sure that it was `backward compatible`( which means that a datagrid functioned and looked the same is it did before the rendering changes) with the existing features and known use cases. Given that this behavior was unsupported before the rendering changes I don't see us adding in the future. However if you feel it should be part of the datagrid please open an issue and take the lead on proposing an architecture that will support it.

**Comment by hippee-lee** [comment]
I'm closing this based on the conversation around the original report.

**Comment by hippee-lee** [comment]
I see why you would use the datagrid if you need selection and actions. You don't seem ungrateful and I've been frustrated before so I empathize with your situation. 

I appreciate your feedback - it helps me better understand how the different datagrid features are being used in the wild.  Again, I'm really sorry for your frustration - if you go down the path of implementing those features and have issues I'm happy to help. Feel free to DM me through twitter [hippeelee](https://twitter.com/hippeelee) or tag me on StackOverflow and I'll take a look.

**Comment by youdz** [comment]
For what it's worth, the template you posted makes the datagrids completely unreadable on a screenreader. For accessibility reasons, tables need to be composed only of table elements (headers, body, rows, cells), and inserting buttons, draggable divs or other elements with entirely different semantics in the middle makes them impossible to navigate on a screenreader.

I don't know how critical accessibility is to you, and this is something that's customized on your side and not in Clarity so it can't really factor in our decision, but I figured it was worth mentioning.

**Comment by vraddy** [comment]
Hi @hippee-lee,
I am a bit late to this, I had a requirement to develop tree table control which looks like clarity Datagrid.
since there is no clarity tree table control, I used Datagrid and tweaked around(created a custom component which wraps rows and nested rows) after a couple of CSS override it was successful.
https://stackblitz.com/edit/clarity-light-theme-v013-wsiu1d

after upgrading to 1.0.2 it seems to be not working https://stackblitz.com/edit/clarity-light-theme-v013-zbetpr, 
understood the reason for this break, not complaining about it.

Any suggestion of workaround or any possible way of doing this which helps to work as earlier?

Thanks, Veeresh
