### ISSUE TITLE
Rename similar looking icons to have similar looking names

### ISSUE THREAD

**Issue by jrharshath** [vmware/clarity#2894]
We have some pairs of icons which look _almost_ identical, but have different
* stroke weights
* amounts of padding around
* usage guidelines

Some examples: 
* "check-circle-line" (more padding, smaller effective size, heavier stroke width), and "success-standard-line" (less padding, larger effective size, lighter stroke width)
* "exclamation-circle-line" and "error-standard-line" (same differences)

I request that we update the names of these (and other similar icon pairs) to be almost identical, and only differ perhaps in a suffix. Example: "error-line-standard" and "error-line-small-heavy".

This will make the icon names more self documenting, so its users know 
* what is the difference between them
* when to use which

**Comment by colinreedmiller** [comment]
This is a sound request. We need to assess the impact on products using the icons in question so missing icons do not unexpectedly occur.

**Comment by gnomeontherun** [comment]
This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this. Applications could create an alias if they wish.
