### ISSUE TITLE
Datagrid Numeric Filter

### ISSUE THREAD

**Issue by IoannesBracciano** [vmware/clarity#2908]
## Summary

Data-grid columns with numeric values should have a dedicated numeric filter. We plan to build this for our team but since it is such a common feature we felt like we should propose a contribution so that more people can benefit from it and not have to write the same filter over and over again.

## Use case

Numeric data-grid columns will make use of the filter. Since it is specific to numbers, the filter can provide comparison options like _=_ equals, _>_ greater than, _<_ less than, between, etc.

## API

The filter can be implemented as an angular component and then be used inside `<clr-dg-filter>` tags:
```
<clr-datagrid>
    <clr-dg-column clrDgField="numericField">
        <clr-dg-filter>
            <clr-numeric-filter></clr-numeric-filter>
        </clr-dg-filter>
    </clr-dg-column>
</clr-datagrid>
```

**Comment by youdz** [comment]
Thanks for offering to contribute to Clarity, as I said before filters are perfect candidates for first contributions.

Before we can go further, do you mind explaining or showing what the filter will be like? You say it will provide comparison options, but how will that be presented to the user? It could be a select element for the comparator, and a number input next to it. It could be multiple number inputs to allow for "between 10 and 20" filtering. It could be a text input that parses some mathematical syntax (please don't do that, it's a terrible idea 😂). It could be many other different interactions for the user.

Second, I recommend looking at our [existing string filter](ithub.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter.ts) and follow the same pattern, this way you'll obtain the much nicer syntax:
```html
<clr-datagrid>
    <clr-dg-column clrDgField="numericField">
        Column title
        <clr-numeric-filter></clr-numeric-filter>
    </clr-dg-column>
</clr-datagrid>
```
No need for that extra `<clr-dg-filter>`, since this will be one of Clarity's built-in filters.

**Comment by amellnik** [comment]
@IoannesBracciano -- I'm also interested in this, and if there's anything I can do to help with this please let me know.

**Comment by IoannesBracciano** [comment]
Greetings,
I have been a bit busy the last days but I took some time today to create a simple template of how we imagine the filter would look like.

<img width="920" alt="screen shot 2018-12-06 at 3 53 20 pm" src="https://user-images.githubusercontent.com/6152794/49588401-4474ee00-f96f-11e8-9bf5-a7cdd89d44b5.png">

That is the simplest idea, featuring a select box to choose the appropriate operator and a numeric input next to it. This will work well for most conventional comparison operators (_equals_, _greater than_, etc.), but the layout does not fit operators like _between_ or _not between_ since in these cases we need two numeric inputs.

I had another bolder idea to use a numeric line instead of standard inputs, on which the user could select numbers or ranges easier and more intuitively. It is not 100% thought through though and I do not have time right now to creating a working PoC, but if someone else has some time to spend on it I could work out the details with them!

**Comment by amellnik** [comment]
I prefer your first idea of allowing the user to input ranges by typing in numbers over having a range slider.  I think they work OK in some cases, but having numbers distributed over a large range (or even having a few outliers) makes them very difficult to use.  

I think a simple implementation would be to provide the user with two numeric inputs that provide a range, perhaps with a format like

```
___ <= x <= ___
```
or
```
[ ___, ___ ]
```
where the blanks are numeric inputs.  This would still allow the user to filter to a specific value with an input like `[ 0, 0 ]`.  

Is your mockup above available somewhere?  If not I can set another one up.  Cheers -A

**Comment by amellnik** [comment]
I'm working on this now -- could someone on the Clarity side please create a topic branch?  (I'm trying to follow the instructions [here](https://github.com/vmware/clarity/blob/master/DEVELOPMENT_CONTRIBUTION.md)).

The rough idea is to make an analog to the existing string filters for numeric contents, closely following the existing framework for string filters.  Rather than a single string input value the numeric filters will include two inputs for low and high limits (which may be +Inf or -Inf which doesn't set a limit).  The built-in numeric filter will always filter items that can't be converted to `number`, but users will be able to create their own numeric filters with custom filter functions.

**Comment by youdz** [comment]
@amellnik (and anyone else who was planning on contributing for this): I just created the `topic/datagrid-numeric-filter` branch off of latest `master`: https://github.com/vmware/clarity/tree/topic/datagrid-numeric-filter

Please make sure to commit your changes on top of this branch (so don't include future commits for now, we'll handle the rebasing), and submit your PRs against that branch.

**Comment by amellnik** [comment]
One more question -- is there any consensus about how generic this should be?  A minimal approach would be to just follow the documentation for [custom filters](https://vmware.github.io/clarity/documentation/v1.0/datagrid/custom-filtering) but that would run into https://github.com/vmware/clarity/issues/2513 and users would always need to specify the column name when constructing the filter.  

A more invasive change would be to put it on equal footing with the string filters, perhaps by attaching an `@Input` up to the [_field](https://github.com/vmware/clarity/blob/topic/datagrid-numeric-filter/src/clr-angular/data/datagrid/datagrid-column.ts#L151-L167) property of the datagrid column, and reproducing all the same stuff for numeric filters that exists for string filters (except for possibly the custom filter functions?)

**Comment by youdz** [comment]
I'd be okay with a `clrType` input next to `clrDgField`, that allows you to specify the data type of the property on the obejcts. It would be string by default, and you could use `clrType="number"` to get the numeric filter. You'd still have to offer them as custom filters for flexibility.

**Comment by colinreedmiller** [comment]
We need to stay with a simple solution. The most basic would be the 'between' paradigm with 2 numeric inputs. The only UX issue I am concerned about with this is clarification of the purpose of the 2 fields - this may be as simple as the hint text saying something like 'from' and 'to' - otherwise the fields would need to be labeled. 

A variation would be to allow the 1st field to be an operator select as in the example above. Since #1632 will replace this in the near future, we want to limit this to either the between solution, or add the operator option at most.

Quick wireframe:

<img width="1303" alt="Screen Shot 2019-03-28 at 10 26 23 AM" src="https://user-images.githubusercontent.com/44213553/55179177-26acde00-5144-11e9-8267-057481fa1974.png">

**Comment by amellnik** [comment]
@colinreedmiller Did you mean to not include the `x` close icon that the existing string filter has?  I don't feel strongly either way, but we should probably make them match.

**Comment by colinreedmiller** [comment]
@amellnik The image above is just a quick wireframe to illustrate the text above it.
