### ISSUE TITLE
Move off Bootstrap

### ISSUE THREAD

**Issue by Vad1mo** [vmware/clarity#291]
I just saw in your backlog https://github.com/vmware/clarity/projects/1  that you are planning to move away from bootstrap.

Is this an idea or is it already planned. If you are really thinking about moving away from bootstrap than we have to rethink our decision with clarity as well.

I know that bootstrap has its issues and drawbacks, but on the inevitable pro side is the huge eco system and popularity and knowledge among devs and ui experts.

**Comment by mathisscott** [comment]
The plan is to move off of Bootstrap starting with version 2.0. So that's a long way off. 

And version 1.0 of Clarity will stay on v4 Bootstrap -- as much as it is today. 

As with any long term goals, the community will have every opportunity to influence our decision and ultimate direction. 

I'm closing this issue because it is a question that has been answered.
