### ISSUE TITLE
Clarity Datagrid dynamic rendering bug

### ISSUE THREAD

**Issue by officialMKL** [vmware/clarity#2961]
## Describe the bug

_When I use the datagrid with pagination and I delete one or more entries of the list. Then there will be one or more empty rows left in the grid. It seems that the datagrid doesn't rerender._

## How to reproduce

_https://stackblitz.com/edit/clr-dg-test_
_https://clr-dg-test.stackblitz.io_

1.  Click on 'Delete'
2.  See empty row in the datagrid

## Expected behavior

_Datagrid rerenders without empty spaces._

## Versions

**App**

* Angular: 7.1.3
* Clarity: 1.0.1 (also 1.0.2)

**Device:**

* Type: Windows
* OS: Windows 7
* Browser: chrome, firefox
* Version: lates

**Comment by youdz** [comment]
When you use pagination, we set the height on the datagrid to avoid the page jumping around between each page, especially on the last one which may have very few items compared to others. It would also make it very hard to click "next page", "next page", "next page" in succession to browse the items, since the footer could jump around every time.

In your case, you can see this by simply removing the pagination component from the footer. Deleting items makes the datagrid smaller. But as long as you use pagination, we'll set the height of the datagrid to avoid unwanted "jumping around".

See #2956 for another recent conversation about this.

**Comment by officialMKL** [comment]
Thank you for the quick responses :)

**Comment by officialMKL** [comment]
Ok thank you :)
I will see if I am fine with the expected or if I will adjust the css a bit.
