### ISSUE TITLE
App Level Alert: Can’t Skin the Outline Button

### ISSUE THREAD

**Issue by ahand** [vmware/clarity#3014]
## Describe the bug

I skinned all of the App-level Alerts properties. However, I cannot figure out how to change the value for the outline buttons shown in the App Level Alerts. None of the properties in the Alerts section of the Dark theme file appears to affect them. 

Please either identify the themeable property to specify for the buttons, or create one.

## How to reproduce

I made changes to the properties shown in the file:  
clarity-master/src/clr-angular/utils/_theme.dark.clarity.scss

Here are relevant values: 

// App Info type
$clr-app-alert-info-bg-color: #0070BA;
$clr-app-alert-info-font-color: #ffffff;
$clr-app-alert-info-border-color: transparent;  
$clr-app-alert-info-icon-color: #ffffff;

$clr-theme-app-alert-font-color: #ffffff;
$clr-app-alert-close-icon-color: #ffffff;

1. In the Alerts section of the Dark Theme file, change all of the values to one's desired theme. 
2.  Run the Clarity Kitchen Sink app.
3.  View the App Level Alerts section of the demo. 
4.  You'll see that the outline button's colors are unaffected by any properties specified in this section. 

## Expected behavior

Consider surfacing the themeable property to specify for the buttons, or create one. Or maybe I've overlooked it? 

## Versions

Kitchen Sink app as downloaded from Git on Monday, Jan. 7, 2019.

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: Appears to be v1.0.3

**Device:**

* MacOS, Chrome

![alert - outline button theme issue](https://user-images.githubusercontent.com/11655671/51003147-80f5b580-14ea-11e9-9d9f-0518d185065b.png)

**Comment by ahand** [comment]
After further investigation, it appears that the outline buttons shown in the App Level Alerts use the Inverse Button properties in the Dark Theme. In the Dark Theme file's Button section, towards the end is the Inverse Button section. When I set these 2 properties to purple, for example, the App Level Alert's outline button had the purple border color and purple fill. (I tested each property separately). I hadn't expected that the App Level Alert used the Inverse Button's skinning properties. 

$clr-btn-inverse-border-color: #640480; //purple
$clr-btn-inverse-bg-color: #640480;  //purple

This issue can be closed. The fact that it uses the inverse button's color properties should be documented, e.g., in the Dark Theme file or elsewhere as appropriate.

**Comment by gnomeontherun** [comment]
This is really more of the fact that we have defaults for buttons and don't override them inside of the alerts specifically. When we compose multiple components into one experience (alerts and buttons in this case), we try our best to keep customization of the additive components to a minimum. 

Since we are dealing with dark background and light text, its natural for us to select the inverse button which were designed for this purpose. In cases like this, we would expect you to override the values of the additive component at its root first, and then write CSS rules to modify it in special cases if there isn't a direct variable.
