### ISSUE TITLE
Angular Form Controls: Theme Issues

### ISSUE THREAD

**Issue by ahand** [vmware/clarity#3026]
## Describe the bug

Using the Dark Theme to set values, there are multiple properties that don't seem to be used or to have the intended effect, or states for controls where they're not pulling from the theme. 

## CHECKBOXES
1. If the radio controls have a disabled shadow property, should the checkboxes have one, too? (If it's implemented, that is.) 
2. I set the mark inside checkboxes to be white, but the mark inside the indeterminate state isn't picking it up. Instead, the mark is using the same color as the border in the indeterminate state. This is incorrect. 
$clr-forms-checkbox-mark-color: #fff; //It's black rather than this color. 
//The internal dash mark is picking up the border color:
$clr-forms-checkbox-indeterminate-border-color: #000; 

## RADIO BUTTONS
//Dark pink. Disabled bg color property appears to be unused.
$clr-forms-radio-disabled-background-color:  #DE0063; 
$clr-forms-radio-disabled-shadow:  #DE0063;  //Also appears unused.

## DATE PICKER
Although the default form text color is set to dark pink, the date picker's text value is showing up as something else instead (#e9ecef). This means it's not picking up the theme color from the new part of the theme file and is using the Deprecated input text color.  
//New generic theme color it should be picking up:
$clr-forms-text-color: #DE0063; //Pink 
//But it's picking up this deprecated section value instead: 
$clr-input-text-color: #e9ecef;

## PASSWORD
Similarly, the password field is also using the Deprecated input text color.  
//New generic theme color it should be picking up:
$clr-forms-text-color: #DE0063; //Pink 
//But it's picking up this deprecated section value instead: 
$clr-input-text-color: #e9ecef;

## How to reproduce

I made changes to the properties shown in the file:
clarity-master/src/clr-angular/utils/_theme.dark.clarity.scss

1. Change the values in the dark theme file as noted above.
2. Run the Clarity Kitchen Sink app.
3. View the Forms > Angular section of the demo.

## Versions

**App**

Kitchen Sink app as downloaded from Github on Friday, Jan. 11, 2019.

Clarity: v1.0.4

![image](https://user-images.githubusercontent.com/11655671/51064045-9b936180-15b2-11e9-8295-64f53158460d.png)

![image](https://user-images.githubusercontent.com/11655671/51064283-c0d49f80-15b3-11e9-9b98-049ed29b254e.png)

![image](https://user-images.githubusercontent.com/11655671/51064577-4dcc2880-15b5-11e9-91f1-a931cd1d3ac2.png)

**Comment by gnomeontherun** [comment]
### Checkboxes

1) There are several variables not modified in the dark theme that you can hook into if necessary, and yes there are some disabled styles. I'm not certain what exactly you're after, but reviewing the full list in the forms/styles/variables.forms.scss file might guide you.
2) This looks like something we can fix, but could be a breaking change for others who've already themed it. So for now, just handle the case and we'll see about a fix for this in 2.0.

### Radios

1) Both are used to define the colors of a selected radio input that is also disabled. Toggle the disabled state off for the radios demo, select a radio, and toggle disabled back on.

### Date picker & Password

Yes, this is because of some old styling that was reused in new forms that we'll have to clean up. For now, just fix by setting both variables to the same value.

**Comment by mathisscott** [comment]
verified fixed with changes coming in #2770
