### ISSUE TITLE
Deploy ksapp on Stackblitz

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3029]
Guys, as far as I can see, there is no publicly deployed and constantly updated instance of ksapp. It would be nice to have it.

**Comment by sdurnov** [comment]
Well, I've found http://clarity-ks.surge.sh, but I'm not sure if it's fresh enough. Also, some pages have broken routes, like treeviews.

**Comment by gnomeontherun** [comment]
We don't have a strategy or reason to deploy it at the moment, its only for occasional testing and long term will probably be removed so we don't have both a dev app and ks-app. I'm not sure what value this can bring on stackblitz vs running the ks-app locally yourself due to the fact it depends on compiling Clarity directly which makes stackblitz deployment more complex.

I'm going to close this in favor of just checking out the repository and running it locally for best results.

**Comment by sdurnov** [comment]
@gnomeontherun many developers use Stackblitz for assembling initial HTML layout, then copying it into vscode and working further.
Also ksapp is a useful place for looking for code examples, while being able to see it in action. TBH, documentation with code examples is less useful, as it has less code snippets and some if them have gaps (or had in past, not sure).
And running ksapp locally is often too slow just to look up for some example.
BTW, I cloned Clarity repo yesterday just to build and run ksapp, but wasn't able to get it built. Not sure what the issue was, but it seems that some additional software is needed (though, I have windows-build-tools installed).
Having it in Stackblitz would be so much more convenient.

**Comment by gnomeontherun** [comment]
I think there is a better solution here, by having dedicated stackblitzes/repos for our primary components. Our dev app also has most if not all of the same demos from ks-app, which is why its largely redundant and plays a specific role in our testing but not in development or documentation. Anyways, I don't expect we'll put the effort into this specific request, but you're validating the initial ideas we have for more easily deployed demos.

**Comment by mathisscott** [comment]
@sdurnov

**Comment by sdurnov** [comment]
@mathisscott I wasn't aware if it, thx, will try.
