### ISSUE TITLE
Bootstrap margin and padding

### ISSUE THREAD

**Issue by ImNightwing** [vmware/clarity#3039]
I know clarity is extended from bootstrap and I use many bootstrap classes. Some in particular are the margin and padding utility classes like mr-1, pl-3 etc.
I see that you are overriding how these classes work and the spacing that they use. Bootstrap has much smaller spacings (they range from .25rem to 3rem) than the overridden spacers in the `_variables.scss`.

Why is this overridden? The new spacings are too large to use. Personally I would prefer these to reverted to use original bootstrap spacings.

**Comment by gnomeontherun** [comment]
Clarity uses some Bootstrap styles internally as a foundation, but our goal is to completely decouple from it in the future. We have different design decisions, so any changes we make are intentional. You could write your own utility classes (its very little CSS to do so) and customize to your preferences, but our margins and paddings are based on our grid and research for consistency and rhythm.

We also cannot revert those without a breaking change, which is not really an option at this stage. Closing since we won't be able to change for this.
