### ISSUE TITLE
Data grid placeholder image is not aligned as vertically centered.

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#3043]
Data grid placeholder image is not aligned as vertically centered.

## How to reproduce

https://stackblitz.com/edit/datagrid-placeholder-image

1.  Go to https://stackblitz.com/edit/datagrid-placeholder-image
2.  See the data grid placeholder image.
3.  Check the alignment of the placeholder image.

## Expected behavior

Data grid placeholder image should be aligned as vertically centered.

## Versions

**App**

* Angular: 7
* Clarity: 1.0.4

**Device:**

* Type: MacBook
* Browser: Chrome
* Version: Latest

**Comment by mathisscott** [comment]
@tarangkhandelwal 
The reason the datagrid placeholder image is not vertically centered is because we cannot predict or control the height of the datagrid in people's applications. In the stackblitz you have shared (thanks for that), you have a datagrid that is 500px tall. Another application may have a datagrid that is 700px or 900px tall.

If we centered the placeholder vertically, then it is likely it would appear so far down the screen on taller datagrids that users would just see an "empty" datagrid and would not see the placeholder unless they scrolled down. Because the placeholder may contain information that would be helpful to the user (as in explaining why the datagrid was empty and what to do if that was unexpected), this would be a bad user experience.

If, in your application where you do have control over the height of every datagrid, the preference is to have vertically centered placeholders, your stackblitz demonstrates how to do that. It's only a couple of CSS rules so I can't see how this would be hard for applications to implement/customize if they needed to.
