### ISSUE TITLE
Button Group - overflow functionality is broken for static button groups

### ISSUE THREAD

**Issue by ChrisKaun** [vmware/clarity#3046]
## Describe the bug

Using a static html button group will break the overflow functionality.

## How to reproduce

This can be tested in the documentation [https://clarity.design/documentation/button-group](https://clarity.design/documentation/button-group).
Also notice that this works for the angular-component.

## Expected behavior

Clicking on the button should show/hide the dropdown menu.

## Versions

**App**

* Angular: 6.1
* Node: 9.11.2
* Clarity: 0.13

**Device:**

* Type: PC
* OS: Windows 10
* Browser Chrome (71.0.3578.98), Firefox (64.0.2)

## Additional notes

Currently can't use the ClarityButtonGroup angular compoment because of the issue that I posted a few months ago, which forces me to use a static html markup. 
[https://github.com/vmware/clarity/issues/2616](https://github.com/vmware/clarity/issues/2616)

**Comment by youdz** [comment]
I'm not sure I understand the issue. Our static components are plain HTML and CSS, so they obviously do not have any dynamic behavior. That's the entire point of the Angular components.

If you have to use the static version of button groups but want the overflow, just add `*ngIf` (or whatever your framework uses for dynamic show/hide of elements) and toggle it when the user clicks on the ellipsis.

I'm closing this since I don't see a bug, but feel free to answer here if there is an actual bug.

**Comment by ChrisKaun** [comment]
Well I was expecting that on-hover the Overflow-Menu would appear. This can be implemented by plain css.
I don't see a real use case where I would use the Overflow option when I still need to apply custom css when using the static component.

**Comment by gnomeontherun** [comment]
You mention hovering, which is not the same as clicking. You can have CSS to have it open on hover, but that is not the UX we have defined. The point is you click the overflow button before the overflow menu shows (which is why you need some JavaScript to handle the click event to show/hide it).
