### ISSUE TITLE
unable to get nested sub menu via plugin-xml 

### ISSUE THREAD

**Issue by Syadav777** [vmware/clarity#3052]
Hi all,
I am trying to achieve nested sub menu via plugin.xml  , I have achieved the child menu but unable to get child of child sub menu .
I have share the code snippet and view .
kindly comment where I am doing wrong or needful suggestion.
Thanks in advance.

![ui_view](https://user-images.githubusercontent.com/45034693/51391350-da4b8d80-1b57-11e9-88ad-394b54eebd70.png)
![uid_view](https://user-images.githubusercontent.com/45034693/51391370-e59eb900-1b57-11e9-96d6-eb2c08b4243c.png)
![menu-view](https://user-images.githubusercontent.com/45034693/51391382-eafc0380-1b57-11e9-9cc3-d420b7270eb8.png)

**Comment by gnomeontherun** [comment]
Hi, this problem is unrelated to Clarity or Angular. You appear to be using custom build tooling and this is beyond something we can triage on GitHub through screenshots. If you need help, I suggest looking at or asking on StackOverflow, but this appears to be a general question about how to shim values from an external file into an Angular project which is beyond scope of Clarity and the default Angular tooling. Closing as a question outside of scope.
