### ISSUE TITLE
Display a datepicker next to HTML5 Time Input

### ISSUE THREAD

**Issue by cat-mandres** [vmware/clarity#3072]
## Describe the bug

It is impossible to display a clarity datepicker next to any other input element. We have the common use case of selecting a date+time and would like to display these 2 input fields next to each other.
After trying every single combination of displaying a datepicker, I still havent managed to display the time picker next to it.
There should really be some way to achieve this without using absolute positioning on my time input. A **clr-date-time-container** would be pretty helpful that works basically the same as the **clr-date-container** but also selecting a input of type="time" and displaying it at the end of it.

## How to reproduce

That wont work obviously:
```
<clr-date-container>
  <label>DateTime label</label>
  <input type="date" [(ngModel)]="date" name="date" clrDate>
  <input type="time" [(ngModel)]="time" name="time">
</clr-date-container>
```

This also does not work:
```
<div class="clr-form-control">
  <label for="date" class="clr-form-control-label">DateTime</label>
  <input type="date" id="date" name="date" [(ngModel)]="date" clrDate>
  <input type="time" [(ngModel)]="time" name="time">
</div>
```

Also tried a couple of other things, none worked.

Input the above code into your page.

## Expected behavior

A HTML5 Input of type="time" can be displayed next to a date picker. See this as an example:
![image](https://user-images.githubusercontent.com/40262875/51748004-5dff0000-20ab-11e9-82ec-eea33e7568be.png)

I would like to be able to write this code:
```
<clr-date-time-container>
  <label>DateTime label</label>
  <input type="date" [(ngModel)]="date" name="date" clrDate>
  <input type="time" [(ngModel)]="time" name="time">
</clr-date-container>
```

Optionally also a clrTime directive could be created and applied or reuse of the clrInput directive.
Currently for standalone time-fields we also use a **clr-input-container** with clrInput directive (thats works fine).

## Versions

**App**

* Angular: 7
* Clarity: 1.0.0

**Device:**

* Type: Notebook
* OS: Windows
* Browser All
* Version All

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This is not possible with current forms in the way you are trying to accomplish this. We don't have a container that hosts multiple types of inputs except for checkboxes and radios. This is difficult due to the validation issues that arise, and something we have slated for #2864. 

This is really an enhancement request, but you could look at how to do this using more of the basic CSS directly like you see in the file below. This is what we'll eventually build with a generic wrapper to support combinations of controls in one.

https://github.com/vmware/clarity/blob/master/src/dev/src/app/forms/input-group/input-group.html

I'm going to close this as a duplicate for #2864 and suggest following that ticket for updates.
