### ISSUE TITLE
Clarity datagrid freezes the browser tab.

### ISSUE THREAD

**Issue by d3lio** [vmware/clarity#3092]
## Describe the bug

When trying to use a single selection datagrid which gets its items from a property getter the browser tab hangs in an infinite loop.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-rwlewu

1. Open the stackblitz example.
2. Observe the content section that never renders and keeps loading.

## Expected behavior

A datagrid should be displayed.

## Versions

**App**

* Angular: 7.2.0
* Clarity: 1.0.5

**Device:**

* Type: iMac
* OS: macOS High Sierra
* Browsers: Chrome 71.0.3578.98 and 72.0.3626.81, Firefox 64.0.2

## Additional notes

Ways to fix:
1. Remove the single selection
2. Refactor the property getter into a simple property.

I'd like to keep both without changing them since this looks like a proper way to use the component.

**Comment by mathisscott** [comment]
The problem is that you are using a getter to return your dataset. What is the use case for using a getter to return a static dataset?

FTFY
https://stackblitz.com/edit/clarity-light-theme-v1-0-fujo7q?file=src%2Fapp%2Fapp.component.ts

**Comment by mathisscott** [comment]
I'm sorry. I wasn't clear.

The problem is with how you are using getter. It is a naive implementation that is causing Angular ChangeDetection to fire off infinitely. It has nothing to do with the datagrid. 

To properly use a getter the way you would like, you need to either pass back a reference or use trackBy.

This is not an issue with Clarity but, rather, an issue with how you are implementing getters. Here's [an example that illustrates the problem for you](https://stackblitz.com/edit/js-qm9teq).

**Comment by hippee-lee** [comment]
@d3lio - it seems your issue may be from how you are using the getter. Is there a reason you don't store users in a private property and then return the reference to that? 

```
  private _users: any[] = [
      { name: 'a' },
      { name: 'b' },
      { name: 'c' },
    ];
  get users(): any[] {
    return this._users;
  }
```

I believe this would solve your problem and allow functions that needed to operate on the list of users to do so with safety. 

https://stackblitz.com/edit/gh-issue-3092

To @mathisscott's point, this is an implementation question and better suited for [StackOverflow.](https://stackoverflow.com/questions/tagged/vmware-clarity) - this link will take you directly to the `vmware-clarity` tag.
