### ISSUE TITLE
Custom filters not showing on ClrDatagridFilterInterface

### ISSUE THREAD

**Issue by adamstauffer** [vmware/clarity#3120]
## Describe the bug

When using a custom datagrid filter component, the filter object is not appended to the ClrDatagridFilterInterface's `filters` attribute.

Attempting to use the `checkbox-list-filter` component described in [this issue](https://github.com/vmware/clarity/issues/1175#issuecomment-334267857), updated per the latest documentation for custom filtering.

Also attempted to use the `state` property on the filter as implemented in #3066 but I may be doing that wrong...

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-znytxw

1. Attempt to filter on the Role or Group field.
2. Console should be logging the ClrDatagridFilterInterface object passed from the `(clrDgRefresh)` method.
3. No `filters` should be present on the `event` object.

## Expected behavior

At the very least the `filters` attribute should exist on the ClrDatagridFilterInterface object

## Versions

**App**

* Angular: 7.2.0
* Node:
* Clarity: 1.1.0 

**Device:**

* Type: 
* OS: Windows 10
* Browser Chrome/Firefox
* Version 71/57

**Comment by Jinnie** [comment]
Your filter has some problems.
The `isActive` function always returns `false`.
This is due to `selectedItems` always being empty.
The `onItemChanged` function fails to update the array properly.
I am not 100% sure about your use-case, but something like this seems to work better:
```javascript
public onItemChanged(item) {
    if (item.checked) { // cases reversed
      item.checked = false;  // update the checked field
      let index = this.selectedItems.indexOf(item);
      if (index >= 0) {
        this.selectedItems.splice(index, 1);
      }
    } else {
      item.checked = true;  // update the checked field
      this.selectedItems.push(item);
    }
    this.changes.next(true);
  }
```
Updated Stackblitz:
https://stackblitz.com/edit/clarity-issue-3120?file=src/app/checkbox-list-filter.component.ts

This type of question is more suitable for StackOverflow than for a github issue. Please, open similar requests there. It is actively monitored. Thank you!
