### ISSUE TITLE
Weird TreeView items design

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3142]
## Summary

_Currently, there are few thing in treeview, which are weird:_

_1. Expandable nodes can't be "active"_
_2. Regular nodes that aren't supposed to be selected has height of 30px, but selectable ones - 34px; text in selectable nodes is shifted to the right._

![image](https://user-images.githubusercontent.com/32732457/53426996-1dbbd600-39f9-11e9-9f34-0f9fcfa07574.png)

* **What is the change?** Make expandable nodes selectable for all tree view types; make selectable and non-selectable nodes have identical height and text position.
* **Why should it go in Clarity?** Because current implementation is pretty limited by things described above.
* **Does this change impact existing behaviors? If so how?** it adds ability to make node both expandable and active. Other changes are cosmetic.

## Use case

_File Browser. Folders can be expandable and selectable simultaneously. Files and folders can exist on a same level of hierarchy._

## Workarounds

For selectable expandable nodes - not sure, for cosmetic changes - css overrides.

**Comment by youdz** [comment]
Expandable nodes can absolutely be active, here is a running example: https://stackblitz.com/edit/tree-active-parent?file=src/app/app.component.html

Give me a little time to understand what you mean with the node height, I'll get back to you on this. But the shift to the right was part of the spec, because it helps to visually "break" the vertical line between parents and children, see better what's nested or not from a glance.

**Comment by youdz** [comment]
Ok, so I inspected the DOM and CSS for tree nodes, and I do not see a 34px height. What we have is 30px for non-button nodes, 32px for button nodes, but no 34px that I can find.

The discrepancy is indeed a bug, and it looks like it's due to use remove the border on the buttons with `border-color`, which keeps a 1px transparent border. This normally wouldn't be an issue with the `box-sizing: border-box` we use everywhere, but tree nodes are not sized with `height` directly, but rather with `line-height`.  So this 1px transparent border creates a 2px difference between nodes that contain a `<button class="clr-treenode-link">` and nodes that don't.

Should be a fairly straightforward fix, so I'm adding this very specific height bug in our backlog, but I think I have answered the rest in my comments. Please tell us if that's not the case.

**Comment by sdurnov** [comment]
@youdz well, looks like I mixed clr-tree-node with buttons (which I was using if node has children) and nodes with plain text (for nodes with no children) in 1 tree view, so this was causing problems for me.
Nodes with plain text have 30px height and they, of course, are not selectable by default, so left padding is also different.

_So, summing up, there are 2 problems:_
1. combining selectable button nodes and non-selectable plain text nodes within 1 level.
2. button nodes and plain text nodes have different height.

**Comment by sdurnov** [comment]
@youdz here are items with 34px height from your example
![image](https://user-images.githubusercontent.com/32732457/53645787-b006e880-3c4a-11e9-8a0d-3b19b541a142.png)
