### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by power721** [vmware/clarity#3147]
## Describe the bug

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'singleSelected: undefined'. Current value: 'singleSelected: null'.

## How to reproduce

1. Html
```html
<clr-datagrid [(clrDgSingleSelected)]="selected">
...
</clr-datagrid>
```

2. Component
```typescript
  refresh(state: ClrDatagridStateInterface) {
      this.selected = null
  }
```

## Expected behavior

no errors.
This code works fine on Clarity 0.12.3-patch.2

## Versions

**App**

* Clarity: 1.1.0

**Comment by gnomeontherun** [comment]
In the future it helps to provide us with a demonstration using StackBlitz, otherwise it is difficult to know what is happening.

This is a common Angular issue, make sure to set your property to null by default `selected = null`. The problem arises because you have changed the value of `selected` inside of the same change detection cycle.

**Comment by Jinnie** [comment]
I can't reproduce it with 0.12.3-patch.2
https://stackblitz.com/edit/issue-3147-0-12-3?file=package.json
This is also a duplicate of this one: https://github.com/vmware/clarity/issues/1519
Instead of applying the workaround proposed above, you could also avoid this error if you initialize this.selected with null instead of leaving it undefined, so the initialization refresh event won't trigger this exception.

And please, prepare stackblitz examples for your future issues, this helps us a lot to be more efficient, and improves the chance of getting quick and precise response to your questions :) 
(https://stackblitz.com/@clr-team)

**Comment by power721** [comment]
I didn't see this error when I was use Clarity 0.12.3-patch.2 and before version.
Now I use Clarity: 1.1.0, I see this error almost on every page.
In other case I use datagird [clrDgLoading], it report this error.
https://stackblitz.com/edit/issue-3147-0-12-3-lxbzzg
