### ISSUE TITLE
How to get master,child,subChild,etc(child of child) pattern in datagrid with expandable rows?

### ISSUE THREAD

**Issue by ags504** [vmware/clarity#3210]
https://clarity.design/documentation/datagrid/expandable-rows

I have a requirement to display expandable row which itself need to be expanded till the last child with lazy loading for each level of the child.

**Comment by gnomeontherun** [comment]
This sounds like a question for StackOverflow instead of an issue with Clarity. Please post how to questions there in the future.

I’m also not clear what you are asking about, but expandable rows can project a component that lazy loads data into the detail row, just like you would do with any component onInit. 

Closing as not an issue, but please post on StackOverflow with better details about your use case if you need.
