### ISSUE TITLE
Datagrid: Content doesn't align well when icon and button are present in cell

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#3256]
## Describe the bug

We have UX design where we have buttons/icons in datagrid cell. However after putting the Clarity button (with `btn-sm`) and icon (with default size 16px), the datagrid overall alignment is not ideal and the rows (normally has height as `35px` with text only) get expanded.

## How to reproduce
https://clarity-light-v1-0-datagrid-with-button-and-icon.stackblitz.io

<img width="811" alt="Screen Shot 2019-03-27 at 8 31 54 PM" src="https://user-images.githubusercontent.com/8813134/55128029-65548100-50cf-11e9-9986-5ae77de90e7e.png">

## Expected behavior

As a component consumer using only Clarity elements (datagrid, clr-icon and button), I'm expecting this to work out of the box. Expanding rows might be ok but the current alignment doesn't look pleasing to the user.

I have to do `CSS overrides` on the data grid cell to make it look satisfying and match our design, which in my opinion is not a sustainable approach as it depends on existing Clarity styles.

## Versions

**App**

* Angular: 7
* Clarity: 0.13.8, also reproduce in 1.0 in above link.

**Device:**

* OS: Mac OS
* Browser: Chrome latest.

**Comment by hippee-lee** [comment]
Hi @yaooluu.
Datagrid cells will grow to fit the content thats put inside of them, I think it would be better to remove the margin from the element (button e.g) with a class that only gets added to elements in datagrid cells that have a margin already applied to them:
```html
<button class="btn btn-sm dg-cell-element">Action</button>
```
css
```css
.dg-cell-element {
  margin: 0;
}
```

I'm leaving this open since I know there has been some internal discussion re: the margin around buttons and the issues that are caused by it. @colinreedmiller - am I correct that there was discussion re: removing the margins from buttons as part of the Hawaii refresh? If so could this issue be closed?

**Comment by colinreedmiller** [comment]
There are a couple factors at play re: margins.

1. We have some irregularities regarding margins and padding, and they effect the vertical rhythm and create layout concerns that require overrides such as in this issue. I'd like to address this as part of HawaiiFresh but @mathisscott and I need to examine the systemic consequences of opening this up.
2. Regardless of what we do with our layout attributes and paradigm, we need to start being thoughtful about 44px touch targets for WCAG 2.1 - unless buttons grow to 44px tall there is some handling of the area around them that we we need to be mindful of @chlane might contribute some insight since it is somewhat complex regarding what is AA vs AAA / mobile / responsive etc.

Regarding this issue: I agree with @hippee-lee suggestion of overriding the margin - it is consistent to the way other spacing issues are currently handled.
