### ISSUE TITLE
alerts-page small for small alerts

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#3271]
## Summary

Please add a _small_ or _size_ option for alerts component so that the text aligns with the alerts when the alerts are small. Or detect automatically to determine the alerts container size.

Currently, the alerts component doesn't have a size option.

* What is the change? - Please add a size option in the alerts component or detect the size of it's children to determine the size.
* Why should it go in Clarity? - In the following use case, the inside alerts should be small, if the alerts component - the container component - is not set the same compact size, it looks weird.
* Does this change impact existing behaviors? If so how? - No impacts.
* If this change introduces a new behavior, is this behavior accessible? - N/A

## Use case

We are using alerts in component level because the project is a plugin inside an iframe.
The alerts resides on the top of a datagrid which is under tabs as sub-nav. If it's not compact, the alerts looks disturbing.

Given the `clrAlertSizeSmall` option of inside alerts is true, the alerts-page looks strange with the text too low.
![image](https://user-images.githubusercontent.com/3956876/55450730-b77f3000-5602-11e9-8736-1bbc153aadec.png)

## Examples

No.

## Workarounds

The size can be overridden by setting the ::ng-deep style. But it's better to have the built-in option.

Thanks.

**Comment by gnomeontherun** [comment]
We don't currently support compact alerts as app level, which is something we'd have to consider if that is proper UX or not to support first. If you can give more information about why you're using the compact that would be great, because compact sizes are problematic for accessibility reasons.

**Comment by KingMario** [comment]
We are using alerts in component level because the project is a plugin inside an iframe.
The alerts resides on the top of a datagrid which is under tabs as sub-nav. If it's not compact, the alerts looks disturbing.

Thanks.

**Comment by hippee-lee** [comment]
@KingMario - this does sound reasonable to me. I would consider this a feature request since it is an enhancement to an existing component for a new use case. 

We definitely want to have UX and design consider this for two reasons, to think through and document the use case and to figure out how this should be captured in the website documentation. 

Usually this request would go through the [new feature issue template](https://github.com/vmware/clarity/issues/new?template=feature-request.md). Since you already have an issue you could update the description with the required info for that or, close this issue and open a new one that uses that template. I don't have a preference so please follow the path that is easiest for you. 

Once we have that we can track the issue and get it into the backlog so that UX/Design resources can take a look.

**Comment by KingMario** [comment]
@hippee-lee The issue description is updated.

Thanks.

**Comment by mathisscott** [comment]
alert-pager will be introduced as an enhancement for app-alerts in core after 4.0

**Comment by mathisscott** [comment]
There's a lot more going on with this change than initially estimated. The sizing of the alert with the pager requires design/ux work. Putting this back for triage and ux.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
