### ISSUE TITLE
Datagrid rendering is very slow

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3276]
## Describe the bug
Modern browsers are now capable of holding large arrays/lists. Even a thousand-record array is not a problem. So, I limit the maximum records to 200-500 that the data grid will display and the rest of the records will be visible in the next page. However, it's rendering the rows very slow especially when there are columns that have custom styling like links, currency and/or numeric formatted, text alignments, etc. This is due to all rows are being rendered into the DOM including the ones that are not visible in the data grid.

## Expected
The data grid should have an option that enables rendering only the rows that are visible within the data grid's height.
![Untitled Project](https://user-images.githubusercontent.com/1977391/55643255-4b204e80-5805-11e9-8995-b24c28441271.gif)

## Actual
All 500 records were already loaded and the HTTP request only took about 20-100 milliseconds. But, the data grid still rendering the rows and it took 20-30 seconds.
![image](https://user-images.githubusercontent.com/1977391/55643805-9f77fe00-5806-11e9-8c37-a6f2ea67001e.png)

## Workaround
Limit the page by 50 but this number is too small. With virtual scrolling, even millions of records can be displayed smoothly.

* Angular: [e.g. 6] 7
* Node: [e.g. 8.10.0] 11
* Clarity: [e.g. 0.12.5] Latest

**Device:**

* Type: [e.g. MacBook] Dell XPS 13
* OS: [e.g. iOS] Windows 10
* Browser [e.g. chrome, safari] Chrome
* Version [e.g. 22] Latest

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
This has been discussed before. Please search the project issues before opening new ones. 

See #41 and #3138 for prior discussion around this topic.

**Comment by TekSiDoT** [comment]
@hippee-lee After reading both #41 and #3138 I am quite certain that the terms virtual and infinite scrolling have been mixed (unjustifiedly so imo). 

 _Infinite Scrolling_ describes the UX of scrolling a table/datagrid to the bottom causing to request and insert a continous stream of additional rows

_Virtual Scrolling_ describes a rendering performance improvement technique aimed to decrease the number of rendered rows to the ones that are actually visible in the DOM.

As far as I can see: #41 is requesting Infinite Scrolling, #3138 and #3276 are requesting Virtual Scrolling.

**Comment by TekSiDoT** [comment]
@hippee-lee Any chance you could revisit this issue? I'd be willing to contribute if necessary.

**Comment by hippee-lee** [comment]
Hi @TekSiDoT - I'm open to virtual scrolling as described here as long as it doesn't have the same issues that infinate scrolling have wrt accessability because those same a11y requirements will still apply. It will need to take into account everything that has already been applied to make the datagrid accessible and ensure that it doesn't block the enhancements that are still needed. E.g - keyboard user enhancements like navigating between cells.

If you are interested in contributing the first step would be to start with the _[proposal template](https://github.com/vmware/clarity/blob/master/DEVELOPMENT_CONTRIBUTION.md)_ so we can start a conversation about the proposal.
