### ISSUE TITLE
Cannot change datagrid header column order when no data in row

### ISSUE THREAD

**Issue by humphrycc** [vmware/clarity#3299]
## Describe the bug

When no data in datagrid row, cannot change column order, it works well when any data in row.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-gfdtib

1.  Click any 'angle bottom' icon button at the bottom
2.  See the first datagrid header and columns order changed, but the second does not.

## Expected behavior

Column or header order can be changed even if no data in datagrid row.

## Versions

**App**

* Angular: 7.2.0
* Node: v10.15.1
* Clarity: 1.0.4

**Device:**

* Type: Mac
* OS: macOS 10.14
* Browser Chrome and Safari
* Version Chrome version 73.0.3683.103, safari version 12.1

**Comment by Shijir** [comment]
Hi @humphrycc, thanks for reporting this. We are currently working on a feature that will allow users to reorder columns through flex order instead of manipulating dom order of the columns. 

But what you are reporting here is indeed bug. I remember this used to work fine before. And I did a quick repro in Clarity v0.13 and it's working here: https://stackblitz.com/edit/clarity-light-theme-v013-dynamic-columns?file=src/app/app.component.html. 

So we will take a look into what was introduced into v1.0 that made it stop working.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
