### ISSUE TITLE
Ability to minimize Sidenav completely to reuse the space on large devices

### ISSUE THREAD

**Issue by mvsrao** [vmware/clarity#331]
Currently Sidenav contents can be minimized but Sidenav title still displaying the screen . Is there a property on the Sidenav to minimize it completely as an icon on the large devices in a way that happens on smaller devices to reuse the screen space.

**Comment by jaffoneh** [comment]
@mvsrao I am assuming what you're asking for is a collapsable side navigation pattern?

I am closing this request since it does not include the issue template we recommend using. Without it, it is unclear if you're reporting an issue, asking for a feature request, or an enhancement. Also, without it and without more details, it is unclear what you're asking for.

Please do reopen another issue using the template provided by default with more details and we'll be happy to address it.
