### ISSUE TITLE
The checkbox's disabled doesn't match the style

### ISSUE THREAD

**Issue by yesterdaytime** [vmware/clarity#3314]
## Describe the bug

When I used the checkbox and clrInLine, the disabled of the checkbox doesn't match the style.

## How to reproduce

https://stackblitz.com/edit/clarity-checkbox-inline?file=src%2Fapp%2Fapp.component.html

If the disabled checkbox is the last one, all the style show the disabled, but the checkbox can be selected.
If the disabled checkbox isn't the last one, all the style show the able, but the disabled checkbox doesn't select.

## Expected behavior

Show the style correct.

## Versions

**App**

* Angular: [7.2.11]
* Node: [8.11.3]
* Clarity: [1.1.2]

**Device:**

* Type: [MacBook]
* OS: [macOs]
* Browser [Chrome]
* Version [73.0.3683.103]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This is actually working as expected, because in a checkbox container all controls roll up under the same validation and disabled state. Here you've mixed disabled on some, when it needs to be consistent. Therefore, you should treat all checkboxes in a container as one control, and right now the behavior is that the last checkbox is used to review the validation/disabled state of the checkboxes. 

If you want to validate/disable checkboxes individually, each needs to be in a separate container. Closing as working as expected.
