### ISSUE TITLE
Datagrid multi select not preserved when list is refreshed

### ISSUE THREAD

**Issue by farlock85** [vmware/clarity#3325]
## Describe the bug

When a list is refreshed it's not taking the selected options into consideration. When re-checking the same item again it's added again to the selected array and not taking the already selected item into consideration.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-whkqxi

## Expected behavior

It should re-check the items that are in the array.

**Comment by gnomeontherun** [comment]
You need to use TrackBy for datagrid to be able to track the items, because you are creating a new object that means there is no reference to keep track of without a track by statement to tell us what property to use (usually an ID or a unique identifier of some type). See https://angular.io/guide/template-syntax#ngfor-with-trackby
