### ISSUE TITLE
In Datagrid *clrDgItems is not working

### ISSUE THREAD

**Issue by yanyixing** [vmware/clarity#342]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Environment details

* **Angular version:** 2.4.1

* **Clarity version:0.8.0

* **OS and version: osx 10.11.6

* **Browser:** [ Chrome 55.0.2883.95 ]

*clrDgItems not working, but *ngFor works fine

**Comment by youdz** [comment]
Angular 2.4.1 and Clarity 0.8.0 are incompatible due to a breaking change introduced in Angular. Please either upgrade to Clarity 0.8.1 or change to a different Angular version (either 2.4.0 or 2.4.2).

See #282, #320 and https://github.com/angular/angular/issues/13641 for more information.

For next time, please take the time to at least look at your browser console, you would have seen a big red error saying "trackBy must be a function", which would have helped all of us.

**Comment by yanyixing** [comment]
please update the clarity-seed 's package.json file
