### ISSUE TITLE
Karma: Elements not known

### ISSUE THREAD

**Issue by davidmehren** [vmware/clarity#3426]
## Describe the bug

When trying to test components using Karma, the custom Clarity elements are not found.

## How to reproduce

1.  Create an empty app using `ng new test-app`
2.  Add Clarity using `ng add @clr/angular`
3.  Replace the contents of `app.component.html` with
```html
<form clrForm>
    <clr-input-container>
        <label>Field 1 label</label>
        <input clrInput type="text" name="example" />
    </clr-input-container>
    <clr-input-container>
        <label>Field 2 label</label>
        <input clrInput type="text" name="example" />
    </clr-input-container>
</form>
```
(This is a sample from https://clarity.design/documentation/forms without the `ngModel` tags.)
4.  Run `ng test`
5.  `AppCompontent` can not be created because of multiple errors like `'clr-input-container' is not a known element`

## Expected behavior

`ng add @clr/angular` correctly configures a project to run Karma tests.

## Versions

**App**

* Angular: 8.0.2
* Node: 11.15.0
* Clarity: 2.0.0

**Device:**

* Type: ThinkPad
* OS: Arch Linux
* Browser: Chrome
* Version 75.0.3770

## Additional notes

After adding
```js
schemas: [
        CUSTOM_ELEMENTS_SCHEMA
      ],
```
to `app.component.spec.ts` the error goes away, but the resulting page does not seem to use Clarity (CSS is not applied).

**Comment by gnomeontherun** [comment]
You actually don't want Clarity to be automatically added to all of your tests, as that adds overhead for the tests running. As with any unit test, it should be isolated and not contain anything that isn't necessary for testing. Adding a the custom elements schema won't make your tests run properly because it just turns off the warning about unknown elements.

In this case, any tests that run using Clarity forms would be setup in your spec file by creating a test bed that includes the ClrFormsModule (we have modules for most of our components and some groups of related components, so you can easily import only the related items to your test).

As far as CSS, if you are including Clarity in your project CSS (through angular.json) then it should be picked up by your tests assuming you have a new project.

Closing this as more of a question about how to write tests with Clarity, feel free to post on Stack Overflow if you have other questions.
