### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by yanyixing** [vmware/clarity#343]
Select one ... (check one with "x")

[x] bug
[ ] feature request
[ ] enhancement
Expected behavior

Actual behavior

Reproduction of behavior

Environment details

Angular version: 2.4.1

**Clarity version:0.8.0

**OS and version: osx 10.11.6

Browser: [ Chrome 55.0.2883.95 ]

In my datagrid template html file, {{users.length}} will meet this error: TypeError: Cannot read property 'length' of undefined
If I using {{users?.length}}, it works fine.

**Comment by youdz** [comment]
Please provide more information, we have no idea what `users` is in your case.
We have an issue template for this reason, so that you can give a detailed explanation of what's happening and a link to a plunker reproducing the issue.

That said, please see my answer to your issue #342: Angular 2.4.1 and Clarity 0.8.0 are incompatible. You can change either of them to a different version, be it future or past.
