### ISSUE TITLE
Stack, stepper, and accordion - visual design

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#3471]
These 3 components need a visual design review, to understand their alignment.
Goals are:
Ensure consistency of global conventions re: color, sizes, spacing etc.
Explore compact sized versions
Explore indicative variations for differentiation once alignment is achieved

**Comment by coryrylan** [comment]
Some additional notes/context on the three components:

The stepper component is the accordion component but with the linear progression and forms requirement. The code/CSS for the accordion and stepper are the same components so visually they have the same spacing, padding, etc.

The stack view is sort of an accordion but is very limited to only key-value pairs of data whereas the accordion can support any generic content. The stackview is one of the oldest components in Clarity and is missing some features the new accordion/stepper component provides.

There was some discussion at one point to deprecate the stack view and only have the accordion since the accordion is much more flexible and supports more use cases. We can also port the paired data layout of the stackview to the accordion to make migrations easier and only have the two components, accordion/stepper in Clarity.

**Comment by colinreedmiller** [comment]
Design for visual alignment here:

https://www.figma.com/file/DSg29G9xgvIgZStrM950ltDr/stepper-stack-accordion?node-id=0%3A1

We need to validate the design and development implications of merging the accordion and stack view.
