### ISSUE TITLE
Introduce new clrOptionsLoading option to clr-select-container

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#3472]
## Summary

* What is the change?

Add an option to set a loading state on the clarity select container component. If true, instead of the select checkbox there should be a spinner displayed.

* Why should it go in Clarity?

Select options are often loaded asynchronously. In large forms it makes sense to begin to fill out the forms, even if not all resources (= select options) are loaded.

* Does this change impact existing behaviors? If so how?

Don't know.

* If this change introduces a new behavior, is this behavior accessible?

Don't know.

## Use case

Imagine a form in which you can configure a new user in some system. You can set stuff like name, email, etc and the interface language. The available languages however need to be loaded asynchronously. 

## Workarounds

You can replace the whole `clr-select-container` by some HTML to align the label and the spinner in the form.

**Comment by gnomeontherun** [comment]
This is really in the realm of #248 which is being worked on, I believe it will address this concern and if you decide to use a regular select box we'll recommend the same workaround to handle it on your end with ngIf to show a loading indicator somehow.

Also, you can disable the select until it has loaded, perhaps also change the helper text for the time being to indicate loading.

Closing since it should be resolved by other work in #248.
