### ISSUE TITLE
Broken scss variables import

### ISSUE THREAD

**Issue by meeroslav** [vmware/clarity#3479]
## Describe the bug

_When importing  **src/utils/variables.clarity.scss** in Angular component styles in order to (re)use clarity variables one must also import grid variables, mixins and layers as they are unresolved dependencies of variables files._

```scss
@import "~@clr/ui/src/utils/_layers.clarity";
@import "~@clr/ui/src/utils/_mixins.clarity";
@import "~@clr/ui/src/layout/grid/variables/variables.clarity";
@import "~@clr/ui/src/utils/_variables.clarity";
```

Omitting grid variables is causing
![Screenshot from 2019-06-19 11-13-59](https://user-images.githubusercontent.com/881612/59755796-db105900-9288-11e9-9dbf-d45a15162e35.png)

Omitting mixins is causing
![Screenshot from 2019-06-19 11-15-35](https://user-images.githubusercontent.com/881612/59755836-e95e7500-9288-11e9-8cb7-bb713a92b211.png)

While omitting layers causes
![Screenshot from 2019-06-19 11-16-23](https://user-images.githubusercontent.com/881612/59755848-eebbbf80-9288-11e9-8a97-953fedb5ba12.png)

## How to reproduce

_[Stackblitz repo](https://clarity-scss-import-variables-bug.stackblitz.io)._

1.  Open the application and you will see the bug
2.  Bug is caused by import in `src/app/app.component.scss`

## Expected behavior

_In order to use scss variables, importing **src/utils/variables.clarity.scss** should be enough. Variables file should not have unresolved dependencies._

## Versions

**App**

* Angular: 8.0.0
* Node: 12.3.1
* Clarity: 2.0.1

**Device:**

* Type: Dell XPS
* OS: Ubuntu
* Browser Chrome
* Version 74

## Additional notes

_This seems to be randomly changing from version to version. It was working in v1. Related to https://github.com/vmware/clarity/issues/2442_

**Comment by mathisscott** [comment]
@meeroslav 
What is the intended end result? Is this an attempt to theme the clarity components or are you trying to reuse the clarity variables in your own SASS files without using the rest of the library?

**Comment by Rush** [comment]
Just wanted to bring my own comment on the same topic https://github.com/vmware/clarity/issues/2442#issuecomment-501149800

I also have an open ticket https://github.com/vmware/clarity/issues/3444

I still owe you an answer @mathisscott. The reason I have not commented yet is that I was awaiting on answer from my frontend dev for all of the reasoning. It wasn't a blocker since we were actually able to stick with the 1.x branch but now it turns out we need Angular Universal ... which for Node.JS 12 needs Angular 8. Which means we need the 2.x branch. 

Anyway ... I'd appreciate any work to make 2.x variables as flexible (or more) as 1.x.

**Comment by mathisscott** [comment]
@Rush 
Thanks for circling back to us on this. 

#3444 is a different issue from this one. I'd prefer to keep the issues relevant to their individual topics so as to not engage in scope creep or conflating seperate bug reports or feature requests into one issue.

I'll comment there on the state of maps and variables in the SCSS.

For this issue (the addition of a dependencies.scss file so people can import individual clarity SCSS files more easily), I'm still unclear on the end goal.

Is the intent to reuse Clarity variables in a product's SCSS?

Is the intent to modify Clarity variables in a manner we would consider theming?

Once I understand what @meeroslav is trying to accomplish, I can try to diagnose either a workaround or what a convenience dependencies import would need to pull in.

**Comment by meeroslav** [comment]
Sorry @mathisscott, I somehow missed your reply.

My intent is to reuse the clarity variables in my custom angular component's SASS files to maintain the same visual style.

**Comment by gnomeontherun** [comment]
As we stabilize and lock Clarity Angular's features, this shouldn't be an issue in the future. Files did move from time to time, which could have broken import chains. With Clarity Core, we don't anticipate this issue because theming should resolve the need to build custom versions of CSS. I'm going to close this as stale and not something that should continue to affect folks in future updates.
