### ISSUE TITLE
Make inputs responsive to grid classes

### ISSUE THREAD

**Issue by MRamos62786** [vmware/clarity#3480]
## Summary

* What is the change?
Inputs wrapped by div with the clr-input-wrapper class would span the horizontal space available when grid classes were applied to the input element. This was originally proposed on https://github.com/vmware/clarity/issues/2704 by @sdurnov.

* Why should it go in Clarity?
Seems the appropriate default behavior when using grid.

* Does this change impact existing behaviors? If so how?
Would cause input to fill desired grid column.

* If this change introduces a new behavior, is this behavior accessible?
N/A.

## Use case

Go to https://stackblitz.com/edit/clarity-light-theme-v2-numrus
Note the input does not span the available horizontal space within the clr-row

## Workarounds

Some vague workaround was described on https://github.com/vmware/clarity/issues/2704.

**Comment by gnomeontherun** [comment]
We discussed this and don't believe this should be the default behavior, but do agree that there are some scenarios where it would be useful. Essentially, we think we can help you do this in an opt-in mode so its easier to manage. However, it may not work or may have to work differently in compact mode due to the complexities of everything being in one row.

Moving to the backlog.

**Comment by gnomeontherun** [comment]
This is a feature available in Clarity Core's forms. Consider using the Clarity Core version of the component for your application to get these benefits. In an effort to clean up our backlog and focus our attention, I’m going to close this as resolved by implementations in Clarity Core.
