### ISSUE TITLE
[Datagrid] The 2nd custom string filter doesn't work

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#3486]
## Describe the bug

Adding custom string filters to columns in a Datagrid works for every column except for the 2nd.  

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-cwbulg?file=src%2Fapp%2Fapp.component.html

1.  Try adding filter values to any of the four columns.  The filters work properly for every column except the 2nd.  

## Expected behavior

All columns work.  

## Versions

**App**

* Angular: 8
* Node: 12
* Clarity: 2

**Device:**

* Type: Mac
* OS: MacOS
* Browser: Chrome (also Firefox)
* Version 47

## Additional notes

This might be related to https://github.com/vmware/clarity/issues/3282

**Comment by hippee-lee** [comment]
Question posted on Stack overflow that might be related: 
https://stackoverflow.com/questions/57066356/clarity-datagrid-custom-filtering-isnt-working-with-more-than-one-filter
Stackblitz: https://stackblitz.com/edit/clarity-light-theme-v2-dwqmgr

**Comment by spitfjre** [comment]
I can confirm this problem in all versions since 2.0.0, that only the first custom filter appears in the `state.filters` object. For all others `state.filters` is `undefined`.

**Comment by kathygit** [comment]
Hi, I wonder if there is a date for it get fixed. This issue prevents us from use Clr 2.0. Thank you!

**Comment by kathygit** [comment]
I dug into the code ... Here is the reason:
When we use clr-dg-string-filter and clr-dg-numeric-filter, we don't project new content, but alter the accepts() to define our own filter criteria. 
In this case _this.customFilter = false

```
var ClrDatagridColumn = /** @class */ (function (_super) {
    __extends(ClrDatagridColumn, _super);
    function ClrDatagridColumn(_sort, filters, vcr, commonStrings) {
        var _this = _super.call(this, filters) || this;
       .....
           /**
         * A custom filter for this column that can be provided in the projected content
         */
        **_this.customFilter = false;**
```

**Comment by kathygit** [comment]
I am not sure what the fix should be, maybe in DatagridFilterRegistrar ?
We shall add a check to search the registrar by filter name ? 

```
DatagridFilterRegistrar.prototype.deleteFilter = function () {
        if (this.registered) {
            this.registered.unregister();
            delete this.registered;
        }
    };
```

**Comment by kathygit** [comment]
or, just remove this block
```
Object.defineProperty(ClrDatagridColumn.prototype, "field", {
        get: function () {
            return this._field;
        },
        set: function (field) {
            if (typeof field === 'string') {
                this._field = field;

                // ***********
                // remove this block ? 
                // ***********

                if (!this.customFilter) {    
                    if (this.colType === 'number') {
                        this.setFilter(new DatagridNumericFilterImpl(new DatagridPropertyNumericFilter(field)));
                    }
                    else {``
                        this.setFilter(new DatagridStringFilterImpl(new DatagridPropertyStringFilter(field)));
                    }
                }
               ....
            }
        },
```

**Comment by gnomeontherun** [comment]
@kathygit thanks for taking a dive into this and doing some triage! I haven't had a chance to dig into the whole extent of the problem, but if you can verify your fixes with the stackblitz demo in the ticket I'd welcome a PR to help us take a closer look and get this fixed up.

**Comment by kathygit** [comment]
Finally I found the root cause --- classic index issue.
Look at the method below:

```
/**
     * Registers a filter, and returns a deregistration function
     */
    FiltersProvider.prototype.add = function (filter) {
        var _this = this;
        var index = this._all.length;  
        var subscription = filter.changes.subscribe(function () { return _this.resetPageAndEmitFilterChange([filter]); });
        var hasUnregistered = false;
        var registered = new RegisteredFilter(filter, function () {
            if (hasUnregistered) {
                return;
            }
            subscription.unsubscribe();
            _this._all.splice(index, 1);
            if (filter.isActive()) {
                _this.resetPageAndEmitFilterChange([]);
            }
            hasUnregistered = true;
        });
        this._all.push(registered);
        if (filter.isActive()) {
            this.resetPageAndEmitFilterChange([filter]);
        }
        return registered;
    };
```

We store "index" with the  registered filter at the filter creation time:
var index = this._all.length;  

Then later on we clear up the default string filter if there is a semi-custom filter at line:
 _this._all.splice(index, 1);

We do the clear up after we have registered all the filters. 
For each semi-custom string filter, there are 2 items in the _all array.
One from the default string filter, one from the semi-custom filter. 

With the example in the stackblitz above:
We have 4 columns, Name, Revision, Type, Status. 
When the filters are created for all columns, _array looks like this:
[0] default Name filter
[1] OrFilter Name
[2] default revision filter
[3] OrFilter Revision
[4] default Type filter
[5] OrFilter Type
[6] default Status filter
[7] OrFilter Status 

Then the code will do the clean up for the column through observer created at the filter creation time. It calls ```  _this._all.splice(index, 1); ``` with the ORIGINAL index at filter creation time. 
And that is the problem. We are using the origin index while we are altering the _all array at the same time. So it is just luck that ONLY the 2nd column doesn't work. 

Here it how it goes:

Clean up default column for Name, index was 0, _this._all.splice(index, 1);
after that _all looks like:
[0] OrFilter Name
[1] default revision filter
[2] OrFilter Revision
[3] default Type filter
[4] OrFilter Type
[5] default Status filter
[6] OrFilter Status 

All good so far, then move on to Revision, _this._all.splice(index, 1);
Clean up default column for Revision, index was 2, after that _all looks like:
[0] OrFilter Name
[1] default revision filter
[2] default Type filter
[3] OrFilter Type
[4] default Status filter
[5] OrFilter Status 

Notice the semi-custom Revisiton filter, that's why the 2nd column DOESN'T WORK. 

Then move on to Type,  _this._all.splice(index, 1);
Clean up default column for Type, index was 4, after that _all looks like:
[0] OrFilter Name
[1] default revision filter
[2] default Type filter
[3] OrFilter Type
[4] OrFilter Status 

Then move on to Status, _this._all.splice(index, 1);
Clean up default column for Status, index was 6, after that _all looks like:
[0] OrFilter Name
[1] default revision filter
[2] default Type filter
[3] OrFilter Type
[4] OrFilter Status 

splice() simply ignores it if the start index is greater than the length of the array. 
So ONLY the 2nd semi custom filter will fail because it s custom filter is deleted by mistake. 

Luckily, this issue only happens with semi-custom filter, because a default string filter is created for it first before the semi-custom filter is created.
For a true custom filter, no default string filter is created.

**Comment by kathygit** [comment]
@amellnik 
Can I send you the fix, it will be faster than me fork and push a PR ?

**Comment by kathygit** [comment]
@amellnik here is the fix:
FiltersProvider.prototype.add = function (filter) {
        var _this = this;
        var index = this._all.length;
        var subscription = filter.changes.subscribe(function () { return _this.resetPageAndEmitFilterChange([filter]); });
        var hasUnregistered = false;
        var registered = new RegisteredFilter(filter, function () {
            if (hasUnregistered) {
                return;
            }
            subscription.unsubscribe();

            // replace the below with fix
            // _this._all.splice(index, 1);

            // *** fix starts
            var matchIndex = _this._all.findIndex(function (item) {
                return item.filter === filter;
            });
            if (matchIndex >= 0) {
                _this._all.splice(matchIndex, 1);
            }
            // *** fix end
            
            if (filter.isActive()) {
                _this.resetPageAndEmitFilterChange([]);
            }
            hasUnregistered = true;
        });
        this._all.push(registered);
        if (filter.isActive()) {
            this.resetPageAndEmitFilterChange([filter]);
        }
        return registered;
    };

**Comment by amellnik** [comment]
@kathygit Great catch!  I'm traveling at the moment but could put together a PR next weekend if you don't get to it first.  Thanks!
