### ISSUE TITLE
Adobe XD Design Resources

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#3492]
## Summary
As Adobe XD is gaining more popularity, support for it would be an great addition in Clarity Design Resources.

## Workarounds
Imported sketch resources work somehow, but clumsy

## Related
Need an Adobe Experience Design UI Kit for mockup and prototyping #1233

**Comment by gnomeontherun** [comment]
Thanks for the request. I don't see us being able to do this anytime soon, because there are certainly too many potential design tools to support and its already a lot of work to keep up the ones we have. I'd rather focus on what we can do beyond supporting specific tools.

Closing this as something we don't intend to do.
