### ISSUE TITLE
Alerts in Wizards are read immediately when not urgent

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3497]
## Describe the bug

When a wizard has an alert in the page, it is read immediately and it is a simple status alert.

## How to reproduce

https://stackblitz.com/github/clane/clarityTest2/tree/master/clarity-test-app

- Using a screen reader, activate the WIZARD + ASYNC FORM VALIDATION button under the Wizards - Wizard with Async Form Validation example
- Notice that the next announcement from the screen reader is "This 
wiki article
 might help you answer the question."

## Expected behavior

The alert should not be read unless it is urgent.

Recommendation: 
Use polite live regions for status updates and ensure they are empty when the page first loads. Then dynamically populate them with messages as needed.

## Additional notes

This might be something we need to address with documentation as well for alerts, as they can be placed anywhere with this same type of problem. This is really not a Wizard issue, but Alerts not always being needed to read out to screen readers.

**Comment by hippee-lee** [comment]
Modify ClrAlert to default to polite live regions and provide an input to set the live region to urgent.

**Comment by bdryanovski** [comment]
The issue here is that the `clrAlert` use `role="alert"` 

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

This automatically set the `aria-live="assertive"` so when trying to change it with `aria-live="polite"` it has no effect at all.

So I got two solutions on the issue here.

* Remove `role="alert"` and handle it with `aria-live="setAriaState"` and input to change its value. 
* Add input to add or remove `role="alert"` if needed. Basicly trigger between `aria-live="off" and `aria-live="assertive"` - there is no option for "polite".

Also when using `role="alert"`.

> If an element already has role="alert" and is initially hidden using CSS, making it visible will cause the alert to fire as if it was just added to the page. This means that an existing alert can be "reused" multiple times.  

When the Alert is `danger` or `warning` could be useful to have the `role="alert"` but this still depends on the use case.

I'm more for removing the `role="alert"` and going with `aria-live` - let the developer handle this in whatever manner the application required it.

Open for discussion 🤓

**Comment by bdryanovski** [comment]
Version A:

```html
// Wait it's turn
<clr-alert ... clrPolite></clr-alert>

// Mimic role="alert" and interept the voiceover
<clr-alert ... clrAssertive></clr-alert>

// Don't do anything.
<clr-alert ... clrOff></clr-alert> 
```

Version B:

```html
// Set role="alert"
<clr-alert ... clrUrgent></clr-alert>

// Don't apply role="alert"
<clr-alert ... ></clr-alert>
```

**Comment by coryrylan** [comment]
I like Version A and this aligns to the same pattern for progress bar
