### ISSUE TITLE
Tabs overflow feature does not fit into ARIA pattern

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3514]
## Describe the bug

Aria doesn't support a concept of an overflow button as part of the tabs and therefore it does not behave as expected.

## How to reproduce

- Go to https://v1.clarity.design/tabs
- Try to navigate to and activate any of the overflow tab options using the arrow keys as expected

## Expected behavior

Tabs overflow implementation should either not break Aria tabs patterns, or develop a custom pattern.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

**We need to define the proper solution before this is tackled, right now we have several ideas but need to settle on the best.**

The main problem is the button is inside of the tablist, so perhaps we could put that button outside of the tablist? This may not work though.

If we are going to keep this feature, we will need to decide how we want this to work with the keyboard only and document it so sighted keyboard-only users can discover how to use this control. 

We will have to use role="application" along with aria-roledescription to describe the purpose of this custom control and aria-describedby to provide visually hidden instructions for blind screen reader users to hear. See https://www.w3.org/TR/wai-aria-1.1/#application. 

Another option may be to ditch tabs and use a grid layout for overflow items to be navigable. This is a bit hacky but could lend itself to expected key patterns.

There may be other options, but for now need to log this ticket to scope the work.

**Comment by gnomeontherun** [comment]
Can talk with H5 about this before we implement a solution to see if it works with their patterns.

**Comment by Jinnie** [comment]
I'll use this as a master for all overflow related issues, which I will subsequently link to this one.

We had a detailed discussion with @chlane and figured out the following overall approach:
1. Overflow button and menu are visual aid to sighted users. Blind users should not really care about it. They do not need it, as they do not have the "screen size limitation" that makes this feature necessary.
2. Keyboard only users only use focus and no screen readers.

Based on 1. and 2. if there is discrepancy between the experience of blind and sighted users, it is of no real importance.

The suggested solution is to implement arrow-key navigation on tabs instead of the current Tab-key navigation (this is by W3C recommendation). Then, when the overflow button is focused we will automatically open the overflow menu and focus the 1st element.
- For blind users this will be no different than selecting next tab without overflow. They will be able to use `->` key for next element, although it will be moving the focus down.
- For sighted k/b users, we'll be _smartly_ predicting what they want to do next and just focus the 1st button of the overflow. They will be able to use `v` arrow key to select next (yes, we'll have to support both keys).
Some details and corner-cases need to be checked, I will be working to present a prototype soon.

The overall benefits of this approach are:
- In ARIA terms we're not introducing foreign object between tabs - it gets hidden from the user.
- So, the component will be accessible and have only a tabs semantics, not tabs+button+menu.
- Arrow key navigation is per standard, so we have to do it anyway.
- It will resolve the nested tabs problem. Going to inner tablist with Tab, navigating in the current tablist with arrows.

**Comment by clane** [comment]
Here is the URL to Ivan's current version, find the Angular component tabs and toggle the overflow http://tabs-overflow-focus.surge.sh/
