### ISSUE TITLE
Clarity Icons with text misaligned in IE11

### ISSUE THREAD

**Issue by rootix** [vmware/clarity#3519]
## Describe the bug

IE 11 shows Icons with text within the text instead of next to it.

## How to reproduce

Go to the Header documentation on the Website with IE 11: https://clarity.design/documentation/header

The header type with the username and the icon shows the issue

![image](https://user-images.githubusercontent.com/874015/60167336-313e4880-9803-11e9-849c-81cd31f60baf.png)

## Expected behavior

The icon is correctly assigned on the left side of the text

## Versions

**App**

* Angular: 8
* Node: 10.16
* Clarity: 2.0.1

**Device:**

IE 11

**Comment by florin-borceanu** [comment]
I investigated this issue and I found that the `top` and `left` properties on icon are set to `initial`, which is not supported by Internet Explorer. 
I switched from initial to auto, and it seems to work just fine. I tried to use the `fixForIE11AndUp` mixin, but it doesn't work. 
With `top` and `left` set to `auto`, the bug is fixed and the behavior remains the same on the other browser i tested on (Chrome, Mozilla, Edge).

Can I start working on it?
If so, can you assign the issue to me?
Thanks!
