### ISSUE TITLE
[Bug] Datagrid server-driven "state.page" property passed in refresh callback is incorrect in v2

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#3536]
## Describe the bug

Datagrid server-driven "state.page" property passed in refresh callback has been incorrectly set to {from: -1, to: -1, size: 20} initially. In v1, it is {from: 0, to: 19, size: 20}, which is expected.

## How to reproduce

Can be reproduced in: https://clarity-light-theme-v2-jkt8kn.stackblitz.io, please see output in console - the value of "state.page" is {from: -1, to: -1, size: 20}

In v1, the value has no problem: https://clarity-light-theme-v1-0-zdrhyd.stackblitz.io, that is {from: 0, to: 19, size: 20}

## Versions

**App**

* Angular: 8
* Node: 10
* Clarity: 2

**Device:**

* Type: MacBook
* OS: OSX 10.13.6
* Browser chrome
* Version 75

**Comment by gnomeontherun** [comment]
This is related to the feature #2947, which solves a problem. This was intentional at the time, to describe that so far nothing has been loaded.

**Comment by omirobarcelo** [comment]
I've encountered the same issue.

Specifically when a filter is applied that returns 0 values, and the total items in pagination is set through `[clrDgTotalItems]`, the next refresh state will come with `{from: -1, to: -1, size: 10}`. 

Is this planned to be solved, or it's going to stay like this to solve the problem fixed by feature #2947 ?

**Comment by gnomeontherun** [comment]
This behavior was accepted to indicate that there were no items. However, I'm open to reverting that change and going back to original behavior. Marking for consideration.

**Comment by gnomeontherun** [comment]
This issue has merit but we are not currently planning to address it due to it likely requiring a breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this and note that it should be easier to manage by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
