### ISSUE TITLE
Datagrid with compact class doesnt style pagination toolbar properly

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#3588]
## Describe the bug

When using the datagrid-compact class on the datagrid component, the styling for the page-size select box is a bit off

## How to reproduce

reproducable on docs site itself. add datagrid compact class to the pagination section of datagrid documentation and check the styling of the pagination toolbar

## Expected behavior

Styles should be clean

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [1.x +]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._
![Screenshot 2019-07-05 at 1 42 58 PM](https://user-images.githubusercontent.com/3402331/60708149-03f04980-9f2b-11e9-9438-5e5d683ded03.png)

**Comment by Jinnie** [comment]
Hi @envyN
This is a known problem, but based on this comment, we don't find great value in prioritizing it:

https://github.com/vmware/clarity/issues/3097#issuecomment-467546121

Thanks for the report!

**Comment by m-tomczyk** [comment]
Compact layout deprecation is really bad news for us. We are displaying lots of very dense data, and this is very crucial feature in our use case. @Jinnie @gnomeontherun is there timeline on that deprecation, maybe workaround? And what's the rationale behind this decision if you are willing to share?

**Comment by mathisscott** [comment]
@m-tomczyk 
We currently don't have an issue to deprecate compact datagrids/tables. It is our plan to do so, however, because ultimately the size of compact datagrids/tables are too small and negatively impact usability on non-desktop form factors as well as accessibility.

Assuming we added the ticket for the deprecation soon-ish, the earliest we could announce the deprecation is 3.0. And the earliest the compact code would be removed is 4.0. 

We won't be jumping compact datagrid/table support to the top of our list anytime soon because the team is locked down on accessibility enhancements. But if this issue affects your team, we would welcome a contribution. It should be a reasonably simple CSS-based fix.

**Comment by GaryHyland** [comment]
Yep compact mode is also a key part of my layouts and will end up having to override some CSS I guess, which I obviously try and avoid. I do need the dense display of this data for desktops / business use apps.

**Comment by mathisscott** [comment]
@GaryHyland 
Well, on the positive side, compact view will be around until 4.0. So that's still a long ways away.

**Comment by gnomeontherun** [comment]
We haven't deprecated compact layout, though we have discussed it due to usability and accessibility concerns. We understand there is use of it in some applications, but before we make a change we need to review and define our research.

I'm going to reopen, as this is a little bug and easy fix.

**Comment by Jinnie** [comment]
So, we're back to https://github.com/vmware/clarity/issues/3097#issuecomment-467311911
Which of the 3 suggested versions should be implemented? The 1.5rem, The 1.1rem or the 1.25rem one?
