### ISSUE TITLE
Login image visual design

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#3640]
Requirements from product:
1. New - login design needs to be updated - Requirement = different.
2. Modern - Priority is that the customer feels it is contemporary. Requirement = contemporary.
3. Supports textual content - current examples show 5 lines of copy: heading, sub heading and 3 bullets / min heading and 1 line. Requirement = supports small copy block
4. Supports CTA (button) accompanying textual content.
5. Needs to support both light and dark themes - probably means 2x illustrations. Requirement = Light and dark support.
6. Nice to have - Delight. User will visit this often and lack of variation form visit to list would be nice to address - suggest tabling this but including concepts for v_002.

Initial agreement is that 1st pass will explore as many options necessary to determine which among those available for ‘contemporary’ are best received.

**Comment by gnomeontherun** [comment]
This request has merit but we are not currently planning to address it due to it likely requiring a design change and possible visual breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this.
