### ISSUE TITLE
Dropdownmenu item autofocus breaks filtering logic

### ISSUE THREAD

**Issue by danail-vasilev** [vmware/clarity#3729]
Hello,
I have a some sort of cross column filter implementation (https://github.com/vmware/clarity/issues/1632) that stopped working properly after upgrading from Clarity 2.0.2 to Clarity 2.1.1 because of the introduced dropdown menu item autofocus.

The filtering component has an input that triggers dropdownmenu open. When you write in the input, items in the dropdownmenu are filtered down. Having such an autofocus, however, contradicts with that behavior

Steps to reproduce:

Stackblitz link - https://stackblitz.com/edit/clarity-dropdown-search-fw7vth?file=src%2Fapp%2Fapp.component.html

1) Open stackblitz link above and click on the input
2) Write "a"
Expected: No focus, so that the filtering can be done
Actual (Clarity 2.0.2) === Expected
Actual (Clarity 2.1.1): Dropdown items is focused. The input is blurred and no filtering is interrupted

It's would be good to have a property that enabled/disabled that autofocus.

**Comment by gnomeontherun** [comment]
Hi @danail-vasilev, thanks for the report. 

What you've got here is an approximation of a combobox, which is a work in progress in Clarity and should be the component to use when its ready. Mixing a dropdown and input is not a use case we support, so unfortunately this is a tricky scenario. Until Combobox is available, I would suggest using the non-Angular version of dropdown since it doesn't manage focus automatically. However, this is still not a use case we want to support or recommend especially when Combobox is available, so your milage may vary.

Dropdown focus management was an enhancement created as part of our accessibility initiatives (https://medium.com/claritydesignsystem/a-commitment-to-accessibility-56dcb88af5c2 see the section on focus management), and this is non-negotiable from our side because disabling this would create a confusing experience for keyboard and screen reader users (essentially they'd have no idea where they were on the page). This is working as expected, and while we understand its a new behavior it is imperative to have for accessibility compliance.
