### ISSUE TITLE
Datagrid custom filtering doesn't work properly with column toggle

### ISSUE THREAD

**Issue by jkjha** [vmware/clarity#3759]
## Describe the bug

With Column toggle, adding custom filtering doesn't work properly. 

## How to reproduce

https://stackblitz.com/edit/clarity-issue-3120-jskbuz?file=src/app/checkbox-list-filter.component.ts

1.  Go to  above stackblitz.
2.  Try appling filter to "Group" Column. It oprns the filter window but at the same time it sorts column too.

## Expected behavior

Clicking the filter icon should just open the filter icon.

## Versions

**App**

* Angular: 7.2
* Clarity: 1.1

## Additional notes

If we remove toggle (ng-container from group column) it works well.

**Comment by hippee-lee** [comment]
This happens in the provided stackblitz because the filter is being projected into the wrong place for the column template because its inside of the `*clrDgHideableColumn` container. 

We have to use the structural directive with the ng-container to get a reverence to the content (in this case 'Group') in order to know what should be used in the toggle for hide/show. 

Here is how the column should look: 
```
        <clr-dg-column [clrDgField]="'group'">
          <ng-container *clrDgHideableColumn="{hidden: false}">
            Group
          </ng-container>
          <clr-dg-filter [clrDgFilter]="groupFilter">
            <checkbox-list-filter #groupFilter [filterParamName]="'group'" [items]="groupFilterOptions">
            </checkbox-list-filter>
          </clr-dg-filter>
        </clr-dg-column>
```

And here is a working fork of the stackblitz: https://stackblitz.com/edit/clarity-issue-3120-ozaybz
