### ISSUE TITLE
Timeline Dark Theme Enhancement

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#3763]
## Summary

The static timeline needs colors and theme-able scss variables in order to provide a dark theme option for this component. 

* What is the change?
Designing the component inline with current Clarity dark theme colors
* Why should it go in Clarity?
To allow Static timeline component usage in dark themed Clarity apps.
* Does this change impact existing behaviors? If so how?
n/a
* If this change introduces a new behavior, is this behavior accessible?
Yes, the dark theme colors need to be accessible. 

## Use case

Clarity consumer with applications that run in dark theme mode need this for their static timeline components. 

## Examples
n/a
## Workarounds
n/a

**Comment by mathisscott** [comment]
The timeline has themeable SASS variables.

It just needs the colors and then to have the SASS variables added to `_theme.dark.clarity.scss`

**Comment by mathisscott** [comment]
@colinreedmiller 
Does this need UX guidance or are you okay with us flipping the variables to what we've used in other components and circling back for you to visually review?

**Comment by colinreedmiller** [comment]
I am fine with flipping what exists to dark theme and reviewing from there. I spoke with Red about this spec and apparently there are some errant colors chosen by the designer rather than being Clarity values so those will need someone to look at them re: dark theme. I can do this all at once as a dark theme timeline review and specify what changes (if any) are needed.

**Comment by hippee-lee** [comment]
Closed with #3755
