### ISSUE TITLE
Form is invalid but error message is not popping up

### ISSUE THREAD

**Issue by NascentSoul** [vmware/clarity#3771]
## Describe the bug
_On submit I can see in console that form is invalid (I am using a custom validator for making sure first date input is less than second date input),  but error message is not showing up._

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v2-1vsbvg
2.  Set first input date to be bigger than second date
3.  Open console and see that form status is invalid
4.  See no error icons on inputs.

## Expected behavior

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v2-1vsbvg
2.  Set first input date to be bigger than second date
3.  See error icons on inputs.

## Versions

**App**

* Angular: 8.0.0
* Clarity:  2.0.0

**Device:**

* Type: PC
* OS: Windows 10 Pro
* Browser chrome
* Version 76.0.3809.132

## Additional notes

I try using markAsTouched(), maybe there is another way

**Comment by gnomeontherun** [comment]
Ok, this is because you've got a FormGroup, and the validator is not actually attached to the individual controls. Therefore, the controls themselves aren't marked as invalid, but the form is. In this case, you would look at showing an error message yourself instead since its a group and not just one control. That is the workaround, and recommendation for the time being.

We can consider group validators but that would require some design and development work to identify the right pattern and API.

I'm going to leave this open as a feature request.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. To help us clean up our backlog, we are going to close this with a functional workaround available.
