### ISSUE TITLE
A super-lightweight alert style

### ISSUE THREAD

**Issue by jrharshath** [vmware/clarity#3791]
**EDIT:** Design specs - https://www.figma.com/file/KTGn0CfxWwwCsFVXlHBKPKmN/Lightweight-alert?node-id=0%3A1

`[x] feature request`

In the designs I've been working on for the past few months, I've found myself using a particular visual style to report a message/status repeatedly, and I wonder if there is room for it in Clarity. 

Here's what it looks like:
![image](https://user-images.githubusercontent.com/85807/64387002-89f24480-cfef-11e9-9d12-cd83affb2421.png)

I've used this alert messages as well as status indicators. Examples:
![image](https://user-images.githubusercontent.com/85807/64387111-e3f30a00-cfef-11e9-94bd-aeab63940060.png)

![image](https://user-images.githubusercontent.com/85807/64387199-1f8dd400-cff0-11e9-9082-3dc3b11416ab.png)

![image](https://user-images.githubusercontent.com/85807/64387257-40eec000-cff0-11e9-8ea3-6d88f97b7fb4.png)

In one instance I've used a list of these messages as a summary of all the details that follow it. Example:

![image](https://user-images.githubusercontent.com/85807/64387392-af338280-cff0-11e9-8860-4a4a16655ac0.png)

# So...
In all these usages, I did not use a Clarity alert (regular or small style) because the background-filled rectangular container is rather overpowering and throws off the visual balance of the UI. 

**My question:** Does this kind of alert/icon usage look okay from a Clarity perspective?

**My request:** Could we create a third Clarity alert style perhaps called "super-lightweight" which has no background container meant for usages like these? At the very least, could we include sample usages like these in the style guide/documentation for alerts to let consumers of Clarity know that this is another suggested way of showing alert messages on the product?

**Comment by hippee-lee** [comment]
This came up in the Office Hours session w/ @colinreedmiller.

Two of the areas I thought it might fit were as an extended, third style of alerts or a special list item that takes wither a status or an icon and display's it as a specialized bullet. After discussion the list item with special icaon didn't seem to be appropriate. 

@jrharshath - can you add in some descriptions of the use cases you had?

**Comment by mathisscott** [comment]
An alternate style of alert would be the easiest path forward.

**Comment by gnomeontherun** [comment]
We need

- A design spec, clear limitations and use cases
- What features does it have compared to other alerts? Probably not going to have features like dismissable, actions, etc
- Some research of other examples to validate 
- Edge cases (stacked alerts, in various contexts)
- Are these given the same or different aria treatments (probably not aria-live)

**Comment by jrharshath** [comment]
Thanks for the responses, folks. 

- I thought about my use cases again, and looks like pretty they are all used as status indicators. I think that should be the guideline on using this style. @gnomeontherun please let me know what is expected of me in the form of a "design spec".
- It will not be dismissable. But it can have actions associated with it (eg, "fix it", "retry" or "see details").
- By research, do you mean other projects that may have similar needs?
- Edge cases: none so far to speak of. I'm thinking of the "stacked" example I had provided as just several individual status indicators positioned below each other. Let me know if that's not the right way to go about it.
- Not sure about aria-live. I don't have a use case so far where the status is live-refreshed on clicking some other action.

**Comment by mathisscott** [comment]
Hi @jrharshath 
Re: the following...

> But it can have actions associated with it (eg, "fix it", "retry" or "see details").

How will we see the actions visually associated with the minimalist alerts? If we place them where they currently show up in alerts, they would be hanging out in space on the right margin. There's no border or background that would visually group them to the alert. This is something worth exploring with design.

> Not sure about aria-live. I don't have a use case so far where the status is live-refreshed on clicking some other action.

aria-live is for accessibility. When an alert shows up, it will need to announce its presence to screen-readers. [Reading up on aria live regions](https://webaim.org/techniques/aria/#dynamic) is  recommended because UX will need to have a recommendation on how visually impaired users will experience this. 

> Edge cases: none so far to speak of. I'm thinking of the "stacked" example I had provided as just several individual status indicators positioned below each other. Let me know if that's not the right way to go about it.

It's a good idea to mock this up to see what these items would look like stacked in this way. That way there are fewer surprises in implementation that would lead to a last minute design session. IMO, it's better to handle known edge cases up front because there will no doubt be unknown edge cases coming at us later.

**Comment by colinreedmiller** [comment]
@jrharshath I am in agreement with @smathis regarding a design that includes actions per item. In your example the group action makes sense - we'd need to see how the alert would update when the content changes i.e. does 'show details' necessitate the container growing or a different type style? If there are several does showing details as a group make sense? In the case of 'run checks again' what is the intermediate state while the check is re-running and the data reloads? What other actions would be available?

re: Research, we use 2 aspects - First is external: what similar components / use cases are out there that we may learn from? Second is internal - what products might benefit from this component and what about their use cases can inform us in designing the functionality?

re: Design spec - I have several in archive and a couple in flight that we can review to ensure everything necessary is included. Working rough is good in the meantime since we are first concerned with fully understanding the questions rather than providing answers.

**Comment by colinreedmiller** [comment]
Design spec:
https://www.figma.com/file/KTGn0CfxWwwCsFVXlHBKPKmN/Lightweight-alert?node-id=0%3A1
