### ISSUE TITLE
How to give Custom width for datagrid? and it should work in all media screens(responsive)

### ISSUE THREAD

**Issue by Chandru22714** [vmware/clarity#3827]
To make the datagrid responsive, I have tried to give custom width for each column. But it is not working. Please tell me the way to handle the datagrid responsive by giving custom width. I could not find any documentation to handle. So, please suggest me the way to fix this.

**Comment by hippee-lee** [comment]
The datagrid responds to its container size and will try to fill the space given to it. 
If there is no paging it will continue to grow vertically the more rows that it is given. If there is paging it will set the height for the datagrid so that when the user pages to the last page the height stays consistent if there are fewer rows on that page. 

Horizontally, the datagrid will do a couple of things. It will fill its width and auto size all of the columns with the data given if it can. If the column width ends up larger than the width of the datagrids container horizontal scrolling will be enabled. 

An app can put a datagrid inside a container and it should size itself to the container. E.g if you set a width on the container it will size the columns to fill the space if it can  (depending on the content projected here) or overflow and enable horizontal scrolling if there are many columns. 

Here is a simple demo of a datagrid in a fixed width container: https://stackblitz.com/edit/clarity-light-theme-v2-poin5j

Alternatively the app can add hide/show to the columns and control that from the app side depending on the responsiveness thats needed for that screen size.

**Comment by Chandru22714** [comment]
Lets say I want to decide width of each column. How i can achieve that?

**Comment by hippee-lee** [comment]
This question has been answered before: https://stackoverflow.com/a/48911927/164398
If you have more questions, please create a new question on stack overflow and tag it with `vmware-clarity`. I'll get notified and look at it there and it will benefit the community.
