### ISSUE TITLE
filterValueChange of ClrDatagridColumn does not emit changes of custom clr-dg-string-filter

### ISSUE THREAD

**Issue by ninodinatale** [vmware/clarity#3836]
## Describe the bug

Title says it all more or less. `ClrDatagridColumn.filterValueChange` does not emit if the filter is a custom string filter (`<clr-dg-string-filter [clrDgStringFilter]="customFilter"></clr-dg-string-filter></clr-dg-column>`)

I created a stackblitz which demonstrates this: https://stackblitz.com/edit/clarity-light-theme-v11-ydvswx

There are two columns, which both have been subscribers to `filterValueChange`. The first is a custom filter and the second an "ordinary" filter. Type something in the filter to see that only the ordinary one does emit changes. I saw an Issue and a merge where it says that this should be fixed, but it does not seem to be? Or am I doing or understanding something wrong?

**Comment by gnomeontherun** [comment]
This might be related to #3486. Needs triage.

**Comment by gnomeontherun** [comment]
To make this work, you subscribe on the filter using `(clrFilterValueChange)` event, accessing the columns doesn't work when you put an explicit filter into the column. 

```
<clr-dg-string-filter (clrFilterValueChange)="change($event)" [clrDgStringFilter]="customFilter"></clr-dg-string-filter>
```

I'm not sure if this is a bug or the expected behavior, but what happens is underneath if you provide a custom filter we remove the default filters and use your filter. That means the column no longer controls the filtering but the custom filter component does, which is why its not emitting. There might be a reason that it is done this way, but at the moment I'm not able to dive into it fully. I'm going to leave this open for future investigation, but this is your workaround. 

Also, this is using 0.11, which is out of support.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
