### ISSUE TITLE
Lines are not shown in datagrid after manual width change

### ISSUE THREAD

**Issue by ArturGudiev** [vmware/clarity#3884]
## Describe the bug

In datagrid a have a column which can contain cells with very long names. If I revise the column width until horizontal scroll appears then some parts of datagrid lines become invisible.

## How to reproduce

1.  Create a datagrid with styles for **clr-dg-cell** `overflow: hidden; text-overflow: ellipsis;`. 
2.  Add long strings in first column.
3.  Manually change width.

## Expected behavior

All parts of datagrid lines should be shown.

## Versions
v1.1.3
**App**

* Angular: 7.3.9
* Node: v10.13.0
* Clarity: v1.1.3

**Device:**

* Type: Dell 
* OS: Windows 10
* Browser Chrome
* Version Chrome 77 on Windows 10

## Additional notes

Here you can see the example 

![Row](https://user-images.githubusercontent.com/4563342/66321644-925cd880-e929-11e9-8151-98f074e7fb59.gif)

**Comment by gnomeontherun** [comment]
Can you help us out by having an isolated reproduction to test this with using Stackblitz?

**Comment by ArturGudiev** [comment]
@gnomeontherun 
Yes, sure. 

This is a link for project https://stackblitz.com/edit/angular-6bbo1x
But there is one problem. You need to manually add style for .**datagrid-table** class from dev tools. For some reason this style is not applied in StackBlitz from styles file (app.component.css). In my local project the style is applied well. 

See example 

![Screen](https://user-images.githubusercontent.com/4563342/66480958-7a5f9300-eaa8-11e9-9f56-406f544eae4a.gif)

**Comment by gnomeontherun** [comment]
This seems to be a problem with putting `.datagrid-table { width: 100% }` in the mix. Here is a better demo because you need to put the widths on the columns, not the whole table. By doing so, CSS calculates the 100% width initially but resizing expands it beyond that and the overflow scrolling kicks in. Also to target classes inside of a component (which is something to avoid) you have to use `::ng-deep` selector to pierce the emulated boundaries.

https://stackblitz.com/edit/angular-lnhrjp?file=src/app/app.component.html

Closing as an implementation question.
