### ISSUE TITLE
Tabs always highlights the first tab when using tabs as routerLinks

### ISSUE THREAD

**Issue by phrehnck** [vmware/clarity#3893]
I'm using tabs as child routes for a component with the following:

                  <clr-tabs>
                    <clr-tab *ngFor="let subComponent of subComponents">
                      <button clrTabLink [routerLink]="subComponent.path" routerLinkActive="active">{{subComponent.label}}</button>
                    </clr-tab>
                  </clr-tabs>

The routerLinkActive attribute works correctly when landing on the first tab's route and highlights the correct tab but loading a child route directly highlights the current tab/route but the first tab is always highlighted.  
![image](https://user-images.githubusercontent.com/2530608/66444697-129e3f00-e9f9-11e9-8629-837fa1866d41.png)

Am I using this incorrectly or is this a bug?

**Comment by gnomeontherun** [comment]
This is likely a problem with your implementation, because you are setting the `routerLinkActive` class based on the URLs. This can happen when you have a root path (like `/status`) and then child paths (like `/status/daily`). With nested routes, its technically true that both would be active when you are on a child.

To fix this usually you just add `[routerLinkActiveOptions]="{exact: true}"` to your routerLinks to force the active class to only be applied to the exact match and not parents.

I'm going to close this as resolved based on the above, but if not please provide a working demo with Stackblitz so we can see what is happening.

**Comment by phrehnck** [comment]
Editor:
https://stackblitz.com/edit/angular-5kueix

Non-default route showing that the first tab is always active on first load:
https://angular-5kueix.stackblitz.io/clients/settings

**Comment by phrehnck** [comment]
Here is a fork of the same thing but without Clarity:

Editor:
https://stackblitz.com/edit/angular-rvhbwz

Non-default route:
https://angular-rvhbwz.stackblitz.io/clients/settings

**Comment by Jinnie** [comment]
Please see https://github.com/vmware/clarity/issues/627
If you want to use the `clr-tabs` component, you'll have to manually update the current `ClrTabLink` component, based on the `router.url`. I have a demo of it, but it's pretty complicated, and seeing that you don't use the tab-content at all, you don't need all the underlying state and services. I'd suggest using the Static version of the tabs like this:
https://stackblitz.com/edit/clarit-tabs-with-router-static?file=src/app/clients/clients.component.html

**Comment by phrehnck** [comment]
Thank you @Jinnie .  Switching to static did the trick.
