### ISSUE TITLE
Theme switcher for the docs site

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#3915]
## Summary
* A control to change the documentation website (clarity.design) from light theme to dark theme
* all components and documentation would switch
* possibly a cookie to remember which theme the user selected so the next time the visit the site, they will be in their preferred theme
* possibly have the switch in the upper right corner in the header

**Comment by MonsieurMan** [comment]
Hello, I just implemented it for our application at work and would love to see it for the doc site that I visit everyday.

> Don't mind the french ^^
![image](https://user-images.githubusercontent.com/13108166/82300977-e2b81080-99b7-11ea-9b48-1804be8e6f4c.png)

Are you open for contribution ?

Also, what would the implementation be like ? For ours, I simply switched the stylesheet, between clr-ui.min.css and clr-ui-dark.min.css, according to a local storage token.

**Comment by hippee-lee** [comment]
Hi @MonsieurMan - Thanks for the kind offer :) 

There is a lot of custom style that makes simply swapping the theme for the website difficult. In addition we are currently re-working the website and one of the new features will be a Storybook playground that lets the user change the theme for the component rather than the whole site. 

The stylesheet switch + localStorage token is one I have seen before. With the changes that are coming in core, theming will get a lot more atomic and easier so keep an eye out for v4.
