### ISSUE TITLE
Date Picker being redered with validation icon

### ISSUE THREAD

**Issue by vanilsonbr** [vmware/clarity#3937]
## Describe the bug

a validation icon (clr-validation-icon) is showing up when I create a a `input[type="date"]`, wrapped by clr-date-container or not. I tried many different combinations of inputs, using [(clrDate)], using [(ngModel)], but the icon shows up every time. I'm not using forms, just two way databinding.

## How to reproduce

Create a `<input type="date" clrDate />` inside your HTML file to be able to see the icon.

1.  import ClarityModule from '@clr/angular' on your app module.
2.  Insert `<input type="date" clrDate />` to your HTML template
3.  render the app

## Expected behavior

date input rendered correctly without the extra validation icon.

## Versions

**App**

* Angular: 8.2.11
* Node: 12.4.0
* Clarity: 2.3.0

**Device:**

* Type: Desktop Windows Machine
* OS: Windows Enterprise x64
* Browser: chrome
* Version: 77.0.3865.120 x64

## Additional notes

Here's a stackblitz to help you.
https://stackblitz.com/edit/angular-acdzwe
I wasn't able to make the icons render, but if you inspect the date input, you're going to see the validation icon there.

**Comment by gnomeontherun** [comment]
Hi there, the validation icon is there, but it should be hidden. It seems like your Stackblitz shows this working as expected, (icon is there, but doesn't appear as expected).

As far as I understand, this is working as expected because that is how we render a form input to be ready for form validation. A hidden icon isn't a problem is it? Closing this as working as expected.
