### ISSUE TITLE
DataGrid Row Nested Group

### ISSUE THREAD

**Issue by daniaremon** [vmware/clarity#3938]
## Summary

Datagrid row grouping, with nested grouping, and with the capability of show total in number columns; without supressing the column sorting and filtering.
In this grouping mode, the paging disappear, because it doesn't apply and would be to much difficult to undestand. And in this mode, the loading of group records must have the options of lazy loading.

## Use case
This is a similiar example to my needs.

I have buses registered in my database, each bus travel once in a day, each travel has a target city, and a bus station where it arrives. I will have around 30 buses. If i filter an specific month, i wil have a datagrid with 900 travel records.

I want to see quickly, how many travels have an station, and which travels belong to a bus, and arranged by date, and with total of travels by each bus inside that station group, and each station.

With a few clicks, i wanto to change that grouping quickly to buses as the first group, then group by statition, and then see sorted records of travel by date.

With the current datagrid that isn't possible.

## Examples

Odoo community filter and grouping

https://apps.odoo.com/apps/modules/11.0/sewi_web_search_group_by_date_intervals/example_order_grouped_list.png

## Workarounds

Maybe, the first step is to sort columns in a nested way. Example, sort by stations, then sort by buses, then by date. But with this aproach, it will still be difficult to the user have a general view of buses, stations, etc.

**Comment by gnomeontherun** [comment]
This appears to be a request for nesting into a hierarchical datagrid. We actively recommend against this pattern and do not plan to support it. The primary reason is that it confuses the behavior of many aspects of a datagrid. See https://github.com/vmware/clarity/wiki/Hierarchical-datagrid for some detail.

Ultimately I recommend you consider a different approach to visualizing your content to avoid hierarchy. It seems more appropriate to use filters to condense the list of content to specific groupings instead of nesting inside of rows.
