### ISSUE TITLE
Header documentation mismatch

### ISSUE THREAD

**Issue by MichaelRegert** [vmware/clarity#396]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Seed project should match component documentation.

### Actual behavior

Documentation states to use the standard <header> tag with a class of "header header-x" but the seed project uses an undocumented clarity-specific tag of <clr-header>.  Should we use <header> or <clr-header>?

### Reproduction of behavior

Latest Master branch as of 1/23/2017

### Environment details
N/A as this is a documentation issue.

* **Angular version:** 2.0.X
N/A as this is a documentation issue.

* **Clarity version:** 
Latest Master branch as of 1/23/2017

* **OS and version:** 
Windows 7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
Hi @MichaelRegert. Are you talking about the `clr-header` tag? If yes, its documented under Navigation (https://vmware.github.io/clarity/documentation/navigation) in the Responsive Navigation section. We are using the Angular component for the main-container and header to demonstrate responsive navigation in the seed app.

![image](https://cloud.githubusercontent.com/assets/1426805/22211097/d729c6d8-e140-11e6-9964-a0501d775b31.png)

But I will pass this feedback back to our team so that we can improve this part of our documentation.
