### ISSUE TITLE
Tooltip is cut off on mobile when content is too long.

### ISSUE THREAD

**Issue by gurumaxi** [vmware/clarity#3960]
## Describe the bug
When its content is too long, a tooltip is cut off when clicking on a info icon on a smartphone screen.

## How to reproduce
1. Got to https://clarity.design/
2. Shrink the window to mobile width
3. Go to tooltips page
4. In the section "Large", click on the info icon

## Expected behavior
The content of the tooltip should be fully visible.

## Versions
mobile device or small desktop window
all browsers

## Screenshot
![tooltip](https://user-images.githubusercontent.com/44405244/67935984-37866c00-fbcb-11e9-87b0-4c043c328deb.png)

**Comment by gnomeontherun** [comment]
This is a worthwhile enhancement request, but is challenging to implement due to the existing behaviors and nature of Clarity Angular. As we build out Clarity Core, this should be possible to realize with the applications managing the state and functionality more directly instead of Clarity Angular. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
