### ISSUE TITLE
[UX] New forms error messages

### ISSUE THREAD

**Issue by ttsvetko** [vmware/clarity#3978]
Hi, we are using Clarity as main component library in our product. We recently managed to upgrade from Clarity 0.13 to Clarity 2.2.1 - if you are interested in our upgrade experience, please let me know.

One of the main changes in v2 is in the position of the error messages - previously, it was as an icon and tooltip when user hovers over the tooltip, now it is as a text below the input.
Clarity also removed the "*" - something that we managed to add easily by css on our end as we are not able to rework all forms based on the clarity suggestion ( although it would be nice if Clarity provide a way to have "*" for required fields at least in v2 and then remove it in v3 and give time for the products to adapt).

The main problem that we are facing is the forms' error messages:
- As the error message is not visible by default, the whole layout jumps up and down when the error message is showing/hiding.
- Clarity does not have a simple example like this one - all of the examples have a "helper" text that occupies a space and the layout does not jumps up and down when error message appears.
- Even if we manage to occupy in a hacky way space under our forms, we cannot be sure that the space is enough for all languages that our product supports. Also, such hacks will make our upgrade from v2 to v3 hard.
- In case we have a helper text which splits in 2+ rows, when we have to show an error message which is in 1 row only, our layout will jumps up and down as well.

Pleas see a video recording here: https://drive.google.com/file/d/1ASovjkao5Bdj4DCcrtsl9ky9fBbIhO2x/view?usp=sharing

Is there a Clarity guidance how to handle all these cases? The current behavior is a pretty unpleasant and we would like to find a easy way to provide better UX to our clients.

**Comment by gnomeontherun** [comment]
To summarize, this seems like an ask to put in a placeholder so that error messages won't 'jump' content vertically. There are a few issues with this, and our goal was to ensure there wouldn't be horizontal jumping while validating, but no guarantees for vertical.

* The old tooltip method was poor usability and hide critical information about errors, hence the change to putting content on the screen.
* We don't know how long the error message is and it could easily overflow to more than one row, which means there would still be vertical jump in some cases, which you pointed out. There is no way around this, and why our default is to allow some vertical jump.
* Helper text is our default pattern, especially in place of using signposts or hidden content, so the general expectation is you'll have a helper text and error text, usually not just an error text. If that is the case, it would be good to know why a lot of fields don't need helper text.
* No hacks are recommended here, but just putting a blank helper text would be better than adding some kind of CSS or other method.

It helps us to provide an isolated demo of your core issues so we can all easily use it and work with it, rather than a video or screenshot. Please provide something with https://stackblitz.com/@clr-team.

**Comment by gnomeontherun** [comment]
Hi @ttsvetko, this has been open for a while without any activity. Based on our policy, we're closing it due to the inactivity and needing a reproduction of the specific issue. We can reopen the issue if you provide more details.
