### ISSUE TITLE
Datagrid filter disappears after entering value

### ISSUE THREAD

**Issue by Wallabeng** [vmware/clarity#3991]
## Describe the bug

When filtering a datagrid removes so much content that your "scroll-y" changes due to lesser content, the filter disappears because the scroll listener for closing popups gets triggered.

## How to reproduce

https://stackblitz.com/edit/clarity-datagrid-overflow-test
Steps described inside stackblitz

## Expected behavior

Filter stays visible.
I would be happy to contribute, but lack any intelligent idea how to fix this.
Maybe somehow disable scroll listener while filtering?

## Versions

**App**

* Angular: 8.x
* Node: 10.15.3
* Clarity: 2.2.0 - 2.3.1

**Device:**

* Type: MacBook Pro
* OS: MacOS
* Browser: Tested on Chrome and Firefox
* Version: latest

**Comment by gnomeontherun** [comment]
This does indeed sound like a scroll event is being fired (by page reflow), so I think the simple workaround would be to set a fixed height so that the datagrid doesn't shrink.

**Comment by bdryanovski** [comment]
The reason for that is the smart-popovers and in particle these lines:

```ts
      <div class="datagrid-filter"
           [id]="popoverId"
           clrFocusTrap
           *clrPopoverContent="open at smartPosition; outsideClickToClose: true; scrollToClose: true">
```

Without the `scrollToClose` the filter will stay open and at the same time will be floating around.

The best thing to do is to give minimum height on the container and this will prevent the scrolling event of happening - or like @gnomeontherun suggested use the fix-height datagrid, you could check the [documentation](https://v2.clarity.design/datagrid/fixed-height) on how to do it - this is not the perfect-all-cases solution but it's a workaround on the issue for the moment.  I don't think that there is an easy to do fix right now, we may have to track and reposition the popover when scrolling and moving it at the same time.

```ts
<clr-datagrid style="min-height: 120px;">
        <clr-dg-column [clrDgField]="'key'">key</clr-dg-column>

        <clr-dg-row [clrDgItem]="element" *clrDgItems="let element of elements">
          <clr-dg-action-overflow>
            <button>test1</button>
            <button>test2</button>
          </clr-dg-action-overflow>
          <clr-dg-cell>{{element.key}}</clr-dg-cell>
        </clr-dg-row>
</clr-datagrid>
```

**Comment by ietabhi** [comment]
Hi,
Can we fix this issue without fixing data grid height? as for different resolution and dynamic header content we cannot fix grid height.

This is major issue with clarity grid.

**Comment by gnomeontherun** [comment]
The workaround here is to either fix the height, or make sure there is some content below the Datagrid when there is very little height in the datagrid. Similar to other smart popover issues, we've gone ahead to close these like #1757.

This is challenging to implement due to the existing behaviors and nature of Clarity Angular. As we build out Clarity Core, this should be possible to realize with the applications managing the state and functionality more directly instead of Clarity Angular. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
