### ISSUE TITLE
Modal inside Wizard doesn't honour Z Pattern of button Placement.

### ISSUE THREAD

**Issue by Vaishak** [vmware/clarity#4011]
## Describe the bug

Modal inside Wizard doesn't honour Z Pattern of button Placement!

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-lhkcnv

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v2-lhkcnv
2.  Click on 'Open Wizard'
3.  Click on 'Show Modal'
4.  Modal doesn't honour Z Pattern of Button Placement, follows F Pattern instead.

## Expected behavior

Wizards and Modals should honour Z Pattern of Button Placement.

![Screenshot 2019-11-13 at 8 03 08 PM](https://user-images.githubusercontent.com/18070461/68772959-b316fd00-0650-11ea-82cc-f004b4f0b9d0.png)

The Z-pattern is a natural way for the user to go through content within a constrained container and when tasks are oriented from the top-left and ending with a primary call to action on the right bottom side of the container. This pattern is reversed for the right to left languages.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Hi there, using a modal inside of a wizard is not a supported pattern (modals on top of modals creates confusion about where a user is inside of the application). I highly encourage you to reconsider the usage of this pattern and keep it from nesting.

However, to fix this you shouldn't put the modal declaration inside of the `clr-wizard` element, since it depends on the modal some of the styles override and cause this unexpected (an unsupported) behavior. Declare your modal at the root of the component template and it displays correctly.

Closing as support resolved with an answer.
