### ISSUE TITLE
Datagrid empty row when there is only one row

### ISSUE THREAD

**Issue by rreymer** [vmware/clarity#402]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No empty row should appear in the datagrid when there is just one row.

### Actual behavior
When a datagrid has only one row, there is an empty row at the bottom.

### Reproduction of behavior
https://plnkr.co/edit/CKX7PeqWGZazcwI7tl97?p=preview

### Environment details

* **Angular version:** 2.3.1

* **Clarity version:**  0.8.2

* **OS and version:** Windows 10

* **Browser:** all

**Comment by youdz** [comment]
This is expected behavior, all datagrids are always at least 2 rows high to accommodate for a potential spinner.

Do you have a specific reason why you would want a datagrid to be that small? Note that what you call an "empty row" is not a row, it's just a simple background, the same one that appears on the last page of a paginated datagrid.

**Comment by jaffoneh** [comment]
Closing based on @youdz's last comment. Feel free to reopen or write a comment if you want to provide more information or reopen the issue to discuss further.
