### ISSUE TITLE
[accordion] missing animation on collapse

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#4023]
## Describe the bug

The Accordion component does not have animation on collapse (while the Stepper component has)

## How to reproduce

1.  Go to [this page](https://stackblitz.com/edit/clarity-accordion-missing-animation)
2.  Expand "Item 1'; a nice animation reveal the Item content
3.  Collapsed "Item 1'
4.  there're no animation to collapse

## Expected behavior

Also collapsing should have an animation (like the Stepper)

## Additional notes

Not sure this is a BUG or should be a Feature request; I've chosen BUG because IMHO this component should be consistent with the stepper

**Comment by gnomeontherun** [comment]
This is a worthwhile enhancement request, but is challenging to implement due to the existing behaviors and nature of Clarity Angular. Clarity Core has an accordion that resolves this issue, so the recommendation is to adopt the Clarity Core version for this capability.

In an effort to clean up our backlog and focus our attention, I’m going to close this as resolved by Clarity Core. Please follow our development and releases to keep up with improvements!

**Comment by mathisscott** [comment]
This is fixed in Core with #5657
