### ISSUE TITLE
Dependencies for ClrStepperModule

### ISSUE THREAD

**Issue by ElesGergo** [vmware/clarity#4024]
I am trying to import only the modles which I am using in my application.
I realised if I import only the ClrStepperModule it is broken, however if I import the ClarityModule it is working.
Can you share what other dependencies the stepper module has ?

**Comment by gnomeontherun** [comment]
Angular tree shakes modules that you don't use, so there is no performance boost to including only the feature modules you use. We recommend you use `ClarityModule` since it will be reduced to just the modules that you use in your application anyways, instead of trying to optimize it manually.

Closing as support question with a solution.
