### ISSUE TITLE
Toggle inside dropdown switches visually on open

### ISSUE THREAD

**Issue by Wallabeng** [vmware/clarity#4033]
## Describe the bug

When putting a toggle inside a dropdown and set its default value to true, the switch from false to true is visually recognizable. Which isn't the case for 'normal' toggles.

## How to reproduce

https://stackblitz.com/edit/clarity-toggle-dropdown-issue

- 'toggle outside' starts visually with the correct value
- 'toggle inside' starts visually with false and gets set to true after opening the dropdown

Inside Stackblitz open the dropdown and see the status switch to programmatically defined default value.
I'm not sure if it's a dropdown rendering behaviour or maybe an angular issue/behaviour, as the value gets interpreted too late.

## Expected behavior

The toggle inside starts in 'toggled' state

## Versions

**App**

* Angular: 8.2.13
* Clarity: 2.3.1

**Device:**

* Type: MacBook
* OS: MacOS
* Browser: Firefox
* Version: 68.2.0esr (64-Bit)

**Comment by hippee-lee** [comment]
This is happening because of the `*clrIfOpen` directive on the `clr-dropdown-menu` element. This directive behaves in a similar way to `*ngIf` so the content is projected into the template and then created in the view which then applies the value to the toggle. This causes the behavior as reported because toggle initialize state as false. 

If this is a real world use case I think the best way to handle it is to remove the *clrIfOpen directive from the drop down menu that has elements that are linked by the data model. 

Here is the behavior without `*clrIfOpen`: https://stackblitz.com/edit/clarity-toggle-dropdown-issue-jsrarc

I'm closing this as a question but please let me know if I misunderstood the use case for having two toggles managed by one model.

**Comment by Wallabeng** [comment]
Thanks, this solves my problem!
The second toggle outside was just for demonstration purposes.
