### ISSUE TITLE
Datagrid Selection/Deselection will be delayed when we have component render in datagrid column

### ISSUE THREAD

**Issue by nagarajns** [vmware/clarity#4059]
## Describe the bug

When we have large data with clarity datagrid selection along with component rendered in datagrid column then there will be delay for each select and deselect option from datagrid selection

[Violation] 'change' handler took 448ms

Here i have just used simple button in component it takes around 300 to 700ms. But in my real application it takes around 500ms to 1.2 sec.

## How to reproduce
here is the link https://stackblitz.com/edit/angular-p3tvzt

1.  Go to 'https://stackblitz.com/edit/angular-p3tvzt'
2.  Goto the inspect console
3.  Click on select checkbox
4.  See the delay

## Expected behavior

For small set of data even if we have component in column then delay will not be visible. Expecting same for larger set of data with component in column

## Versions

**App**

* Angular: [7]
* Node: [8.10.0]
* "@clr/angular": "1.1.0"
*  "@clr/icons": "1.1.2"
*  "@clr/ui": "1.1.0",

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Comment by gnomeontherun** [comment]
Pagination is the solution for this, because there is only so much we can do to optimize a complex datagrid with such a large dataset. It is a usability challenge for a user to have 1000 items visible on the page at once, which pagination also helps with. This is especially true when you have subcomponents in each row that have bindings, as they add to the overall complexity greatly.

Also, you should use `trackBy` to simplify change detection. 

```
// In your controller
trackBy(user, index) {
  return user.id;
}

// In your template
<clr-dg-row [clrDgItem]="user" *clrDgItems="let user of users; trackBy: trackBy">
```

**Comment by gnomeontherun** [comment]
I'm going to close this as having a solution to use pagination, also to optimize and reduce your child components (the more components you are rendering, the longer change detection and rendering will take).
