### ISSUE TITLE
Feature request: Color picker

### ISSUE THREAD

**Issue by water42** [vmware/clarity#408]
**Select one ...**  (check one with "x")
```
[ ] bug
[ x] feature request
[ ] enhancement
```

### Expected behavior
There are lots of color pickers out there, but it would be great to have a properly maintained ng2 color picker themed consistently with Clarity. Expected behavior would be something similar to any one of these libraries:

1) https://itsjavi.com/bootstrap-colorpicker/
2) https://github.com/Alberplz/angular2-color-picker

**Comment by jaffoneh** [comment]
@sdemurjian anything specific you'd like improved over those libraries or just having a Clarity-based component for color-picker? (that's valid, just making sure if there are improvements we can make, we're able to make them and we know about them)

**Comment by sdemurjian** [comment]
@jaffoneh nope, nothing specific, just having a clarity component would be good enough. thanks for the library!

**Comment by jaffoneh** [comment]
Adding a color picker does not seem like a fit for Clarity. Color picker does not seem like a component within a design system or a core component used by the majority of applications built on top of Clarity. Although we would be interested in considering an open source project on top of Clarity built as a side project by the Clarity team or external contributors, building it as a requirement within Clarity itself seems to be a lot more in depth than a component within a design system. Thanks for filing the issue though!

**Comment by patriceo** [comment]
Hi ! this is too bad you are not considering it as a core component, I'm sure majority of applications actually use that kind of component :(

**Comment by hippee-lee** [comment]
Hey @patriceo -
This is a really old issue so commenting here makes it hard to have a discussion around your needs (use cases and contribution motivation).
 
Please feel empowered to look at our [contribution guidelines](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md) and open an issue for your use case. If it is really integral to what the app does it may be worth exploring the use cases and design for the component. We are a small team and aren't able to prioritize everything that the community feels is useful but we also don't want to preclude things like this even if they have been discussed before. 

Things change and understanding your use cases and motivation for contributing helps us refine the long term vision for Clarity components. So having an updated issue for your needs helps facilitate the conversation. I'm going to lock this issue since it is so old but please do review the contribution guidelines and consider starting a design conversation around your use cases and design specs.
