### ISSUE TITLE
Datagrid - ChangeDetection Error when initial refresh hook fires

### ISSUE THREAD

**Issue by colinskow** [vmware/clarity#4102]
## Describe the bug

When the initial `(clrDgRefresh)` hook fires, a change detection error is thrown if the hook changes any component properties.

`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'loading: false'. Current value: 'loading: true'.`

## How to reproduce

StackBlitz demo: https://stackblitz.com/edit/clarity-light-theme-v2-lavnxn

1.  Open StackBlitz project
2.  See code in `app.component.ts`
3.  Look at error in the console

## Expected behavior

The refresh hook should not cause errors with Angular change detection.

## Versions

**App**

* Angular: 8
* Node: 10
* Clarity: 2.3.3

**Device:**

* Chrome (latest) on Ubuntu

**Comment by colinskow** [comment]
Here is the [line of code](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid.ts#L243) that is causing the problem.

[Initial research](https://blog.angular-university.io/angular-debugging/) seems to indicate that data shouldn't be changed after the view has been initialized.

I believe a solution would be moving `this.refresh.emit(this.stateProvider.state);` into the `ngAfterContentInit` hook instead of `ngAfterViewInit`.

**Comment by hippee-lee** [comment]
The clrDgRefresh event is emitted in the AfterViewInit lifecycle hook. There are two places that the initial (true because when the datagrid is initialized it is fetching its data when its server driven) value for loading can be set. I usually set the `loading` value to true when the component declares it and then let the refresh callback manage its state from there. 

Closing as this is a question with a workaround.
