### ISSUE TITLE
Alt attribute is missing for svg's present inside info buttons

### ISSUE THREAD

**Issue by bhanupradeep7** [vmware/clarity#4113]
## Describe the bug
This is for accessibility of screen readers.
"Alt" attribute should be added (or provide a provision to add) for all elements. 
For eg: clr-control-error, clr-signpost etc 

## How to reproduce

1.  Go to 'https://v2.clarity.design/input'
2.  Scroll down to 'Helper and error messages'
3. Try to edit "full name" input field and focus else where leaving input field blank  
4.  There will be a error message with exclamation circle .
5. This svg has role as "img" but does not have "alt" text . 

## Expected behavior

_All the SVG's should have "alt" text_

## Versions

**App**

* Angular: 8
* Node: 10
* Clarity: 2

**Device:**

* Type: MACBOOT
* OS: Mac OS Mojave
* Browser chrome
* Version 78

**Comment by gnomeontherun** [comment]
Actually we intentionally do not do this because the icons should have content next to them that has meaningful content. With the Angular controls we have it set the icon to `role=none` for example. If you use the CSS version of the controls, you'll have to implement the roles yourself since that is out of our control.

Use the `clr-control-error` element to properly link error messages and then the icon is treated as purely visual.

This sounds like something detected by an automatic process, is there a real use case or requirement from manual testing or user experience that causes this problem? If so please report.

I'm going to close as working as expected, unless we get additional information.
