### ISSUE TITLE
not working clr-control-error

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#4114]
## Describe the bug

Not add control error in input after markAsTouched

## How to reproduce

https://clarity-light-theme-v2-error-input.stackblitz.io

1.  touch input
2.  untouch input
3.  clr-control-error - is view

reload
1.  click button submit
2.  controls markAsTouched
3.  clr-control-error - not view

## Versions

**App**

* Angular: 8 last
* Clarity: 2 last

**Comment by gnomeontherun** [comment]
Please review the https://v2.clarity.design/forms documentation under "Reset and Force Validation". It shows that you also need to tell the Clarity forms to check validation (otherwise it can't know about programmatic validation changes).

```typescript
import {ViewChild, Component} from "@angular/core";
import {FormGroup, FormControl, Validators} from "@angular/forms";

@Component({
    template: `
    <form clrForm [formGroup]="exampleForm">
        <input clrInput formControlName="sample" />
        <button class="btn btn-primary" type="submit" (click)="submit()">Submit</button>
    </form>
    `
})
export class ReactiveFormsDemo {
    @ViewChild(ClrForm, {static: true}) clrForm;

    exampleForm = new FormGroup({
        sample: new FormControl('', Validators.required),
    });

    submit() {
        if (this.exampleForm.invalid) {
            this.clrForm.markAsTouched();
        } else {
            // Do submit logic
        }
    }
}
```

Closing as working as expected and I was able to update your demo to make it work here https://stackblitz.com/edit/clarity-light-theme-v2-error-input-tsjepv?file=src/app/app.component.ts.
