### ISSUE TITLE
clr-signpost cannot be used in custom element/ShadowDom

### ISSUE THREAD

**Issue by royling** [vmware/clarity#4122]
## Describe the bug

I am creating custom elements with ShadowDom with Angular Elements and Clarity but got the below error when using `clr-signpost`:

```
ERROR TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type
```

## How to reproduce

Will try to provide a stackblitz example...

## Expected behavior

All clarity components can be used.

## Versions

**App**

* Angular: 8.x
* Node: 10.x
* Clarity: 2.x

**Device:**

* Type: Mac
* OS: macOS
* Browser: Chrome
* Version: latest

**Comment by mathisscott** [comment]
I'm not real sure why signpost is showing this error. I don't see where it would be trying to call that method unless you're trying to put a signpost inside of something like the vertical nav or datagrid.

That said, Angular Elements' support for libraries is not great. If you're making a set of Angular Element widgets that include Clarity in them, you'll be asking your consumers to download multiple versions of the Clarity library inside each widget.

Given the nature of how the Clarity library (as a monolithic, stateful library) goes about its business, this can have unpredictable effects concerning shared resources/services.

Until Angular Elements supports the use of libraries (even things like Bootstrap) and also meets our requirements for browser support (note that they do not support IE and never plan to), we cannot say that the Clarity Angular library being used inside of Angular Elements is a supported use case.

It is recommended that you investigate using Clarity Core `@clr/core` or work out another solution.

I am closing this because it's not a Clarity issue but an issue with Angular Elements support of libraries (to which the Angular core team isn't circling back until after Ivy is done).
