### ISSUE TITLE
Latency while rendering large data (JSON) in Datagrid

### ISSUE THREAD

**Issue by utkarshdang7** [vmware/clarity#4141]
Hi,

I am using Clarity version 1.1.3.
While using Datagrid, we are facing a lot of latency to render the data.
The data is in JSON format with around 600 or more entries. 

We are using 2 loops - one inside <clr-dg-row> with *clrDgItems and one inside <clr-dg-cell> with *ngFor.

The same works fine on normal HTML table.

Please help with this.

**Comment by gnomeontherun** [comment]
Hello, for bug reports and other issues please provide a demo using Stackblitz (https://stackblitz.com/@clr-team has starters). It is hard to know exactly what you are experiencing otherwise and what to suggest if this is a Clarity issue or an application issue.

The more content you have to render, the longer it will take to render. Pagination is also recommended to reduce the amount of rendering required as well as improve usability as long datasets are hard to consume.

**Comment by gnomeontherun** [comment]
Hi @utkarshdang7, due to inactivity we are closing this issue based on our issue management policy. If you can provide a working reproduction of the issue for us to review, we'll reopen the issue and investigate further.
