### ISSUE TITLE
Input property "clrTabLinkInOverflow" of clr-tabs component does not work well

### ISSUE THREAD

**Issue by AllForNothing** [vmware/clarity#4149]
## Describe the bug
For the  below code:
```html
<clr-tabs>
    <clr-tab>
        <button [clrTabLinkInOverflow]="a" clrTabLink type="button">
            <a class="nav-link">A</a>
        </button>
    </clr-tab>
    <clr-tab>
        <button [clrTabLinkInOverflow]="b" clrTabLink type="button">
            <a class="nav-link">B</a>
        </button>
    </clr-tab>
    <clr-tab>
        <button [clrTabLinkInOverflow]="c"  clrTabLink type="button">
            <a class="nav-link">C</a>
        </button>
    </clr-tab>

</clr-tabs>
```
## How to reproduce
1. By default,  variables a and b are both false, and c is true;
2. change a to false, then tab A  goes to "..."
3. change a to true, then tab A won't be back

## Expected behavior

I believe tab A should be back from "..." after changing a to false

## Versions

**App**

 "@clr/angular": "^2.2.0",
"@angular/core": "^8.2.0",
node: v10.16.0

**Comment by gnomeontherun** [comment]
Can you please provide a Stackblitz demo of your issue so we can see it reproduced in isolation? 

https://stackblitz.com/@clr-team has a set of starters to use.

**Comment by AllForNothing** [comment]
@gnomeontherun I set up a demo for your reference:
EDITOR URL: https://stackblitz.com/edit/angular-jwgfrw
APP URL:  https://angular-jwgfrw.stackblitz.io
EMBED URL: https://stackblitz.com/edit/angular-jwgfrw?embed=1&file=src/app/app.component.html

**Comment by AllForNothing** [comment]
@gnomeontherun And I noticed that overflowed tab "C" is the key point to reproduce the bug,  if  remove tab "C", the bug will disappear

**Comment by gnomeontherun** [comment]
Ok the first thing is that it is not advisable to change the order of tabs by moving an item into the overflow if it isn't at the end. This is an accessibility problem, and would cause people to lose track of what is happening or where they are. This works fine (even with C) if you toggle tab B instead (which is last). So yes there does seem to be something funny when you move an item into the overflow (which already has an item) that isn't the last item in the list, but that makes it a pretty low priority since its a usability and accessibility issue to reorder the tabs in this manner.

**Comment by AllForNothing** [comment]
In my case, I have a lot of tabs on one page，so I want them to be self-adapted to window size and cover window resize event.   Down window size,   put overflowed items to the overflow; up window size, then get related items back(I met this issue here). 
And I got a workaround:  use ChangeDetectorRef to  re-render  the whole clr-tabs component when I change clrTabLinkInOverflow of a tab from true to false.
