### ISSUE TITLE
Allow the Wizard to run also as part of the page, not only inside a modal.

### ISSUE THREAD

**Issue by neoswf** [vmware/clarity#418]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Sometimes a need is rising for the _Wizard component_ to be part of the page, while opening the wizard in a modal doesn't fit, since it breaks the user's navigation flow.

### Actual behavior
Wizard open in modal only. No way (AFAAK) to configure it to run as an inline, page-integrated component.

### Reproduction of behavior
Wizard's documentation can be found here: https://vmware.github.io/clarity/documentation/wizards

### Environment details

* **Angular version:** 2

* **Clarity version:** Latest

* **OS and version:** Mac Sierra

* **Browser:** all

**Comment by neoswf** [comment]
thank you @jaffoneh for taking a look at this 👍

**Comment by yaooluu** [comment]
Hi @neoswf , I'm having the same requirements and I did some CSS overriding to achieve this. Please refer to the plnkr below: 

https://plnkr.co/edit/HvFMLyeXw0dsL023xg0Z?p=preview

**Comment by mathisscott** [comment]
@yaolu and @neoswf : This is a version of what @yaooluu did with a lighter approach to the CSS selectors. Just make sure to add the `.clr-wizard--inline` classname to your wizard HTML.

https://plnkr.co/edit/sv4Shf7lAzQJoFX4gCyv?p=preview

**Comment by mathisscott** [comment]
This was addressed in #156 

It is accomplished with CSS classnames applied to `clr-wizard`. An example can be found here in the demo app: https://github.com/vmware/clarity/blob/master/src/app/wizard/wizard-inline.demo.html

This will remain undocumented because it is not a recommended use case for the wizard. But the code is there to accommodate users.
