### ISSUE TITLE
Can not preserve datagrid selection, when the reference to the datagrid items changes

### ISSUE THREAD

**Issue by georgiatanasov147** [vmware/clarity#4275]
## Describe the bug

We have a client side single selection grid. Whenever an action on an item is made, we need to make an api call for the whole collection. After switching the reference of the items to the new one, we try to manually set the selection, but the `clrDgSingleSelected` event emits an `undefined` value slightly after our reselection attempt and clears it. The only way to make this work is to use a timeout to wait for the `undefined` emit. 

## How to reproduce

Here is a stackblitz example. 
https://stackblitz.com/edit/clarity-light-theme-v2-mixpkg?file=src/app/app.component.html

1.  Select an item
2.  Click on 'EDIT'
3.  Observe behavior

## Versions

**App**

* Angular: 8
* Node: 12.7.8
* Clarity: 2.2.2

**Comment by gnomeontherun** [comment]
Thanks for the report, this does look like a buggy behavior but we'll have to investigate the lifecycle. The challenge is if you clear the list (because say it was filtered) the selection should change and become `undefined`. So we have to review it from multiple angles to ensure we don't break other behaviors.

The proposed workaround is valid and suggested for now.
