### ISSUE TITLE
Min and max date input naming does not follow the naming convention

### ISSUE THREAD

**Issue by martinbrom** [vmware/clarity#4295]
## Summary

All inputs should be prefixed with "clr", the "min" and "max" inputs for date on the date-picker however don't follow this convention.

* What is the change?

Rename inputs for min & max date to clrMinDate & clrMaxDate (or clrMin & clrMax, etc.)

* Why should it go in Clarity?

> To avoid conflict with non-Clarity components, inputs, and outputs of our directives and components should be prefixed with clr.

* Does this change impact existing behaviors? If so how?

Yes, a breaking change, inputs are being renamed.

## Conclusion

Should be straightforward :)

**Comment by hippee-lee** [comment]
Hi Martin, you are correct about our coding guidelines and prefixing with clr. However, there is one exception 😉. When the input has the same name as a native HTML5 attribute we keep that so that it behaves as a native element. Mimicing/preserving the native browser behavior is more important than prefixing these attributes/inputs with clr. We do have some other components that also repeat this pattern sprinkled throughout the library. 

I'm going to close as this isn't something we will change.
