### ISSUE TITLE
Documentation on using Clarity without Angular

### ISSUE THREAD

**Issue by deAngelisAlex** [vmware/clarity#4308]
Hello,

I would like to know if there's any loss of basic functionality if we use Clarity as an HTML/CSS/JS framework *without* Angular, as I have not been able to find that information on the website.

Thank you!

**Comment by mathisscott** [comment]
@deAngelisAlex 
Presently, using Clarity without Angular means you are just using the HTML/CSS. So that is only styles and formatting.

We are working on [Clarity Core](https://github.com/vmware/clarity/tree/master/src/clr-core) which is a library of web components. Right now we are awaiting our 3.0 release to take core out of beta. There are only a few components but we will be adding more.

These components also work in other frameworks (Preact, Vue, Elm, Ember, etc.) and will work in React as well (but we are still vetting that approach and are going to publish it sometime after 3.0.
