### ISSUE TITLE
"trigram for heaven" icon visibility

### ISSUE THREAD

**Issue by joshvanal** [vmware/clarity#431]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

"Hamburger" icon or the "trigram for heaven" icon visbility should be configurable based on the developer's decision.
### Actual behavior

The icon  is only visible in tablet/mobile view. 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I'm really doing this as a discussion item to understand what was the decision behind making it visible only in smaller devices.

**Comment by mathisscott** [comment]
I don't think this is an icons issue as much as a question about responsive navigation.

Pinging: @adityarb88

**Comment by adityarb88** [comment]
@joshvanal: The reason that the icon is just shown on xs, sm and md breakpoints is because our navigation is collapsible on those breakpoints only. Those icons are just meant to show and hide the navigation. On larger breakpoints, our UX team recommends that the navigation should remain visible and hence the icons are hidden.

I will cc @yenmade to this ticket to confirm this and provide more information.

**Comment by joshvanal** [comment]
Thanks @adityarb88!

**Comment by jaffoneh** [comment]
Closing based on last comment. We're considering additional aspects of navigation as we go through but seems like this is resolved based on the last comment. @joshvanal let me know if you'd like to reopen it to discuss further.
