### ISSUE TITLE
Not able to have focus in Angular CDK popovers over clr-modal as Focus is Trapped

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#4321]
## Describe the bug

Similar to signposts, if we have Angular CDK based popovers on top of clarity modal, focus gets trapped into the modal. Any inputs or elements to be focussed are not accessible inside popover.

## How to reproduce

https://stackblitz.com/edit/clarity-with-cdk-popover

Steps to reproduce the behaviour:

1.  Click on 'Show Dialog'
2.  Dialog would appear.
3.  Click on 'Show CDK Popover'
4.  Popover appears on top of clarity popover.
5. Try focussing on input elements or buttons inside CDK popover via keyboard.
6. Observe that elements inside cdk popover cannot be focussed .

## Expected behavior

There has to be a way move focus to popovers shown above clarity modal.
Understand here that these are injected at the root of DOM and thus are not child elements of the modal element.

## Versions

**App**

* Angular: 8
* Clarity: 2.1.1

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Based on the demo and examples, the workaround is to use the HTML/CSS markup for the modal and implement the modal manually to avoid focus trap issues. You'll need to be sure to implement all of the accessibility behaviors as well, so refer to the modal implementation for guidance.

Alternatively, a different pattern could be used since the issue here is that the CDK and Clarity don't communicate and end up conflicting here. The pattern or use of the CDK and a popover may be replaced with a Clarity component or reimagined to avoid having nested dialog like behaviors.

**Comment by gnomeontherun** [comment]
Closing this as it seems unactionable for Clarity, by mixing these two libraries things are difficult to manage. By using the static modal apps can reimplement the modal behavior of focus trapping on their own if necessary.
