### ISSUE TITLE
[Docs] Clarification on the use of icons in v3

### ISSUE THREAD

**Issue by michaelbromley** [vmware/clarity#4333]
Hello Clarity team!

First of all, thank you for this library! This is a question for clarification around the documentation for using icons in an Angular app.

### Q: What is the correct way to use icons in an Angular app?

In the [release notes for 3.0.0-next.6](https://clarity.design/news/3.0.0-next.6) it states 

> All Clarity Icon sets now available in @clr/core (#3905)
We've added over 470 icons to the @clr/core icon library! The tree-shakeable web components in Clarity Core now offer all the icons in the old Clarity Icons library and will continue to grow in the future.

> @clr/core icons are tree-shakeable (#2599)
Clarity Core has released a long-requested feature that allows teams to import only the icons they need into their projects. The Clarity team has built automated tests to verify that this remains in working order out into the future. Note that this only applies to the icon library in @clr/core!

But in the [icons getting started guide](https://clarity.design/icons/get-started) it gives the following example:

```ts
import '@clr/icons';
import '@clr/icons/shapes/essential-shapes';
import '@clr/icons/shapes/technology-shapes';
```

Is that guide out of date now? If so, are you able to give a quick guide to how to use the icons shipped in `@clr/core`? I have searched through issues and your own PRs to try to glean some hints but I can't figure it out.

I'd love to take advantage of the tree-shaking to reduce my bundle size. 

Thanks for your time!

**Comment by gnomeontherun** [comment]
Hi @michaelbromley, for now there is nothing that changes for anyone using Angular and Icons today. Long term, we'll be helping migrate projects to use the new implementation, hopefully in a seamless manner. To that end, we aren't recommending changes for most folks unless they are willing to 

We haven't integrated the new implementation of icons into Angular yet, so this is why the guide has not changed. If you want to change to the new implementation manually, you may do so by reviewing the https://clarity.design/storybook/core/ documentation. There is a working solution to easily move listed here https://clarity.design/storybook/core/?path=/docs/components-icon--legacy. If you want to move fully to Core without the shim, you'd have to change all uses `clr-icon` to `cds-icon`, but otherwise the API should be the same.
