### ISSUE TITLE
@clr/core not included in manual setup of clarity in Angular application

### ISSUE THREAD

**Issue by jakehova** [vmware/clarity#4349]
## Describe the bug

In the documentation "Angular Option 2: Manually adding Clarity to an Angular project", the @clr/core library is missing from the npm install list.  ng build/serve will fail if @clr/core is not installed as it is a dependency of @clr/angular

## How to reproduce

1) create new angular app using cli (ng new testproject)
2) walk through "Angular Option 2: Manually adding Clarity to an Angular project"
3) run ng serve
4) See error saying that @clr/angular requires @clr/core

## Expected behavior

Expect to walk through manual steps and being able to run project

## Versions

all versions latest: 
Angular 9,
Clarity 3

## Additional notes

Need to: 
1) Update documentation as to the purpose of @clr/core
2) add @clr/core to npm install list: npm install @clr/icons @clr/angular @clr/core @clr/ui @webcomponents/webcomponentsjs --save

**Comment by bdryanovski** [comment]
@jakehova 

`@clr/core`, is still in early-stage so we are working on the documentation and providing good examples of how to use. We gonna address this in our next releases as well as adding more examples and more components. 

Thanks for bringing it to our attention.

**Comment by gnomeontherun** [comment]
@jeeyun can we get this fix in with the next release?

**Comment by phelgren** [comment]
I ran into the same issue as #4244  Which pointed to this error:
`
ERROR in The target entry-point "@clr/angular" has missing dependencies:
 - @clr/core/common
    ERROR in node_modules/@clr/angular/utils/i18n/common-strings.service.d.ts:1:46 - error TS2307: Cannot find module '@clr/core/common'.
    1 import { CommonStringsServiceInternal } from '@clr/core/common';
`
Ran npm install @clr/core  and that took care of it.  Posting here since fix to #4244 didn't mention running that command explicitly (as a noob: the issue mentioned "Did you make sure you have @clr/core@3 installed?" but didn't say how)  If @clr/core@3 is essential, why doesn't it install as a dependency? Curious...a couple of other examples broke on the same error.

**Comment by gnomeontherun** [comment]
When a package is missing, you can install it with `npm install @clr/core` or `yarn add @clr/core` depending on your package manager, so when NPM mentions a missing dependency this can help you resolve it in your project.

Clarity has peer dependencies because some of our packages are used in isolation, so we don't force install the peer dependencies if you aren't using them. We may change this policy in the future, but that is why it is this way right now.
