### ISSUE TITLE
Slow rendering of clarity datagrid with larger page size

### ISSUE THREAD

**Issue by pyovchev** [vmware/clarity#4391]
## Describe the bug

The clarity datagrid is very slowly rendered when the number of items in a single page is relatively large. When an array of length of 100, 200 or 500 records is passed to the datagrid, it takes anywhere between a second and 4 seconds to load. In many cases it takes more time to render the datagrid compared to retrieving data with thousand of records from the back-end servers. The options for filtering are limited in some cases due to the need to support and work with legacy APIs which lack server side filtering and thus when working with large datasets the page has to be relatively large as well. At the moment everything over 100 items in a single page which takes around one second to be rendered, from an UX perspective is considered too slow.

## How to reproduce

I've prepared a stackblitz demo project which has three options - to display a datagrid with page size of 100, 200 or 500 items and shows the time it takes to render each of them: https://stackblitz.com/edit/clarity-datagrid-slow-rendering

1.  Load a datagrid with 100/200/500 items
2.  Observe the time it takes to render

## Expected behavior

The clarity datagrid to be loaded in more manageable time - up to 2 seconds for 1000 items.

## Versions

**App**

* Angular: 7
* Clarity: 3

**Device:**

* Type: MacBook
* OS: macOS High Sierra
* Browser Chrome
* Version 80.0.3987.132

**Comment by mattmutt** [comment]
a few directions to consider:

Reduce and fit an overly long Clarity grid into a condensed viewport. 

Clarity team to comment if the `clr-dg-pagination`component is efficiently built for large row count, or state if there is an upper bound on the number of physical rows it can render in the DOM and remain performant. The debate may lead to "use more paging and less scrolling through the rows"

1000 rows in 1 second
![Screen Shot 2020-03-20 at 09 39 25](https://user-images.githubusercontent.com/8688570/77185738-20b7b780-6a8f-11ea-8fbe-7af5ab9aa956.png)

**Comment by hippee-lee** [comment]
Thanks @mattmutt for looking into this. 

@pyovchev - I forked the original stackblitz to play with it a bit. Here are some observations. 

1) The pagination component was updated so I changed that to the correct one.
2) The provided example is using `clrDgItems` for the iterator so I am assuming that it is not server driven. E.g the whole datagrid model will delivered in one payload. In this case, the datagrid expects all data to be handed to at once and then it needs to figure out the pagination internally. 
3) I would recomend using the built in page size selection that is part of the pagination component. and limiting the page size to an acceptible performance. 

All of that said I do see some issues but I'm not sure if its the demo or the datagrid so further investigation is warrented. 

https://stackblitz.com/edit/gh-4391-datagrid-performance

**Comment by Jinnie** [comment]
The same setup with a simple `<table>` produces rather small difference. About 400-500ms on average per 500 items. Varies between runs, and yes, it's in favor of the `<table>` scenario, but from what I see, still the rendering thread is what takes most of the time and high CPU. It can get down to 2300 from 2700. Is this what we're after? From the user perspective 2300 should be as bad as 2700.
I guess it may scale up with a more complex example, but it would still be nice to make some comparative analysis with a normal table.

**Comment by gnomeontherun** [comment]
The comparisons of performance can only be done on the same machine with variables minimized. The pagination component is only rendered once, the real impactor here is the number of rows being rendered. The complexity of each row, the number of cells, the content inside of each cell, and other variables will contribute to overall render time. 

1. The user will have increasingly poorer experience with larger datasets on the same page, not just because of performance. The amount of data, the potential lag for the browser to scroll, the amount of scrolling all contribute to a poor experience. The Clarity team long has asserted that reasonably sized pages of data provide the best balance of access to data and usability.
2. The amount of performance gain that Clarity can provide is likely minimal in these scenarios. As @Jinnie shared even a normal table has large rendering requirements. Also, the features the Datagrid supports do require overhead to maintain state and awareness of what is going on. Even the fastest, most optimized car is too slow when you are aiming to drive off a cliff and launch into space.
3. We have to support back to IE11, which also limits our options and the performance of IE11 is quite poor without a small dataset per page. See https://github.com/vmware/clarity/issues/1385#issuecomment-573490062
4. Stackblitz is not a great place to do accurate performance testing due to it being a complex page and a bit of an unusual setup without performance.

A quick look at this specific demo and I see a few things.

1. The _initial load_ time of the rendering of the Datagrid is slow (because a lot happens to bootstrap the component), but if you start with a smaller number like 10 rows and increase it to 500 rows (without the destroying and recreating the Datagrid with `*ngIf`), the render time is quite fast. 
2. You are currently using `this.licenses.push()` to mutate the array onInit, and by creating a temporary array `items.push(item)` and then assigning it to this.licenses = items` after the loop improves performance as well.
3. The demo is creating an empty object then setting each property. This is overhead vs setting the whole object at once.
4. There is no trackBy, which is always recommended to improve performance and caching with Angular, plus required to correctly track state in some cases (server side).
5. The UUID function is adding around 10% to the overall render time based on toggling it on and off. Side effects on the app side impact overall rendering because this is a blocking function call to calculate text for interpolation.
6. The removal of icons and the `*ngIf` in the cells made the largest improvement by 50% or more. This is actually a bigger concern to me.

With these kinds of adjustments, I'm consistently seeing this demo load under .1 seconds. It's not just the Datagrid but the data sources and rendering lifecycles of the whole application that impact performance.

So long and short of it all, don't render large datasets initially on page load. Start with a smaller page size, and let the user increase it after the initial render.

I'm going to close this as unactionable, because there are optimizations as I've suggested that make it faster based on changing the situation. The actual basic datagrid renders reasonably fast (compared with a table of similar structure) so the workarounds are optimizing the content of your datagrids.
