### ISSUE TITLE
Datagrid detail panel UI glitch

### ISSUE THREAD

**Issue by abbey24** [vmware/clarity#4392]
Looks like there is some UI glitch when detail panel is shown.
https://clarity.design/documentation/datagrid/detail-pane 
<img width="887" alt="Screen Shot 2020-03-20 at 9 09 02 AM" src="https://user-images.githubusercontent.com/15808331/77188350-18617b80-6a93-11ea-94d0-361755c6e19d.png">

**Comment by hippee-lee** [comment]
Thanks for reporting this. 

This is happening because the demo has a fixed height and not enough rows to fill up the space. 
I'm going to close as not an issue because its specific to how the demo is set up. If this is happening in a production application please recreate a stackblitz that is similar to the application with the issue.

**Comment by abbey24** [comment]
hmm I doubt it's just because of that tho. When the detail panel is not opened, there is no such gap. when open the detail panel, all the rows shrink a little bit in height. See there is no gap in default view:
<img width="876" alt="Screen Shot 2020-03-20 at 12 57 18 PM" src="https://user-images.githubusercontent.com/15808331/77201870-849ba980-6aaa-11ea-9cce-bea3c4abaf85.png">

**Comment by gnomeontherun** [comment]
This was fixed in https://github.com/vmware/clarity/pull/4399 and its not a problem with detail pane but the color swatch was making the rows too large.
