### ISSUE TITLE
add aria-checked for clrInput checkbox

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#4427]
## Summary

Add aria-checked for checkbox's.

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role

**Comment by gnomeontherun** [comment]
Hi @KANekT, the need for `aria-checked` is only necessary on elements that aren't default HTML elements. Aria doesn't need to be put onto standard elements so long as they are used as expected, and since a checkbox already has the checkbox role, it comes for free.

I'm going to close this as not an issue, unless you have more context or details to share about the request here.

**Comment by KANekT** [comment]
@gnomeontherun how can the reader know that the checkbox is selected if not add aria-checked?
