### ISSUE TITLE
Font-Size Variables in CSS Theming

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#4433]
Is there a replacement for the font-size variable in the theming via CSS custom property.

With the SCSS theming it was possible to override the font-size of the different headings
```scss
$clr-h1-font-size: 28px;
$clr-h2-font-size: 22px;
$clr-h3-font-size: 18px;
```

**Comment by gnomeontherun** [comment]
Hi @twittwer, you are correct that there is not a CSS custom property for font-sizes. The reason is we didn't want to enable custom properties that affect layout, there will be an alternative way to manage this through tokens (work in progress).

That said, its unfortunate but true that our headers are not broadly used inside of components in a consistent manner. You'll like have to target individual headers if you want to change their sizes inside of components, and if you just want to adjust the generic header element sizes, you can override it with custom CSS globally. We recommend that you use rem units to allow for more flexibility in allowing users to resize content on the page.

```
h1 {
  font-size: 1.2rem;
}
h2 {
  font-size: 1rem;
}
/* ... and so on **/
```

Based on this, I'm going to mark this as answered. You can also continue to use SCSS theming in v3, though we will have to remove it functionally in a future release, which will come with a migration strategy and automation to assist.

**Comment by twittwer** [comment]
Thx for the detailed response 👍 
Your suggestion is our current workaround - so we will keep it this way and reevaluate it when the tokens arrive
