### ISSUE TITLE
Warning button color same as error color

### ISSUE THREAD

**Issue by GaryHyland** [vmware/clarity#4436]
## Describe the bug

Warning button color same as error color, solid and outline versions.

## How to reproduce

Can see within the v2 and v3 documentation pages for butttons.
![image](https://user-images.githubusercontent.com/39715655/78316282-d3107400-7591-11ea-97fb-940afb7ed2c8.png)

## Expected behavior

"btn-warning" should result in a "warning" color, similar to Alerts, etc

## Versions

**App**

* Angular: 8
* Node: 12.16
* Clarity: 2 or 3 (doc page)

**Device:**

* Type: desktop
* OS: Win 10
* Browser Edge Chrome
* Version

**Comment by gnomeontherun** [comment]
Hi @GaryHyland this is intentional. There hasn't been a clear use case for having a 'warning' button, in addition a yellow button is hard make accessible with contrast ratio requirements. The reason it is provided is we have success/warning/error in other places, but it is intentionally red. 

I'm going to close this as we won't be making any changes for this.
