### ISSUE TITLE
I could not find any way to disable the data grid based on condition

### ISSUE THREAD

**Issue by im-minion** [vmware/clarity#4459]
## I could not find any way to disable the data grid based on condition

I want o disable(the data-grid should be greyed out like disable options in other component) my multi-select data grid based on some conditions
I don't find if there is any way to do so.

Also,  it would be great if we have a choice of keeping all the selected records on the top, specifically for pre-populated data.

**Comment by gnomeontherun** [comment]
Hi @im-minion, there isn't a 'disabled' state for the datagrid like a form field. The datagrid isn't a typical form field, if you have to 'disable' it I think there is probably a better pattern where you would remove it from the page instead. 

There is a way to disable specific rows by using `clrDisableSelection` on a given row. https://clarity.design/documentation/datagrid/selection

Finally, moving selected items to the top is actually not a recommended pattern as it would be potentially confusing to keep track of items. For example, if you are on the second page and select an item it would move to the first page. Applications could optionally display a list of the selected items since the selected items are tracked with the two way `clrDgSelected` binding.

Based on the above guidance, I believe we've address the question and I'm going to mark this as closed. We don't anticipate creating a disabled state nor reordering items based on their selection state.

**Comment by im-minion** [comment]
okay! thanks for quick response @gnomeontherun  :)

**Comment by shravansofts** [comment]
is this available in Clarity 2.0 as well?

**Comment by bdryanovski** [comment]
As @gnomeontherun said above, the datagrid is not designed to be disabled as form controls are. So a better solution will be to completely remove the datagrid or datagrid data to represent that there no feature action that could be done with it.

In v3 there is `[clrDgSelectable]="!disabled"` as an input of `ClrDgRow` - with it, you could disable single rows or lock so no changes could be done to them. There is an example at the end of the documentation [here](https://clarity.design/documentation/datagrid/selection)
