### ISSUE TITLE
StackView expanding/collapsing

### ISSUE THREAD

**Issue by mathisloge** [vmware/clarity#4462]
## Describe the bug
 When having some input field on the main block inside the stack-view. It toggles when the user focuses the input field.

## How to reproduce

Go to https://clarity.design/documentation/stack-view section "Stack View With Editing in a Modal"
And click "Edit"

1. Click on "Edit"
2.  Click on some main header input
3.  See described toggle

## Expected behavior

I would like to ignore the toggle when the input field will be focused.

## Versions

**App**

* Angular: 9.1.1
* Node: 12.9.1
* Clarity: 3.1

**Device:**

* OS: Windows
* Browser: edge chromium

**Comment by Shijir** [comment]
Hi @mathisloge! I see the issue you are describing. But that stack block is not expanding because of the focus on its input. It's opening because when you click on the input to focus on it, the click event bubbles to the stack block; that's why you would unintentionally expand the stackblock. A workaround you could use to circumvent this issue is stopping the click event bubbling on the stackblock input like this:
```
<input type="text" clrStackInput [(ngModel)]="block.content" (click)="$event.stopPropagation()" />
```

**Comment by mathisloge** [comment]
Yes, right.

Thanks for the workaround!

**Comment by civanova** [comment]
Hi,
After staring the upgrade to v3 we started hitting the same issue.
Unfortunately our stack views are rich with interactable elements - inputs, selects, buttons, links, sign posts etc.
The workaround will most definitely work, but we need to pass through hundreds of places and stop the propagation for each element.

**Comment by civanova** [comment]
Hi,
It seems the issue is new for V3.
Some info that might help root causing and fixing the issue:

The change of the behavior seems to have happened with -  https://github.com/vmware/clarity/commit/1280cf1e936705b4935bafef983e32561fbadf94
And is caused because the toggleExpand method is now attached to the parent of both the label and the content, and not only for the label as it was until V2
