### ISSUE TITLE
clrDgSingleSelected is throwing error in clarity version 3

### ISSUE THREAD

**Issue by rajashreethimmappa** [vmware/clarity#4477]
I am creating a Datagrid with single selection option using Clarity version 3 and Angular 9. but this is throwing error "ERROR TypeError: Cannot read property 'findIndex' of undefined at Selection.isLocked (clr-angular.js:11557)..." in @clr/angular library and datagrid is not rendered.

## Versions

**App**

* Angular: 9.1.0
* Node: 10.16.2
* Clarity: 3.1.0
Below is code snippet: app.component.html

`<clr-datagrid [(clrDgSingleSelected)]="selectedUser" [clrDgRowSelection]="true">
   <clr-dg-column>User ID</clr-dg-column>  
   <clr-dg-column>Name</clr-dg-column>
   <clr-dg-column>Favorite color</clr-dg-column>
   <clr-dg-row *ngFor="let user of users" [clrDgItem]="user">
     <clr-dg-cell>{{user.id}}</clr-dg-cell>
     <clr-dg-cell>{{user.name}}</clr-dg-cell>
     <clr-dg-cell>{{user.color}}</clr-dg-cell>
   </clr-dg-row> 
   <clr-dg-footer>{{users.length}} users</clr-dg-footer>
  </clr-datagrid>`
app.component.ts
`import { Component } from '@angular/core';
@Component({
  selector: 'app-root',
   templateUrl: './app.component.html',
   styleUrls: ['./app.component.scss']
})
export class AppComponent {
 title = 'ang9VMC3POC';`
  users = [{
     id:"1",
     name:"test1",
    color:"red"
 },
{
 id:"2",
 name:"test2",
 color:"blue"
},
{
 id:"3",
 name:"test3",
 color:"green"
},
];
selectedUser = this.users[2];
}`

**Comment by rajashreethimmappa** [comment]
any suggestion or help on this is appreciated.

**Comment by gnomeontherun** [comment]
Hi @rajashreethimmappa you should be using `clrDgItems` with `clrDgItem` or else you'll see these kinds of errors. https://clarity.design/documentation/datagrid/selection-single

```html
<clr-dg-row *clrDgItems="let user of users" [clrDgItem]="user">
```

Update the above to iterate over the items correctly.

Closing as resolved with an implementation change.

**Comment by krlf** [comment]
Hi @gnomeontherun ,

Could you please comment of how to use datagrid in server-driven manner from point of view you have mentioned. I mean the clarity [documentation](https://clarity.design/documentation/datagrid/server-driven) has the following note:

> One important thing to note is that since you don't have all the data available at once, you cannot use the smart iterator *clrDgItems: it would sort, filter and paginate a subset of the data that has already gone through all that. So all you need to do is to go back to a simple *ngFor, which we support. 

I'm asking because encountered the same issue as @rajashreethimmappa has reported.

Thank  you in advance.

**Comment by krlf** [comment]
Hi @gnomeontherun ,

The clarity [documentation](https://clarity.design/documentation/datagrid/server-driven) has the following note:

> One important thing to note is that since you don't have all the data available at once, you cannot use the smart iterator *clrDgItems: it would sort, filter and paginate a subset of the data that has already gone through all that. So all you need to do is to go back to a simple *ngFor, which we support.

But I have the same error:

`TypeError: Cannot read property 'findIndex' of undefined at Selection.isLocked (http://localhost:4200/vendor.js:95297:61) at ClrDatagridRow.get clrDgSelectable [as clrDgSelectable] (http://localhost:4200/vendor.js:95476:32) at ClrDatagridRow_ng_template_5_div_4_Template (http://localhost:4200/vendor.js:84357:154) at executeTemplate (http://localhost:4200/vendor.js:29693:9) at refreshView (http://localhost:4200/vendor.js:29540:13) at refreshDynamicEmbeddedViews (http://localhost:4200/vendor.js:30898:21) at refreshView (http://localhost:4200/vendor.js:29563:9) at refreshDynamicEmbeddedViews (http://localhost:4200/vendor.js:30898:21) at refreshView (http://localhost:4200/vendor.js:29563:9) at refreshDynamicEmbeddedViews (http://localhost:4200/vendor.js:30898:21)`

On the code:
`<clr-dg-row *ngFor="let user of users">`

Could you please comment of how to use datagrid in server-driven manner?

Thank you in advance.

**Comment by hippee-lee** [comment]
Hi @krlf, we have docuemtation on server driven datagrids [here](https://clarity.design/documentation/datagrid/server-driven). 

In a short summary, the app component with a server driven datagrid needs to implement the refresh function so that when the datagrid state is changed (usually b/c a user wants to sort / filter / or navigate through pagination) it can be sent to the backend with the infomration needed so that the server does the correct thing and sends back the new listof items for the datagrid. 

If you haven't already, have a look at the [server driven docs](https://clarity.design/documentation/datagrid/server-driven). If you have and its still not clear how to implement your server driven datagrid, please use one of the stackblitz starter to create an example with what you are tyring, then use that to post a question on Stack overflow so we can answer it there. If you have a stackblitz with a server driven datagrid that is simple and it has an error similar to the error reported above, please open a new issue describing your setup and answer the other questions in the template and provide the stackblitz edit link so we can take a look.
