### ISSUE TITLE
Vertical Nav: Change API to allow additional icons at the top of the. menu

### ISSUE THREAD

**Issue by digish777** [vmware/clarity#4527]
I am not sure if it is a feature request. My requirement is I want to add another icon to the left side of the navigation toggle button.

https://clarity.design/documentation/vertical-nav/collapsible-nav/normal

I am not able to replace the toggle button with normal button and I want open and hide  of menu on hover. The minute I place:

 (mouseenter)="collapsed = false;" (mouseleave)="collapsed = true;"

from clr-vertical-nav to button.

I lose the capacity to hide and open menu on hover.

How can I replace inbuilt toggle button generated by Clarity with normal button?, So that I can add another button to the toggle button?

Possibly a stackblitz sample would be helpful

**Comment by hippee-lee** [comment]
Hi @digish777 - yes, a stackblitz that demonstrates what (and how) you are trying to achieve this would be helpful. 

Also, please use the issue template so we have enough information to properly triage and investigate this. Issue templates are [here](https://github.com/vmware/clarity/tree/master/.github/ISSUE_TEMPLATE). You can update the description with the details when you provide the stackblitz. THanks.

**Comment by hippee-lee** [comment]
@digish777 - I'm revisiting this and I made a simple stackblitz with the vertical nav. As I look at it it seems like this would be a feature request. Can you update the issue to include some details for the use case(es) that require adding more icons to the vertical nav? 

Currently the implementation is that the toggle button takes up the horizontal space so that the user can click on the whole width and activate the expand/contract behavior. This change would introduce multiple click targets and that changes the UX for this behavior.

**Comment by digish777** [comment]
I made an html div and made it float to the very left. It did task. I placed a pin in the div. My requirement was to make the menu stay when the pin was clicked. Because I could not find a template to open up the header and place the pin in the left section of the header. I had to rely on floating div. I hated to do it. as I do not trust floating div.

**Comment by hippee-lee** [comment]
Thanks for the extra information. It is something we need to consider.

**Comment by gnomeontherun** [comment]
This will be possible with the cds-navigation component and will be the recommendation to accomplish this feature. Follow #6024 for updates on that.

I'm going to close this as resolved by the above PR.
