### ISSUE TITLE
Dropdown content loses position relative to toggle button

### ISSUE THREAD

**Issue by GrahamFord** [vmware/clarity#4544]
## Describe the bug

The content of a dropdown menu doesn't stay positioned next to the button that opened it if the browser is resized.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-light-theme-cc6xua

1.  Click on the button to open the drop-down
2.  Make the browser window wider or narrower.
3. The content of the dropdown will not keep its position relative to the button that opened it.

## Expected behavior

The content of the dropdown stays positioned relative to the toggle button.

## Versions

**App**

- Angular: [9]
- Node: [8]
- Clarity: [3.1.1]

**Device:**

- Type: MacBook
- Browser [Firefox 75, Opera 67]

**Comment by gnomeontherun** [comment]
This is known because we don't add global listeners to window resize to try and reposition. The frequency of resizes is low, and if you scroll it does auto-close. The workaround here if you need this behavior would be to listen to scroll events, and close it yourself programmatically. 

In the meantime, we'll consider if this is something that Clarity would support, as we try to avoid global listeners like this.

**Comment by GrahamFord** [comment]
@gnomeontherun thanks for the clarification. I'll give the workaround a go.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
