### ISSUE TITLE
Sidenav separation line not displayed in all cases

### ISSUE THREAD

**Issue by elendil-software** [vmware/clarity#462]
Not sure
```
[x] bug
[ ] feature request
[ ] enhancement
[x] question
```
Hi,

I'm not sure it's the right place to post this question, I'm quite new in Angular 2 developement. I have a problem with Clarity but I doesn't know if it's a Clarity bug or if I'm doing something wrong.

I need to develop an app that will be divided in 3 or 4 main components (I will use the header-nav to access them). Each main component will provide from 1 to 4-5 sub-components (use of subnav to access them).

Finally some sub-components will need a Sidenav

I began to develop a simple test app where I put the Clarity layout in the app.component.html with a <router-outlet></router-outlet> : https://embed.plnkr.co/SjOeN48ud6wgDqtAZsaZ/
Works fine.

Then I tried to move the subnav and content-container elements to one of my main components. Here is my problem, now the thin vertical line of the sidenave doesn't occupy the whole height of the window : https://embed.plnkr.co/ExU5o2ls6vM8d0gpjctf/

Where is my mistake ?

### Environment details

* **Angular version:** Last version

* **Clarity version:** 
0.8 and 0.8.5

* **OS and version:** 
Windows 10

* **Browser:** 
Tested with Chrome and Firefox (last versions)

**Comment by adityarb88** [comment]
Hi @elendil-software. We have a few users who raised this issue. This is happening because our layout requires that the `.subnav` and the `.content-container` are direct descendants of `.main-container` because of the way flexbox works. 
There are two solutions right now:
1. You refactor your layout to meet those requirements
2. You add the following styles to your home and module components:
`display: flex; flex-direction: column; flex: 1 1 auto`

That said, we are thinking of implementing the 2nd method in the form of a utility class for our layout. But we need to make sure that it solves all issues before doing that. I will keep this issue open and update it when I research more about other combinations. Thanks!

**Comment by elendil-software** [comment]
Thank you.

Now I have understood where is the problem, I have managed to get something that - almost - work.

The simple case, the page without subnav nor sidebar, works of course.

The case with the sidenav works also correctly. For this one I have done two things :

- removed the <div class="content-container"> and put the content-container directly on the component that contain the sidebar and the content with : 

`
@Component({
	host: { '[class.content-container]': 'true' }, 
	...
})
`

- I've done the same thing with the content-area by adding the css class to the content component :

`
@Component({
	host: { '[class.content-area]': 'true' },
	...
})
`

Now the most complex case, the one I didn't put in the plunker. It has a subnav and each of its option can display a simple content (like the simplest case I explained above) or a sidebar + content.

For the simple content I put a `host: { '[class.content-container]': 'true' }` on the content component and a `<div class="content-area">` in the template. Works fine.

For the case with the sidebar I've done the same thing than in the case with the sidebar explained above,  and added `host: { '[class.content-area]': 'true' },` to the component that contains the subnav.

I put my test project on GitHub : https://github.com/elendil-software/ng2-clarity-nested-components
And installed it here : http://www.elendil.software/ng/

The last problem I have is that the link in the sidebar don't work. Probably something wrong in my routing

**Comment by adityarb88** [comment]
@elendil-software: I see that you are using the `.main-container` inside of a `.main-container`. That might cause issues if you plan to implement our responsive navigation. I still think that you should use the 2nd method which I had described above. Simply replace the the nested `.main-container` class with your own custom class and add the corresponding flex properties.

And yes, like you mentioned above, the last issue is not related to the layout. I think there is something wrong with your routing.

**Comment by elendil-software** [comment]
> I see that you are using the .main-container inside of a .main-container

Ooops, missed this one.

> Simply replace the the nested .main-container class with your own custom class and add the corresponding flex properties.

So I should define my own, say `.my-main-container`, `.my-content-area`, ... classes and use it where I put `host: { '[class.content-container]': 'true' }`, `host: { '[class.content-area]': 'true' }`, ... ?

**Comment by adityarb88** [comment]
@elendil-software: Nope. I am just saying that since `.content-container` is not the direct child of `.main-container` in your case, you could create a class, say for eg: `.my-main-container` which is actually a vertical flexbox with these styles: `display: flex; flex-direction: column; flex: 1 1 auto` and use that to wrap the `.content-container`. Don't next the `.main-container` inside of the `.main-container`. 

In the below screenshot just replace the selected `.main-container` with the custom class that you create:
![image](https://cloud.githubusercontent.com/assets/1426805/22890542/83676e88-f1c1-11e6-929e-842796d5d6bc.png)

**Comment by elendil-software** [comment]
Ok, it works now.  Thanks

**Comment by meije702** [comment]
I am really sorry guys, I don't want to be that guy but I have been hitting my head against the wall over this. I am using modules to separate parts of my app. But I can't get the side-nav to work. I have tried your solution but somehow I can't get that to work either. Is there any way I can have a look at a simple example on plunker or can someone change this: https://github.com/elendil-software/ng2-clarity-nested-components so it mirrors your suggested solution?

**Comment by elendil-software** [comment]
> can someone change this: https://github.com/elendil-software/ng2-clarity-nested-components so it mirrors your suggested solution?
It's already done (except the router.

**Comment by meije702** [comment]
Thanks, your solution is working. I am lazy loading the modules and have dedicated per module routing modules, so I have to fiddle around a bit more to get my solution to work as well. Thank you again for the response.
