### ISSUE TITLE
add the avility to apped clr-modals to body

### ISSUE THREAD

**Issue by edward2990** [vmware/clarity#4681]
right now the modals code is placed inside the container you declare it, but it would be nice if it'll be a way to append the modal to the body

**Comment by hippee-lee** [comment]
It sounds like this is a feature request to enable modal to optionally be appended to the body instead of its current node in the DOM. Can you run through the relevant parts of the [contribution guidelines](https://github.com/vmware/clarity/blob/master/docs/CONTRIBUTING_DEVELOPMENT.md#i-proposal-template) to help me understand better why the current solution isn't enough?

**Comment by gnomeontherun** [comment]
Due to lack of detail, and the ability to do this on the app side if you wish, I'm going to close this. Modals are injected where they are defined, and this could be done at the root of the page.
