### ISSUE TITLE
Datagrid filter input dismiss on Enter keypress

### ISSUE THREAD

**Issue by dbaker111413** [vmware/clarity#4709]
## Summary

When filtering columns on a datagrid, I would like to be able to dismiss the input box when the enter key is pressed. Right now in V3, it will only dismiss when the escape key is pressed. I'm unsure whether this is a feature request or a bug, because when I was going through examples I discovered that this functionality USED to exist before V3. 

- What is the change?
       Dismiss the datagrid filter input box when the enter key is pressed.

- Why should it go in Clarity?
       Most of my users tend to press enter after typing in a filter. While
       I can't speak for all users, it seems like a natural thing to do in my opinion. Additionally, the
       input box blocks cells in the first few rows, so I want to get rid of it conveniently as soon as I 
       am done typing my filter.

- Does this change impact existing behaviors? If so how?
       None that I know of.

- If this change introduces a new behavior, is this behavior accessible?
       Just as accessible as pressing the escape key, if not more.

## Workarounds

Pressing the escape key, clicking outside the input box, or clicking the X button in the input box all provide the desired result.

**Comment by gnomeontherun** [comment]
It is possible that this could be done by creating your own filter, but we intentionally don't do this by default. 

This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
