### ISSUE TITLE
Add right side icon support for buttons

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#4727]
## Summary

_Buttons support icons and best practice / recommendation for consistency is to always have the icon on the LEFT and badge on the right if used. 2 cases warrant an icon on the RIGHT side with no badge:
Buttons which initiate download or pop-out (new-window)._

**Comment by colinreedmiller** [comment]
see spec on page entitled SPEC:
https://www.figma.com/file/gd6va7TaFy3Tjh3gqyjiaG/token-4727?node-id=0%3A1

**Comment by sdurnov** [comment]
I believe support is there already. Putting icon after text works just fine.

**Comment by mathisscott** [comment]
@sdurnov : this is for buttons in `@clr/core`

**Comment by hippee-lee** [comment]
# Visual Spec

![update-specs](https://user-images.githubusercontent.com/433692/90683186-fd01c480-e21a-11ea-8fdc-04640ce3a3e2.png)

@colinreedmiller - should this change also support buttons with icons, text and badges?

**Comment by coryrylan** [comment]
The icon vs badge seems like it should be defined as a guideline but not enforced at a code level. With content projection anything can be passed in and we can't easily detect or block all use cases. 

Instead of trying to predict the thing that is projected maybe the button should only have a single default `<slot>` element? We may have made a mistake with the current internals trying to be to smart about where things are projected. If a user has a valid use case for a different layout we then are blocking and would require an escape hatch style API.
