### ISSUE TITLE
clr-tree-node on triggering collapse a scroll appears on Chrome, an overlapping on Firefox

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#4734]
## Describe the bug

When we try to collapse a clr-tree-node from a clr-tree a scroll appears on Chrome and an overlapping on Firefox.

## How to reproduce
It is visible on the docs site https://clarity.design/documentation/tree-view#recursive-tree

1.  Go to https://clarity.design/documentation/tree-view#recursive-tree
2.  Click to collapse a tree node
4.  [Chrome] See the scroll when a node starts collapsing
5.  [Firefox] See the overlapping when a node starts collapsing

## Expected behavior

The component's UI should be clean without the scroll and the overlap.

## Versions

**App**

- Angular: [9]
- Clarity: [3]

**Device:**

- Type: [pc]
- OS: [win10]
- Browser [Chrome 83.0.4103.106 (Official Build) (64-bit)]
- Browser [Firefox 77.0.1 (64-bit)]

**Comment by hippee-lee** [comment]
@iivanovgit - I looked at this on windows and macOS in both Chrome and FF and I'm not sure what you mean by 
> a scroll appears on Chrome
and
> overlapping on Firefox

In both borwsers on macOS and windows I'm only seeing a page scrollbar as I would expect because the content of the page is longer than the viewport. 

Can you clarify this a bit and  create an isolated reproduction in stackblitz that demonstrates what you are seeing in your application? Website demos on the website are not a good representation of real world use cases and should not be used for submitting issues. 

We keep starter apps here: https://stackblitz.com/@clr-team

**Comment by iivanovgit** [comment]
https://stackblitz.com/edit/clarity-v3-light-theme-nw42ve?file=src/app/app.component.html

On Chrome: Initially the **Michael Scott (Regional Manager) tree node** is expanded. When collapsing it, the scroll appears on its child node. 

The same situation in Firefox: instead of scroll there is overlapping of child nodes on top of the remaining page content.

**Comment by dexfab** [comment]
Any chance this bug gets prioritized? We're seeing this in our production app too.
