### ISSUE TITLE
Implement single-selection for datagrid

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#475]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

We need to allow datagrids that are selectable but only allow one selection at a time.

### Actual behavior

Currently the only options are 1. not selectable, or 2. multi-selection. There's no way to enforce single-selection.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** All

* **OS and version:** All

* **Browser:** All

**Comment by youdz** [comment]
Just to link the issues, this is a fork for part of the discussion on #17.

Single-selection should simply be solved by using radio buttons instead of checkboxes in the Datagrid.

**Comment by chunghha** [comment]
With 0.8.7, I have "clr-dg-action-overflow" on this datagrid. I selected 2nd row as the checkbox on, then clicked the action-overflow on the 1st row.
![image](https://cloud.githubusercontent.com/assets/24458075/23036918/2334efbe-f44a-11e6-9ce6-04bc00245fcd.png)

Per the pdf on #17, I assume that intention of the action overflow is to attach actions for single row selected. (Please correct me if I am wrong.) So for the above case, either of these two should be happened, ( but not sure which makes more sense).

1. datagrid changes checkbox selection to the 1st row per the action-overflow clicked.
2. datagrid disables the action-overflow on the other rows not checked on.

Because I think this issue is also considered as "radio" behavior of single row selection, I put my comment here instead of opening new issue.

**Comment by jeeyun** [comment]
Hi @chunghha thanks for your comment. We initially considered implementing option 1 from what you have written. However, from the UX point of view, the action overflow is kind of like a right-click on the row and not linked to the current selection. Consider this scenario: you are selecting items that match your criteria, and then you want to do a quick action on a given row before continuing to select items. You don't want the clicking of the overflow to unselect all the other rows. 

The radio behavior implementation mentioned in this issue is in review right now so feel free to subscribe to it for updates: #507
