### ISSUE TITLE
Implement selection of whole row when no clickable items in the row in datagrid

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#476]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Need to evaluate if this is something we need to provide as a built-in option. There's no technical constraint even in the current version (see plunkr). However this pattern should never be used if your datagrid's row contains clickable cells. Need more input from UX side.

### Reproduction of behavior

https://plnkr.co/edit/Cwp2irAbmozAdivFelwg?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** All

* **OS and version:** All

* **Browser:** All

**Comment by youdz** [comment]
Just to link the issues, this is a fork for part of the discussion on #17.

**Comment by mathisscott** [comment]
@youdz and @jeeyun : is this something we're still looking to implement?

**Comment by youdz** [comment]
Still open to implementing it, just waiting to see if people really need/use it.
So I'd say not exactly backlog, just open possibility.

**Comment by halachliyskid** [comment]
Yes, this is still a required behavior.
I acknowledge the the potential UX issue here (if something in the row is clickable), but we should also note that this is an issue generally concerning touch interfaces.
The app developer/designer should have the possibility to use this functionality, and should be responsible to use it in a way that does not degrade the overall UX. In many cases this would bring much more UX value than the harm it may potentially do. 
If I have a datagrid with no clickable elements, and selecting a row drives a details panel, then it would be plain awkward to have to change selection using a small (36x36 or 48x48, etc) click target in the beginning of the row, rather than being able to aim at the whole row. (not to mention that such unnecessary click targets/radio buttons would eat up real-estate in the most prominent and important part of the datagrid)

**Comment by mathisscott** [comment]
@halachliyskid 
Thanks for adding use case details on this item. It will help us to evaluate the feature and help our UX team when they make their recommendation.

**Comment by cgarveyie** [comment]
There  is already an option for a single clickable row (albeit using radio buttons). I am unclear as to the value these radio buttons provide other than that of a visual cue to the educated user that the rows are single select.
I myself was surprised that it wasn't possible to click select a row, especially when there is a hover effect.
So.. +1 for row select from me :)

**Comment by mathisscott** [comment]
this should be indicated by a cursor on the row.

**Comment by mathisscott** [comment]
Plunkr is presently experiencing some issues with unpkg. Here is the code behind the workaround @jeeyun mentioned:

```
<clr-main-container>
    <div class="content-container">
      <div class="content-area">
        <clr-datagrid>
            <clr-dg-column>User ID</clr-dg-column>
            <clr-dg-column>First name</clr-dg-column>
            <clr-dg-column>Last name</clr-dg-column>
        
            <clr-dg-row *ngFor="let user of users" (click)="selected = (selected === user ? null : user)" [clrDgSelected]="selected == user">
                <clr-dg-cell>{{user.id}}</clr-dg-cell>
                <clr-dg-cell>{{user.firstname}}</clr-dg-cell>
                <clr-dg-cell>{{user.lastname}}</clr-dg-cell>
            </clr-dg-row>
        
            <clr-dg-footer>{{users.length}} users</clr-dg-footer>
        </clr-datagrid>
        
        <h4 *ngIf="selected">Currently selected: {{selected.firstname}} {{selected.lastname}}</h4>
      </div>
    </div>
</clr-main-container>
```
...note the click action on the datagrid row.

**Comment by mathisscott** [comment]
In order to prep for contributions, we need to know which aria-roles/attributes we want to use and name of options...

**Comment by mathisscott** [comment]
@jeeyun 
Could you fix the plunkr on this issue?
