### ISSUE TITLE
Date-picker keyboard navigation is broken when NVDA is on and in Browse Mode

### ISSUE THREAD

**Issue by itaneva** [vmware/clarity#4761]
1. Start NVDA Screen reader in Browse mode
2. Try to navigate the calendar using the arrow keys
- Left/Right do not function properly and screen reader reads not relevant text
- Up/Down can be used to navigate left or right instead of up/down.

This can be seen in the examples in the clarity documentations page with NVDA screen reader turned on: https://clarity.design/documentation/datepicker

Simple adjustment of element roles might fix the issue.

**Comment by Jinnie** [comment]
@chlane do we target this and are there any known related issues about the datepicker?
Thanks

**Comment by chlane** [comment]
Hi @itaneva, It appears to be working correctly with the browsers we recommend for using Clarity.  I'm not sure what browser you were using with NVDA, but for Clarity we recommend using Firefox/NVDA or Safari/VoiceOver. 

This is documented at [vmware-clarity-design-system-vpat-2.2.pdf](https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/product/vpat/vmware-clarity-design-system-vpat-2.2.pdf) and pasted below.

```
Clarity Design System is best experienced on:
• Safari and VoiceOver running on the macOS operating system
• Firefox and NVDA running on the Windows operating system

```
I recommend adding this information in a prominent location when the new website is created.

Regarding the expected behavior.  When using either of of these combinations you should find that dates are accessible with either standard cursor navigation i.e,  up or down arrows with NVDA and  Ctrl + Option + left/right arrow keys for VoiceOver. You can also use table navigation commands with NVDA i.e. Ctrl + Alt + arrow keys.

**Comment by Jinnie** [comment]
Closing based on the comment by Chris above
