### ISSUE TITLE
Accordion inside Stepper Component  inherits the styling and some state from the Stepper

### ISSUE THREAD

**Issue by exequiel09** [vmware/clarity#4821]
## Describe the bug

The Accordion nested in the Stepper component inherits the numbering, opened state styling even if the Accordion is closed and the arrow indicator for the Accordion is hidden.

![Screen Shot 2020-07-27 at 6 41 01 PM](https://user-images.githubusercontent.com/1289472/88533340-bb756380-d038-11ea-9adf-60d7f6675c19.png)

## How to reproduce

Head to the reproduction stackblitz link and you'll immediately see the bug described above.

https://stackblitz.com/edit/angular-ivy-xsfa3q

## Expected behavior

Nested Accordion component  shouldn't inherit the state of the Stepper component, the numbering and it should display the arrow indicator

## Versions

**App**

- Angular: 9+
- Node: 12.18.1
- Clarity: 3.1.5

**Device:**

- Type: MacBook
- OS: macOS
- Browser Chrome, Safari, Firefox, Edge

**Comment by gnomeontherun** [comment]
We intentionally haven't supported nesting accordions (a stepper is a specialized accordion), as it creates usability and accessibility considerations. See https://github.com/vmware/clarity/issues/3543 and I'll close this as a duplicate.

I'm also not opposed to some styling updates as a contribution that can address this case, but its not something we intended to directly support. Likely the issue is to solve the specificity of some CSS rules, but I suspect there might also be other behavioral questions.

**Comment by exequiel09** [comment]
I managed to solved it via custom CSS rules. I'll close this since this is a duplicated. Thanks.
