### ISSUE TITLE
[NG] Datagrid: selection behavior on state change

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#484]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

What should be the behavior of the current selection when the state of the datagrid changes in any way? State change includes page change, filters change, data refresh from the server, ...
Once UX settles on the most natural behavior for the user, we can start implementing it.
A few use cases to consider, but **please note that this list is absolutely not exhaustive!**
- User moves to a different page. Most natural behavior here is that the items selected in the previous page stay selected.
- User stays on the same page, but adds a filter. Already selected items might be filtered out. Do they stay selected? I believe this would be very unexpected to the user.
- User selects an item, then moves to the next page, _then_ modifies a filter. The selected item from the previous page is not visible on the screen, the user doesn't know if it has been filtered out or not. Does the item stay selected?
- User selects items and moves to different pages, but the datagrid refreshes its data from the server (either automatically through a "heartbeat" or based on some user action), deleting and adding new items all over the datagrid. What should become of the current selection? Especially items that completely disappeared from the dataset?

### Actual behavior

Currently, since the behavior hasn't been decided on, we've literally had [a TODO in the code](https://github.com/vmware/clarity/blob/master/src/clarity-angular/datagrid/providers/selection.ts#L20) since v1 of the datagrid. I can't believe this issue hasn't been posted on GitHub yet. We simply erase the whole selection whenever anything changes. This has been raised as an issue for apps that need to preserve the selection across pages.

### Reproduction of behavior

See the current behavior on the live "full demo" example in our documentation: https://vmware.github.io/clarity/documentation/datagrid

### Environment details

* **Angular version:** 2.X

* **Clarity version:** 0.8.X

* **Browser:** all

**Comment by reddolan** [comment]
1. If a user makes a row selection and navigates to another page (pagination), the selection should persist. There should also be a visible system status of the count of selections made, incrementing as a user makes more.
2. If a user selects something and filters against the data, the selection is lost. The complexity of designing to and handling those edge cases seems overly unnecessary.
3. User selects an item, then moves to the next page, then modifies a (an existing) filter. The selection is lost, only modified filtering is done
4. If a user selects and there is a data refresh (heartbeat), if we can, we should persist the selection (assuming it is still available)
5. That said, if it is possible, I could see persisting the selection after filtering if it is still available. We could possibly even go further to notify that selections not in the filtering were lost. Both of these things seem to complicate things unnecessarily.

Say we do 1-4 above and wait to see what happens. If we *then* get a lot of feedback about people needing the 5th item, we could then look to implement it.

or something similar to #5, some message saying that some selections were lost in the refresh

**Comment by reddolan** [comment]
@youdz you had mentioned two different implementations for the count indicator: icon & number, and text & number. Here are screens for each. 
- I think we can go with the "icon & number" version
- If we go with "text & number", it would need to have override hooks built into it for internationalization
- Count indicator would show after one row selection, hide after all rows have been deselected

![row-selection](https://cloud.githubusercontent.com/assets/1858226/23764419/10e07890-04c3-11e7-81f3-32baf3c7f174.png)

Just realized Count Indicator sounds like a vampire name...

**Comment by bobsheehan1** [comment]
Hi. This is a critical feature for our VMWare project. Rddolan's 1-4 would be  great. We need to be able to paginate across 1000-2000 items (VMs) and retain selected items. Would like to allow sorting without losing selection, but I suppose if there s a filter change we would be ok losing selection. We need this in the next few weeks. Any ETA or predicted version for this fix ? Also is there a recommended hack for us to get around this issue until then ? Otherwise we may have to bail on datagrid :(

**Comment by Jinnie** [comment]
I have a workaround for preserving selection:
https://plnkr.co/edit/C9SzUi?p=preview
In its current implementation it will not work well with filters and sorting. But you can build on it, if this is hard requirement, and you don't get satisfactory ETA.
Note that I am not part of the core Clarity team, so consider this as a peer hint, not as a Clarity "recommended hack" 😃

**Comment by halachliyskid** [comment]
Hi @reddolan @youdz 

Shouldn't we have a broader discussion before stating that you are going ahead and implementing something right now and only changing it afterwards if there is "a lot" of bad feedback? 

I could give you many examples with datagrids containing thousands of items. The user's only help in these situations is the ability to filter to find the items they need (otherwise they'd have to page through literally hundreds of pages). Losing the selection would basically be a stopper for these workflows. Most probably whenever a grid has more than 2 pages, people would tend to use filtering instead of paging...
Since you are planning to have an indicator in the footer, is preserving the selection of "not visible" items really an issue at all?

**Comment by reddolan** [comment]
@halachliyskid Users have an idea of what they are looking for in thousands of rows in dataset, and filtering/sorting to start off will help make the data more manageable. Selection and filtering both have unique goals. These actions aren’t necessarily tied to one another at the same time. Users would be doing themselves a favor by filtering the data down, and *then* making selections. Here are a couple things to think about:

First complexity: A user wanting to select a bunch of items and then filter would be a confusing interaction. Are they expecting data to be filtered against just their selection or across the entire dataset? I could see both use cases arising. This means that we would need to figure out how those independent experiences are handled, both in datagrid design and experience. 

Second complexity: If a user were to make selections, then filter, and all selections show up after filtering, then no problem. However, what happens if one or many selections are not part of that filter criteria? We need to notify the user of those instances. If it is only a few, not a huge issue. But if several are lost? The user will specifically want to know which ones are lost?

We made a conscious decision on how to handle selections being made before filtering. This decision was to reduce the complexity in design and development work needed for this. Also, the need to select and then filter is more of an edge case than the majority of cases.

I understand your comment on “changing it afterwards if there is 'a lot' of bad feedback”. That is why I said previously, if we get a lot of feedback about people needing it, then we can look into it. The feedback will help us understand if this isn’t an edge case and is a higher use case than we had anticipated. In the meantime, users are still able to use the datagrid with filter and selection without poor experience.

**Comment by Jinnie** [comment]
Hi guys, 

It's great that you decided to have a public discussion on this, based on user feedback.
I am an engineer, not a UX expert (although everyone considers himself an expert in football, politics and UX nowadays 😈).
So I will present you with my point of view, which is the engineering and dev point of view.
The data of a grid should be considered as something monolithic, something basic and predictable.
As it can be large, we can't see all the data at once and we might want to make it easier to find items in it. Our view of the data is limited. All sorting, filtering, pagination, are operations on the view. They don't change the data itself.
Selection on the other hand is operation on the data. I select many items to perform a single operation on them. I may apply one or more view operations, simultaneously or subsequently, to easily find/navigate to my items, but when I select an item, my expectation is to be doing this on the data layer, not on the view layer.
Losing the selection comes as a surprise to me.

That's my 2 bitcoins 😄

**Comment by halachliyskid** [comment]
@Jinnie thanks for the comments - I absolutely support that.

@reddolan 
You're saying that sorting and filtering are two very distinct things - then why are we making a hard connection between them (using filter removes selection)? If they are unique operations, then they have to be able to work at the same time. I do not see this as an edge case - I'd ask the question: "Why is someone filtering?". 
Is it because they just want to read the info from a datagrid? I wouldn't agree with this. 
Datagrids are typically used by our users to either navigate to a single object, or perform an action on a single object, or perform an action on multiple objects at the same time.
Multiple selection using checkboxes (our case) is aimed exactly at allowing to easily perform actions on multiple objects.
The most common filter criteria I can think of is "Name". It's obviously unique and if I have to search for 2 objects using the filter (instead of going manually though 10 pages), I'll never be able to perform the action on these 2 objects at the same time.
I do not think this qualifies as an edge case.

First complexity: I don't recall a UI which behaves in the way you describe. Is there user research data suggesting that if people need to use selection + filtering, they get confused thinking that filtering only works on the selected items?

Second complexity: In your design, there is a selection counter in the datagrid footer. Couldn't it be used to handle this?

I fear that by reducing the complexity on the design and development part, we are increasing the complexity for the user and in fact breaking some workflows.

**Comment by Jinnie** [comment]
There is one case, though, that I am uncertain about.
Performing "Select All" on filtered (and possibly paged) content.

@reddolan, @halachliyskid, what are your thoughts about that?

**Comment by yenmade** [comment]
@Jinnie, I agree with you that datasets can be large and our view of the data is limited. That’s why sorting and filtering help users narrow down what they are looking for and interact with that subset of the larger view. We spent a lot of time discussing this topic and made a conscious decision to not persist the selection after operations such as sorting and filtering have been applied, post-selection. The decision to do this is largely based on usability problems that arise in these cases, and not around the debate that this can satisfy edge (or possibly a bigger set of) use cases.

There’s no question that filtering will narrow down a single object, or multiple objects that a user can perform an action on at the same time; that is the purpose of batch selection. However, it is problematic to allow the user to perform actions that affect other pages that the user can’t see and has to rely on memory to recall what was selected – this is an anti-pattern. It is important that the user is aware of the consequences of their actions and has the ability to view and undo selections that they have made. Otherwise they will need to start over and redo everything, especially if the action is destructive. In this scenario, the selection count loses meaning and becomes guesswork. For example, if the filtered view is the only visible set of data and nothing is selected but my count displays 40 selected items, again I may not remember or be able to verify what it is that I’m performing an action against. 

While I see the possibility that a user may rely on filter and re-filtering to locate what they’re looking for to perform a batch action, I don’t think that this case justifies the complexity in the experience and the additional cognitive load required to figure out what the count means with no easy way of undoing the selection(s). The risk is minimized by pushing the user to filter the data down first, then make selections and to perform actions against filtered data, versus a lot of upfront work that can result in uncertainty. The compromise is that the user will have to do this in smaller, manageable chunks rather than large, batch actions, but I think the minimized risk is worth it.

Thanks everyone for your thoughts on this, all is greatly appreciated. We’re going to move forward with Red’s original recommendation so that we can release this fix soon, and continue to monitor feedback around this feature.

**Comment by Jinnie** [comment]
@yenmade, thanks for the detailed answer.
I understand your point and respect your research and decision.
Popular services like gmail and yahoo mail preserve selections on filtering or paging. On the other hand MS OWA is not preserving selection.
There are different approaches, different solutions, and you've made your choice.
Also, if a user really needs it, there are ways to achieve selection preservation with some additional code outside the component itself.

**Comment by pshterev** [comment]
What @halachliyskid described is a very important case and also a pretty common one. Selecting more than one item with very different names(so that you can't have a common filter for them) among thousands is practically impossible when you lose the selection in case item is filtered out, so I can see that issue as a must fix. I would also vote for including a selected items indicator in the grid footer which will absolutely remove any confusion that some clients might have when they have filter out the selected items. You may also include a very tiny button for example "X" next to the selected items which will clear the selection.

Another aspect that is pretty important for me is restoring the grid selection when new data is set on the grid but the items are practically the same. To implement this and also the suggestion above you may need to have a reliable way for comparing the items from the grid's dataprovider. Since it is actually a client's logic to compare the items then you might solve this issue by providing an option for the clients to provide callback function that should be used for comparison. For example the function might have the following signature:
function areEqual(first: any, second: any): boolean;

Then all you have to do is check if the function is provided and if that's the case then use it to check each of the objects in the selected array for equality against the new data array. In case equality is fact then you just replace the "old" object in the selected array with the corresponding object from the new data array and I believe this should be enough for this feature.

**Comment by youdz** [comment]
Closed by #632.

**Comment by luis-cortina** [comment]
Looking at this thread it tells me that filtering will remove my current selection.

My use case is that I have a property in my object that I want to bind the selection to using the approach described in the docs:

`<clr-dg-row *clrDgItems="let item of items" [clrDgItem]="item" [(clrDgSelected)]="item.selected">
    <-- ... -->
</clr-dg-row>`

Now, I think filtering should not affect me in this case since the model would persist the selection and not the datagrid itself. But it still removed the selection.

 Is there anyway this can be achieved?

Luis

**Comment by matonev** [comment]
Guys,
I see this closed, but this is a blocker for us.
Here is our use-case:
1. We I have a bunch of items in a grid (300)
2. When the grid is loaded there are preselected items. Let's say 10.
3. Then I want to select a specific item and I know it's name, but I don't know on which page it is.
4. Now I can filter, but I will lost the selection or I can go through the pages and search for the item.
This is very inconvenient.

My expectation is that the selection is persisted. I would expect that after removing the filter I would have my items selected again.

**Comment by reddolan** [comment]
For those following this issue, we have opened a [new issue](https://github.com/vmware/clarity/issues/2342) with the intent of solving this scenario. Please subscribe to the new issue for updates
