### ISSUE TITLE
[Treeview]: ERROR RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bencheick** [vmware/clarity#4850]
## Describe the bug

I am trying to display a huge data in the treeview with "lazy loading recursive tree" mode. When we display the treeview, by expanding all of nodes. The result seems good. But when we look at the console of browser,  an error message "ERROR RangeError: Maximum call stack size exceeded" is displayed.
Each time we refresh the browser, the error messge is still there.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-xvhksm?file=src%2Fapp%2Fapp.component.html

1.  Go to the following stackblizt https://stackblitz.com/edit/clarity-v4-light-theme-xvhksm?file=src%2Fapp%2Fapp.component.html
2. Go to the console of the browers
3.  See error message ERROR RangeError: Maximum call stack size exceeded

## Expected behavior

I don't understand why this error message appears. I think something is broken when the treeview manipulate the data, among 600 nodes. I would like to have no message errors.  I don't know exactly the root cause of this errors message. 
Could you help me please ?

## Versions

**App**

- Angular: [10]
- Node: [ 8.10.0]
- Clarity: [4.0.0]

**Device:**

- Type: [e.g. MacBook]
- OS: [Windows 10]
- Browser [chrome]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Browsers have a limit for how many instructions they'll process in a stack, which is what the error is reporting. Because you are automatically expanding every node, the stack of instructions required to process all of the nodes grows beyond what the browser allows. When it hits this limit, its stops processing, so you aren't getting the full tree rendered.

I believe the fix is to not automatically expand all of the nodes. That adds a lot of processing to resync the tree state and doing it 300x is exceeding limits. You should be able to expand a few nodes as necessary, but traversing the whole tree and updating properties on each node has the side effect of many model syncs.

**Comment by Jinnie** [comment]
Тhis has been fixed with a recent tree-view fix https://github.com/vmware/clarity/pull/5426
I updated the stackblitz to 4.0.11 and the call stack error is not thrown anymore.
