### ISSUE TITLE
Incorrect role is read by the screen readers for the tooltips

### ISSUE THREAD

**Issue by kalpeshhpatel** [vmware/clarity#4984]
## Describe the accessibility issue

The screen reader reads the `role=button` for the tooltip which is incorrect.

## How to reproduce

1.   Go to 'https://clarity.design/documentation/tooltips'
2.  Open the NVDA screen reader
4.  Focus the tooltip icon elements of any `clr-tooltip` demo component.
3.  Observe that screen reader reads the role as `button` for the tooltip info icon.

Attaching the screenshot for the reference:

![Screen Shot 2020-08-31 at 3 42 33 PM](https://user-images.githubusercontent.com/5223493/91716492-6daac880-ebad-11ea-9f91-4df67b326d5a.png)

## Versions

**App**

- Angular: 8.x
- Node: 10.x
- Clarity: 2.x, 3.x and 4.x

**Comment by Jinnie** [comment]
The tooltip pattern is still work-in-progress on the W3C website:
https://www.w3.org/TR/wai-aria-practices-1.1/#tooltip
They are tracking the work on it in their #127 issue,
https://github.com/w3c/aria-practices/issues/127#issuecomment-363750096
where they point the users at an external example:
https://inclusive-components.design/tooltips-toggletips/
Where this code can be observed:
```
<button class="notifications" aria-labelledby="notifications-label">  
  <svg><use xlink:href="#notifications-icon"></use></svg>
</button>  
<div role="tooltip" id="notifications-label">Notifications</div>  
```
From it, and the discussion in issue 127, it's obvious that the tooltip anchor and target is usually a button.
That's what I found.

@chlane can we have your comment too, please?

**Comment by chlane** [comment]
Our stance on tooltips is documented at https://confluence.eng.vmware.com/display/A11Y/ARIA+Tooltips and pasted below.

- A tooltip is a popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it. It typically appears after a small delay and disappears when Escape is pressed or on mouse out. See https://www.w3.org/TR/wai-aria-practices-1.1/#tooltip.
- Per the WCAG 2.1 Success Criterion 1.4.13 Content on Hover or Focus most common tooltip implementations are not considered to be accessible because they disappear when hovered over.
- Clarity is also facing this issue with its tooltips. See https://github.com/vmware/clarity/issues/3880.
- Unfortunately there is no authoritative tooltip example from the ARIA working group at this time.  The design pattern is a work in progress that does not yet have task force consensus. Progress and discussions are captured in issue 128. Work to develop a tooltip example is tracked by issue 127.
- This http://whatsock.com/tsg/Coding%20Arena/Tooltips/Tooltip%20(Internal%20Content)/demo.htm# appears to be accessible, allowing the tooltip to be hovered over and not disappear.
- Until https://github.com/vmware/clarity/issues/3880 is resolved we recommend using Clarity signpost components instead of tooltips or use  http://whatsock.com/tsg/Coding%20Arena/Tooltips/Tooltip%20(Internal%20Content)/demo.htm#

**Comment by Jinnie** [comment]
Based on researches provided by both Chris and me, I'm closing this, as all seen examples feature interactive element (button or link) as a target, the overall best practice is not defined from W3C yet, and we're tracking the rest in #3880 
If you want to add more detail to it, please be welcome to update #3880, so we can keep it in mind when working on it.
Thanks for the report.
