### ISSUE TITLE
[clr-tree] Problem with selecting tree nodes in drag and drop enabled tree.

### ISSUE THREAD

**Issue by mibryamov** [vmware/clarity#4990]
## Describe the bug

Selection of nodes in a tree with drag and drop enabled fails sometime. The issue is observed on MacOs and Windows 10 with Chrome browser. Sometimes it requires 3-4 clicks over the node to select it. On FF it works fine.

## How to reproduce

1.  Go to [clarity-draggable-tree-selection](https://stackblitz.com/edit/clarity-draggable-tree-selection?) with Chrome.
2.  Expand the nodes in `Draggable tree - selection problem` tree and start selecting. See that sometimes the clicked tree node gets focused, but is not selected - its background color is not changed to light-blue and the node's click handler is not invoked. To demonstrate the issue better i added logs to the console for every document click and tree node click events, see when the tree node is not selected its clicked message is not logged.
3.  Now do the same on the second tree - `Non-draggable tree - no selection problem` - and see there is not a problem with the tree nodes selection no matter how fast you change the selection.

## Expected behavior

The tree nodes selection should work as expected even on drag and drop enabled tree - similar to how it works on FF, or like when DnD is not enabled.

## Versions

**App**

- Angular: [9.1.9]
- Clarity: [3.1.3]
We observed the same issue also with Clarity 2.x.x, so i dont think it is a regression.

**Device:**

- Type: [MacBook, PC]
- OS: [macOS Mojave, WIndows 10]
- Browser [Chrome]
- Version [70+]

## Additional notes

Captured the behavior on an animated gif:

![Screen Recording 2020-09-01 at 11 30 37](https://user-images.githubusercontent.com/18374949/91842777-4c091a00-ec5d-11ea-9b1a-f3bb5dcb0689.gif)

**Comment by mibryamov** [comment]
Ping... Any updates on this issue?

**Comment by Jinnie** [comment]
Micro-drags that happen during some of the clicks are causing the observed behavior.
In Chrome drag events are preventing mouseup and click events by design, while in Firefox they are emitted regardless of the drag. Which is the correct behavior I cannot judge. Issues can be found on the Mozilla and Chrome issue trackers requesting either one or the other.
The W3C specs are only defining the events within the drag/drop cycle, but not the surrounding mouse events.
https://www.w3.org/html/wg/spec/dnd.html#dndevents
The W3C section for mouseup (https://www.w3.org/TR/uievents/#event-type-mouseup) has this note:
> In some implementation environments, such as a browser, a mouseup event can be dispatched even if the pointing device has left the boundary of the user agent, e.g., if the user began a drag operation with a mouse button pressed.

It implies that drag operations should be expected to prevent mouseup (and possibly click), but warns that implementations are variable.

As a conclusion, a stable event you can use if you want to force the selection is "mousedown". It happens before the drag started and gets emitted in all cases. Your example can be updated to use mousedown successfully, hope this will work for your real use case.
