### ISSUE TITLE
Tabs overflow menu do not become hidden after selecting an item from it

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#5006]
## Describe the bug

Tabs overflow menu do not become hidden after selecting aт item from it.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-tabs-overflow-fix

1.  Click on '...'
2.  Select an item from overflow menu, e.g. Settings
3.  See error

## Expected behavior

Tabs overflow menu should become hidden after selecting an item from it.

## Versions

**App**

- Angular: 9.1.0
- Node: 10.13.0
- Clarity: 3.1.0

**Device:**

- Type: MacBook
- OS: MacOS
- Browser: Chrome
- Version: Latest

## Additional Notes

On old versions of Clarity the menu was hidden in this case:
https://vmware.github.io/clarity/documentation/v0.13/tabs

**Comment by Jinnie** [comment]
The tabs overflow pattern is very disputable from accessibility point of view and our recommendation is to try to avoid it if possible and use vertical tabs if you need more options than your interface will be able to display at once. When the tabs overflow was created, the vertical tabs were not yet implemented.
There is no such pattern in the W3C recommendations and examples and it's been a real challenge to make it cover as much as possible of the needs of all accessibility groups. Unlike dropdown menus, which are designed to execute immediate actions, the tab labels represent the current page context. If we hide them right away, after selecting an option, this may affect the experience of accessibility users with short term memory problems, who need to have an indicator of the current context visible.
The 0.13 example you are referring to, has nice behavior for the ordinary sighted mouse user, but is suffering from heavy accessibility problems.

Given the accessibility implications and lack of W3C ARIA recommendations, any implementation will remain controversial to some extent. So, though it may look like a regression from the perspective of the mouse user, this is a compromise we've decided to accept in favor of the a11y scenarios.

@chlane please, as accessibility expert, correct me if I am wrong and you think this should be addressed.

**Comment by Jinnie** [comment]
This is the master issue for the problem:
https://github.com/vmware/clarity/issues/3514
And these are the related PRs:
https://github.com/vmware/clarity/pull/3609
https://github.com/vmware/clarity/pull/3700
https://github.com/vmware/clarity/pull/4323
The discussion with the A11Y team we've had have been internal, and most of the specific issues were on an internal system they use for communicating with both us and product teams, which are not managed as open source projects.
That's why I requested confirmation from Chris in my previous comment.

**Comment by GaryHyland** [comment]
I had also noticed this with 2.4.2 and consider it a nuisance regression to my end users, who use this on PC, tablet and mobile. This was a nice way for them to be able to access less used tabs that would otherwise overflow the page. I would set tabs to overflow depending on screen width. Vertical tabs are not a good alternate for me here as there will take up horizontal space which is at a premium.
I get your point about not knowing what tab was selected from the dropdown though. To me a great alternative would be to make the ellipse (overflow menu) button somehow stand out as having options ie. maybe dropdown arrow, but change the text to the selected tab from the menu (have ellipse or some other text if none selected yet). That way people could have a visual, and readable? prompt of the active tab and what option is showing? Would just have to ensure space was allowed to show the text.
Otherwise I fear I may be trying to see whether there is a way to override and make the overflow tab list hide again afterwards.
Even if you made it optional? Regressing functionality is not ideal and should at very least be noted in release notes.

**Comment by chlane** [comment]
I concur with @Jinnie 's comment.

**Comment by Jinnie** [comment]
Thanks for the detailed feedback.
I'll reopen the issue while we'll be reiterating over the details with the accessibility team once again in the next week.

The talks are about the close on click functionality, not about discarding the overflow completely. We do _recommend_ using the alternatives, because they have better accessibility, but we're not removing it, so you can keep using it.

**Comment by Jinnie** [comment]
After discussion with the accessibility team, we do not intend changing the current close on click behavior.

**Comment by GaryHyland-SierraAcuity** [comment]
OK. That means most of my users will need 2 clicks then. One to select the tab from the menu and one to click somewhere to get the dropdown menu to hide which obscures part of the screen underneath when displayed.
