### ISSUE TITLE
[Icon Request] Payment Icons

### ISSUE THREAD

**Issue by chunghha** [vmware/clarity#501]
Please provide icons in this link including one for 'Electronic Check' to clarity-icons.
http://fontawesome.io/icons/#payment

Many thanks for considering my request.

**Comment by lil-kim** [comment]
There may be legal problems with distributing other companies’ corporate branding on the Clarity site. This issue will be on hold until we do some research and have approval from our legal department.

**Comment by chunghha** [comment]
@lil-kim thanks for replying. Understood. It's a "nice to have" request so I can wait for any decision will be made from your team. :)

**Comment by jaffoneh** [comment]
Anything that does not include a logo (or a trademark) should be added. Anything that involves a trademark, we'll default to not adding it for now.

**Comment by lil-kim** [comment]
@chunghha 
Apologies for this late response. With the exception of "credit card", all the icons in the fontawesome link you provided contain a branded company logo. Because of legal issues in copying/distributing other companies' branding, we won't be able to complete your request. 

If you can use the generic "credit card" icon, it can be found on the Clarity site: https://vmware.github.io/clarity/documentation/iconography

You also requested an icon for "eCheck". Did you still need this icon? As far as I can tell, this one doesn't have a trademarked logo and I could add it to the next batch of icons. Please let me know. 
Thank you!

**Comment by chunghha** [comment]
@lil-kim yes please for "eCheck". Thanks for offering.
