### ISSUE TITLE
Removing the possibility to `trackBy` ClrDatagrid items with `ngFor`

### ISSUE THREAD

**Issue by bbogdanov** [vmware/clarity#5044]
## Summary

`ngFor` along with `trackBy` inside `ClrDatagrid` are used largely by our clients. Sometimes, but not specifically, datagrid column headers are generated using `ngFor`. For more performance optimization people seems to use `trackBy` inside the columns header loop and based on this our `ClrDatagridItemsTrackBy` sets the `trackBy` used in the column header loop as the primary `trackBy` function for the datagrid items(data) even in case the user doesn't intend to change the primary `trackBy`. 

Sometimes there can be more than one `ngForTrackBy` used in the datagrid and currently with our directive we provide a `Many -> One` relation where the last one provided will be assigned to track the datagrid items. 

Even that we do not see a benefit, in any case, to use more than one `trackBy` inside the datagrid, we receive reports regarding multiple `trackBy` usage in the datagrid and we would like to remove the misunderstanding and guide the people using our ClrDatagrid in the best possible way. One way can be to force datagrid items generation only from `*clrDgItems="....`.

## Use case

Sometimes, but not specifically, datagrid column headers are generated using `ngFor`. For more performance optimization people seems to use `trackBy` inside the columns header loop.

## Examples

#3936

## Workarounds

There is a workaround and it is to guide people not using more than one `trackBy` inside the datagrid. The issue with this is that we will still receive reports about these cases.

**Comment by gnomeontherun** [comment]
This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
