### ISSUE TITLE
Expandable datagrid: support expand all / collapse all rows function

### ISSUE THREAD

**Issue by abbey24** [vmware/clarity#5074]
We received requests from customer and GSS folks of being able to expand all / collapse all rows in expandable datagrid. In several places, people want to quickly scan through the whole datagrid, without having to click the rows one by one to expand them. For example, when GSS are troubleshooting, they would like to scan all rows quickly to find clues. 
We have select all / deselect all in datagrid, this can be a similar capability.

**Comment by bbogdanov** [comment]
Hi @abbey24! 

We had similar requests before and there are situations when user experience of expanding all rows can become extremely unpleasant. 

Having in mind that the platform you develop for is browser and JavaScript is single-threaded expanding all rows at once will require more power from the CPU and GPU than usual. If the components you use in the expanding rows are many this will require more time for the browser to render all elements and the situation can get into minutes of waiting to render all elements in all expanding rows. Quick example https://stackblitz.com/edit/clarity-scrollbar-expandall?file=src/app/app.component.html

Also what the team will encourage you is to switch using [Detail pane](https://clarity.design/documentation/datagrid/detail-pane) instead of expanding rows. We are about to drop support of expanding rows in near future.

**Comment by bbogdanov** [comment]
Hi @abbey24 

The expandable rows are tricky from a11y perspective and a11y is one of the new main targets of`Clarity`. 

Having layers of expanding is a trigger to think in a different direction and rethink your case.

Hope the example above solves your question of `how to do a all at once expanding`. Just be careful how many data/html elements you render when expanding the rows.
