### ISSUE TITLE
Opening clrModal through checkbox change results in ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by rogerfar** [vmware/clarity#5077]
## Describe the bug

When you try to open a clrModalOpen through a `[click]` or `[change]` event on a regular checkbox or clrCheckbox it will throw an ExpressionChangedAfterItHasBeenCheckedError error.

## How to reproduce

https://clarity-v3-light-theme-gflxbg.stackblitz.io/

## Versions

**App**

- Angular: 9.1
- Clarity: 3.1.5

**Comment by gnomeontherun** [comment]
This appears to be a problem with Angular specifically, because the exception is about ng-touched and that is part of Angular forms. Essentially this kind of error occurs when something changes unexpectedly, and probably doesn't appear if you run it in prod mode. Either way, you can read more about this kind of error on this issue: https://github.com/angular/angular/issues/22426. NgModel has an internal behavior that can cause odd behaviors at times because of change detection.

Here is the fix suggestion for you to workaround if necessary: https://stackblitz.com/edit/clarity-v3-light-theme-fhkiov?file=src%2Fapp%2Fapp.component.ts

I don't know what the use case is to open a modal from selecting a checkbox, it seems like an unexpected side effect, but this solution would allow you to do this.

Closing as not Clarity specific.
