### ISSUE TITLE
Show columns popup doesn't keep tab focus

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#5097]
## Describe the bug

On a datagrid you can open the Show Columns popup. Focus gets top the [x]. Pressing tab is supposed to get to the column, but with v4 the popup closes. This work with Clarity v2 and v3.

## How to reproduce

https://clarity.design/documentation/datagrid/hide-show

Open show columns and press tab.

## Expected behavior

Focus should be trapped inside the popup.

## Versions

**App**

- Clarity: 4

**Device:**

- Browser [chrome]
- Version [85]

**Comment by mathisscott** [comment]
Looking into this. I've verified that it's a problem with the Clarity Angular focus trap. There's been some change between v3 and now that broke the focus trap for this panel...

**Comment by mathisscott** [comment]
The issue is that there are no elements being set as the `firstFocusableEl` and `lastFocusableEl` in the `clrFocusTrap` directive that is being placed on the hide/show column panel. It is not clear to me how this issue is not being seen in more focus traps.

While I've identified the problem, this issue is a much bigger issue than I can timebox as the support person this week. So I'm adding it to the backlog and will bring it up with the team.

**Comment by amellnik** [comment]
Is there design or similar for how focus traps should work and be used in Clarity?  In addition to this, there's a few other places like this where `clrfocustrap` is being used but doesn't actually trap focus, like the column filter dialog.

**Comment by Jinnie** [comment]
This can be reproduced with any of the smart popovers in the datagrid. If the focus goes out of the close button - popover gets closed. Another side effect is that if the trigger is focused than any key will trigger a toggle. Even a Shift.
