### ISSUE TITLE
Clarity signpost/dropdown  gets triggered inside a form when clicked on any form controls.

### ISSUE THREAD

**Issue by jeevanm18** [vmware/clarity#5205]
## Describe the bug

When we have a  clarity component within the form for ex: we have an sign post and normal input text within the form when we hit enter key on input text field sign post button triggers.This happens with most of the clarity components used within a form .

## How to reproduce

Stackblitz link to reproduce the issue [https://stackblitz.com/edit/clarity-light-theme-v2-xedwjs?file=src%2Fapp%2Fapp.component.html](url)

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v2-xedwjs?file=src%2Fapp%2Fapp.component.html
2.  Click on Empty input field
3.  See that sign post pop up opens
4. Remove the sign post component from html and now try clicking on input field.Now drop down menu gets opened

## Expected behavior

Sign post should be triggered only when we click on the info icon.
Drop down should open only when clicked on it

## Versions

**App**

- Angular: [8]
- Node: [12]
- Clarity: [2]

**Device:**

- Type: [MacBook]
- OS: [iOS,Windows]
- Browser [chrome, [safari,firefox,IE]]

## Additional notes

All the clarity component inside form have this issue

**Comment by coryrylan** [comment]
This is because of the `<form>` element around the inputs and buttons. When using the enter key it will trigger the first button as a submit event. Add type button to all the buttons within the form to prevent them from being triggered as submit types. 

```html
<button type="button"></button>
```

https://stackblitz.com/edit/clarity-light-theme-v2-qb6hwl?file=src%2Fapp%2Fapp.component.html

**Comment by jeevanm18** [comment]
Thanks a lot @cfryanr
