### ISSUE TITLE
Request new icons for VCSA UI installer for vSAN bootstrap

### ISSUE THREAD

**Issue by jazhang** [vmware/clarity#528]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
New icons in VCSA UI installer for vSAN bootstrap

### Actual behavior
Currently there're no usable icons for vSAN bootstrap in VCSA UI installer

### Reproduction of behavior
1. Get a build of VCSA UI installer 2.0 and run the installer;
2. Connect the installer to a host that meet following requirements:
- Get a ESXi host from vSAN patch branch;
- Make sure this host is not managed by a vCenter Server
- Connect the installer 2.0 to this host
- Choose create a new vSAN datastore at select datastore step
- Go to claim disks for vSAN step
- Check icons on this step

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.4

* **OS and version:** Mac/Windows/Linux

* **Browser:** [all]

**Comment by mathisscott** [comment]
Hi @jazhang 

We would be happy to look into this but we would need...

a) a list of the icons you require
b) some visual reference to them (either a screenshot or image file) so that we can understand the use case better.

Once we get that information from you, the Clarity team can prioritize this effort.

Thanks!

**Comment by jaffoneh** [comment]
@jazhang when requesting icons please make sure you provide a list of the icons you'd like to see, an example of their use within your product (so we're able to figure out what the icon is trying to represent), as well as exact naming for it in case it is specific to storage for example.

If you'd prefer to send this over email (if screenshots are not available to the public) that's fine. However, installing vSAN in a datacenter within specific instructions shouldn't and couldn't be a requirement for a designer to get a list of icons.

Once you have the list of icons, please open a **_new issue with that list of icons_** and we'll be happy to take a look and discuss. Closing this issue for now since it doesn't make sense to keep it open in the meantime.

Thanks.

**Comment by jazhang** [comment]
![claimdisksforvsan](https://cloud.githubusercontent.com/assets/4121778/23326997/df2389c8-fb3f-11e6-9861-35f1dc4321af.png)

1. vSAN cache tier
2. vSAN capacity tier
3. Do not claim disk
4. Flash disk
5. HDD disk
6. Normal disk (see row 6 in the attachment)
