### ISSUE TITLE
Datalist inside table cells too small

### ISSUE THREAD

**Issue by duzenko** [vmware/clarity#5291]
## Describe the bug

I'm trying to make use of `clr-datalist-container` inside a table but for some reason it does not fill the cell width

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

```
	<table class="table no-hover">
...
		<tbody class="striped">
			<tr *ngFor="let item of items; let i = index">
				<td>
					<clr-datalist-container class="no-top-margin">
						<input clrDatalistInput [(ngModel)]="item.title"/>
						<datalist>
							<option *ngFor="let option of titleOptions" [value]="option"></option>
						</datalist>
					</clr-datalist-container>
				</td>
```

The data list control takes 10/12 of the cell width

## Expected behavior

I would expect it to fit width on such small containers

## Versions

**App**

![image](https://user-images.githubusercontent.com/1481807/98960270-e367d480-250c-11eb-8ebf-af967d51266e.png)

**Device:**

![image](https://user-images.githubusercontent.com/1481807/98960294-ebc00f80-250c-11eb-9b9c-2c50c9536e0d.png)

## Additional notes

_Add any other notes about the problem here._
![image](https://user-images.githubusercontent.com/1481807/98959764-46a53700-250c-11eb-82fe-025ea572a056.png)

![image](https://user-images.githubusercontent.com/1481807/98960533-36418c00-250d-11eb-8259-1e6e6bc16273.png)

**Comment by Jinnie** [comment]
Our datalist is just a wrapper around the HTML datalist. You should be able to style it the same way as a normal datalist.
Please create a stackblitz reproduction, as requested in the template, if you would like us to be able to provide more detailed guidance.

**Comment by duzenko** [comment]
https://stackblitz.com/edit/clarity-v4-light-theme-rgx621?file=src/app/app.component.html
My problem is the input does not fit the entire yellow box width
I'm not sure how I'm supposed to style the clarity-generated div that has no specific classes on it - please advise

I'm talking about `<div class="clr-control-container clr-col-md-10 clr-col-12" ...`

**Comment by duzenko** [comment]
@Jinnie Do you need anything else here? Should I create another issue about this?

**Comment by Jinnie** [comment]
Thanks for the stackblitz.

The input container is responsible for providing space for a label, for help and validation messages, it also handles responsive layout, etc. So, yes, it will be a challenge to override all this layout functionality. But it's intended for use in linear forms where elements follow each other in designated form space.
In your case, you simply want a datalist inside a space (datagrid) provided and managed by yourself. So you don't really need all the above functionality.
That's why my suggestion is to use a plain html datalist instead and add the "clr-input" class on the input field, to style it as a Clarity component.
