### ISSUE TITLE
Add support for [clrLoading] for Wizard buttons

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5299]
## Summary

Add support for the [clrLoading] directive to `clr-wizard-button` buttons.

## Use case

Would be useful for async finish steps and async validation in between steps.

## Workarounds

Use a `clr-spinner`.

**Comment by bbogdanov** [comment]
This looks like a 2 liner solution. I will need to check several situations before introducing the feature.

**Comment by bbogdanov** [comment]
After taking some time to introduce it, it turns out to be a bigger change than I expected.

We are moving our focus to `@clr/core` development and we are less likely to bring new features to `@clr/angular`. I'll encourage you to proceed with the workaround.

https://stackblitz.com/edit/clarity-wizard-button-loading Leaving this stackblitz example for future reference.
