### ISSUE TITLE
    How do I make Custom Range Input with labels and Percentage  

### ISSUE THREAD

**Issue by riyaz02** [vmware/clarity#5314]
How do I make Custom Range Input with labels, Percentage and Colors..

**Comment by gnomeontherun** [comment]
Hello there, we ask that you use GitHub discussions for questions like this, and also you will likely need to provide a lot more detail about what you are asking about to get meaningful help. I'm going to close this issue since it has very little detail, and we do have a range input provided with documentation with available features at https://clarity.design/documentation/range.
