### ISSUE TITLE
Dark Theme build (clr-ui-dark.css) does not expose CSS custom properties

### ISSUE THREAD

**Issue by maurerke** [vmware/clarity#5365]
## Describe the bug

I dynamically add the @clr/ui/clr-ui.css and @clr/ui/clr-ui-dark.css stylesheets to the application, so the user can switch the theme. This works great and witout any issue. However, I started to use the css variables that clarity exposes to style custom components in order to fit the clarity theme. I also wanted to do this, so the theme switch also works for my custom components out of the box. **Unfortunately it only works for the main theme because the clr-ui-dark.css file does not expose the css variables.** Is there any specific reason for that? It would be so cool, because it would be a really easy way of theme switching.

I couldnt even find the css variables for the dark theme in the source code. Is that on purpose or is it that a bug?

## How to reproduce

1.  Include the prebuild clr-ui.css file to a simple html page
2.  Check in the dev tools if any css variables are available -> yes, they are
3.  Include the prebuild clr-ui-dark.css file to a simple html page
4.  Check in the dev tools if any css variables are available -> nope :-( 

## Expected behavior

The dark theme file should also expose its css variables - or: Publish the css variables for the dark theme to customize and integrate for developers.

## Versions

**App**

- Clarity: 4.0.7

**Device:**

- Browser: Chrome

## Additional notes

I like Clarity! Keep it up! :-)

**Comment by mathisscott** [comment]
@maurerke 
You are correct that the compiled dark theme CSS doesn't expose the CSS custom properties. [the line of code that blocks that is here](https://github.com/vmware/clarity/blob/8b0b27e6386385199e53c4c9dc5ba46315dd0754/packages/angular/projects/clr-angular/src/utils/_theme.dark.clarity.scss#L35).

You'll notice that the theme is set up use SCSS variables as well. When we introduced custom properties into Clarity, we stopped short here. It was related to concerns that we would introduce breaking changes and the custom properties effort was already significant at that point.

I don't think there's a good way to do what you're asking in the near term. We've just introduced theming to `@clr/core` and it is [a significant improvement](https://github.com/vmware/clarity/blob/next/packages/core/src/styles/themes/themes.stories.mdx) because `@clr/ui` and `@clr/angular` were not initially built to be themeable.

Our recommendation moving forward is to use `@clr/core` if possible. I acknowledge that `@clr/core` doesn't yet have all the Angular components if they are needed. In that instance, you could try making [your own copy of the `@clr/angular` theme file](https://github.com/vmware/clarity/blob/8b0b27e6386385199e53c4c9dc5ba46315dd0754/packages/angular/projects/clr-angular/src/utils/_theme.dark.clarity.scss) and changing that flag from `false` to `true`. You'd need to update the import paths and change all the `$clr-` to `--clr-`. And there might be some visual hiccups with the colors, although that depends on what your app is using from Clarity. I'm not aware of any issues so that's a blanket "be on the lookout" kind of statement.

If you try that and see no major issues, I'd like to hear back. Because we could accept that as a contribution if you're up for it.

**Comment by maurerke** [comment]
@mathisscott 
Thank you for your prompt reply!
I will try to compile it, test it and report back. 

I found this (which was linked in the docs): https://github.com/mathisscott/clarity-theming-starter/blob/clarity-css-dark-theme-switcher/src/dark-theme.css

Was this file generated somehow or just a proof of concept?

Thanks!

**Comment by mathisscott** [comment]
@maurerke 
That was a proof of concept. It is a good starting point and may be all you need. Thanks for tracking it down. I had forgotten about it.

**Comment by gnomeontherun** [comment]
Given that Clarity UI/Angular are frozen, I would expect that you could workaround this issue by copying the relevant variables into your project so it works with dark theme. This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require major changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by implementations in Clarity Core, which have better theming capabilities. Please follow our development and releases for our progress on Clarity Core.
