### ISSUE TITLE
Undesired submit call on collapse of stepper step

### ISSUE THREAD

**Issue by nishant-gh** [vmware/clarity#5368]
## Describe the bug

I'm using stepper example from doc (the reactive forms one). When all steps have been completed the submit callback fires as expected. Although at this state if you try to expand and collapse any step it fires again. This is undesired as one would normally want to invoke the submit handler only when the submit button in clicked. Invocation of the handler in any other case like expand & collapse of a step will cause the handler to be called many times.

## How to reproduce

I'm using the same example from doc copied here - https://stackblitz.com/edit/clarity-v4-light-theme-ndv6xr
- Complete all steps
- Watch console which logs 'reactive form submit' with data on last step submit
- Now expand & collapse any step
- Watch the logging repeat 

## Expected behavior

Submit handler invocation should happen only when a submit button in clicked.

**Comment by bbogdanov** [comment]
Hi @hthserhs! Thank you for sharing this with us!

After some investigation I see that even when the stepper is completed and panel is closing [this function](https://github.com/vmware/clarity/blob/10c6b32161938f19255084801e537e71667f93b0/packages/angular/projects/clr-angular/src/accordion/stepper/stepper.ts#L81) is still executed and it triggers the form to submit again. I'll investigate further and I'll let you know what are the next steps when I have more clarity on the issue.

**Comment by bbogdanov** [comment]
I got the root of the issue.

[Expected behavior example](https://stackblitz.com/edit/clarity-v4-light-theme-gfcmev?file=src/app/stepper/stepper.component.html) 

Quick summary of the example:

- Removing `(ngSubmit)="submit()"` from the form
- Applying a click event to the submit button `(click)="submit()"`

When you submit a stepper you would reset it after that. Closing this as a non Clarity issue.
