### ISSUE TITLE
The multi-select datagrid doesn't emit selection change event when it receives selection  programmatically

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#5377]
## Describe the bug

I have a multi-select clarity datagrid and have bind my component to listen for selection changes:

<clr-datagrid [clrDgSelected]="selected"
              (clrDgSelectedChange)="selectionChanged($event)">
...
<clr-datagrid>

When I set programmatically the  selected items the grid is updated but I don't receive selection change event and my 
selectionChanged(...) handler is not call.

The same case work as it expected for single selection grid.
## How to reproduce

https://stackblitz.com/edit/clarity-v3-datagrid-selection-3

1.  Open the slack and click on "Select first row button"
Observe:
The grid selection of both grids is updated, but the "Selected user:" value of the multi-select grid is not updated, as
the grid doesn't emit selection change event.

## Expected behavior
The selection change event to be emitted as it is happening for single selection grid.

**App**

- Angular: 9
- Clarity: 3.1.x

**Comment by bbogdanov** [comment]
Hi @dkanev! 

It doesn't emit cause passing a new object to `selected` is not actually a selection. We probably have to change the behavior in the single selected as well but having in mind that we are focusing on bringing the datagrid in `core` we are more likely to unify this behavior in `core`. 

Providing a [stackblitz example](https://stackblitz.com/edit/clarity-v3-datagrid-selection-3-vn6478?file=src/app/app.component.ts) for selecting programmatically an item and trigger the `selectionChanged`

**Comment by dkanev** [comment]
@bbogdanov Thank you for the help! 
Is it OK when I want programmatically to select row in the datagrid to use
datagrid.selection.setSelected(itemToSelect, true);  ?

**Comment by bbogdanov** [comment]
It is. That's why we made it available to use. 

On the other hand, I would go over the solution one more time and think about it. Is it really necessary to select something programmatically and expect the notifier to trigger something else? 

By setting the `selected` items as you do in your example and on the next line execute the same code that the subscription executes, might be a better approach, than triggering the observable(saving some calculation time). Unfortunately, I don't know what your case is so it is up to you.
