### ISSUE TITLE
Datagrid: vertical scrollbar appears because of the horizontal scrollbar

### ISSUE THREAD

**Issue by alexpichler99** [vmware/clarity#5381]
## Describe the bug

When resizing the browser window and therefore reducing the width of the datagrid, a horizontal scrollbar appears. Because the horizontal scrollbar reduces the area where the rows are displayed also a vertical scrollbar will appear.

![image](https://user-images.githubusercontent.com/17060999/102088355-15759a80-3e1b-11eb-8a33-6cd434e95512.png)

## How to reproduce

1.  Have a datagrid
2.  Reduce width of the browser window to make the horizontal scrollbar of the datagrid to show
3.  The vertical scrollbar now also appears

## Expected behavior
No vertical scrollbar should appear.

## Versions

**App**

- Angular: 10.0.14
- Node: 10.16.0
- Clarity:  4.0.3

**Device:**

- Type: Laptop
- OS: Windows 10
- Browser: Chrome 
- Version: 87.0.4280.88

**Comment by bbogdanov** [comment]
Hi @alexpichler99, 

Could you please provide us a stackblitz example?

**Comment by Jinnie** [comment]
In an effort to optimise our backlog, I'm closing this as stale. If you manage to provide the reproduction requested, we'll reopen it, unless it gets locked by our inactivity bot, then you'll have to file a new issue. 

A side note, based on the description provided is that due to performance reasons we're not handling windows resize events on our side, as this might cause huge overhead in column size evaluation. Sometimes you must call the "ClrDatagrid#resize()"  TS API method yourself to help trigger reevaluation as response to the correct browser or application events.
