### ISSUE TITLE
UI Template for Pencil Project

### ISSUE THREAD

**Issue by pjtmatos** [vmware/clarity#541]
[ ] bug
[ ] feature request
[X ] enhancement

It would be a "really nice to have" if the UI template was ported to something like the Pencil Project (http://pencil.evolus.vn/).

It's open source and cross platform.

**Comment by reddolan** [comment]
Thank you for the feedback. What value do you see porting Clarity's UI Template to Pencil Project? What types of actions, or behaviours are you hoping to achieve with this?

On a side note, I have been working on a [Craft Library](https://www.invisionapp.com/craft#library) version of the Clarity UI Template which may cover some of your use cases. Have you looked into this tool at all?

**Comment by pjtmatos** [comment]
Hi.
Now yes. :)

It's seams really cool for designers, but for me, a "not so design inclined" developer (more of the code-monkey-keep-those-pesky-designers-at-bay-and-remove-that-photoshop-virus-from-my-computer :) kind of guy ) Pencil gives me the ability to do some quick mock-ups just for getting some ideas organized or simply gather some requirements.

While a can do that with some of the current stencils, it would be a nice to be able to do something more Clarity-like.

No biggie. Just a nice to have kind of thing.

**Comment by reddolan** [comment]
After reading more up on Pencil it seems it can do many of the same things that can be done in the Sketch template as well. At this time, I don't see us building a Pencil template. This is mostly due to the majority of our users using Sketch and the lack of industry support around a new tool like Pencil. I am going to close this ticket for now, if we consider expanding beyond Sketch in the future, I will add this to our list of considerations.
