### ISSUE TITLE
Data in Clarity DataGrid component is not aligned properly

### ISSUE THREAD

**Issue by vinayk406** [vmware/clarity#5485]
## Description
With asynchronous way of setting the data inside application, we ran into a scenario in which the data inside the grid component is not aligned properly.
Here is a screenshot of the grid component in our application. 

![image](https://user-images.githubusercontent.com/5180606/105446782-d7c92480-5c98-11eb-83d7-fed391fe83cc.png)

## How to reproduce
Here is the stackblitz link to reproduce the issue: [https://stackblitz.com/edit/angular-q8qzbu](https://stackblitz.com/edit/angular-q8qzbu)

### Actual output
![image](https://user-images.githubusercontent.com/5180606/105446943-37273480-5c99-11eb-94ce-17d09e1567eb.png)

### Expected output
![image](https://user-images.githubusercontent.com/5180606/105446959-41e1c980-5c99-11eb-9ee1-96012ba128b7.png)

We have observed a memory leak in our application related to this. Grid is trying to set the width of destroyed cells. 
_(Not able to reproduce this out side of our application)_

![image](https://user-images.githubusercontent.com/5180606/105447071-781f4900-5c99-11eb-8444-f29ce1849ca5.png)

The below suggested probable fix inside **main-renderer.ts** solved the problem.

![image](https://user-images.githubusercontent.com/5180606/105447118-98e79e80-5c99-11eb-8a73-da801f6af43f.png)

## Versions

**App**

- Angular: [v10]
- Clarity: [v4]

**Comment by Jinnie** [comment]
Dynamic column assignment/reassignment is not a pattern that we recommend. There are many challenges to it from the practical standpoint, with minimal value in return. Our support is to the level of configurable hideable columns, or *ngIf-ing certain predefined columns.
If you are downloading the column structure and expect the possibility that it will drastically change in subsequent data retrieval calls, this is in essence a new datagrid, so it would better be recreated. This will handle all initialization, memory leak issues, etc.
A quick and easy solution is to set a flag on starting the async operation and binding an *ngIf to it on the clr-datagrid level.

This is an updated example of your stackblitz:
https://stackblitz.com/edit/clarity-issues-5485?file=src%2Fapp%2Fapp.component.ts

**Comment by vinayk406** [comment]
@Jinnie Stackblitz shows a simplified version of the problem we have. 

In our use case, column data and row data are dynamic in nature. 
Columns can be configured by the end users which cannot be determined upfront. 

show/hide(*ngIf) workaround may result in a flicker effect and does not comply with our UX guidelines.

**Comment by gnomeontherun** [comment]
As @Jinnie said, we don’t support reordering columns in Clarity Angular. I’m not sure how column order is configured in your app, but it must be done outside of the Datagrid. The root issue here appears to be related to our assumption that columns are not changed and our auto-sizing feature assumes the columns size upon creation If you change the columns later, the sizes do get miscalculated. Also we expect you to set a size in px not in rem. Since we do not support this behavior directly, Ivan’s suggestion to recreate the Datagrid is the best path to render it properly. 

What version of Clarity are you using?

I'll reopen this for the moment, I'm not sure about the proposed changes and what side effects may occur, but it would add overhead to always recalculate rows so we must tread carefully.

When the Clarity Core version of the Datagrid is available then I think this will be possible to do on the app size since we’ll decouple the Datagrid from the application state better. We’re starting to work on it now, but don’t have an ETA for it at the moment.

**Comment by nghiado** [comment]
@gnomeontherun We are using Clarity 4/ Angular 10.
This happens without reordering columns. Basically, we have two async APIs one to get raw data for table, one to fetch columns metadata(name/label).

**Comment by gnomeontherun** [comment]
@nghiado A possible fix would be to delay rendering the datagrid until both columns and rows have loaded.
