### ISSUE TITLE
ClrTabs  component focus & key support issues when applying clrTabLinkInOverflow to in-between tabs.

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#5548]
## Describe the bug

Clarity ClrTabs component focus (trying to move between tabs using keyboard) does not go to ClrTab present after a tab with clrTabLinkInOverflow set as true. Opening the overflow menu also set's focus to the wrong element.

I am having a use case where some items in between all the tabs can have **clrTabLinkInOverflow**=true

Currently, the component we have in clarity is static in terms of what elements to be put under the overflow menu. I am using a directive in the consumer application to dynamically set tabs as normal vs in the overflow menu based on number of tabs that can fit in the tab container width.
This handling brings up the scenario of skipping some tabs in between to be shown upfront (Normally one's with larger text width) when the available width is less.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-ltab-overflow?file=src/app/app.component.html

1.  Select tab 1: Dashboard
2.  Use keyboard arrows to go to the next tabs
3.  Notice we cannot move to the third visible tab i.e. 'cloud'

## Expected behavior

Key support should work the same irrespective of in which order tabs are set to be in the overflow menu.
Focus should be set on correct element while opening the overflow menu.

## Versions

**App**

- Angular:  10
- Node: 12
- Clarity: 4.x

**Device:**

- Type: MacBook
- Browser chrome
- Version 87.0.4280.88 

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
Adding clrTabLinkInOverflow is not a very common scenario, though it looks pretty valid to me.

I have to state that the tab overflow is not the most accessible pattern by itself and recommend it should be avoided if possible, or substituted to vertical tabs, but still it would be nice to evaluate the effort to fix our key focus handling, especially if it is small and does not need any breaking change or architectural changes. Otherwise, we should explicitly document the pattern as not supported.
