### ISSUE TITLE
Can't use ngFor on clr-wizard-step or clr-wizard-page

### ISSUE THREAD

**Issue by nishantshreshth** [vmware/clarity#555]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
One should be able to add ngFor directive on wizard child components to build the wizard dynamically. For example, this should work:

```html
<clr-wizard #wizard>
  <div class="wizard-title">Wizard Title</div>
  <clr-wizard-step *ngFor="let step of [1,2,3]">Step {{ step }}</clr-wizard-step>
  <clr-wizard-page *ngFor="let page of [1,2,3]">Content for step {{ page }}</clr-wizard-page>
</clr-wizard>
```

### Actual behavior
Instead we get an exception saying:
```
Expression has changed after it was checked.
Previous value: 'undefined'. Current value: 'clr-wizard-0-tab-0'.
```
### Reproduction of behavior
https://plnkr.co/edit/YUf4vi 
(check console).

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.9

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
What we are calling the "old wizard" has a few issues with things like content projection and bog standard angular framework functionality. The wizard refactor #156 should allow for things like this.

The wizard refactor is planned for release with 0.9.0.

I'm closing this issue because there is no viable means of correcting it without refactoring the wizard -- which we are already doing.
