### ISSUE TITLE
Datalist without label has extra left padding from left side

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#5602]
## Describe the bug

Datalist without label has extra left padding from left side.

## How to reproduce

1.  Go to [documentation page](https://v4.clarity.design/documentation/datalist)
2.  Find Basic Example
3.  See error

## Expected behavior

Datalist without label should not have extra left padding.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [ ] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 10

**Device:**
- Type: MacBook
- OS: Mac OS High Sierra
- Browser: Chrome
- Version: latest

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
The Clarity datalist is designed to be used as form element, built with all clarity-form utilities in terms of responsive layout, accessible helper-text, error-message, success-message etc. This padding is the place reserved for label by the datalist-container.
In case you need to use a simple datalist outside a form, instead of trying to strip the advanced features of the datalist component, you'd better use a plain html datalist and add clarity styles to its input field, like this:
```
<input list="browsers" name="browser" id="browser" class="clr-input">     <-- add clr-input class

<datalist id="browsers">
  <option value="Edge">
  <option value="Firefox">
  <option value="Chrome">
  <option value="Opera">
  <option value="Safari">
</datalist>
```

**Comment by belyan** [comment]
Basic input don't reserve any place for label. Label is optional and can be omitted in favour of use placeholder or title.
https://v4.clarity.design/documentation/input 

Datalist is a kind of form control and can be used without label too. Just fix bug in your datalist styles, guys. I can easily fix this in my code, but I spend my time to report this defect to make your library better. If you don't want to fix defects, I can don't report them to you. It will save my time for more useful things.

**Comment by Jinnie** [comment]
The text input does not require a container, so it may be used without it.
The datalist component though, requires its container. It needs a service which is defined there. Here I can agree that we can try to make the dependency optional and allow the datalist to be used without a container. I don't see any cycles getting spent on this for Clarity Angular, given that we have a very light workaround. 
But we might want to consider it for the Clarity Core implementation, because now it also does not support datalist without label.
CC @gnomeontherun Jeremy, do you think we should add this as a Clarity Core datalist feature?

**Comment by gnomeontherun** [comment]
Accessibility requires labels, placeholders and titles are not sufficient to meet those requirements. All of our Angular form controls autowrap with a container even if you don't provide it as a way to ensure standards. However, as @Jinnie says the simple solution is to not use our automatic wrappers which enforce certain standards. I don't believe we will change this default behavior so the workaround is best.
