### ISSUE TITLE
Able turn on clrDgSingleSelected row with BehaviorSubject

### ISSUE THREAD

**Issue by chunghha** [vmware/clarity#568]
**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Radio input should be able to turn on with code all the time for clrDgSingleSelected.

### Actual behavior
I can't turn on radio input with subscribed BehaviorSubject. This might be a bug on clrDgSingleSelected or my bad. Please check out the plnkr below.

### Reproduction of behavior
https://plnkr.co/edit/k5P8iro4jnwN6xj5Wgvo?p=preview

From app component, I can turn on the radio for the 1st row as coded in constructor.
![image](https://cloud.githubusercontent.com/assets/24458075/23683421/8b1f7ed2-035e-11e7-9b3d-1b9d723552a8.png)

Also, I see the BehaviorSubject works correctly with row selections.

Then, click the another component link, I see "selectedUser" gets displayed with the BehaviorSubject correctly, but can't find a way to turn on radio button to the specific row selected from app component.

(components here are just to mimic my scenario, I need the above working correctly with that
1. (router-outlet) display datagrid with separate detail view so per selection on row, detail view reflects.
2. go to another component using router-outlet
3. go back to the datagrid component and like to see detail view still displayed with the selection made.
4. all 3 above works fine, except radio input not turned on the datagrid row selected in 1.
 

### Environment details

* **Angular version:** 2.4.9

* **Clarity version:** 0.8.9

* **OS and version:** Windows7

* **Browser:**Chrome 56

**Comment by youdz** [comment]
The reason this is not working is that Angular (and us, simply by using it) pretty much only considers object reference equality. For instance, in your plunker, you use `[clrDgSelected]="selected == user"`. But when you change from one component to another, each component re-instantiates a whole list of users from scratch, with new objects in it. So even VanillaJS would tell you that `selected == user` is false.
You can see this fixed in this plunker: https://plnkr.co/edit/niXni7NZz8i2vftPyt20?p=preview
I just used the same list for both components, by putting it in a separate module and importing it. 

That said, there are a few other issues in your code that make the plunker not work properly:
- You are using both `[(clrDgSingleSelected)]` on the datagrid itself and `[clrDgSelected]` on the rows. That's a bad idea, you are going to get "Expression has changed after it was checked" errors. You are basically using two conflicting inputs to do the exact same thing, so you're opening yourself to sync issues. We expose both options because they serve different use cases, but you should choose the one that fits your need. In your case, the `[(clrDgSingleSelected)]` on the datagrid is clearly what you need, it's by far the simplest.
- You have waaay too many sources of truth and listeners to keep them in sync. The point of an application state is to have a single source of truth. Right now just on component initialization, between the constructor/ngOnInit, the ngAfterContentChecked, the two-way binding on the datagrid, and the subscription to the BehaviorSubject, your are literally setting the `selectedUser` on your component *5 times*. You can see this in this plunker, where I'm just logging when you set the `selectedUser`: https://plnkr.co/edit/YU1LQIw5xfgnpJBJqQqz?p=preview
This is the logs I see just on initialization, before even interacting:
![screen shot 2017-03-08 at 09 42 06](https://cloud.githubusercontent.com/assets/4647197/23708335/996043de-03e3-11e7-90ba-8eaa81253a88.png)
At this point, it's far too much work to figure out the bugs and the `selectedUser` overriding that makes the application not behave correctly and not preserve the correct `selectUser` accross components. 

So my recommendation overall is to simplify, only use the subscriptions your actually need, trim the extra setters everywhere that prevent you from having a single source of truth, and avoid using multiple options to achieve the same result. That will help you see clearer and pinpoint the exact issues much faster.

**Comment by chunghha** [comment]
Thanks a lot, @youdz 

I was confused by "selected == user" while looking at your commit on enabling row selection with code for checkbox then tried to test with [clrDgSelected]="selected == user" without clearly understanding, but as you said that is what I wanted to avoid only with [(clrDgSingleSelected)]

I know the side effect by setting selected user in ngAfterContentChecked, just prefer to less lines of code with no harm on the state of selectedUser. And, setting that in constructor was only for the plnkr to check if initial row selection can be made with code. But, I much appreciate all your points in your reply and advice.
