### ISSUE TITLE
Combobox selects wrong item when using enter to confirm

### ISSUE THREAD

**Issue by sneksinnej** [vmware/clarity#5756]
## Describe the bug

Combobox uses wrong selection when using enter to confirm typed selection.
It keeps your last focused item instead of picking the first one of the filtered list.

## How to reproduce

1. Go to https://stackblitz.com/edit/clarity-light-theme-v5-hefc3o?file=src/app/app.component.ts
2. Open the application
3. Type in Fennel
4. Press enter
5. See error (It selects Foo because that was focused when the combobox was focused)

## Expected behavior

When typing then confirming with an enter press I expect the first item from the visible list to be selected.
This is the behavior on the aria-practices site:
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

## Versions

**Clarity project:**

- "@cds/angular": "5.0.2",
- "@cds/core": "5.0.2",
- "@clr/angular": "5.0.2",
- "@clr/icons": "5.0.2",
- "@clr/ui": "5.0.2",

**Clarity version:**
- v4.x (also tried the clarity-light-theme-v4 from stackblitz creates the same issue)
- v5.x (version we are using & stackblitz is made in)

**Framework:**
- Angular

**Framework version:**
- Angular 11.0.8

**Device:**
- Type: Desktop
- OS: Windows 10
- Browser Chrome
- Version 89.0.4389.90 (Official Build) (64-bit)

## Additional notes
-

**Comment by Jinnie** [comment]
Thanks for the provided reproduction and W3C link.
When the Clarity combobox was first designed, it was decided to go with "Example 1: List Autocomplete with Manual Selection" from the same W3C spec. 
What you request is also valid, though it's illustrated with "Example 2: List Autocomplete with Automatic Selection".
If I remember well, the Manual Selection was preferred for two reasons (both Accessibility):
- We didn't want to implicitly do a selection without a selecting action.
- In multi-select case we need to land on the 1st already selected item, and we didn't want two different experiences in single-select and multi-select.
Nevertheless, I see a bug in our current implementation - we do select the 1st option implicitly if Enter is hit without active selector on any option.

@scroniser do you think we need to re-evaluate our model with the future Core implementation and use "Autocomplete" instead of "Manual" there?
