### ISSUE TITLE
Add a variant to core flat buttons to align correctly when sitting left or right in a component

### ISSUE THREAD

**Issue by jaybellew1** [vmware/clarity#5775]
## Summary
As we are moving to clarity core, we’ve bumped up against a layout issue with the flat buttons. They’re not super useful for cases where they are positioned in layouts or components on the left or right as they won’t align correctly.  

- What is the change?
My proposal is that we add a variant to the flat button for these cases, just removing the left/right inside padding (or even 2px would do the trick) and changing the radius on the button container to zero.

- Why should it go in Clarity?
I think the biggest impact will be for cards…since most of the VMware apps have dashboards with cards and the clarity system leans on the flat buttons at the bottom of cards.  It’s really the only thing I have run across that you can’t make using core out of the box (without an alignment problem that is)..  attaching a few screens from the design system site.  You can’t actually do this with with core unless we all add customizations.

- If this change introduces a new behavior, is this behavior accessible?
The change only removes left/right padding, but leaves the container intact for focus and disabled state.  I don't see any impact on a11y

## Examples

Examples of the new variant in a card attached.  

![Flat Button Variant- No Left-Right Padding](https://user-images.githubusercontent.com/32872744/112369868-15572780-8cb3-11eb-930e-87e277f15e51.png)

Other examples we have include: flat buttons over a datagrid and the back button positioned over the page title.  I can see this being an issue with flat buttons at the bottom of menus, forms and any time you need to add a button above or below another element and need to it visually align with that element.

**Comment by astorije** [comment]
I think we'll run into this with _every_ flat button we use, because one way or another the left or right side will never align, by design.

Instead of a new variant for this, what if flat buttons were given a `--padding: 0` by default (or `--padding: 2px` like @jaybellew1 suggested)? This could still be customized using the design token, but that would ensure proper alignment by default.

Here are a couple examples of how it would look. In both examples, the left button has `--padding: 0` while the right button has the current default padding. First example is `size="md"`, second one is `size="sm"`.

![md](https://user-images.githubusercontent.com/113730/112709024-f16c2f80-8ec6-11eb-91b0-4916948e41fd.gif)
![sm](https://user-images.githubusercontent.com/113730/112709025-f16c2f80-8ec6-11eb-9dca-321c35e29165.gif)

I am happy to open a PR if that's a welcome contribution :)

**Comment by astorije** [comment]
More screenshots of the same example to showcase the alignments. Left screenshot has current default padding, right screenshot has `--padding: 0` on both buttons.

Before | After
--- | ---
<img width="722" alt="Screen Shot 2021-03-26 at 11 39 36 PM" src="https://user-images.githubusercontent.com/113730/112709095-71929500-8ec7-11eb-905c-f50e311edcd1.png"> | <img width="720" alt="Screen Shot 2021-03-26 at 11 40 07 PM" src="https://user-images.githubusercontent.com/113730/112709096-722b2b80-8ec7-11eb-9f02-02844bb9d06f.png">

**Comment by Jinnie** [comment]
I believe we've already had some discussions about this previously. I'll leave it to the UX team to comment.
Thank you for the good illustrative materials.

**Comment by hippee-lee** [comment]
While this is under discussions and vetting, there is a workaround:

```css
.my-flat-button {
  --padding: calc(#{$cds-global-space-6} - var(--border-width)) 0;
}
```
```html
<cds-button action="flat" class="my-flat-button"></cds-button>
```
