### ISSUE TITLE
Naming of CSS rules in v5 breaks styling of pages created with v4

### ISSUE THREAD

**Issue by grahamford** [vmware/clarity#5843]
## Describe the bug

We're trying to move to version 5 of Clarity but have noticed subtle style changes across our site. It appears that the style rules in V5 use the pseudo selector `:not([cds-text])` on many items, increasing the specificity of the rule. This overrides some of our component styling where we have updating specific styles.

In the stylesheet for an angular component with V4, you can use a rule like this and it has the expected result. The margin on paragraphs is set to zero.
```
p {
    margin: 0;
}
```

After upgrading to V5, this no longer works because the package rules are now more specific and our component styles aren't used. This is an example of the package style that prevents the example above from working.
```
body p:not([cds-text]) {
    ...
    margin-top: 1.2rem;
    ...
}
```

## How to reproduce

Example with version 4
https://stackblitz.com/edit/clarity-4-onlyl-paragraph-style?file=src/app/app.component.css

Example with version 5
https://stackblitz.com/edit/clarity-v5-paragraph-spacing?file=src/app/app.component.css

## Expected behavior

Component styling should be unaffected when upgrading from ver 4 to ver 5.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 10+

## Additional notes

A workaround would be to increase the specificity of the style rules in the components but it's difficult to tell what's been affected because it means visually checking the whole site. 

I did raise this on the GitHub Discussions page but haven't had any replies. It does feel like a bug to me.

**Comment by sis0k0** [comment]
@GrahamFord, thank you for reporting this! @mathisscott, this behavior seems to be caused by https://github.com/vmware/clarity/pull/5409. Is this expected?

**Comment by mathisscott** [comment]
The `:not()` rule was necessary to avoid a collision between the existing Clarity UI css (which has margin built in to various HTML tags) and Clarity Core's layout and typography tokens (which do not). We can't remove those because it will cause Core layouts and styles to break. It is a legacy issue driven by a bad decision in the early days of Clarity UI.

If an application's existing overrides of the Clarity UI css are being impacted, the workaround is to increase specificity on the product size by replicating the `:not([cds-text])` pseudo-selectors. #5409 shows which styles are affected and would need to be updated on the product side.
