### ISSUE TITLE
Inverse button should have bright text/borders on dark theme

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#5851]
## Summary

- What is the change?

Update the inverse mode of Clarity Core's `cds-button` to keep its dark style in dark theme.

- Why should it go in Clarity?

Because while it's frequent to have elements with dark backgrounds in light modes (e.g. GitHub's top nav is black in light mode), it's usually not common or expected to have elements with light backgrounds in dark modes (e.g. GitHub's top nav stays black in dark mode).

Additionally, other components that currently support an inverse mode in Clarity Core (spinners and icons that I could find) follow this pattern already, as demonstrated on the Core Storybook:

Light theme | Dark theme
--- | ---
<img width="479" alt="Screen Shot 2021-04-14 at 12 38 24 AM" src="https://user-images.githubusercontent.com/113730/114790948-4b596a00-9d8e-11eb-92cd-176a68a9f59a.png"> | <img width="457" alt="Screen Shot 2021-04-14 at 12 38 45 AM" src="https://user-images.githubusercontent.com/113730/114790956-4bf20080-9d8e-11eb-959f-af6773a6ab5e.png">
<img width="517" alt="Screen Shot 2021-04-14 at 12 45 40 AM" src="https://user-images.githubusercontent.com/113730/114790958-4d232d80-9d8e-11eb-85f3-18d9b2225314.png"> | <img width="504" alt="Screen Shot 2021-04-14 at 12 45 49 AM" src="https://user-images.githubusercontent.com/113730/114790961-4dbbc400-9d8e-11eb-913a-09940666bcbc.png">
<img width="564" alt="Screen Shot 2021-04-14 at 12 46 28 AM" src="https://user-images.githubusercontent.com/113730/114790965-4eecf100-9d8e-11eb-8a9c-1ea931868877.png"> | <img width="565" alt="Screen Shot 2021-04-14 at 12 46 34 AM" src="https://user-images.githubusercontent.com/113730/114790966-501e1e00-9d8e-11eb-88fa-f2ad7892bfea.png">

As you can see, while the colors of spinners and icons do not change in dark theme, buttons need to flip their background or they would appear dark-on-dark.

- Does this change impact existing behaviors? If so how?

Yes, in theory, this will cause existing uses of the inverse button to have incorrect colors in the unlikely event they are located on a light background in dark theme. In practice, I expect this has been locally customized with design tokens to prevent this behavior already.

- If this change introduces a new behavior, is this behavior accessible?

There should not be accessibility implications, and if any, I expect them to be positive.

## Use case

Here is our use case: we currently use an inverse "Sign out" button to display in a navbar, which happens to be on the darker side (and this is true for all of VMware Cloud Services, e.g. the "Sign in" button on the top right [here](https://console.cloud.vmware.com/csp/gateway/portal/#/api-docs)).
If using the default inverse button with no further customization, here is what happens when toggling `cds-theme="dark"` on:

https://user-images.githubusercontent.com/113730/114790228-11d42f00-9d8d-11eb-8880-ca363052619c.mov

The button “disappears", because it now features the same `border-color` and text `color` as the navbar background.

This is the proposed change, keeping it the same color in both light and dark themes, as the assumption is that if it is used on a dark background in light theme, it will also be used on a dark background in dark theme:

https://user-images.githubusercontent.com/113730/114790597-b0f92680-9d8d-11eb-8151-abd66e782e60.mov

This can currently be achieved using the existing CSS properties and, in fact, the above video was generated using `--border-color: var(--cds-global-color-white); --color: var(--cds-global-color-white);`, however I do believe this merits to be the default style of the inverse button on dark theme.

## API

This does not cause any changes to the API of `cds-button`. It will however cause a styling change for whoever uses the `inverse` button on both dark theme **and** a light background as detailed above.

## Implementation plan

- What parts of the code are affected?

Essentially only lines related to `status='inverse'` in `base-button.element.scss` and `button.element.scss`. I'd also update the stories to look accordingly.

## Conclusion

I am obviously more than happy to contribute with that change myself. I'm actually pretty sure it would have taken me less time to open a PR directly rather than start with an issue, but I wanted to make sure it would be welcome and duly documented/defended :D

EDIT: I'm preparing a PR right now, let me know if you're against this idea!

**Comment by sis0k0** [comment]
Thank you for the suggestion! The proposed change seems reasonable to me. @colinreedmiller, what do you think?

**Comment by colinreedmiller** [comment]
Nice callout @astorije - thanks!

We may indeed wish to address this with the inverse button, but we need to be careful about how themes are defined so we don't assume use cases and create the opposite issue elsewhere. I'll take it up in our next theming discussion.

In the meantime - Why use primary-inverse rather than outline?
There is a neutral status that makes it light if you don't want to indicate a specific status.
The values are:

`--cds-alias-status-neutral`
`--cds-alias-status-neutral-tint`
`--cds-alias-status-neutral-shade`

`https://clarity.design/storybook/core/?path=/story/foundation-color--page'

(I believe) "neutral" is not listed as a status in the API because it is the default if a status is not specified.
Action would be "outline"

**Comment by astorije** [comment]
> We may indeed wish to address this with the inverse button, but we need to be careful about how themes are defined so we don't assume use cases and create the opposite issue elsewhere. I'll take it up in our next theming discussion.

I completely understand (and appreciate!) this of course :)
In the meantime, I opened a PR at https://github.com/vmware/clarity/pull/5857, in case it helps the discussions with illustrations.

> In the meantime - Why use primary-inverse rather than outline?
> There is a neutral status that makes it light if you don't want to indicate a specific status.

Unfortunately, `neutral` is not a status available for `CdsButton`:

<img width="711" alt="Screen Shot 2021-04-15 at 10 32 32 PM" src="https://user-images.githubusercontent.com/113730/114934790-0c392080-9e43-11eb-8861-2170e7d26ea1.png">

I actually noticed the `warning` variant is missing for buttons so I am going to open a PR for that, I can add `neutral` as well.
However, I don't believe it would work as expected, the button would be dark on the dark background (light theme) and then switch to bright colors on the same dark background (dark theme).

After experimenting more, I still believe the inverse button should act the same as inverse alerts and icons, but I'm happy you're considering bringing it up during the next theming discussion. Let me know if there is anything I can do to help!

**Comment by mathisscott** [comment]
I would say that the inverse icons and progress circle are wrong here. Inverse is intended to give people a path to put icons/buttons/progress circle on a page when they have a light background in a dark theme or vice versa. So having them dark in a dark theme and light in a light theme is intended.

I think what is missing here is a neutral option (which would indeed by light in a dark theme and dark in a light theme like what @astorije is wanting). We have a status type alias in Core that includes neutral and we use it in other components. It seems like we need to apply it here as well.

I'm happy to have a deeper discussion over Zoom if we feel that is warranted.

**Comment by astorije** [comment]
> Inverse is intended to give people a path to put icons/buttons/progress circle on a page when they have a light background in a dark theme or vice versa.

My argument here is that it is highly uncommon to see a page with a dark mode and an element on the page that has a light background, while the opposite is not uncommon at all.
So I think it would make more sense to have inverse reflect this representation as it would correspond to a more common case, and in the unlikely event someone has a light-background element on a dark theme, they can use design tokens. I would expect anyone currently using the `inverse` button to have overrides to support their dark mode (obviously have not compiled any data for that, besides all VMware Cloud Services examples).

> I think what is missing here is a neutral option (which would indeed by light in a dark theme and dark in a light theme like what @astorije is wanting).

I have opened a PR to add the neutral option at https://github.com/vmware/clarity/pull/5859 :)

However, we will not be able to use the `neutral` status: while it would work fine in dark theme, if you look at the first video that is in light theme, you can see it would appear as follows by default:

<img width="105" alt="Screen Shot 2021-04-15 at 11 50 42 PM" src="https://user-images.githubusercontent.com/113730/114942870-d6e60000-9e4d-11eb-8977-b88cc861086f.png">

This obviously would require overriding the design tokens, which... back to square one 😅

**Comment by mathisscott** [comment]
> However, we will not be able to use the `neutral` status: while it would work fine in dark theme, if you look at the first video that is in light theme, you can see it would appear as follows by default:

So, given that `inverse` means the _inverse_ of whatever theme (light vs. dark) you are in... if you had a dark background in dark theme, a `neutral` style works and is what you want.

But if you then use `neutral` in light theme over a dark background (where inverse would be more appropriate), why is that considered a bug? It would seem to me that if you give the button neutral in a dark theme because you have a dark background, you would then want to change the status to inverse in a light theme because you are working with the light theme now but still have a dark background...

I think we should move this offline. Please block off some time with myself and @colinreedmiller to discuss next week. Thanks!

**Comment by astorije** [comment]
I think I get it: you are saying the `status` attribute would change based on theme: `inverse` in light theme, and `neutral` in dark theme, correct?

If that's the case, then that's even more impractical than overriding a couple design tokens given how dark theme works with Clarity (attribute on `body` + design tokens). By using the very helpful color aliases + the dark theme CSS file, one can accomplish complete light/dark theme support without introducing any custom logic, and this would require hooking the value of the attribute based on theme by either listening to an event change on `body[cds-theme]` or maintaining an extra state. Completely doable, but far less convenient than leveraging design tokens.

Sure thing, I'll book some time, great idea!

**Comment by mathisscott** [comment]
> I think I get it: you are saying the `status` attribute would change based on theme: `inverse` in light theme, and `neutral` in dark theme, correct?

That's one way to do it and consistent with how I described it. But I think the larger point is that there is an outlier in the design of the application here. And that needs to be accounted for on the application side.

Depending on how the implementation is approached...

1. Either we use `inverse` so that the button is light against the dark background in light theme (as expected) and we have to customize it for dark theme (where the dark background in dark theme is not appropriate for an `inverse` style) or...
2. We use `neutral` where the button is light against the dark background in dark theme (as desired) and the dark background in light theme is the outlier...

Core is flexible enough to handle that by changing the status when the theme is switched or through custom properties on the app side. But either way this situation is specific to the app – whether the dark background in light theme is your outlier or your dark background in dark theme is your outlier.

On Core's end, we lacked a `neutral` style. Thanks for the PR on that. Additionally, the implementation of `inverse` for icons and the progress circle in dark theme look to be wrong. 😊 

I look forward to chatting next week.

**Comment by astorije** [comment]
> Additionally, the implementation of `inverse` for icons and the progress circle in dark theme look to be wrong. 😊

That part I disagree with. As a user of Clarity Core, they are doing exactly what I would expect for icons and progress circle.
My GitHub example above is another illustration of this, and in my experience most apps, Clarity or not, act like this. So in practice, the `inverse` status will always require customization.
