### ISSUE TITLE
Datagrid slow render on large datasets - reintroduced

### ISSUE THREAD

**Issue by Dedme** [vmware/clarity#5919]
## Describe the bug
A data grid without pagination takes a long time to render for data sets above about 2000 records.
is exponentially (maybe geometrically)  delayed with size.

the block happens when updating from a large size to smaller, or to a large size.
the page also suffers performance constantly when trying to highlight hover row.

this was an issue back in v1.
https://github.com/vmware/clarity/issues/3082

## How to reproduce
https://clarity-v4-dark-theme-ktm65o.stackblitz.io/

Populate a datagrid with more then 2000 or so records.
you can change the number of items using the button and input on top.
when its over 2000, changing to a smaller number still takes some considerable time.
changing between 2 large numbers is very slow.
and if you select over 6000 the page also seems to stop.

1.  Load stackblitz and wait 4 seconds for the first population.
2. change the size on top with the input and click button.

## Expected behavior
the datagrid should load in a reasonable time and not block page renders for 2+ seconds.

## Versions

**Clarity project:**
- [4.0.11] Clarity Core
- [4.0.11] Clarity Angular/UI

- [4.0.3] Clarity Core
- [4.0.3] Clarity Angular/UI

**Clarity version:**
- [ ] v3.x
- [x] v4.x
- [ ] v5.x

**Framework:**
- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other: 

**Framework version:**
Angular 10

**Device:**
- Type: Desktop AMD High End Gaming PC
- OS: Windows
- Browser Edge(ium)
- Version 90

also happens within my Electron App:
V: 12.0.2

**Comment by Dedme** [comment]
Attached is the profile i got.
looks like the resize function does a lot.

![image](https://user-images.githubusercontent.com/40647185/116494821-d2572800-a8e0-11eb-9854-6b9191d79398.png)

[Profile-20210429T114433.txt](https://github.com/vmware/clarity/files/6395924/Profile-20210429T114433.txt)

**Comment by hippee-lee** [comment]
That makes sense. The resize fn is how the datagrid figures out how wide column widths and cell widths need to be and setting that up for the projected content. The more rows and cells there are the more work it has to do. 

I would suggest using pagination at a reasonable page size.

**Comment by Dedme** [comment]
it would be great if that could be avoided in pace of a standard flex grow or something? - have a dynamic width flag that can be disabled?

there is a real gap in not having performant large lists - ie with virtual scroll.

**Comment by hippee-lee** [comment]
Virtual scroll is something that we have investigated, tried and revisited multiple times since 2017. The biggest hurdle was, and still is, **how can it be made it accessible**? Internally at VMware, besides our efforts on the Clarity side, several product teams have invested in research and prototyping ideas to make it accessible to the current WCAG standards. None of those efforts has found a solution. Virtual scrolling has been a common enough request that we have a wiki page for it [here](https://github.com/vmware/clarity/wiki/Virtual-scrolling) and a collection of notes internally. If you are interested lmk and I'll see if they can be made public on the wiki page.

Internally, on the team, we are not planning to make structural changes to `ClrDatagrid` for a few reasons. The main reason being that the core web component version of a datagrid is under active development.

But, I hear you. This can be frustrating for consumers who have specific requirements for the datagrid that prevents them from using reasonably sized pages to present the data. If this is important enough to you, or someone in the community, we are happy to listen to proposals that that add the features they need to the existing Angular components in an accessible way.

**Comment by gnomeontherun** [comment]
The long term solution for this will be to leverage the Clarity Core implementation of the Datagrid when it is released. That is still a few months away, but it will allow applications to implement different behaviors without the concerns of internal logic (like resize) which are needed to make our Clarity Angular Datagrid function. As @hippee-lee says, pagination is the proper approach that Clarity supports, as other things like virtual scrolling are not accessible. 

I'm going to close this as out of scope for what we'll do with Clarity Angular.
