### ISSUE TITLE
Is it possible to prevent closing of ClrAccordionPanel?

### ISSUE THREAD

**Issue by real-artswan** [vmware/clarity#5925]
I need to don't allow users to close panel until some conditions are not met.

Here is a sample:
https://stackblitz.com/edit/clarity-light-theme-v5-1cypdf?devtoolsheight=33&file=src/app/app.component.ts

1.  Open "Panel 2"
2.  Close it
3.  You can see in console that component reads `clrAccordionPanelOpen` property 4 times and it is always true but panel is closed anyway

I expect it to not get closed.

Clarity 5.1.1
Angular 11.2.11

**Comment by jeeyun** [comment]
Hi @real-artswan,
Unfortunately there isn't an easy way to prevent the user from closing the panel. You can separate out the two-way binding to call a function when the open state has changed, however this does not prevent the boolean value from changing (it only allows you to perform some additional functionality when the state has changed):
https://stackblitz.com/edit/clarity-accordion-1?file=app%2Fapp.component.ts

This is because the Angular component internally updates the open state when user clicks on the panel header.

This is a problem we encountered often with our users in Angular. If you are able to, I'd recommend you to check out our web component version of the accordion where we never automatically open or close the panel. It's up to the application to respond to the event and doing something like you propose is very easy to do so:
https://stackblitz.com/edit/clarity-accordion-core?file=app/app.component.ts

Here's a documentation on how to install and use our web components in an Angular application:
https://clarity.design/get-started/developing/#angular
