### ISSUE TITLE
Combobox width

### ISSUE THREAD

**Issue by wittm** [vmware/clarity#5963]
## Describe the bug

The width for the combobox cannot be changed

## How to reproduce
https://stackblitz.com/edit/clarity-v4-dark-theme-1rufu3

1.  Place a combobox within the header-nav area
2.  attempt to set it's width through any of the following means
3. 'width' attribute on the combobox selector
4. width style via css on the clr-combobox-input class
3.  the width of the combobox remains unchanged

## Expected behavior

It is expected to be able to change the width of the combobox to support GIS applications with parcel numbers that need to be seen in their entirety e.g. 01-4.0-19-0-000-000-001.00

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [ ] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 10

**Device:**

- Type: MacBook
- OS: OSx
- Browser Chrome, Firefox
- Version Chrome 90, Firefox 88

**Comment by coryrylan** [comment]
The width can be changed. The issue is the custom styles that were applied existed in the app component. Those styles are encapsulated and only apply to the app component template. Move the styles to the global style sheet or disable the component style encapsulation https://stackblitz.com/edit/clarity-v4-dark-theme-t1ixdt?file=src%2Fstyles.css
