### ISSUE TITLE
Bug: Loading Button Sizing Problems

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#5967]
## Describe the bug

When using a clarity button with `[clrLoading]` the initial width is not wide enough.

![image](https://user-images.githubusercontent.com/8677948/118937576-f80aa680-b94d-11eb-8527-8f3b27cfc4a1.png)

After it stops loading it adjusts to the correct size.
But if it starts loading again the spinner icon contains an unexpected ellipsis.

![image](https://user-images.githubusercontent.com/8677948/118938022-7109fe00-b94e-11eb-92f6-0f8a4dbacdbb.png)

## How to reproduce

https://stackblitz.com/edit/clarity-v4-loading-button

1.  Go to https://stackblitz.com/edit/clarity-v4-loading-button
2.  See the cut spinner icon
3.  Click 'Stop Loading' & 'Start Loading'
4.  See '...' behind loading spinner

## Expected behavior

* button should have initial min width of spinner icon
* in loading state the spinner icon should be shown without ellipsis

## Additional Notes

Maybe it would help to set a min-width for the initial state:
https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/button/button-loading/loading-button.ts#L105

Maybe the ellipsis text-overflow can be disabled for `.btn-icon`.

**Comment by bdryanovski** [comment]
I could confirm that this bug is still active even with the latest version 

```json
    ...
    "@angular/animations": "~12.0.2",
    "@angular/common": "~12.0.2",
    "@angular/compiler": "~12.0.2",
    "@angular/core": "~12.0.2",
    "@angular/forms": "~12.0.2",
    "@cds/city": "^1.1.0",
    "@cds/core": "^5.4.0",
    "@clr/ui": "^5.4.0",
    "@clr/angular": "^5.4.0"
    ...
```

Even with changing the expected type from `boolean` to `ClrLoadingState` the issue persist 

```ts
isLoading$ = new BehaviorSubject<ClrLoadingState>(ClrLoadingState.LOADING);
```

I think that because of the state change in the middle of the render cycle we don't calculate or set the correct width of the button.

```html
style="width: 26px;transform: translateZ(0px);"
```

The width is set from this method:

```ts
  private setExplicitButtonWidth() {
    if (this.el.nativeElement && this.el.nativeElement.getBoundingClientRect) {
      const boundingClientRect = this.el.nativeElement.getBoundingClientRect();
      this.renderer.setStyle(this.el.nativeElement, 'width', `${boundingClientRect.width}px`);
    }
  }
```
There is also an animation that is triggered at the beginning, 

```ts
 trigger('spinner', [
      transition(':enter', [style({ opacity: 0 }), animate('200ms 100ms ease-in', style({ opacity: 1 }))]),
      transition(':leave', [style({ opacity: 1 }), animate('100ms ease-out', style({ opacity: 0 }))]),
    ]),
```

My guess here is that `boundingClientRect.width` is called at the beginning of the render when the button is only a simple box without the spinner inside - after that, the animation will continue but now the `width` will be wrong.
