### ISSUE TITLE
cds-select + React Testing Library: `TypeError: 'set' on proxy: trap returned falsish for property 'disabled'`

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#5985]
## Describe the bug

When Clarity is used in conjunction with the React Testing Library, selecting a `CdsSelect` by its corresponding label throws:

```
    TypeError: 'set' on proxy: trap returned falsish for property 'disabled'

      at node_modules/src/internal/utils/lit-element.ts:42:20
          at Array.forEach (<anonymous>)
      at syncProps (node_modules/src/internal/utils/lit-element.ts:42:6)
      at HTMLElement.updated (node_modules/src/forms/control/control.element.ts:291:5)
      at HTMLElement.performUpdate (node_modules/lit-element/src/lib/updating-element.ts:792:12)
      at node_modules/lit-element/src/lib/updating-element.ts:725:25
      at asyncGeneratorStep (node_modules/lit-element/lib/updating-element.js:8:103)
      at _next (node_modules/lit-element/lib/updating-element.js:10:194)
```

## How to reproduce

I could not reproduce this using a StackBlitz as the test runner runs outside of a browser context (and StackBlitz's super new Node beta support had some issues), but I set up a repro repo at [astorije/repro-clarity-proxy-set-disabled](https://github.com/astorije/repro-clarity-proxy-set-disabled).

1.  Clone the repo
2.  Install dependencies with `yarn install`
3.  Run `yarn test`
4.  The error posted above is thrown. This is triggered by [astorije/repro-clarity-proxy-set-disabled `index.test.tsx#L35-L54`](https://github.com/astorije/repro-clarity-proxy-set-disabled/blob/main/index.test.tsx#L35-L54)

## Expected behavior

When I comment out [this line](https://github.com/vmware/clarity/blob/a222f9972d5e0e384c4270ee036a3192236711f4/packages/core/src/forms/control/control.element.ts#L298), the test passes as expected.

Using the repo above, open `node_modules/@cds/core/forms/control/control.element.js` and comment out L191. Run the tests again and they will be green. By adding `screen.debug()` after the `expect` statement, we can see the DOM as it's supposed to be rendered:

```html
<body cds-supports="js no-flex-gap" cds-version="5.2.1">
  <div>
    <cds-select
      _nfg=""
      cds-control=""
      control-width="stretch"
      responsive=""
      status="neutral"
    >
      <style />
      <label for="_b3i52678e" slot="label">
        Foo
      </label>
      <select id="_b3i52678e" slot="input">
        <option>Bar</option>
      </select>
    </cds-select>
  </div>
</body>
```

I doubt the fix is to simply remove that line as it was recently added as a bugfix itself in https://github.com/vmware/clarity/pull/5739 or that upgrading `lit` to a non-fork will fix the issue.

I don't follow this code too well yet. `CdsSelect` extends `CdsControl`, could that mean `CdsSelect` is not set up properly to accept the `disabled` attribute? I'm happy to help with a fix but will need a little guidance 😅

## Versions

**Clarity project:** `@cds/core` + `@cds/react` v5.2.1, v5.3.0
**Framework:** Tested this is an issue with React 16 and 17.
**Node:** v14.16.1

**Comment by astorije** [comment]
@coryrylan, do you have any idea what's going on here? Is there anything I could help with?

**Comment by coryrylan** [comment]
I havent been able to dig into this yet. It seems similar to other issues we have had with React proxying the native setters which collides with our custom element setters. My initial guess is to add an additional check here https://github.com/vmware/clarity/blob/next/packages/core/src/internal/utils/events.ts#L24

```typescript
if ((element as any)._valueTracker && (propertyKey === 'checked' || propertyKey === 'value' || propertyKey === 'disabled')) {
```

**Comment by astorije** [comment]
Mmmh, I just tried that and unfortunately it made no difference, the failure is unchanged.

**Comment by astorije** [comment]
I just updated the description above, as `control.element.ts` has recently changed and the highlighted line was incorrect. I can make the tests pass by disabling [this line](https://github.com/vmware/clarity/blob/a222f9972d5e0e384c4270ee036a3192236711f4/packages/core/src/forms/control/control.element.ts#L298). I'm wondering if there is a conditional I could wrap this statement with.

**Comment by dturcotte** [comment]
I ran into this exact issue recently when trying to use `CdsSelect`, any luck investigating?

**Comment by coryrylan** [comment]
I dug into this a bit more this morning but no luck yet. [This line](https://github.com/vmware/clarity/blob/a222f9972d5e0e384c4270ee036a3192236711f4/packages/core/src/forms/control/control.element.ts#L298) is setting the html input `disabled` property anytime the `disabled` property on `cds-select` or any `cds-control` type is set.

A guess, but I'm not sure is React is setting a Proxy on the native input and when `disabled` is set on the html select/input its throwing unexpectedly.

**Comment by Eve-YeShen** [comment]
+1 
I have the same issue

**Comment by coryrylan** [comment]
I am unfamiliar with React Testing Library would these issues be related? Possibly the test using select needs to be modified? (edit): seems maybe not? The issue is similar but related to the `multiple` attribute

https://github.com/testing-library/react-testing-library/issues/375
https://github.com/testing-library/user-event/issues/123
https://testing-library.com/docs/ecosystem-user-event/#selectoptionselement-values

**Comment by dturcotte** [comment]
We haven't gotten that far yet - we're not using `multiple` and we're not trying to interact with it yet, simply rendering a minimal `CdsSelect` in an async test is enough to see the error. I made a repro here if you want to see it for yourself: https://github.com/dturcotte/cds-select-test

**Comment by ayanchakravoty** [comment]
+1 I’m also facing this same issue. Any updates on this?

**Comment by ashleyryan** [comment]
Matt said this sounds like a lit issue, so I've reported it here: https://github.com/lit/lit/issues/2281

However, now that I think about this some more and think about the error message, this sounds like the boolean attribute issue in React. I also came across this from a different github issue: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set#invariants

**Comment by justinfagnani** [comment]
Can anyone say why they think this is a Lit issue? I can't tell what files are involved from the stack trace. Which package is `src/internal/utils/lit-element.js` in? Also, does anyone know where the Proxy is coming from? We don't use them.

**Comment by ashleyryan** [comment]
@justinfagnani I just replied above, but the more I think about this, the more I don't think this is a lit issue.

I'm not a clarity dev, just a consumer of their react package, but we've had a lot of ongoing issues with boolean attributes in React - when passing a prop like `disabled` into a React input, you would do something like:

`<selected disabled={false} />` but in web components/native html, you wouldn't set `disabled` to false, you would omit it entirely. 

Based on the error message, it sounds like it's something like that (especially when reading the MDN link above), but for some reason we *only* get the issue with React Testing Library. 

I don't know where/how/if Clarity uses the proxy though.

**Comment by hippee-lee** [comment]
@ashleyryan - in our discussion I mentioned that it seems like this is a testing-lib or react issue. I 👍🏼ed the idea to report the issue to lit because that is where the reported stack trace is coming from. I looked through the `@cds/core` select and forms base classes code and we don't use any Proxy's. We only use one Proxy in the whole project and it has to do with the global CDS state on the window.

If we eliminate lit and cds-select (plus forms base classes) as packages that might be using a Proxy and causing the error, what is left? Am I missing something besides react-testing-library and react? 

I am going to test my theory that the issue is in React or react-testing-library by forking @dturcotte 's sample repo to see what happens when I create a standalone web component similar to the cds-select. So,  no lit and no clarity and just a vanilla web component. I'll post the results here.

**Comment by mathisscott** [comment]
> Which package is `src/internal/utils/lit-element.js` in? 

The lit-element utils is  a file of helper functions that focus on syncing properties down the DOM tree. So if a child needs to stay in sync with some property of a parent or grandparent, those utilities do that. 

I'm not sure how those helpers could break the React testing library in this one specific case and not in others (like alerts) where they are used. 

I think the utils are a red herring here. I think Matt is on the right track.

**Comment by ashleyryan** [comment]
It could also be jsdom - that's ultimately what is used to create a DOM in Node for testing.

react-testing-library is a very lightweight wrapper on top of dom-testing-library. RTL really doesn't do much more than call react's `render` into jsdom. dom-testing-library is a set of utilities and jest matchers for interacting with the dom. 

It could definitely be a red herring, but we don't interact with alert's in our tests the way we do with inputs. Largely because testing-library doesn't query the shadow dom, so we really *cant* - so it makes sense that that we wouldn't get an issue like this from alerts, but we might from a more interactable element like select. We don't, however, get this error from other cds controls like radios or checkboxes, which is odd.

I'm also pulling down Doug's repo and seeing if I can reproduce this without testing-library

It might also be an interesting experiment to try testing the `cds-select` component with dom-testing-library and seeing if it's reproducible there and cutting out react completely

**Comment by mathisscott** [comment]
That's good info. Thanks for sharing. 

The utility functions are used throughout all controls. So seeing them failing on one and not the others doesn't eliminate them. But it doesn't make them stand out as a root cause. ￼

It might be worth it to see if this fails with v4. We switched to the new Lit react wrapper in our latest v5 versions. 

So if this is something that used to work and doesn't anymore, it would be good to see if there's any relation there. 

All this code extends back to v4 or earlier. So I'm just thinking out loud re: items I know have changed in the last few months.

**Comment by ashleyryan** [comment]
I forked Jeremie's repo above and [switched to using dom-testing-library](https://github.com/ashleyryan/repro-clarity-proxy-set-disabled/blob/main/index.test.tsx) with just clarity core and no react. I [followed this blog article](https://matthias-kainer.de/blog/posts/testing-webcomponents-with-jest-and-dom-testing-tools/) which referenced `@open-wc/testing-helpers`. My bare bones test of finding a button worked, but I couldn't even *render* cds-select without the same error. So this doesn't appear to be a react issue at all. 

If I downgrade to 5.0.2 it works, which makes sense, as it's the version before https://github.com/vmware/clarity/pull/5739 that Jeremie mentioned above. It breaks in 5.1.1. If I dig into `syncProps` some more, I see that it's trying to set `disabled` to `false` on the target element right before blowing up, which obviously matches the error above.

Also, I don't set a reference to a Proxy in testing-library, but I do see it in jsdom here: https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/custom-elements/CustomElementRegistry-impl.js#L40

If I edit the file in node_modules to console.log the `value` I see the following: 

```
[class GapShim extends CdsIcon]
[class GapShim extends CdsControl]
[class GapShim extends CdsControlAction]
[class GapShim extends CdsInternalControlGroup]
[class GapShim extends CdsInternalControlInline]
[class GapShim extends CdsInternalControlLabel]
[class GapShim extends CdsControlMessage]
[class GapShim extends CdsFormGroup]
[class GapShim extends CdsSelect]
[class GapShim extends CdsProgressCircle]
[class GapShim extends CdsButton]
[class GapShim extends CdsIconButton]
[class GapShim extends CdsInlineButton]
```

It doesn't really look like that proxy is used anywhere, so that could be a red herring, but it does make me think this is an issue with clarity+jsdom, not testing-library.

One more edit:[ JSDom's Select implementation](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLSelectElement-impl.js), perhaps it's much stricter about setting disabled to a falsey value than the browsers are:

**Comment by hippee-lee** [comment]
@ashleyryan - it sounds like you are right. This issue lays somewhere with `clarity+jsdom`. I'm worried that the issue is JSDOM because it only emulates a subset of a real web browser and it looks like they are using [polyfills](https://github.com/jsdom/jsdom/issues/1030) to support web-components. Perhaps that is why we don't see/cannot reproduce the reported issue in an application vs the testing environment?

This seems to be a pretty big blocker for your team. So, since yesterday, aside from meetings I've stopped my other work and put my full focused this. My current investigation involves isolating only cds-select + JSDOM to see what happens. I've done some parsing / AST stuff before with JSDOM before but It's taking some time to figure out the right way to test my theory (JSDOM or the polyfills are causing the reported issue) and create an isolated cds-select node with JSDOM. My goal is to prove that JSDOM can or cannot render the cds-select isolated from anything else. So no test framework or other things, only cds-select + JSDOM. 

If you have any more ideas please post them here.

**Comment by ashleyryan** [comment]
Thanks @hippee-lee - rendering the component in jsdom without any testing framework was going to be my next step too. I have no other ideas currently

I'm in the process of finding out our devs use cases where they're blocked. I think we can work around this by mocking CdsSelect for now - it gets a bit more complicated for control message and control actions, but not impossible.

**Comment by hippee-lee** [comment]
I hit a snag on rending with JSDOM, I will pick it up tomorrow.

**Comment by ashleyryan** [comment]
this mock will work in the meantime:

```js
jest.mock('@cds/react/select', () => ({
  CdsSelect: (props: PropsWithChildren<ComponentProps<typeof CdsSelect>>) => {
    const ref = useRef<HTMLDivElement>(null);

    useLayoutEffect(() => {
      const id = `id-${Math.trunc(Math.random() * 1000)}`;
      ref.current?.querySelector('select')?.setAttribute('id', id);
      ref.current?.querySelector('label')?.setAttribute('for', id);
    }, []);

    return <div ref={ref} {...(props as unknown)} />;
  },
}));
```

**Comment by hippee-lee** [comment]
Hi @ashleyryan, @dturcotte and @astorije. 

# Summary (tl;dr)
 I'm sorry I do not have better recommendations for you (see below). After spending a significant amount of time this week investigating this issue I have come to the following belief:
The rendering strategy is different between `@testing-library` and `enzyme` and it is the JSDOM dependency in `@testing-library` that is causing the issue. 

# Description
I did not make the jump into `@testing-library` or `JSDOM` to investigate within those codebases. I did try to render our components with JSDOM but did not get anything wired up and working, it was largely an exercise in working through build and compile issues and did not yield anything useful. After chasing Alice in Wonderland down though the rabbit hole several times, she kept leading me off track. So I limited the investigation to **enzyme** (no JSDOM) and **@testing-library** (JSDOM).

I distilled down my various investigations and created a [repo](https://github.com/hippee-lee/cds-select-proxy) with two projects. One is the original used to report this issue. That product was left untouched since it reliably produces the Proxy error. The second project was copied from the original and modified to use enzyme. Using the same test there is no Proxy error (I think it is the same but please do let me know if I got any of the react/enzyme changes wrong). While not included I tested the other @cds/react forms components and did not have any issues when using the enzyme framework.

# Conclusion
The usage of JSDOM in `@testing-library` causes the Proxy error reported for this issue. I believe that because Enzyme defaults to rendering in a headless browser it does not have any issues with web components or react wrapped web components. Please correct me if I am wrong about what I took away from the Enzyme documentation. 

Based on [this](https://github.com/jsdom/jsdom/issues/1030) issue, it looks like JSDOM added support for web-components through the addition of polyfills. While I am not able to provide definitive proof, I strongly suspect that the support for web-components is different enough from the full web component spec that is implemented in browsers that the Proxy error is caused when it tries to render and interact with CdsSelect component from `@cds/react`. 

# Recommendations

1. For @testing-library users: use the workaround posted [here](https://github.com/vmware/clarity/issues/5985#issuecomment-962131488)
1. If there is a choice in testing frameworks, use `enzyme` or a testing framework that uses browsers or headless browsers to ensure full web-component support
1. We should leave the issue open; Further investigation is welcome from members of the react / @testing-library community who have more experience configuring and using react+@testing-library

**Comment by ashleyryan** [comment]
Thanks for the investigation @hippee-lee.

I happened to be in one of our apps that still uses Enzyme and I see a bunch of `UnhandledPromiseRejectionWarning: TypeError: 'set' on proxy: trap returned falsish for property 'disabled'` in the console with CdsSelect there as well. I believe that when using Jest, Enzyme uses JSDom. I wanted to document it here for further evidence that this is a jsdom issue.

Either way, Airbnb stopped supporting Enzyme about 18 months ago, and it still doesn't support React 17, which has been out for a year. So we definitely should not be recommending teams use Enzyme. I would recommend react-testing-library, with the workaround described above.
