### ISSUE TITLE
Add a dark mode top nav background color to core

### ISSUE THREAD

**Issue by jaybellew1** [vmware/clarity#6029]
## Summary

Hi Folks, is there any chance we can add a dark mode top nav BG color to core like we did for angular in 5.2.1?  I think it would be #0E161B which is on the clarity site/colors page for dark mode backgrounds or it would be #0F171C which is currently running on a lot of the vmware apps.  Those two colors are near identical.  

## Use case

Teams using clarity core and clarity core color variables that would like to enable the dark mode for components.  Currently there is no dark mode top nav background color equivalent for apps using core.

**Comment by astorije** [comment]
From an engineering standpoint: while this extra color(s) will be helpful, the real differentiator here is if those could be design token aliases so that we could just use them in our navigation and the aliases would switch to the correct colors in `cds-theme="dark"` mode.

Could this be the direction this takes? I'm happy to work on a PR right away if we define the color(s) and alias(es) we want to add here :)

**Comment by jaybellew1** [comment]
Also, it would help to have the colors for the global left navigation available in clarity core.  Here is my assessment/recommendation of what they might be...bases on the attached screenshot

<img width="722" alt="Screen Shot 2021-06-07 at 2 04 15 PM" src="https://user-images.githubusercontent.com/32872744/121070487-c7739b00-c79c-11eb-996f-2797f2c07c68.png">


Left Nav Bg is #17242b ...this color is in the clarity angular dark theme set
   --cds-alias-status-neutral-shade. is close in current core set but not exact

Font and icons (non active) is #acbac3
    --cds-global-color-cool-gray-100 is close...#ADBBC4 is the color in the clarity angular dark theme set

Font and icons (active) is #fff
   --cds-global-color-white

Background for active item is #324F61 ...no core color currently close..this #324f561 is currently in the angular dark theme set though
--cds-global-color-cool-gray-600 is the closest core color but not really near exact

Separator line is #565656
--cds-global-color-cool-gray-600 is close but not in the angular set either

**Comment by hippee-lee** [comment]
@colinreedmiller can you weigh in here with feasibility for this request.

**Comment by hippee-lee** [comment]
@astorije, @jaybellew1  - not sure if you are asking to define specific navigation aliases but the [cds-navigation component](https://github.com/vmware/clarity/pull/6024) (currently in PR status) will ship with custom properties that tie into the [interaction aliases](https://clarity.design/storybook/core/?path=/story/foundation-interaction-styles--page#vertical-navigation-interaction) and can also be overridden the same way any Core component public custom property could be. 

As far as the request to add the color and what token group it should be organized under, I'll leave that to Colin.

**Comment by colinreedmiller** [comment]
The color set for Core was created with a few things in mind, namely:

- Alignment with NG as much as possible
- Supporting both light and dark themes in the global set
- Fixing a lot of a11y bugs.

For this reason there will be cases where alignment is exact, others where there are imperceptible shifts, and some where the shift is apparent on close examination. There should be no shifts that are large enough to be meaningful.
While there is no Navigation component in Core yet the discussion is somewhat academic. When we do specify a color to be used for this case it will need to be one of the Core globals and referred to by its Global token and HSL value.

**Comment by jaybellew1** [comment]
OK, so is this a no on adding any new colors to the core set?  How about just adding that color for the top nav header?

**Comment by hippee-lee** [comment]
@jaybellew1 - correct. We are resistant to adding one-off colors to the current system. It doesn't mean we will never add colors/ But if/when color(s) are added they need to be looked at carefully because of the domino effect it has on the rest of the colors and a11y vetting that has already been done wrt contrast ratios etc. 

As far as the `top nav header` can you clarify if you are using the `@clr/ui` element or something else? There is no top nav element in core. I am currently working on the `cds-navigation` element which will either support a horizontal layout or be the base class for a `cds-header` element. 

Since this is about adding the color I'm going to close this but feel free to continue the conversation here about the top-nav ask you have. If I can help make something easier for you I'll try to.
