### ISSUE TITLE
Clarity core components - Alert not closable

### ISSUE THREAD

**Issue by koninos** [vmware/clarity#6038]
## Describe the bug

Cannot close the alert message using the close button (x icon)

## How to reproduce
Create a closable alert like this and try to close it by clicking the x icon.
```
<cds-alert-group status="danger">
  <cds-alert closable="true" cds-i18n='{ "closeButtonAriaLabel": "close danger alert"}'>
	  This example is an alert a user may be able to close inside an alert group with a status of "danger".
  </cds-alert>
</cds-alert-group>
```
[Stackblitz](https://stackblitz.com/edit/clarity-light-theme-v5-hpb5of?file=src/app/app.component.html)

## Expected behavior

Alert should close

## Versions

**Clarity project:**
Clarity Core 5.3.0
Clarity Angular/UI 5.3.0

**Clarity version:** 5.3.0

**Framework:** Angular

**Framework version:**
Angular 11.2.13

**Device:**
OS: Windows 10
Browser Chrome 91.0.4472.77

**Comment by grahamford** [comment]
I ran in to the same problem. 

I had to wire it up manually using the `(closeChange)` binding. https://clarity.design/core-components/alert/api/#alert-events

**Comment by mathisscott** [comment]
@grahamford is correct. The core alerts don't close themselves. They will tell the application that an interaction wants to close an alert. The application can take that information and close the alert. Or not...

**Comment by coryrylan** [comment]
This is by design. Clarity Core components are stateless meaning they will emit events when the user interacts with the component but not change/mutate its own state. This ensures the application retains the state and has full control of when it should change.

Example:
When the user closes a modal/alert the app can determine if it should close rather than the component. This is helpful for intercepting interactions like save before leaving. Here is a demo of an alert show/hide in angular https://stackblitz.com/edit/angular-s8zjxb?file=src%2Fapp%2Fapp.component.html
