### ISSUE TITLE
No cards in @clr/core anymore?

### ISSUE THREAD

**Issue by dave105010** [vmware/clarity#6051]
## Describe the bug

There used to be .card class in clarity v4. We are upgrading to clarity v5 and use it with modern js tools(webpacker) to bundle our js and css. 

However, v5 requires every module to be "imported" since there is no more "@clr/ui" documentation on the official site(discontinued?) and no more ways to just load clarity css file and use css classes. I cant even find the list of css classes. Also, everything starts with "cds" like <cds-something> and they are tags instead of css classes.

We implemented and upgraded everything to webpacker with clarity v5 but there are no cards in v5 core components. There are no grids either!!

It's almost impossible to develop apps without a grid(clr-col-md-4 etc.) or cards. 

What is going on?
Am I missing something?

**Comment by wokis** [comment]
You can find documentation on the old card component at [https://clarity.design/angular-components/card](https://clarity.design/angular-components/card).

**Comment by gnomeontherun** [comment]
Hi @dave105010, it sounds like you are looking at the two different implementations, Clarity Angular/UI and Clarity Core. So when we talk about versions, we have to be more clear about which implementation we are talking about.

Clarity Core is not yet complete, so there are some gaps. You can continue to use the original Clarity Angular/UI components, but long term we are focusing on Clarity Core implementations for better accessibility, higher quality, and broader compatibility.

Clarity Core  _just_ launched [cards](https://clarity.design/storybook/core/?path=/story/components-card--page). We also have a [layout system](https://clarity.design/storybook/core/?path=/story/layout-get-started--page). Some documentation is not yet moved to the main website, so that might explain some gaps you are seeing.

You can also continue to use Clarity Angular/UI in your project with Clarity Core at the same time. We are hoping to complete the rebuild of all components in the coming months, but it will still be a little bit of time. If you are not ready to update to use Clarity Core components, you can certainly continue to use the existing Clarity Angular/UI components for as long as you need, they will not go away. 

We have promoted some content on our blog about what is happening, so you can follow it as well for updates. We are also working on some website enhancements to help with questions like these in the coming weeks.

**Comment by dave105010** [comment]
Hi @gnomeontherun ,

What's the reasoning behind switching from css classes to actual tags?
Before, it was easier to switch from bootstrap to clarity. It was easier for any developer to start building on.
Now, it's almost its own niche and the learning curve keeps increasing. Especially with those cds tags and attributes with very long names.

I think I've never spent this much time understanding what's going on in the frontend while trying to make clarity work.

Also, I couldn't manage to remove padding in the "cds-card". The docs are very limited.
Before, the padding was separate with ".card" and ".card-block".
.card would add the actual card and the block inside would add padding when I used it.

Also, I still cannot find the CSS classes/examples of the Clarity v5 even if I wanted to use UI component classes.
On v4, it was here (e.g. badges): https://v4.clarity.design/documentation/badges#examples

Now, it's like CSS disappeared from existence for clarity.
I couldn't find anything that mentions that in the changelog either. The stuff in the changelog is mostly linking to closed github issues. I'm very very confused.

**Comment by mathisscott** [comment]
@dave105010 
The tags are web components. We've written some [articles about our rationale for moving to web components](https://medium.com/claritydesignsystem/clarity-core-72f6d3a029bc) as well as a [blog detailing the performance benefits of moving in this direction](https://medium.com/claritydesignsystem/design-system-performance-with-clarity-core-web-components-fbab56516f30).

While web components may be unfamiliar to some, they are a web standard that is gaining a lot of traction. As far as styling the web components, we do that with CSS custom properties. It makes it easier for an application to customize the components individually or application-wide. What's more, the CSS styling of the web components is self-contained so there's the added benefit of Clarity's styles are no longer contributing to any sort of CSS cascade inflation. It will also be easier to use something like Bootstrap alongside Clarity if a team needed to. There's less risk of the two libraries stomping on each other.

For what it's worth, the Clarity Core components are far easier to customize and support more radical customization than was possible (at least without significant CSS hackery) with Clarity UI.

Other libraries that are moving in the direction of web components and/or CSS custom properties include the aforementioned Bootstrap, Material, IBM Carbon, and more.

@coryrylan did a [presentation on web components](https://www.youtube.com/watch?v=kzfAi3qZpJk) and more of the lower level details of what we are doing, how, and why.

EDIT: I almost forgot. There's more [dev-focused (sort of beta) docs for the web components](https://clarity.design/storybook/core/?path=/story/documentation-welcome--page) too. These might be helpful if you are trying to customize the components in core.

**Comment by dave105010** [comment]
@mathisscott Thank you so much for your detailed answer. It makes much more sense now. I'm reading the articles as we speak.
EDIT: I will see what I can do more to make the transition smoother for us.
