### ISSUE TITLE
Datagrid columns do not align correctly when new rows are added dynamically to the datagrid

### ISSUE THREAD

**Issue by rreymer** [vmware/clarity#618]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If you dynamically add row elements to the datagrid, the length of columns should change accordingly.

### Actual behavior
At the moment if you add dynamically row elements to the datagrid, column width does not change and the text overlaps. A horizontal scroller appears and if try to use it the data does not align with the column headers.

### Reproduction of behavior
https://plnkr.co/edit/RhbX8K4OhX72HHRT8fEZ?p=preview

### Environment details

* **Angular version:** 2.3.1

* **Clarity version:** 0.8.11

* **OS and version:** Win 10 Enterprise

* **Browser:** all

**Comment by youdz** [comment]
Actually, if you look at it precisely, the columns do align nicely. The "Long Id user" is positioned right where it should be, it's just the first cell that overflows on top of it.

This is the expected behavior. We do not want to use `overflow: hidden` on the cells by default because the could contain anything, including stuff that _should_ overflow (like tooltips). On top of that, if you were using actual text rather than an id, you'd see that the text wraps over several lines to avoid overflowing.

So in your specific case, all you need to do is to put an `overflow: hidden` on the ID cell, and a `text-overflow: ellipsis` for good measure. See it in action here: https://plnkr.co/edit/Giu24gt6JCdSQI8Zw5h4?p=preview
I only added a class to ID cells, and put the 2 styles mentioned in the CSS.

**Comment by rreymer** [comment]
Hi youdz,

Thank you for your example with ellipsis option for the text. My case is a little bit different. 

The text that I display in the datagrid call should be displayed in one line even if there are spaces in the text(this is a hard requirement). Based on this, my only option is to use ellipsis but as most of the cells contain such texts this becomes unreadable. The only option to use tooltips is also unacceptable because the user is not able to have the information presented at a glance.

Having all that in mind, I cannot use the datagrid in it's current form.
Is it possible to force the datagrid to recalculate the width of the columns when new rows are added?

**Comment by jaffoneh** [comment]
@rreymer I am a little confused on the requirement, are we saying that we need text not to wrap, not to have ellipses and force the datagrid to react to that? That does not seem like a typical use case or one that would scale. What if the text is far larger than the whole screen? Coding this into the datagrid itself for such a non-typical use case is not the right approach, in my opinion. Let me know if you're able to provide more concrete use cases and examples of why this is the case here.
