### ISSUE TITLE
[NG] Drag & Drop directives

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#620]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

We need to offer a set of directives to make drag & drop behavior easier to use. The first directives that come to mind are:
- `clrDraggable`, which makes any element it is an attribute of draggable. If a draggable element needs too many specific items added to it (like a handle), this might become a wrapper component. Hopefully not. It should emit outputs when picked up and when dropped.
- `clrDropTarget`, which indicates that something draggable can be drop onto this element. It should obviously emit an output when a draggable is dropped on it, but also when a draggable is simply dragged on top of it without being dropped.

Since we can have several draggable and drop targets on the same page without them being related, they need to be somehow bound by an ID or a shared object to avoid conflicts.

**Comment by stpeev** [comment]
A couple of particular use cases you can take into account are 

(a) Drag & Drop between nodes in a tree (inside the same tree instance should be more common case that DnD between different tree instances)

(b) Drag & Drop a row from a grid/list onto a tree node 

I'm not sure about how nicely the directives fit in those two cases. When defining lists and  trees, the user don't describe the individual nodes/rows - but provide some data source and the control generates the representation for you.  So the user is not in control to put clrDraggable or clrDropTarget on nodes/rows individually. So the configuration must be something that can be put directly on the tree/list declaration element, but should not be treated as if the whole tree/list can be dragged. Because in this case the intention is to configure the tree/list individual nodes/items.

**Comment by kannan625** [comment]
Thanks for the update @mathisscott, am all set.
