### ISSUE TITLE
@cds/core: CdsControl should support `aria-disabled` in addition to `disabled`

### ISSUE THREAD

**Issue by ashleyryan** [vmware/clarity#6213]
## Describe the bug

A CdsControl displays as disabled when the `disabled` property is set on the element with the `cds-control` attribute on it. This attribute is invalid on anything that's not an input element, but `aria-disabled` is allowed. 

## How to reproduce

This is a contrived example, but our real use case involves non-clarity dropdown/combobox components that we're trying to wrap in `CdsControl`

https://codesandbox.io/s/clarity-core-cdscontrol-disabled-227m7?file=/src/App.tsx

1.  Notice that the label renders light grey as disabled, but there's a red squiggly line/typescript error for attempting to put `disabled` on a `p` tag.

## Expected behavior

The label would show as disabled when `aria-disabled` is set, in addition to `disabled`.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Comment by mathisscott** [comment]
Thanks for submitting this issue, @ashleyryan . I think I see a way where we can make this work. I'll dig around some more to see how complex the solution would be.

**Comment by mathisscott** [comment]
@ashleyryan 
Checking in here. I have a fix that makes this work. But want to run the following by you:

The fix will render the control inert. Meaning that having a `[cds-control]` element with `[aria-disabled]` set to `"true"` will gray out the label and control message, etc. 

BUT

I'm not applying any styling to the `[cds-control]` element. The reasoning here being similar to what I just fixed in #6212 

Mainly that apps will/should manage the styling of their custom controls. 

Does that sound correct to you?

**Comment by ashleyryan** [comment]
@mathisscott 

Yes, that makes sense! I agree that apps should handle the disabled styling of their custom controls themselves - as long as the label is marked as disabled. 

Unsurprisingly, my custom component is the same as @astorije's in that example.

**Comment by astorije** [comment]
This is great, and I totally agree! And yep that component already takes care of its own disabled styling :D
