### ISSUE TITLE
UI getting crash in <clr-datagrid> component having <clr-dg-placeholder> with custom icons

### ISSUE THREAD

**Issue by dilipshelake03** [vmware/clarity#6217]
## Describe the bug

When user tries to filter data from **clr-datagrid** component, having **clr-dg-placeholder** with **custom icon** then,  while filtering somehow UI is getting crash with  below error. 

Uncaught TypeError: Cannot read property 'indexOf' of undefined at HTMLElement._shapeTemplateSubscription (scripts.ed758b85cef043972290.js:65) at HTMLElement.s.attributeChangedCallback (scripts.ed758b85cef043972290.js:9) at l.invoke (polyfills.a75a54c75e112fdb669a.js:13) at a.runGuarded (polyfills.a75a54c75e112fdb669a.js:13)

## How to reproduce

Please check with https://stackblitz.com/edit/clarity-light-theme-v5-ggw3as

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v5-ggw3as
2.  Click on filter text box, search anything  then clear search field 
3.  Repeat step 2 for few times.
4.  See error UI is getting crash with error Error in /turbo_modules/@clr/icons@4.0.3/index.js (614:55)
**Cannot read property 'indexOf' of undefined**

## Expected behavior

There should not be any UI crash or console exception while filtering data-grid.

## Versions

**Clarity project:**

- [] Clarity Core 3.1.5
- [] Clarity Angular/UI 4.0.3

**Clarity version:**
- [] v4.x 4.0.3

**Framework:**
- [] Angular

**Framework version:**
- Angular 11

**Device:**
- Reproducible on any device with any OS.

**Comment by mathisscott** [comment]
there's a lot going on in that stackblitz and right now stackblitz is crashing everytime i fork and try to edit.

so[ i rebuilt the app in Angular 11 like you had](https://github.com/mathisscott/6217_poc/tree/main/my-app). I think the biggest difference is [how the custom icons are being loaded in](https://github.com/mathisscott/6217_poc/blob/3a55d060c9e3b9198d8c8f85dedca498d67e3bc8/my-app/src/app/app.component.ts#L37). there's no need to make that a service.

the demo in the link above works and i was able to activate the toggle button you had commented out.

closing because this isn't a clarity issue. but you can fork that repository, run it locally, and get where you need to go from there.
