### ISSUE TITLE
cds-icon size property does not work when you add an inline style

### ISSUE THREAD

**Issue by wendellestradairely** [vmware/clarity#6262]
## Describe the bug

I tried to customize the color of the icon but by adding an inline css, but the custom size was lost. It works on angular version with clr-icon though.

```<cds-icon size="128" shape="check-circle" style="color: rgb(194, 117, 117)"></cds-icon>```

With inline css:
![image](https://user-images.githubusercontent.com/50942719/129509530-510e1b2c-83a0-4bad-a359-5a59d011ddbe.png)

Without inline css (but I can't change the color):
![image](https://user-images.githubusercontent.com/50942719/129509601-4ede4010-3ccd-4599-b257-0f0a84f8cc1f.png)

Clarity: Latest
Angular: 12+

**Comment by Shijir** [comment]
With `cds-icon`, It's not recommended to mix API styling with inline styling. So you should try to control the style through either API or inline style attribute. 

If you see the API offered is too limited to cover your use cases and needs, you could try to take over the styling through the inline style attribute and apply your custom styles.

**Comment by mathisscott** [comment]
@wendellestradairely 
Instead of setting the color directly, we recommend using the CSS custom property that we expose to customize the icon.

The reason you can't set the inline style here, however, is because the icon uses the style attribute when it is given a custom numeric size. If you need to combine a custom numeric size with other customizations, consider using a CSS class. That way you can keep the style attribute clear but still get the color customizations you want.

It would look like this...

```
<style>cds-icon.orange { --color: orange; }</style>
<cds-icon size="128" shape="check-circle" class="orange"></cds-icon>
```

**Comment by wendellestradairely** [comment]
@mathisscott Thanks! That worked.
