### ISSUE TITLE
cds-button prevents form submission when there is more than one input field

### ISSUE THREAD

**Issue by grahamford** [vmware/clarity#6263]
## Describe the bug

A form that uses `cds-button` and has more than a single field, can't be submitted with the Enter key.

## How to reproduce

https://stackblitz.com/edit/clarity-keyboard-submit-dlrdzm?file=src/app/app.component.html

* The first example with two input fields, can't be submitted with the Enter key. 
* The second example with just a single text input field can be submitted ok. 
* Adding a regular `<button>` in the third example, enables the form to be submitted via the keyboard again.

## Expected behavior

The form should be submitted by the user pressing the Enter key when in a text field, regardless of the number of input fields.

## Versions

**Clarity project:**

- [X] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.5.1 / 12.0.1

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12.0.2

**Device:**
MacBook
Chrome 92.0.4515.131

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
Your reproduction is using CDS button inside Clarity Angular form, which seems a bit confusing at first, but I reproduced it inside CDS form too.
The form with one input gets submitted only because forms with one input get submitted on enter even without a button.
The reason seems to be that our CDS button implementation is not internally based on button or input elements.

As a workaround, an offscreen, or even hidden input field can be added to the form.
`<input type="submit" style="display: none"/>`

Not tested if the `display: none` version above will work in all browsers, but seems to work in Chrome at least.

**Comment by grahamford** [comment]
Thanks for confirming @Jinnie 

We're slowly moving over from @clr components to the @cds ones in our project. It's just that we've run into a number of niggles along the way. This was the reason for the mixture in the demo, it was the scenario we encountered.

The workaround you suggest does seem to work but feels like an awful bit of code to introduce. Do you think it's possible to fix the issue with the CDS button?

**Comment by Jinnie** [comment]
We're still working on this. It is related to some accessibility requirements that we have, combined with certain Safari browser only limitations. If we find a solution that does not introduce accessibility problems, we'll do this fix.
For now, I can confirm that `<input type="submit" style="display: none"/>` is a viable workaround in different browsers.
We actually add something similar dynamically and destroy it on the fly, after being used, as part of the component lifecycle. The problem is that it is not there when Enter is pressed on an adjacent input.
