### ISSUE TITLE
<cds-file> not working when using lazy loaded modules unless its used inside a <cds-modal>

### ISSUE THREAD

**Issue by exp625** [vmware/clarity#6357]
## Describe the bug

When using the ``<cds-file>`` file selector in an Angular module that is lazy-loaded, the file selector does not open. However, when the ``<cds-file>`` tag is enclosed in a ``<cds-modal>`` tag, the file selector works.

## How to reproduce
See [Stackblitz example](https://stackblitz.com/edit/clarity-light-theme-v5-eiojkm?file=src/app/main/file/file.component.html)

In the same component ``file.component.html`` the ``<cds-file>`` file selector is used. Using it directly within the component does not work. Click the modal button to open a ``<cds-modal>`` in which the same ``<cds-file>`` file selector is used and the file selector works. This example uses a shared.module to organize imports of all components used between different modules. See ``shared.modules.ts`` for the imports of the components of clarity.

## Expected behavior

The <cds-file> selector should work in both cases.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: [Laptor, Desktop]
- OS: [Windows]
- Browser [Chrome, Firefox, Edge]
- Version []

**Comment by coryrylan** [comment]
This looks to be a lifecycle issue on our end. A temporary workaround is to set the `for`property on the label to the id of the input.

### Workaround 
https://stackblitz.com/edit/clarity-light-theme-v5-smqzzc?file=src%2Fapp%2Fmain%2Ffile%2Ffile.component.html 
```html
<cds-file>
  <label [for]="file.id">working</label>
  <input type="file" #file />
</cds-file>
```

### Potential Fix
The button does not trigger the file since it clicks the label which is not getting the proper id association to the input. I _think_ the fix for us is to move the `associateInputAndLabel` call to a slot change event in the two label slots in the `control.element.ts` That way if there is any delay/update from the host app rendering the label the control will pick it up. `<slot name="label" @slotchange=${() => associateInputAndLabel()}></slot>`.
