### ISSUE TITLE
Datagrid column alignment incorrect

### ISSUE THREAD

**Issue by siteslave** [vmware/clarity#643]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Environment details

* **Angular version:** 2.4.X

* **Clarity version:** 0.8.12

* **OS and version:** macOS 10.12.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Before click on web page: 

![screen shot 2560-03-24 at 00 14 21](https://cloud.githubusercontent.com/assets/526890/24260701/591af44a-1027-11e7-9cff-fef006caf552.png)

After click on web page:
![screen shot 2560-03-24 at 00 14 31](https://cloud.githubusercontent.com/assets/526890/24260729/6918974e-1027-11e7-9464-85fca288a6a4.png)

**Comment by adityarb88** [comment]
@siteslave: Please provide a plunker which replicates the issue for us to investigate. Thanks!

**Comment by Jinnie** [comment]
Probably data is loaded dynamically?
I had some workaround posted in another issue yesterday.

Inject a ChangeDetectorRef instance
`constructor(private ref: ChangeDetectorRef) {....
`
and later on, after data is loaded run this:
`ref.detectChanges();`

**Comment by siteslave** [comment]
Thanks @Jinnie.

Data is loaded dynamically, now it work with this solution. 👍 

**In v0.8.9 is work but v0.8.10-v0.8.12 don't work.**

**Comment by xuxinsheng** [comment]
After the upgrade,datagrid becomes abnormal
![a003a02c-d3c6-4824-9091-18c2b92ba06c](https://cloud.githubusercontent.com/assets/20919543/24281476/fa30b358-1093-11e7-8523-b41d7a252889.JPG)

**Comment by Shijir** [comment]
Hi @xuxinsheng, please file a separate issue with Plunkr reproduction as your issue looks different than the original issue posted here.

**Comment by amellnik** [comment]
I'm having the same problem, but I can't use @Jinnie's workaround and add a call to `detectChanges()` since I already have something listening for changes to the filter settings (and I end up infinitely redrawing the table).  

![image](https://cloud.githubusercontent.com/assets/7132414/24314499/26fafe56-109f-11e7-949f-68eff03cbb18.png)

(Note to others: Jinnie is referring to his comment in #623 and #622 is also a dupe).

**Comment by rreymer** [comment]
There is also an issue that I believe is related to this one.

I am loading my datagrid data dynamically. At the beginning there are just few records, but once the records become too much to be accommodated in the datagrid a scroller appears. The scroller takes part of the space and pushes the cells to the left. Because of this the cells become misaligned.

**Comment by Jinnie** [comment]
@rreymer, could you provide a screenshot or a plunker?

**Comment by rreymer** [comment]
Here is the plunker example: https://plnkr.co/edit/3o7x0ryvap5SSDg1wrk9?p=preview
Just add 2 users to the grid by pressing the button.

![image](https://cloud.githubusercontent.com/assets/3208651/24658417/4f0c1914-1952-11e7-8781-b9f36fb21166.png)

![image](https://cloud.githubusercontent.com/assets/3208651/24658429/56e3e856-1952-11e7-90b4-52135149d557.png)

**Comment by klaussilveira** [comment]
Confirming this issue: https://plnkr.co/edit/xBpBbQlGSCc2f8tJopK4

**Comment by s-rusev** [comment]
@klaussilveira If you replace clrDgItems with ngFor - everything works as expected. Although you cannot use the smart iterator.

**Comment by youdz** [comment]
Wow, this issue sure got a lot of traction. Sorry for the delay everyone, the fix is now ready, it'll be part of next weeks' release. We will make sure to merge it in both `0.8.x` and `0.9.x` to accommodate everyone, no matter if you use Angular 2.x or 4.x.

**Comment by klaussilveira** [comment]
This same issue appears to happen with the new `clr-dg-row-detail` feature. Unless you click anywhere on the datagrid, the expansion icon does not show.
