### ISSUE TITLE
CdsInternalVisualCheckbox border color is too light and disabled prop nonfunctional

### ISSUE THREAD

**Issue by kdavidenkovmware** [vmware/clarity#6442]
## Describe the bug

- `CdsInternalVisualCheckbox` disabled prop does not alter appearance or functionally
- `CdsInternalVisualCheckbox` unchecked border does not have same color as `cds-checkbox`
NOTE: We requested access to the internal checkbox for performance, to avoid rendering dozens of checkboxes on certain drop-downs.

## How to reproduce
Code Sandbox to show side-by-side of the checkboxes in various disabled/checked states.
https://codesandbox.io/s/competent-wave-vybbw

## Expected behavior
- `CdsInternalVisualCheckbox` border should look similar to the `cds-checkbox` border (color is light and closer to cds-checkbox disabled)
- Additionally, the disabled prop should affect `CdsInternalVisualCheckbox` in a similar way to `cds-checkbox` 

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**React version:** 16.8.0

**Device:**

- Type: Macbook
- OS: iOS
- Browser: Chrome
- Version: 87.0.4280.88 

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
### Behavior
`cds-internal-visual-checkbox` doesn't have any built in behavior. `cds-tree` and `cds-tree-item` implement the behavior that allows or disallows checking/un-checking for the checked/un-checked state. If you are using this in a dropdown and want checkbox like behavior I would suggest creating a wrapper component and following a similar pattern as implemented in [cds-tree](https://github.com/vmware/clarity/blob/next/packages/core/src/tree-view/tree.element.ts) and [cds-tree-item](https://github.com/vmware/clarity/blob/next/packages/core/src/tree-view/tree-item.element.ts).

### Visual Styles
It looks like the `cds-internal-visual-checkbox` ships with disabled styles but they are not applied. I'm not sure if this is intentional or a bug. @coryrylan / @mathisscott - do you have any insight into this? In an[ isolated stackblitz](https://stackblitz.com/edit/http-server-ngidyu?file=src/index.html) with just the native web component it looks like only checked styles work. Disabled and checked+disabled do not. Is that intentional? 

@kdavidenkovmware - as a workaround you could wrap it in a similar way that cds-tree-item does [here](https://github.com/vmware/clarity/blob/next/packages/core/src/tree-view/tree-item.element.scss#L91) and [here](https://github.com/vmware/clarity/blob/next/packages/core/src/tree-view/tree-item.element.scss#L69) to implement the styles you want for the state: unchecked+disabled, checked+disabled, etc.

**Comment by kdavidenkovmware** [comment]
Yes, @hippee-lee the issue appears to be that the disabled prop does not seem to do anything as far as disabling the checkbox. I'll look into the workarounds you mentioned. The check/unchecking we are handling fine in the code we've implemented in, the disabled styles were the concern.

**Comment by kdavidenkovmware** [comment]
@hippee-lee additionally, I'm not sure it was clear or not, the unchecked and enabled checkbox has a much lighter styling than the cds-checkbox.

**Comment by hippee-lee** [comment]
Yeah - I'm not sure if that was intentional or not, as mentioned, these were internal b/c they were specific to the tree view. @colinreedmiller - do you remember any details around developing these for the tree-view component?

**Comment by colinreedmiller** [comment]
Components present in more complex components should reflect the styling and behavior of the base component in an atomic manner. I'd expect the checkbox in the tree to look and behave the same as it does as a form element unless a design requirement specified otherwise. I don't recall anything that has happened with the tree that would cause this. What I see in Stackblitz looks like a bug - the color for enabled / unchecked is inaccessible.
Correct color is `--cds-alias-object-border-color`

**Comment by coryrylan** [comment]
I can take a look at this as part of our figma audit work @colinreedmiller
