### ISSUE TITLE
Datagrid numeric filter CSS is broken 

### ISSUE THREAD

**Issue by ygangrades** [vmware/clarity#6465]
Hi Clarity team, I’m using a numeric range filter in Datagrid. But the CSS is breaking here as I can't see the min and max fields properly. How can it be fixed?  Here is the stack blitz link https://stackblitz.com/edit/clarity-v4-light-theme-8zpyma?file=src/app/app.component.ts

https://stackblitz.com/edit/clarity-v4-light-theme-8zpyma?file=src/app/app.component.ts

**Comment by bbogdanov** [comment]
Hi @ygangrades,

This seems like a bug. We will take some time to investigate and we'll let you know when we have some resolution.

**Comment by ygangrades** [comment]
Thanks, @bbogdanov. For now, can it be fixed by overriding the clarity CSS or any workaround?

**Comment by bbogdanov** [comment]
@ygangrades 
We did some investigation but we are not done yet to find the root cause. What we observe is that the manager of our popover component that calculates the position of the popover provides coordinates that are our of the viewport.

If that helps you can just make the first column bigger and that will cause the popover to show in its full potential until we provide a solution.
