### ISSUE TITLE
Access the clrDgField or displayed value from the clrDgSortBy comparator function

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#650]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
This is more of a question first, and a request only if what I'm trying to do is not possible.

I'd like to be able to access the clrDgField from the clrDgSortBy comparator function. I am using ngx-tranlsate to translate strings in my app. This is done in my HTML templates via a translate pipe so the values backing my datagrid are untranslated, but displayed as translated text. The built in comparators are using the object property values to run the comparisons on instead of the string values shown in the UI (which have been translated). What I would like to do is create one TranslatedComparator that can access the current field (or better yet, the actual text value being displayed in the UI) and just translate all of the column values on the fly during sort (so it sorts in the correct order based on the translated values, not the actual data values). I realize I can create a customized comparator for each column, but that seems like overkill since the main functionality will always be the same - take a string, convert it to its translated version, then compare. I would love to make this reusable rather than have a bunch of one offs with the only difference being which object property is being translated. So:

1) Is this already possible?

2) If not, can this be added as an enhancement?

3) I would ask for the same to be available for custom filters as well

**Comment by youdz** [comment]
As you mentioned, creating a custom comparator would be a reasonable way to do this. I understand your concern about creating a bunch of one-offs, but this is easily handled by creating a single comparator that takes the field as a property:
```typescript
export class TranslatedPropertyComparator implements Comparator<any> {
    constructor(private prop: string) {}

    public compare(a: any, b: any): number {
        let translatedA = myTranslator(a[prop]);
        let translatedB = myTranslator(b[prop]);
        return translatedA.localeCompare(translatedB);
    }
}
```
Of course, you might have to add undefined detection and stuff like that, but that's the idea.
The same works for `StringFilter`.

Now, I'm not convinced I would _recommend_ this, because when you're sorting or filtering a 10k items datagrid, you perform the translation for each item _when you use it in a comparison_. That means with, say, a standard `O(n*log(n))` sort, you'll translate `n*log(n)` times for `n` elements. Really not optimal. And then you'll re-do it for every re-sort or re-filter.
I would really recommend you have the translations for the current local in your model, without persisting them of course. This can happen as a pass over the items when you receive the data from the server, for instance.

Note that we stay away from i18n because there are still many different solutions for it out there, and picking one would pretty much mean dropping support for the others (or even worse, forcing everyone to move to our choice because we have a hard dependency on it). So any feature that would have us integrate an i18n solution is going to be a "no" for quite some time.

I hope this helps, I'll leave the issue open in case you want to discuss it more or have additional questions. Feel free to close if you want. 😄

**Comment by jbgarr** [comment]
Great, thanks for the feedback on this. I'll this out.
