### ISSUE TITLE
Pagination don't show when use *ngFor

### ISSUE THREAD

**Issue by siteslave** [vmware/clarity#654]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Pagination don't show when use *ngFor but work for clrDgItems
### Reproduction of behavior
https://plnkr.co/edit/Vc86lKr1Px9CCoPK9NHz?p=preview

### Environment details

* **Angular version:** 2.4.X

* **Clarity version:**  0.8.12

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
Yes, this is the intended behavior. There are two possibilities:
- If you have all the data upfront, use `*clrDgItems` and let us handle pagination, sorting, filtering, ...
- If you don't have all the data because pagination is handled by your server, use `*ngFor` in this case, you need to use either `[clrDgTotalItems]` or `[clrDgLastPage]` on the pagination for us to know how many page links to display.

Your plunker is a weird hybrid where you have all the data but try to use `*ngFor`. This is not a case we support, because there is no reason not to use `*clrDgItems` at that point.
