### ISSUE TITLE
Undefined variables when upgrading from 0.13.3 to 12.0.8

### ISSUE THREAD

**Issue by itsvamshiks** [vmware/clarity#6541]
Describe the bug
We have just upgraded our app using Angular (8) to use Angular(13) and configured @clr/angular - 12.0.8 (Clarity v12.0.8) for it, along with @clr/ui - 5.5.2 and @clr/icons - 5.5.2. The earlier versions of these dependencies were v0.13.3. After update I get a bunch of Undefined variable errors when I do an ng serve like:

> SassError: $string: (((((((((), input[type=text]), input[type=password]), input[type=number]), input[type=email]), input[type=url]), input[type=tel]), input[type=date]), input[type=time]), input[type=datetime-local] is not a string.
>    ╷
> 22 │   @return quote($inputs);
>    │           ^^^^^^^^^^^^^^
>    ╵
>   ../node_modules/@clr/ui/src/utils/_helpers.clarity.scss 22:11             inputs()
> ../node_modules/@clr/ui/src/forms-deprecated/_variables.forms.scss 48:16  @import
> ../node_modules/@clr/ui/src/utils/_variables.clarity.scss 81:9            @import
> ../node_modules/@clr/ui/src/utils/_dependencies.clarity.scss 42:9         

> SassError: Undefined variable.
>    ╷
> 25 │ $clr-card-border: $clr-default-borderwidth solid rgba(215, 215, 215, 1);
>    │                   ^^^^^^^^^^^^^^^^^^^^^^

> SassError: Undefined variable.
>    ╷
> 11 │ $clr-link-visited-color: $clr-link-color;
>    │                          ^^^^^^^^^^^^^^^

> SassError: Undefined variable.
>   ╷
> 1 │ @if $enable-flex {
>   │     ^^^^^^^^^^^^
>   ╵
>   ../node_modules/bootstrap/scss/_media.scss 1:5                   @import
>   ../node_modules/@clr/ui/src/utils/_components.clarity.scss 11:9  @import

I currently have some imports of @clr/ui/src/utils/dependencies.clarity, @clr/ui/src/utils/components.clarity and some Clarity CSS overrides. Just trying to figure out what I should be doing to make this work. 

EDIT : @gnomeontherun , I did try updating clr angular to 13.0.0-next.0, and I still am getting the same issues. Below I am posting the code snippet of the stylesheets causing the issue, as a sample to debug. 

```
@import "../node_modules/@clr/ui/src/utils/dependencies.clarity";
@import "../node_modules/@clr/ui/src/utils/components.clarity";

.card.compact .card-block {
  line-height: $clr-table-lineheight;
  font-size: $clr-table-fontsize;
}

$clr-card-border: $clr-default-borderwidth solid rgba(215, 215, 215, 1);
$clr-link-visited-color: $clr-link-color;
$clr-table-bgcolor: $clr-global-app-background;
$clr-table-border-color: $clr-global-app-background;
$clr-table-borderstyle: $clr-table-borderwidth solid $clr-table-border-color;

$clr-progress-bgColor: $clr-global-app-background;
.page-header {
  color: $clr-link-color;
}

.text-highlight {
  color: $clr-link-color;
}

.highlight-hover:hover {
  background-color: $clr-vertical-nav-hover-bg-color;
  color: $clr-link-color;
}
.card.clean, app-card.card.clean {
  background-color: $clr-global-app-background;
}
```

The issue here seems to be with the clarity variables like $clr-global-app-background, $clr-table-borderwidth etc which Im using in the stylesheet. I am including this stylesheet in my angular.json. Hope this snippet helps in debugging the issue

**Comment by gnomeontherun** [comment]
This can be hard to debug without some samples, but the first thing to check is that you are using the same versions of `@clr/angular` `@clr/ui` and `@clr/icons`. Then, use our Clarity v13 beta `ng update @clr/angular@next` to get the Angular 13 compatible release, because Clarity 12 and Angular 13 aren't compatible due to TypeScript changes between Angular 12 and 13. Get yourself on the same version of the packages and see if that helps resolve issues.

**Comment by itsvamshiks** [comment]
> This can be hard to debug without some samples, but the first thing to check is that you are using the same versions of `@clr/angular` `@clr/ui` and `@clr/icons`. Then, use our Clarity v13 beta `ng update @clr/angular@next` to get the Angular 13 compatible release, because Clarity 12 and Angular 13 aren't compatible due to TypeScript changes between Angular 12 and 13. Get yourself on the same version of the packages and see if that helps resolve issues.

@gnomeontherun , I updated my question with the sample code. Please check it out. Also, I tried updating to clr/angular-next but it didnt help.

**Comment by gnomeontherun** [comment]
Since you are updating from 0.13, which is several years old, to the latest in one big jump, you'll find that some of our SCSS code has moved over time for new features and bugfixes. The issue sounds like you are trying to use some Clarity CSS directly in your code, but don't have all of the imports needed. This is a shortcoming of how our Clarity UI SASS files are setup. Loading the file once in your project doesn't make those variables available in your application SASS files unless you directly import them.

I see two main paths here. 

1. Move away from SASS variables and utilize the CSS Custom Properties instead that we offer.
2. Update your imports as necessary to import missing functions or variables, which requires doing a bit of digging into the Clarity source code to find where those items exist to fix the imports on your side.
