### ISSUE TITLE
Publish as Ivy Distribution

### ISSUE THREAD

**Issue by TekSiDoT** [vmware/clarity#6745]
## Describe the bug

@cds/angular latest (`5.6.4` as of writing) is still being distributed as legacy View Engine library. 

## How to reproduce

Any fresh repo w/o prior ngcc run.

## Expected behavior

Clarity should be distributed as an Ivy Distribution

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

**Comment by coryrylan** [comment]
Yes it looks like this was disabled due to a compatibility issue we were waiting on for angular v12 here https://github.com/vmware/clarity/pull/5888/files 

We should be able to migrate cds/angular to use `compilationMode: 'partial'` to at least match clr/angular. This should be applied to v6 and v5 cds/angular. https://github.com/vmware/clarity/blob/angular/projects/angular/tsconfig.lib.prod.json#L8 

It might also be worth investigation on when libraries should move from `partial` to `full` as its currently not clear https://angular.io/guide/angular-compiler-options#compilationmode

**Comment by coryrylan** [comment]
Will go out with next release for v6 and v5
