### ISSUE TITLE
Initial Load Error - yeoman aspnetcore-spa, angular-universal, clarity, webpack2

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#687]
[x ] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Once clarity dependencies are added to the project and entry points included in the webpack vendor config I expect clarity to work inside the application

### Actual behavior
If clarity components (like the responsive navigation) are included in the source on initial compilation I get this error..

---------------------------
An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: TypeError: Cannot read property 'add' of undefined
at NavLevelDirective.addNavClass (C:\[...]\dist\main-server.js:9844:29)[........]
---------------------------

If I leave out the -- [clr-nav-level]="1" -- navigation attribute on initial compilation the app loads. I can then add the attribute back into the source code and the Hot module replacement builds the component correctly and the desired functionality works.

Windows 7 x64
Visual Studio 2017
node v7.8.0
npm v4.2.0
webpack v2.3.3

### Reproduction of behavior
Couldn't find a way to upload project to plunker. Plunk command line tool didn't work. Uploaded to github instead.

https://github.com/jacobbutton/aspnetcore-spa-angular-clarity-initial-load-fail
To reproduce behavior Remove or Add attribute -- [clr-nav-level]="1" -- to ~/ClientApp/app/components/app/app.component.html Line 5

App should fail on initial load.  If you remove the attribute from the app.component.html file and rebuild it should run. If you then re add the attribute and let hot module swapping do its thing the desired functionality of a hamburger collapsing side nav menu thing will happen.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 8.13

* **OS and version:** Win 7

* **Browser:**  Chrome

**Comment by youdz** [comment]
Yes, we do not support Angular-Universal yet. Having all our components work and render on the server in headless mode is actually a very complex issue, for which Angular doesn't provide the necessary tools yet. You'll notice that angular-material and other libraries have the same issue.

That said, for this very specific case, it turns out we can probably do something. For a reason that I ignore, we are manually adding classes with the native API rather than the Renderer. Unless I missed a good reason to do this, we should be able to fix that and get the navigation working with Angular-Universal. Please note, however, that this is not true for all components: for instance, you will still not be able to pre-render a Datagrid on the server.

**Comment by jacobbutton** [comment]
I'm new to angular and not married to this particular set-up. Just using it because that's what was in the project after running the generator. After looking into what angular-universal actually is, I'm not convinced I need it.

Is angular-universal something clarity is planning on adding support for (and if so, is there a time frame to expect support for it?) or would I be better served by modifying my project to not use angular-universal.

**Comment by youdz** [comment]
Yes, we'd like to support it, but we can't give you any kind of time frame because we're waiting for the necessary tools from Angular. As I said, other libraries (including angular-material) are in the same situation, so maybe the Angular team will get to in soon enough?

Once we fix the navbar issue, you should be fine pre-rendering the overall layout of your app. So you should be fine keeping Angular Universal after the fix.

**Comment by jacobbutton** [comment]
If anyone is in a similar position and would like to use clarity with the aspnetcore-spa yeoman generator, I was able to turn off server-side rendering by changing the line 

`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>`

to 

`<app>Loading...</app>`

in ~/Views/Home/Index.cshtml - Line 5.

**Comment by Shijir** [comment]
We believe this is no longer an issue. Our components are fully pre-renderable and our documentation site is SSRed; hence, closing this issue.
