### ISSUE TITLE
unavailability of state object at the column/filter level 

### ISSUE THREAD

**Issue by chaturvedi-varun89** [vmware/clarity#692]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
We should have some mechanism to grab the state object at the sub data-grid level, for example at the row/column. 

### Actual behavior
The state object for now is available only at the data-grid level. It restricts to capture the state on custom filters.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.8.8

* **OS and version:** Ubuntu 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
Could you post an example of what you're expecting? Because with such a short description, I cannot think of a use case that doesn't work with what we currently offer. Especially for custom filters (which you mention), where you literally control the whole filter template and logic, so the state is entirely on the application's side, as opposed to the library's side.

**Comment by mathisscott** [comment]
@chaturvedi-varun89 
It's been a while and you haven't posted a plunkr replicating your issue. I am assuming it's now working for you. Please post a plunkr with the expected behavior and/or breakage if that is not the case.
