### ISSUE TITLE
[NG] DataGrid: Reset Filters

### ISSUE THREAD

**Issue by wodCZ** [vmware/clarity#753]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
DataGrid should have a button to reset all filters.
Even better to reset individual filters.
At least there should be method to reset/remove filters programatically.

### Actual behavior
Currently, the only way to clear filters is to manually delete the search input content for each field/column.
Custom filters (like color picker) need to have initial/default value listed and a user needs to find it and click it.
Also, it's currently not possible to clear filters programatically.

### Reproduction of behavior
N/A

### Environment details

* **Angular version:** 4.0.2

* **Clarity version:** 0.9.0

* **OS and version:** macOS Sierra 10.12.4

* **Browser:** all

**Comment by youdz** [comment]
Yes, this is actually something @yenmade has been raising and pushing for many times. But I believe we still don't have a good UX pattern that would solve this.

I think it might have been forgotten a bit because we didn't have an issue tracking it, so thank you for creating one. 😄  That way we can track it better and prioritize it accordingly.

**Comment by Jinnie** [comment]
Is this good enough? 🤔 
![image](https://cloud.githubusercontent.com/assets/1798828/25239254/2d5a7bc8-25f8-11e7-99cb-24dcc37e3d53.png)
Source: 
https://msdn.microsoft.com/en-us/library/windows/apps/hh465498.aspx

Frankly, the X-button that floats in the current filter widget was initially confusing to me, and I thought it does exactly this - clear the field. So I closed my filter several times before I got used to it. I think that this widget closing X is out of place there. You probably need it to have an explicit way to close the popup, for accessibility reasons, but it's not playing well with the input next to it.

**Comment by adityarb88** [comment]
Regarding what @Jinnie mentioned, this always appears on IE by default:
![image](https://cloud.githubusercontent.com/assets/1426805/25239731/bfbf9d02-25a5-11e7-9f1c-c60b2666fc0e.png)

**Comment by youdz** [comment]
The problem is that you still need to open the filter, clear it, close the filter. 3 actions to clear a single filter, and 3*N actions to clear N of them. 😞 

This is why we haven't implemented something like this, but are waiting on a recommendation from UX on what a more sensible pattern would be.

**Comment by wodCZ** [comment]
In addition to that it's a lot of steps, this will be only applicable to textbox based filters, not custom (select, checkbox, color picker, ...).
I think this should be solved on higher level.

Something like this (excuse my graphical skills) comes to my mind.
![image](https://cloud.githubusercontent.com/assets/1174421/25246907/7a5bef40-2609-11e7-843a-dc02a41cdb4c.png)

Instead of `X` button provide new "apply/tick" button, and make "clear/X" button, which resets the filter to original/empty state.

To be honest, I'm not a big fan of this popup filter thing. As @youdz says, it takes at least 3 steps to filter the results/to reset the filter. I'm only a developer that uses the filter few times a hour for testing purposes and I already hate it. I'm pretty sure that person which will use our software every day for many hours will be irritated with this pretty soon :)

**Comment by water42** [comment]
@youdz  I would like to suggest that clearing filters programmatically be prioritized independently from the redesign being discussed in this issue, if that is possible.

We have several datagrids generated dynamically based on a form selection. When the form selection changes, the datagrid is populated with different data but the filter cannot be reset except for by the user. So we are not currently taking advantage of the built in datagrid filters since it's a confusing experience to not have the filter reset when the data changes. This seems like it would be a fairly common use case

Regardless, thanks for the awesome library - really enjoying it so far.

**Comment by BlakeDraper** [comment]
I hereby add my explicit +1 for the issues raised in this thread by @wodCZ, @Jinnie  and @water42. The need to go through so many steps to set a filter, and then reset it does feel clunky. I really like the Clarity UI package overall, so thanks for the great work. The app I am building relies heavily on the datagrid, so these little improvements would allow me to keep using the Clarity datagrid (which I would prefer) instead of replacing it with another 3rd party datagrid library, which I may be forced to.

**Comment by samdidos** [comment]
Hi, this could be a great feature, since the only way to dynamically clear filters now is to define binding value to `[(clrFilterValue)]` in all rows. It can be interesting to have an icon at the bottom left that indicates the active filters (can be handful because columns can be hidden and have an active filter at the same time) and it could have an X icon to clear active filters.

Something like that : 
![filterindicator](https://user-images.githubusercontent.com/7490081/28781120-0586cd0c-75d7-11e7-9064-3d0457d7e6a2.PNG)

And then when you hover over it, the X icon appears : 
![filterresetproposition](https://user-images.githubusercontent.com/7490081/28781136-176d228c-75d7-11e7-8a37-5d753b5e806b.PNG)

**Comment by mathisscott** [comment]
@reddolan ^

**Comment by reddolan** [comment]
While I believe having an ability to quickly clear filters is helpful, having it at the bottom of the datagrid will likely be overlooked by users. The filtering actions take place at the top of the datagrid, not at the bottom. The best place for this would be somewhere in the context of filter being added. I have some ideas, but I would need to design them out. @mathisscott

**Comment by mathisscott** [comment]
Design completed. Implementation will be tracked in #1632

**Comment by jaanreddy** [comment]
How to reset the selected VMware clarity checkboxes once close the wizard and open.

**Comment by gnomeontherun** [comment]
@jaanreddy I'm not sure what you're after here, but this is a stale issue. We request you post to stack overflow with questions (tag with `vmware-clarity`) and we respond to questions there. We use github for features and bugs only.
