### ISSUE TITLE
Clarity stops working when bootstrap is included 

### ISSUE THREAD

**Issue by learnuser521** [vmware/clarity#756]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```
Using Clarity along with Bootstrap 4 is causing both the css frameworks to stop working. 

I know it is not the best to use multiple css frameworks but was curious as to why it is not working.  

https://plnkr.co/edit/2WDxlc?p=preview

### Environment details

* **Angular version:** 2..X

**Comment by adityarb88** [comment]
@learnuser521: I just switched the order in which bootstrap is loaded. I moved it to load before Clarity since Clarity depends on Bootstrap for a few things and it started to work.

https://plnkr.co/edit/v7KgOz?p=preview

**Comment by adityarb88** [comment]
Please note that we do not guarantee that things will work as expected because you are loading both the frameworks because there a lot of classnames which are similar in both of them.

**Comment by learnuser521** [comment]
@adityarb88  thanks for the quick reply. 
Clarity is working but bootstrap is not https://plnkr.co/edit/lICBxTy77rgx0tPYrBxE?p=preview

**Comment by learnuser521** [comment]
@adityarb88 : Clarity does not work either. It worked for the modal but for the dropdown it is not - https://plnkr.co/edit/YSSSIGxYZf9xTOWmeKYg?p=preview

**Comment by adityarb88** [comment]
@learnuser521: We are not sure why bootstrap is not working. Your clarity dropdown on the other hand had the `top-left` direction and the screen was clipping off the menu. Updated plunker with a working solution:
https://plnkr.co/edit/CNIgfV5Vyyifr3UqwEXu?p=preview

Please refer to the layout and dropdown sections on our documentation for more information:
https://vmware.github.io/clarity/documentation/app-layout
https://vmware.github.io/clarity/documentation/dropdowns

Again, we don't recommend & wont be able to support requests for issues using both the frameworks together because of the number of conflicts you will face.

**Comment by learnuser521** [comment]
@adityarb88 : thanks again. That was a mistake from my side about the position. Should have noticed it, sorry, my bad. 

I hear you, was just curious.
