### ISSUE TITLE
[DataGrid] Provide ability to debounce filters

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#793]
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
I would like to debounce the filter input so that it will only fire after the user stops typing for x milliseconds.

### Actual behavior
Filters are fired immediately on keypress. This causes the table's `clrDgRefresh` event to fire repeatedly as the user types in the input. With a server driven datagrid that means api calls are being fired for each keypress. 

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.0

**Comment by youdz** [comment]
Our current recommendation regarding this is that you simply debounce the `clrDgRefresh` event on your side, it'll do the exact same thing.

Having the debounce on each filter would currently bloat the API far too much for something that doesn't bring much to the table, since the `clrDgRefresh` debounce takes less code than manually giving us a couple additional options on each filter.

**Comment by jbgarr** [comment]
@youdz Thanks for the recommendation. That seems like a reasonable way to handle it and makes things easier on my part too.

**Comment by jimmyshephard** [comment]
I know this is old but I have the same issue, wow exactly did you debounce on the clrDgRefresh event? I can debounce the call to back end but don't want my grid busy loading on every keypress as well

**Comment by ramsbaron** [comment]
Hi all, there doesn't seem to be a way to differentiate between a filter usage and the grid loading. Adding the debounce on the `clrDgRefresh` makes the grid loading delayed by that debounced time.

**Comment by gnomeontherun** [comment]
You can inspect the state to see if any filters are set or not to differentiate.

**Comment by hippee-lee** [comment]
It's hard to say what I recommend in your case since I can't see your code but differentiating using common rxjs operators can easily be handled on the app side. 

Take a look at a [simple demo](https://stackblitz.com/edit/so-55130715-debounce-refresh-events) that uses the `debounceTime` operator to prevent requests from a filter until after the user has stopped typing. 

As @gnomeontherun suggested, you could inspect the state and handle the debounce behavior in a way that works for your app.

**Comment by geyuqiu** [comment]
@youdz 
current situation is that pagination is not leveraged / wished from the client, and we do experience performance issue for loads of data. 
Couldn't we add a debounce [here](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter.ts)
```
this.filter.value = value;
this.filterValueChange.emit(value);
```

**Comment by hippee-lee** [comment]
@geyuqiu - as was previously mentioned, adding debounce to (all of the filters) will be a pretty big change to add to the fitering API. And it would have a pretty big impact. The changes would need to be added in a way that extends the `ClrDatagridFilterInterface` as well as the existing built-in filters and anyone who has built a custom filter who might need to modify for the new api if they are already debouncing with `clrDgRefresh`on the app side. 

What is the issue you are having with debouncing on the app side? If you can provide a simple reproduction that highlights the difference I can take a look at it.
