### ISSUE TITLE
Datagrid sorting and filtering should not be tied together.

### ISSUE THREAD

**Issue by MJuma** [vmware/clarity#831]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior

We should be able to make certain columns in the Datagrid sortable or filterable.

### Actual behavior

Sorting and filtering are currently tied together. There currently is no way to make a column just sortable or just filterable.

### Reproduction of behavior

The "Binding model properties to columns" example in the Documentation is a good example of this. The User ID column doesnt have the [clrDgField] input binding on it so it cant be sortable or filterable. If you add that binding then you end up having to both sort and filter that column but you cant choose one and without the other.

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.2

* **OS and version:** Linux Ubuntu 16.04

* **Browser:** Chrome 57

**Comment by youdz** [comment]
You can have just sort or just filter by simply using the "Custom sort" or "Custom Filter" features. You can just Ctrl-F for them in our documentation: https://vmware.github.io/clarity/documentation/datagrid

And if for some reason you do have a simple binding to a property in your model but do not want filter (I can't think of a valid use case for that), then we even export our `DatagridPropertyComparator` so you don't have to write your own.

**Comment by uded** [comment]
@youdz - I can give you a simple example of such use case: currency values. I do not want to filter it since it is complex and difficult to implement, but sorting is absolutely a valid use case and makes a hell lot of sense.

Can someone point me to a simple implementation that will enable me to switch off filtering on a column?

**Comment by youdz** [comment]
@uded: We enforce a strict policy not to answer "How to" questions on GitHub, both because other people interested in the question would never find the answer buried here, and to avoid polluting our bug tracker.

Could you please ask your question on StackOverflow with the tag [vmware-clarity](https://stackoverflow.com/questions/tagged/vmware-clarity)? As per StackOverflow rules, you should post a StackBlitz or plunker of what you tried, or at least one of a datagrid using currency values but no sort of filter, so we can simply add sorting to it without having to write the whole example from scratch. 

We check StackOverflow every weekday, so questions like these get an answer pretty quickly every time. Thank you! :-)

**Comment by uded** [comment]
OK, let me then rephrase this question.

As per a simple use case in which I would like to enable sorting on a column but skip on filtering as it is not needed or requires a complex model. A simple example of that are fields with currency or similar number based columns that provide summary or detailed information to the user. As such my suggestion would be to introduce a simple, boolean based or array based property to enable/disable features per binding, like:

```
    <clr-dg-column [clrDgField]="'name'" [clrDgFieldSort]="false">Name</clr-dg-column>
    <clr-dg-column [clrDgField]="'creation'" [clrDgFieldFilter]="false">Creation date</clr-dg-column>
    <clr-dg-column [clrDgField]="'pokemon.name'" [clrDgFieldFeatures]="sort,filter">Pokemon</clr-dg-column>
    <clr-dg-column [clrDgField]="'color'" [clrDgFieldFeatures]="filter">Favorite color</clr-dg-column>
```

Above I gave a proposal for two different types of handling, both valid, which just take a different approach to this problem. In either case, the goal is to give the control to the developer to choose whether on specific columns it makes sense to keep the filtering available with the specific type of data and presentation. 

I do understand that it simpler to make this model enable by default for both or to force developers to implement custom filtering/sorting/etc. But for a majority of simple columns, like a column with monetary values, that is excessive and unnecessary from the perspective of what should be achieved. On top of that, especially in business and accounting software, filters on such columns can be and quite often are very complex, which makes it impossible to "fit" into a default, simple filter box but rather quires a large modal or similar solution.

I believe at this point it's rather a change request to extend the feature and, unless there is a simple workaround, I would prefer to treat it as such. Otherwise, this workaround should be properly documented as it seems like a common use case.

**Comment by anaice** [comment]
@uded I think you can use this approach:

Use `[clrDgSortBy]="'field'"` alone if you want only sorting features (up and down arrows). See [custom sorting](https://vmware.github.io/clarity/documentation/v0.12/datagrid/custom-sorting)
Use `[clrDgField]="'field'"` if you want both sorting and filtering features (arrows + input)

**Comment by kathygit** [comment]
The above answer doesn't work. As long as you have [clrDgField]="'name'", sorting is enabled even if you set [clrDgSortBy]="null" here is the code:
```
Object.defineProperty(ClrDatagridColumn.prototype, "sortBy", {
        get: function () {
            return this._sortBy;
        },
        set: function (comparator) {
            console.log('setsortBy', comparator, this._field)
            if (typeof comparator === "string") {
                this._sortBy = new DatagridPropertyComparator(comparator);
            }
            else {
                if (comparator) {
                    this._sortBy = comparator;
                }
                else {
                    if (this._field) {
                        console.log('!!!!!!! this is an UNNECESARY assumption !!!!!!!!!!!>>>>>>>>>')
                        this._sortBy = new DatagridPropertyComparator(this._field);
                    }
                    else {
                        delete this._sortBy;
                    }
                }
            }
        }
```

**Comment by kathygit** [comment]
I wonder why not let us use sortable boolean ?? 
We are stuck ...
