### ISSUE TITLE
ie11 Stack-view overlaps after collapse 

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#865]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
It should not overlap the rows after expand/collapse

### Actual behavior
It overlaps the rows after expand/collapse

### Reproduction of behavior

Expand then Collapse the same row under Internet Explorer 11
[https://vmware.github.io/clarity/documentation/stack-view](url)

### Environment details

* **Angular version:** 4.x

* **Clarity version: 0.9.3

* **OS and version: windows 10 

* **Browser: ie11

**Comment by mathisscott** [comment]
@youdz : Please triage and add to the backlog.

**Comment by jaql** [comment]
The CSS,
    clr-stack-block .stack-children {
        overflow: hidden;
    }

Fixed this for me in Edge.  I think that Edge/IE11 need this when the children contain flex layouts.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support, and we have recently dropped IE11 support as of the end of 2020 for any version of Clarity. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
