### ISSUE TITLE
Login page > needs some design adjustments

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#929]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ X ] enhancement
```
### Need some design updates to Login page

- Decrease left/right margins
- Added text
![image](https://cloud.githubusercontent.com/assets/23196444/26082981/cab701be-3987-11e7-811f-eff485d0ee57.png)

Refer to numbers in image above
1) Reduce left and right margins to 60 px
2) Add "Welcome to" text
3) Add line of text "Use your Company ID to sign in or create one now."
4) New container width = 384 px
5) Left panel width = 504 px (no change)

Additional input line specs:
![image](https://cloud.githubusercontent.com/assets/23196444/26083001/e33cb97c-3987-11e7-8d53-6d849d8113e4.png)

**Comment by lil-kim** [comment]
cc @yenmade

**Comment by chunghha** [comment]
> Add "Welcome to" text
> Add line of text "Use your Company ID to sign in or create one now."

By reading these, I am wondering that if user can have an option as component input to override the background-image, which would be nice and easier. I mean right now with current login component, I got to override the image with login-wrapper's background-image at css level to show   my login background image. One more thing on topic of login-wrapper, user can also have another option to display background-image to full size and top of that modal kind of this login form,  instead of  login-form/background-image displayed side by side?

Please consider the above two options while giving design love to this component.

**Comment by mathisscott** [comment]
Thanks for the feedback, @chunghha. We will take your suggestions under consideration.

**Comment by jeeyun** [comment]
hi @chunghha, since login component is a css/html only (non-angular), it's up to you to include the "Welcome to" text, so it's already optional. We aren't planning on angularizing the login component at this moment, so how you are overriding the image is the right way to go.
