### ISSUE TITLE
Datagrid paging and scrolling at the same time

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#934]
Not sure if that is a bug or enhancement. Set it properly if required.
```
[ ] bug
[ ] feature request
[ x ] enhancement
```

### Expected behavior
We should be able to calculate clrDgPageSize dynamically since the grid is display:flex based and its proper behavior is to fill certain portions of the view dynamically and be more flexible.

### Actual behavior
We have to set clrDgPageSize with static values (ex: clrDgPageSize="10") and the result is paging and scrolling at the same time when wrapper's height is smaller than clr-datagrid's height.

### Reproduction of behavior
https://plnkr.co/edit/KJhNDD?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.4

* **OS and version:** Windows 10

* **Browser:** [all]

**Comment by adityarb88** [comment]
@iivanovgit: I am not sure if I understand the issue correctly because the page size is set by the user. I am not sure if we should override it at our end. Do you need the wrapper when you can simply control the page size? Or are you saying that there should be an option which enables paging and decides the page size based on the height of the datagrid wrapper?

**Comment by iivanovgit** [comment]
@adityarb88  There should be an option which enables paging and decides the page size based on the height of the datagrid wrapper.

**Comment by mathisscott** [comment]
Per UX, we will not be adding this feature to datagrid. It introduces a number of behaviors to page flow and sizing that we would consider to be anti-patterns.
