### ISSUE TITLE
App-level "danger" and "warning" alerts are too similar in color

### ISSUE THREAD

**Issue by ramonaisonline** [vmware/clarity#977]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

App-level "danger" and "warning" alerts should be clearly differentiable visually so the user can respond with appropriate urgency

### Actual behavior

App-level "danger" and "warning" alerts look almost identical in color

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

See the app-level alert examples on this page: https://vmware.github.io/clarity/documentation/alerts

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Hi @ramonaisonline 

Thanks for submitting this! We took a look at the issue you have described and it doesn't appear to us that the colors are that similar. Based on that, we’ve decided not to implement this in Clarity.

Thanks again for submitting the request, we’re always happy to help and look at feedback!

**Comment by joshjohnson72** [comment]
Can you all look at this once more and verify that you're looking at "App-Level" alerts?
![screen shot 2017-05-31 at 4 47 54 pm](https://cloud.githubusercontent.com/assets/8105536/26658738/00f2d00a-4621-11e7-8f65-46d7e1bfca90.png)
If you looked at warning apart from anything else, I think most people could call that "red".

**Comment by joshjohnson72** [comment]
Just for kicks, here's what it looks like when you place it apart from any other color context.
![screen shot 2017-05-31 at 4 50 13 pm](https://cloud.githubusercontent.com/assets/8105536/26658794/48667644-4621-11e7-89e6-76469225da16.png)

**Comment by jaffoneh** [comment]
@joshjohnson72 yeah, when placed alone (which is how app-level alerts appear), it is delivering the message intended especially considering the warning icon. Warning in an app-level alert is supposed to bring attention where a user needs to address the issue (or be aware of it), that's why it is *app-level*. Danger is clearly more obvious in the above with an icon provided and a color change and considering it would appear alone as an app-level alert. We haven't heard any feedback from customers that we've worked with (in the context of apps) to the opposite so for now, there is no need to make any changes. If you have feedback that indicates otherwise, we'd love to look at it and reconsider.
